---
permalink: cloud-connector/backup-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector backup 
summary: SANtricity 클라우드 커넥터 응용 프로그램의 왼쪽 탐색 패널에서 백업 옵션에 액세스할 수 있습니다. 백업 옵션은 새 이미지 기반 또는 파일 기반 백업 작업을 생성할 수 있는 백업 페이지를 표시합니다. 
---
= SANtricity Cloud Connector를 사용하여 E-Series 볼륨 백업을 생성하고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 클라우드 커넥터 응용 프로그램의 왼쪽 탐색 패널에서 백업 옵션에 액세스할 수 있습니다. 백업 옵션은 새 이미지 기반 또는 파일 기반 백업 작업을 생성할 수 있는 백업 페이지를 표시합니다.

SANtricity Cloud Connector 애플리케이션의 * 백업 * 페이지를 사용하여 E-Series 볼륨의 백업을 생성 및 처리합니다. 이미지 기반 백업이나 파일 기반 백업을 만든 다음 이러한 작업을 즉시 또는 나중에 수행할 수 있습니다. 또한 마지막으로 수행된 전체 백업을 기준으로 전체 백업 또는 증분 백업을 수행하도록 선택할 수 있습니다. SANtricity 클라우드 커넥터 애플리케이션을 통해 수행된 마지막 전체 백업을 기준으로 최대 6개의 증분 백업을 수행할 수 있습니다.


NOTE: SANtricity 클라우드 커넥터 애플리케이션에 나열된 백업 및 복원 작업에 대한 모든 타임스탬프는 현지 시간을 사용합니다.



== 새 이미지 기반 백업을 생성합니다

SANtricity 클라우드 커넥터 애플리케이션의 백업 페이지에 있는 생성 기능을 통해 새 이미지 기반 백업을 생성할 수 있습니다.

.시작하기 전에
웹 서비스 프록시에서 SANtricity 클라우드 커넥터에 등록된 스토리지 배열이 있는지 확인합니다.

.단계
. 백업 페이지에서 * 생성 * 을 클릭합니다.
+
백업 생성 창이 표시됩니다.

. 이미지 기반 백업 생성 * 을 선택합니다.
. 다음 * 을 클릭합니다.
+
사용 가능한 E-Series 볼륨 목록이 백업 생성 창에 표시됩니다.

. 원하는 E-Series 볼륨을 선택하고 * Next * 를 클릭합니다.
+
백업 생성 확인 창의 * 백업 이름 지정 및 설명 * 페이지가 표시됩니다.

. 자동 생성된 백업 이름을 수정하려면 * Job Name * 필드에 원하는 이름을 입력합니다.
. 필요한 경우 * Job Description * 필드에 백업에 대한 설명을 추가합니다.
+

NOTE: 백업 내용을 쉽게 식별할 수 있는 작업 설명을 입력해야 합니다.

. 다음 * 을 클릭합니다.
+
선택한 이미지 기반 백업의 요약이 Create Backup 창의 * Review backup information * 페이지에 표시됩니다.

. 선택한 백업을 검토하고 * Finish * 를 클릭합니다.
+
Create Backup 창의 확인 페이지가 표시됩니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * 예 * -- 선택한 백업에 대한 전체 백업을 시작합니다.
** * 아니요 * -- 선택한 이미지 기반 백업에 대한 전체 백업이 수행되지 않습니다.
+

NOTE: 선택한 이미지 기반 백업에 대한 전체 백업은 나중에 백업 페이지의 실행 기능을 통해 수행할 수 있습니다.



. 확인 * 을 클릭합니다.
+
선택한 E-Series 볼륨에 대한 백업이 시작되고 백업 페이지의 결과 목록 섹션에 작업 상태가 표시됩니다.





== 새 폴더/파일 기반 백업을 생성합니다

SANtricity 클라우드 커넥터 애플리케이션의 백업 페이지에 있는 생성 기능을 통해 새 폴더/파일 기반 백업을 생성할 수 있습니다.

.시작하기 전에
웹 서비스 프록시에서 SANtricity 클라우드 커넥터에 등록된 스토리지 배열이 있는지 확인합니다.

파일 기반 백업은 지정한 파일 시스템의 모든 파일을 무조건 백업합니다. 그러나 파일 및 폴더의 선택적 복원을 수행할 수 있습니다.

.단계
. 백업 페이지에서 * 생성 * 을 클릭합니다.
+
백업 생성 창이 표시됩니다.

. 폴더/파일 기반 백업 생성 * 을 선택합니다.
. 다음 * 을 클릭합니다.
+
백업에 사용할 수 있는 파일 시스템이 포함된 볼륨 목록이 백업 생성 창에 표시됩니다.

. 원하는 볼륨을 선택하고 * 다음 * 을 클릭합니다.
+
선택한 볼륨에서 사용 가능한 파일 시스템 목록이 Create Backup 창에 표시됩니다.

+

NOTE: 파일 시스템이 나타나지 않으면 SANtricity 클라우드 커넥터 애플리케이션이 파일 시스템 유형을 지원하는지 확인하십시오. 자세한 내용은 을 참조하십시오 link:learn-intro-concept.html#supported-file-systems["지원되는 파일 시스템"].

. 백업할 폴더나 파일이 들어 있는 원하는 파일 시스템을 선택하고 * 다음 * 을 클릭합니다.
+
백업 생성 확인 창의 * 백업 이름 지정 및 설명 * 페이지가 표시됩니다.

. 자동 생성된 백업 이름을 수정하려면 * Job Name * 필드에 원하는 이름을 입력합니다.
. 필요한 경우 * Job Description * 필드에 백업에 대한 설명을 추가합니다.
+

NOTE: 백업 내용을 쉽게 식별할 수 있는 작업 설명을 입력해야 합니다.

. 다음 * 을 클릭합니다.
+
선택한 폴더/파일 기반 백업에 대한 요약이 Create Backup 창의 * Review backup information * 페이지에 표시됩니다.

. 선택한 폴더/파일 기반 백업을 검토하고 * 마침 * 을 클릭합니다.
+
Create Backup 창의 확인 페이지가 표시됩니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * 예 * -- 선택한 백업에 대한 전체 백업을 시작합니다.
** * 아니요 * -- 선택한 백업에 대한 전체 백업이 수행되지 않습니다.
+

NOTE: 선택한 파일 기반 백업에 대한 전체 백업은 나중에 백업 페이지의 실행 기능을 통해 수행할 수도 있습니다.



. 닫기 * 를 클릭합니다.
+
선택한 E-Series 볼륨에 대한 백업이 시작되고 백업 페이지의 결과 목록 섹션에 작업 상태가 표시됩니다.





== 전체 및 증분 백업을 실행합니다

백업 페이지의 실행 기능을 통해 전체 및 증분 백업을 수행할 수 있습니다. 증분 백업은 파일 기반 백업에만 사용할 수 있습니다.

.시작하기 전에
SANtricity 클라우드 커넥터를 통해 백업 작업을 생성했는지 확인합니다.

.단계
. 백업 탭에서 원하는 백업 작업을 선택하고 * 실행 * 을 클릭합니다.
+

NOTE: 이전에 수행된 초기 백업 없이 이미지 기반 백업 작업 또는 백업 작업을 선택할 때마다 전체 백업이 자동으로 수행됩니다.

+
백업 실행 창이 표시됩니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * 전체 * -- 선택한 파일 기반 백업에 대한 모든 데이터를 백업합니다.
** * Incremental * -- 마지막으로 수행된 백업 이후 변경된 내용만 백업합니다.
+

NOTE: SANtricity 클라우드 커넥터 애플리케이션을 통해 수행된 마지막 전체 백업을 기준으로 최대 6개의 증분 백업을 수행할 수 있습니다.



. Run * 을 클릭합니다.
+
백업 요청이 시작됩니다.





== 백업 작업을 삭제합니다

삭제 기능은 백업 세트와 함께 선택한 백업의 지정된 타겟 위치에서 백업된 데이터를 삭제합니다.

.시작하기 전에
완료, 실패 또는 취소 상태의 백업이 있는지 확인합니다.

.단계
. 백업 페이지에서 원하는 백업을 선택하고 * 삭제 * 를 클릭합니다.
+

NOTE: 전체 기본 백업을 삭제하도록 선택하면 관련된 모든 증분 백업도 삭제됩니다.

+
Confirm Delete(삭제 확인) 창이 표시됩니다.

. 삭제 작업을 확인하려면 * 유형 삭제 * 필드에 '삭제'를 입력합니다.
. 삭제 * 를 클릭합니다.
+
선택한 백업이 삭제됩니다.


