---
permalink: cloud-connector/config-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector configuration 
summary: 설치가 완료되면 구성 마법사를 통해 SANtricity 클라우드 커넥터 응용 프로그램을 설정할 수 있습니다. SANtricity 클라우드 커넥터에 처음 로그인하면 구성 마법사가 표시됩니다. 
---
= SANtricity 클라우드 커넥터를 처음으로 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치가 완료되면 구성 마법사를 통해 SANtricity 클라우드 커넥터 응용 프로그램을 설정할 수 있습니다. SANtricity 클라우드 커넥터에 처음 로그인하면 구성 마법사가 표시됩니다.



== SANtricity 클라우드 커넥터에 처음으로 로그인합니다

SANtricity 클라우드 커넥터를 처음으로 초기화하는 경우 응용 프로그램에 액세스하려면 기본 암호를 입력해야 합니다.

인터넷에 연결된 브라우저에 액세스할 수 있는지 확인합니다.

.단계
. 지원되는 브라우저를 엽니다.
. 구성된 SANtricity 클라우드 커넥터 서버에 연결합니다(예: '+http://localhost:8080/+`).
+
SANtricity 클라우드 커넥터 애플리케이션의 초기 로그인 페이지가 표시됩니다.

. Administrator Password(관리자 암호) 필드에 기본 암호 "password(암호)"를 입력합니다.
. 로그인 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터 구성 마법사가 표시됩니다.





== 구성 마법사 사용

SANtricity 클라우드 커넥터에 처음 로그인하면 구성 마법사가 표시됩니다.

구성 마법사를 통해 관리자 암호, 웹 서비스 프록시 로그인 관리 자격 증명, 원하는 백업 대상 유형 및 SANtricity 클라우드 커넥터의 암호화 암호 구문을 설정합니다.



=== 1단계: 관리자 암호를 설정합니다

관리자 암호 설정 페이지를 통해 SANtricity 클라우드 커넥터에 대한 후속 로그인에 사용되는 암호를 사용자 지정할 수 있습니다.

관리자 암호 설정 페이지를 통해 암호를 설정하면 SANtricity 클라우드 커넥터 응용 프로그램의 초기 로그인 중에 사용되는 기본 암호가 효과적으로 대체됩니다.

.단계
. 관리자 암호 설정 페이지의 * 새 관리자 암호 입력 * 필드에 SANtricity 클라우드 커넥터에 대해 원하는 로그인 암호를 입력합니다.
. 새 관리자 암호 * 필드를 다시 입력하십시오. 필드에 첫 번째 필드의 암호를 다시 입력하십시오.
. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터의 암호 설정이 수락되고 암호 설정 페이지가 구성 마법사 아래에 표시됩니다.

+

NOTE: 사용자 정의 관리자 암호는 구성 마법사를 완료할 때까지 설정되지 않습니다.





=== 2단계: 암호문 설정

암호화 암호 입력 페이지에서 8자에서 32자 사이의 영숫자 암호를 지정할 수 있습니다.

SANtricity 클라우드 커넥터 응용 프로그램에서 사용하는 데이터 암호화 키의 일부로 사용자 지정 암호가 필요합니다.

.단계
. 암호 정의 * 필드에 원하는 암호를 입력합니다.
. 암호 구문 * 필드를 다시 입력하십시오. 필드에 첫 번째 필드의 암호를 다시 입력하십시오.
. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터 애플리케이션에 대해 입력한 암호문이 수락되고 구성 마법사의 대상 유형 선택 페이지가 표시됩니다.





=== 3단계: 대상 유형을 선택합니다

백업 및 복원 기능은 SANtricity 클라우드 커넥터를 통해 Amazon S3, AltaVault 및 StorageGRID 타겟 유형에 사용할 수 있습니다. 대상 유형 선택 페이지에서 SANtricity 클라우드 커넥터 애플리케이션에 대해 원하는 스토리지 타겟 유형을 지정할 수 있습니다.

AltaVault 마운트 지점, Amazon AWS 계정 또는 StorageGRID 계정 중 하나가 있는지 확인합니다.

.단계
. 드롭다운 메뉴에서 다음 옵션 중 하나를 선택합니다.
+
** Amazon AWS
** AltaVault
** StorageGRID
+
선택한 옵션의 대상 유형 페이지가 구성 마법사에 표시됩니다.



. AltaVault, Amazon AWS 또는 StorageGRID에 대한 적절한 구성 지침을 참조하십시오.




==== AltaVault 어플라이언스를 구성합니다

대상 유형 선택 페이지에서 AltaVault 어플라이언스 옵션을 선택하면 AltaVault 대상 유형의 구성 옵션이 표시됩니다.

.시작하기 전에
* AltaVault 어플라이언스에 대한 NFS 마운트 경로가 있습니다.
* AltaVault 어플라이언스를 대상 유형으로 지정했습니다.


.단계
. NFS 마운트 경로 * 필드에 AltaVault 타겟 유형의 마운트 지점을 입력합니다.
+

NOTE: NFS 마운트 경로 * 필드의 값은 Linux 경로 형식을 따라야 합니다.

. 선택한 타겟 유형에 구성 데이터베이스의 백업을 만들려면 이 대상에 구성 데이터베이스의 백업 저장 * 확인란을 선택합니다.
+

NOTE: 연결을 테스트할 때 지정된 대상 유형에서 기존 데이터베이스 구성이 감지되면 SANtricity 클라우드 커넥터 호스트의 기존 데이터베이스 구성 정보를 구성 마법사 아래에 입력된 새 백업 정보로 대체할 수 있습니다.

. 지정된 AltaVault 설정에 대한 연결을 테스트하려면 * 연결 테스트 * 를 클릭합니다.
. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터에 대해 지정된 대상 유형이 허용되고 웹 서비스 프록시 페이지가 구성 마법사에 표시됩니다.

. "4단계: 웹 서비스 프록시에 연결"을 진행합니다.




==== Amazon AWS 계정을 구성합니다

대상 유형 선택 페이지에서 Amazon AWS 옵션을 선택하면 Amazon AWS 타겟 유형에 대한 구성 옵션이 표시됩니다.

.시작하기 전에
* Amazon AWS 계정이 설정되었습니다.
* Amazon AWS를 타겟 유형으로 지정했습니다.


.단계
. 액세스 키 ID * 필드에 Amazon AWS 타겟의 액세스 ID를 입력합니다.
. 비밀 액세스 키 * 필드에 대상의 비밀 액세스 키를 입력합니다.
. [버킷 이름] * 필드에 대상의 버킷 이름을 입력합니다.
. 선택한 타겟 유형에 구성 데이터베이스의 백업을 생성하려면 * 이 대상에 구성 데이터베이스의 백업 저장 * 확인란을 선택합니다.
+

NOTE: 데이터베이스를 잃어버린 경우 백업 대상의 데이터를 복원할 수 있도록 이 설정을 사용하는 것이 좋습니다.

+

NOTE: 연결을 테스트할 때 지정된 대상 유형에서 기존 데이터베이스 구성이 감지되면 SANtricity 클라우드 커넥터 호스트의 기존 데이터베이스 구성 정보를 구성 마법사 아래에 입력된 새 백업 정보로 대체할 수 있습니다.

. Test Connection * 을 클릭하여 입력된 Amazon AWS 자격 증명을 확인합니다.
. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터에 대해 지정된 대상 유형이 허용되고 웹 서비스 프록시 페이지가 구성 마법사 아래에 표시됩니다.

. "4단계: 웹 서비스 프록시에 연결"을 진행합니다.




==== StorageGRID 계정을 구성합니다

대상 유형 선택 페이지에서 StorageGRID 옵션을 선택하면 StorageGRID 대상 유형에 대한 구성 옵션이 표시됩니다.

.시작하기 전에
* StorageGRID 계정이 설정되어 있습니다.
* SANtricity 클라우드 커넥터 키 저장소에 서명된 StorageGRID 인증서가 있습니다.
* 대상 유형으로 StorageGRID를 지정했습니다.


.단계
. URL * 필드에 Amazon S3 클라우드 서비스의 URL을 입력합니다
. 액세스 키 ID * 필드에 S3 대상의 액세스 ID를 입력합니다.
. 비밀 액세스 키 * 필드에 S3 대상의 비밀 액세스 키를 입력합니다.
. Bucket Name * 필드에 S3 타겟의 버킷 이름을 입력합니다.
. 경로 스타일 액세스를 사용하려면 * 경로 스타일 액세스 사용 * 확인란을 선택합니다.
+

NOTE: 이 옵션을 선택하지 않으면 가상 호스트 스타일 액세스가 사용됩니다.

. 선택한 타겟 유형에 구성 데이터베이스의 백업을 생성하려면 * 이 대상에 구성 데이터베이스의 백업 저장 * 확인란을 선택합니다.
+

NOTE: 데이터베이스를 잃어버린 경우 백업 대상의 데이터를 복원할 수 있도록 이 설정을 사용하는 것이 좋습니다.

+

NOTE: 연결을 테스트할 때 지정된 대상 유형에서 기존 데이터베이스 구성이 감지되면 SANtricity 클라우드 커넥터 호스트의 기존 데이터베이스 구성 정보를 구성 마법사에 입력한 새 백업 정보로 바꿀 수 있습니다.

. Test Connection * 을 클릭하여 입력한 S3 자격 증명을 확인합니다.
+

NOTE: 일부 S3 호환 계정에는 보안 HTTP 연결이 필요할 수 있습니다. StorageGRID 인증서를 키 저장소에 배치하는 방법에 대한 자세한 내용은 를 참조하십시오 link:install-intro-concept.html#add-storagegrid-certificate-into-a-keystore["StorageGRID 인증서를 키 저장소에 추가합니다"].

. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터에 대해 지정된 대상 유형이 허용되고 웹 서비스 프록시 페이지가 구성 마법사 아래에 표시됩니다.

. "4단계: 웹 서비스 프록시에 연결"을 진행합니다.




=== 4단계: 웹 서비스 프록시에 연결합니다

SANtricity 클라우드 커넥터와 함께 사용되는 웹 서비스 프록시의 로그인 및 연결 정보는 웹 서비스 프록시 URL 및 자격 증명 입력 페이지를 통해 입력됩니다.

SANtricity 웹 서비스 프록시에 대한 연결이 설정되어 있는지 확인합니다.

.단계
. URL* 필드에 SANtricity 클라우드 커넥터에 사용되는 웹 서비스 프록시의 URL을 입력합니다.
. 사용자 이름 * 필드에 웹 서비스 프록시 연결의 사용자 이름을 입력합니다.
. 암호 * 필드에 웹 서비스 프록시 연결의 암호를 입력합니다.
. 입력한 웹 서비스 프록시 자격 증명에 대한 연결을 확인하려면 * 연결 테스트 * 를 클릭합니다.
. 테스트 연결을 통해 입력한 웹 서비스 프록시 자격 증명을 확인한 후
. 다음 * 을 클릭합니다
+
SANtricity 클라우드 커넥터에 대한 웹 서비스 프록시 자격 증명이 수락되고 스토리지 배열 선택 페이지가 구성 마법사에 표시됩니다.





=== 5단계: 스토리지 배열을 선택합니다

구성 마법사를 통해 입력한 SANtricity 웹 서비스 프록시 자격 증명을 기반으로 사용 가능한 스토리지 배열 목록이 스토리지 배열 선택 페이지에 표시됩니다. 이 페이지에서는 SANtricity 클라우드 커넥터가 백업 및 복원 작업에 사용하는 스토리지 어레이를 선택할 수 있습니다.

SANtricity 웹 서비스 프록시 응용 프로그램에 스토리지 배열이 구성되어 있는지 확인합니다.


NOTE: SANtricity 클라우드 커넥터 애플리케이션에서 확인할 수 없는 스토리지 스토리지는 로그 파일에서 API 예외를 발생하게 됩니다. 이는 연결할 수 없는 스토리지에서 볼륨 목록을 가져올 때마다 SANtricity Cloud Connector 애플리케이션의 의도된 동작입니다. 로그 파일에서 이러한 API 예외를 방지하려면 스토리지 배열에서 직접 루트 문제를 해결하거나 SANtricity 웹 서비스 프록시 응용 프로그램에서 영향을 받는 스토리지 배열을 제거할 수 있습니다.

.단계
. 백업 및 복원 작업을 위해 SANtricity 클라우드 커넥터 애플리케이션에 할당할 스토리지 어레이 옆의 각 확인란을 선택합니다.
. 다음 * 을 클릭합니다.
+
선택한 스토리지 배열이 수락되고 호스트 선택 페이지가 구성 마법사에 표시됩니다.

+

NOTE: 스토리지 배열 선택 페이지에서 선택한 스토리지 배열에 대해 유효한 암호를 구성해야 합니다. SANtricity 웹 서비스 프록시 API 설명서를 통해 스토리지 배열 암호를 구성할 수 있습니다.





=== 6단계: 호스트를 선택합니다

구성 마법사를 통해 선택한 웹 서비스 프록시 호스팅 스토리지 어레이를 기반으로 사용 가능한 호스트를 선택하여 호스트 선택 페이지를 통해 백업 및 복구 대상 볼륨을 SANtricity 클라우드 커넥터 애플리케이션에 매핑할 수 있습니다.

SANtricity 웹 서비스 프록시를 통해 사용할 수 있는 호스트가 있는지 확인합니다.

.단계
. 나열된 스토리지 배열의 드롭다운 메뉴에서 원하는 호스트를 선택합니다.
. 호스트 선택 페이지에 나열된 추가 스토리지 시스템에 대해 1단계를 반복합니다.
. 다음 * 을 클릭합니다.
+
SANtricity 클라우드 커넥터에 대해 선택한 호스트가 수락되고 검토 페이지가 구성 마법사에 표시됩니다.





=== 7단계: 초기 구성을 검토합니다

SANtricity 클라우드 커넥터 구성 마법사의 마지막 페이지에는 검토를 위해 입력된 결과가 요약되어 있습니다.

검증된 구성 데이터의 결과를 검토합니다.

* 모든 구성 데이터의 유효성을 성공적으로 확인 및 설정한 경우 * Finish * 를 클릭하여 구성 프로세스를 완료합니다.
* 구성 데이터의 섹션을 확인할 수 없는 경우 * Back * 을 클릭하여 구성 마법사의 해당 페이지로 이동하여 제출된 데이터를 수정합니다.

