---
permalink: cloud-connector/index.html 
sidebar: sidebar 
keywords: Cloud Connector 
summary: SANtricity 클라우드 커넥터 
---
= SANtricity ® Cloud Connector 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Cloud Connector는 호스트 기반 Linux 애플리케이션으로, E-Series 볼륨을 S3 불만 계정(예: Amazon Simple Storage Service 및 NetApp StorageGRID) 및 NetApp AltaVault 어플라이언스로 전체 블록 기반 및 파일 기반 백업 및 복구를 수행할 수 있습니다.

RedHat 및 SUSE Linux 플랫폼에 설치할 수 있는 SANtricity 클라우드 커넥터는 패키지 솔루션(.bin 파일)입니다. SANtricity 클라우드 커넥터를 설치한 후 애플리케이션을 구성하여 E-Series 볼륨의 백업 및 복원 작업을 AltaVault 어플라이언스 또는 기존 Amazon S3 또는 StorageGRID 계정에 수행할 수 있습니다. SANtricity 클라우드 커넥터를 통해 수행되는 모든 작업은 REST 기반 API를 사용합니다.


NOTE: SANtricity 클라우드 커넥터 도구는 더 이상 사용되지 않으며 다운로드할 수 없습니다.



== 고려 사항

이러한 절차를 사용할 때는 다음 사항에 유의하십시오.

* 이 절차에서 설명하는 구성 및 백업/복원 작업은 SANtricity 클라우드 커넥터의 그래픽 사용자 인터페이스 버전에 적용됩니다.
* SANtricity 클라우드 커넥터 애플리케이션의 REST API 워크플로우는 이 절차에 설명되어 있지 않습니다. 숙련된 개발자의 경우 API 설명서에서 각 SANtricity 클라우드 커넥터 작업에 대해 엔드포인트를 사용할 수 있습니다. API 설명서는 브라우저를 통해 ''http://<hostname.domain>:<port>/docs``'으로 이동하여 액세스할 수 있습니다.




== 백업 유형

SANtricity 클라우드 커넥터는 이미지 기반 백업과 파일 기반 백업의 두 가지 백업 유형을 제공합니다.

* * 이미지 기반 백업 *
+
이미지 기반 백업은 스냅샷 볼륨에서 원시 데이터 블록을 읽고 이를 이미지라고 하는 파일에 백업합니다. 스냅샷 볼륨의 모든 데이터 블록은 빈 블록, 삭제된 파일이 차지하는 블록, 파티셔닝과 관련된 블록, 파일 시스템 메타데이터 등을 포함하여 백업됩니다. 이미지 백업에서는 파티션 구성이나 파일 시스템에 관계없이 스냅샷 볼륨에 모든 정보를 저장할 수 있습니다.

+
이미지는 백업 타겟에 단일 파일로 저장되지 않고 대신 64MB 크기의 일련의 데이터 청크로 분할됩니다. 데이터 청크를 통해 SANtricity Cloud Connector는 백업 타겟에 대한 여러 연결을 사용할 수 있으므로 백업 프로세스의 성능이 향상됩니다.

+
StorageGRID 및 Amazon Web Services(S3)로 백업하는 경우 각 데이터 청크는 별도의 암호화 키를 사용하여 청크를 암호화합니다. 키는 사용자가 제공한 암호와 사용자 데이터의 SHA256 해시의 조합으로 구성된 SHA256 해시입니다. AltaVault로 백업할 경우 AltaVault가 이 작업을 수행하므로 SANtricity 클라우드 커넥터는 데이터 청크를 암호화하지 않습니다.

* * 파일 기반 백업 *
+
파일 기반 백업은 파일 시스템 파티션에 포함된 파일을 읽고 64MB 크기의 일련의 데이터 청크로 백업합니다. 파일 기반 백업은 삭제된 파일 또는 파티션 분할과 파일 시스템 메타데이터를 백업하지 않습니다. 이미지 기반 백업과 마찬가지로 데이터 청크를 통해 SANtricity Cloud Connector는 백업 타겟에 대한 여러 연결을 사용할 수 있으므로 백업 프로세스의 성능이 향상됩니다.

+
StorageGRID 및 Amazon Web Services에 백업하는 경우 각 데이터 청크는 별도의 암호화 키를 사용하여 청크를 암호화합니다. 키는 사용자 제공 암호문과 사용자 데이터의 SHA256 해시의 조합으로 구성된 SHA256 해시입니다. AltaVault로 백업하는 경우 AltaVault가 이 작업을 수행하기 때문에 SANtricity 클라우드 커넥터에 의해 데이터 청크가 암호화되지 않습니다.


