---
permalink: cloud-connector/install-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector installation, install Cloud Connector 
summary: 'SANtricity 클라우드 커넥터 패키지 솔루션(.bin 파일)은 RedHat 및 SUSE Linux 플랫폼에서만 사용할 수 있습니다.' 
---
= SANtricity 클라우드 커넥터를 설치합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 클라우드 커넥터 패키지 솔루션(.bin 파일)은 RedHat 및 SUSE Linux 플랫폼에서만 사용할 수 있습니다.

호환되는 Linux 운영 체제에서 그래픽 모드 또는 콘솔 모드를 통해 SANtricity 클라우드 커넥터 응용 프로그램을 설치할 수 있습니다. 설치 프로세스 중에 SANtricity 클라우드 커넥터에 대한 비 SSL 및 SSL 포트 번호를 지정해야 합니다. SANtricity 클라우드 커넥터가 설치되면 데몬 프로세스로 실행됩니다.

다음 참고 사항을 검토하십시오.

* SANtricity 웹 서비스 프록시가 SANtricity 클라우드 커넥터와 동일한 서버에 이미 설치되어 있는 경우 비 SSL 포트 번호와 SSL 포트 번호 충돌 간에 충돌이 발생합니다. 이 경우 SANtricity 클라우드 커넥터 설치 중에 SSL이 아닌 포트와 SSL 포트에 적절한 번호를 선택합니다.
* 호스트에서 하드웨어 변경이 수행되는 경우 암호화 일관성을 보장하기 위해 SANtricity 클라우드 커넥터 애플리케이션을 다시 설치합니다.
* SANtricity 클라우드 커넥터 애플리케이션의 버전 3.1을 통해 생성된 백업은 SANtricity 클라우드 커넥터 애플리케이션의 버전 4.0과 호환되지 않습니다. 이러한 백업을 유지 관리하려면 이전 버전의 SANtricity 클라우드 커넥터를 계속 사용해야 합니다. SANtricity Cloud Connector의 3.1 및 4.0 릴리즈를 성공적으로 설치하려면 애플리케이션의 각 버전에 대해 고유한 포트 번호를 할당해야 합니다.




== 장치 매퍼 다중 경로(DM-MP) 설치

SANtricity 클라우드 커넥터를 실행하는 모든 호스트는 Linux 장치 매퍼 다중 경로(DM-MP)를 실행하고 다중 경로 도구 패키지를 설치해야 합니다.

SANtricity 클라우드 커넥터 검색 프로세스는 백업 또는 복원할 볼륨 및 파일을 검색하고 인식하기 위해 다중 경로 툴 패키지를 사용합니다. 장치 매퍼를 설정하고 구성하는 방법에 대한 자세한 내용은 에서 사용 중인 SANtricity 릴리스에 대한 _SANtricity 저장소 관리자 다중 경로 드라이버 안내서_를 참조하십시오 https://mysupport.netapp.com/info/web/ECMP1658252.html["E-Series 및 SANtricity 문서 리소스"^].



== Cloud Connector를 설치합니다

Linux 운영 체제에 SANtricity 클라우드 커넥터를 그래픽 모드 또는 콘솔 모드로 설치할 수 있습니다.



=== 그래픽 모드

그래픽 모드를 사용하여 Linux 운영 체제에 SANtricity 클라우드 커넥터를 설치할 수 있습니다.

SANtricity 클라우드 커넥터 설치를 위한 호스트 위치를 지정합니다.

.단계
. SANtricity 클라우드 커넥터 설치 파일을 원하는 호스트 위치로 다운로드합니다.
. 터미널 창을 엽니다.
. SANtricity 클라우드 커넥터 설치 파일이 포함된 디렉토리 파일로 이동합니다.
. SANtricity 클라우드 커넥터 설치 프로세스를 시작합니다.
+
[listing]
----
./cloudconnector-xxxx.bin –i gui
----
+
이 명령에서 xxxx는 애플리케이션의 버전 번호를 지정합니다.

+
설치 프로그램 창이 표시됩니다.

. Introduction 문을 검토한 후 * Next * 를 클릭합니다.
+
NetApp, Inc. 소프트웨어에 대한 라이센스 계약은 설치 프로그램 창에 표시됩니다.

. 사용권 계약 조건에 동의하고 * 다음 * 을 클릭합니다.
+
이전 릴리스의 SANtricity 클라우드 커넥터 페이지에서 생성된 백업이 표시됩니다.

. 이전 릴리스의 SANtricity 클라우드 커넥터 메시지로 생성된 백업을 확인하려면 * 다음 * 을 클릭합니다.
+

NOTE: 이전 버전을 유지하면서 SANtricity 클라우드 커넥터 버전 4.0을 설치하려면 각 응용 프로그램 버전에 대해 고유한 포트 번호를 할당해야 합니다.

+
설치 선택 페이지가 설치 프로그램 창에 표시됩니다. 설치할 위치 필드에는 기본 설치 폴더 'opt/netapp/sSANtricity_cloud_connector4/'가 표시됩니다

. 다음 옵션 중 하나를 선택합니다.
+
** 기본 위치를 그대로 사용하려면 * 다음 * 을 클릭합니다.
** 기본 위치를 변경하려면 새 폴더 위치를 입력합니다. 비 SSL Jetty 포트 번호 입력 페이지가 표시됩니다. 기본값이 8080인 경우 비 SSL 포트에 할당됩니다.


. 다음 옵션 중 하나를 선택합니다.
+
** 기본 SSL 포트 번호를 적용하려면 * 다음 * 을 클릭합니다.
** 기본 SSL 포트 번호를 변경하려면 원하는 새 포트 번호 값을 입력합니다.


. 다음 옵션 중 하나를 선택합니다.
+
** 기본 비 SSL 포트 번호를 그대로 사용하려면 * 다음 * 을 클릭합니다.
** 기본 비 SSL 포트 번호를 변경하려면 원하는 새 포트 번호 값을 입력합니다. 사전 설치 요약 페이지가 표시됩니다.


. 표시된 설치 전 요약을 검토하고 * 설치 * 를 클릭합니다.
+
SANtricity 클라우드 커넥터 설치가 시작되고 Webserver 데몬 설정 프롬프트가 표시됩니다.

. OK * 를 클릭하여 Webserver Daemon Setup 프롬프트를 확인합니다.
+
Installation Complete(설치 완료) 메시지가 표시됩니다.

. Done * 을 클릭하여 SANtricity 클라우드 커넥터 설치 프로그램을 종료합니다.




=== 콘솔 모드

콘솔 모드를 사용하여 Linux 운영 체제에 SANtricity 클라우드 커넥터를 설치할 수 있습니다.

SANtricity 클라우드 커넥터 설치를 위한 호스트 위치를 지정합니다.

.단계
. SANtricity 클라우드 커넥터 설치 파일을 원하는 IO 호스트 위치로 다운로드합니다.
. 터미널 창을 엽니다.
. SANtricity 클라우드 커넥터 설치 파일이 포함된 디렉토리 파일로 이동합니다.
. SANtricity 클라우드 커넥터 설치 프로세스를 시작합니다.
+
[listing]
----
./cloudconnector-xxxx.bin –i console
----
+
이 명령에서 xxxx는 애플리케이션의 버전 번호를 나타냅니다.

+
SANtricity 클라우드 커넥터 설치 프로세스가 초기화됩니다.

. 설치 프로세스를 진행하려면 * Enter * 를 누르십시오.
+
NetApp, Inc. 소프트웨어에 대한 최종 사용자 라이센스 계약은 설치 프로그램 창에 표시됩니다.

+

NOTE: 설치 프로세스를 취소하려면 설치 프로그램 창 아래에 quit를 입력합니다.

. 최종 사용자 사용권 계약의 각 부분을 진행하려면 * Enter * 를 누르십시오.
+
사용권 계약 수락 진술은 설치 프로그램 창 아래에 표시됩니다.

. 최종 사용자 사용권 계약 조건에 동의하고 SANtricity 클라우드 커넥터 설치를 계속하려면 설치 프로그램 창에서 'Y'를 입력하고 * Enter * 를 누르십시오.
+
이전 릴리스의 SANtricity 클라우드 커넥터 페이지에서 생성된 백업이 표시됩니다.

+

NOTE: 최종 사용자 계약 조건에 동의하지 않으면 "N"을 입력하고 * Enter * 를 눌러 SANtricity 클라우드 커넥터의 설치 프로세스를 종료합니다.

. 이전 릴리스의 SANtricity 클라우드 커넥터 메시지로 생성된 백업을 확인하려면 * Enter * 를 누르십시오.
+

NOTE: 이전 버전을 유지하면서 SANtricity 클라우드 커넥터 버전 4.0을 설치하려면 각 응용 프로그램 버전에 대해 고유한 포트 번호를 할당해야 합니다.

+
SANtricity 클라우드 커넥터에 대한 다음 기본 설치 폴더가 있는 설치 폴더 선택 메시지가 표시됩니다. ""/opt/netapp/sSANtricity_cloud_connector4/".

. 다음 옵션 중 하나를 선택합니다.
+
** 기본 설치 위치를 그대로 사용하려면 * Enter * 를 누릅니다.
** 기본 설치 위치를 변경하려면 새 폴더 위치를 입력합니다. 비 SSL Jetty 포트 번호 입력 메시지가 표시됩니다. 기본값이 8080인 경우 비 SSL 포트에 할당됩니다.


. 다음 옵션 중 하나를 선택합니다.
+
** 기본 SSL 포트 번호를 그대로 사용하려면 * 다음 * 을 누릅니다.
** 기본 SSL 포트 번호를 변경하려면 원하는 새 포트 번호 값을 입력합니다.


. 다음 옵션 중 하나를 선택합니다.
+
** 기본 비 SSL 포트 번호를 그대로 사용하려면 * Enter * 를 누릅니다.
** 기본 비 SSL 포트 번호를 변경하려면 새 포트 번호 값을 입력합니다. SANtricity 클라우드 커넥터의 사전 설치 요약이 표시됩니다.


. 표시된 사전 설치 요약을 검토하고 * Enter * 를 누릅니다.
. Enter * 를 눌러 Webserver Daemon Setup 프롬프트를 확인합니다.
+
Installation Complete(설치 완료) 메시지가 표시됩니다.

. SANtricity 클라우드 커넥터 설치 프로그램을 종료하려면 * Enter * 를 누릅니다.




== 서버 인증서와 CA 인증서를 키 저장소에 추가합니다

브라우저에서 SANtricity 클라우드 커넥터 호스트로의 보안 https 연결을 사용하려면 SANtricity 클라우드 커넥터 호스트에서 자체 서명된 인증서를 수락하거나 브라우저와 SANtricity 클라우드 커넥터 응용 프로그램에서 인식되는 인증서와 신뢰 체인을 추가할 수 있습니다.

SANtricity 클라우드 커넥터 애플리케이션이 호스트에 설치되어 있어야 합니다.

.단계
. 'stemctl' 명령을 사용하여 서비스를 중지합니다.
. 기본 설치 위치에서 작업 디렉토리에 액세스합니다.
+

NOTE: SANtricity 클라우드 커넥터의 기본 설치 위치는 '/opt/netapp/SANtricity_cloud_connector4'입니다.

. 'keytool' 명령을 사용하여 서버 인증서 및 인증서 서명 요청(CSR)을 생성합니다.
+
* 예 *

+
[listing]
----
keytool -genkey -dname "CN=host.example.com, OU=Engineering, O=Company, L=<CITY>, S=<STATE>, C=<COUNTRY>" -alias cloudconnect -keyalg "RSA" -sigalg SHA256withRSA -keysize 2048 -validity 365 -keystore keystore_cloudconnect.jks -storepass changeit
keytool -certreq -alias cloudconnect -keystore keystore_cloudconnect.jks -storepass changeit -file cloudconnect.csr
----
. 생성된 CSR을 선택한 CA(인증 기관)에 보냅니다.
+
인증 기관이 인증서 요청에 서명하고 서명된 인증서를 반환합니다. 또한 CA 자체로부터 인증서를 받습니다. 이 CA 인증서를 키 저장소로 가져와야 합니다.

. 인증서와 CA 인증서 체인을 "/<설치 경로>/작업/키 저장소" 응용 프로그램 키 저장소로 가져옵니다
+
* 예 *

+
[listing]
----
keytool -import -alias ca-root -file root-ca.cer -keystore keystore_cloudconnect.jks -storepass <password> -noprompt
keytool -import -alias ca-issuing-1 -file issuing-ca-1.cer -keystore keystore_cloudconnect.jks -storepass <password> -noprompt
keytool -import -trustcacerts -alias cloudconnect -file certnew.cer -keystore keystore_cloudconnect.jks -storepass <password>
----
. 서비스를 다시 시작합니다.




== StorageGRID 인증서를 키 저장소에 추가합니다

StorageGRID를 SANtricity 클라우드 커넥터 응용 프로그램의 대상 유형으로 구성하는 경우 먼저 SANtricity 클라우드 커넥터 키 저장소에 StorageGRID 인증서를 추가해야 합니다.

.시작하기 전에
* 서명된 StorageGRID 인증서가 있습니다.
* 호스트에 SANtricity 클라우드 커넥터 애플리케이션이 설치되어 있습니다.


.단계
. 'stemctl' 명령을 사용하여 서비스를 중지합니다.
. 기본 설치 위치에서 작업 디렉토리에 액세스합니다.
+

NOTE: SANtricity 클라우드 커넥터의 기본 설치 위치는 '/opt/netapp/SANtricity_cloud_connector4'입니다.

. StorageGRID 인증서를 "/<설치 경로>/작업/키 저장소" 응용 프로그램 키 저장소로 가져옵니다
+
* 예 *

+
[listing]
----
opt/netapp/santricity_cloud_connector4/jre/bin/keytool -import -trustcacerts -storepass changeit -noprompt -alias StorageGrid_SSL -file /home/ictlabsg01.cer -keystore /opt/netapp/santricity_cloud_connector/jre/lib/security/cacerts
----
. 서비스를 다시 시작합니다.

