---
permalink: cloud-connector/modify-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector settings 
summary: SANtricity 클라우드 커넥터 응용 프로그램의 왼쪽 탐색 패널에서 설정 옵션에 액세스할 수 있습니다. 설정 옵션을 사용하면 S3 계정, 관리되는 스토리지 배열 및 호스트, 웹 서비스 프록시 자격 증명에 대한 응용 프로그램의 현재 구성을 수정할 수 있습니다. 설정 옵션을 통해 SANtricity 클라우드 커넥터 응용 프로그램의 암호를 변경할 수도 있습니다. 
---
= SANtricity 클라우드 커넥터 설정을 수정합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설정 옵션을 사용하면 S3 계정, 관리되는 스토리지 배열 및 호스트, 웹 서비스 프록시 자격 증명에 대한 응용 프로그램의 현재 구성을 수정할 수 있습니다. 설정 옵션을 통해 SANtricity 클라우드 커넥터 응용 프로그램의 암호를 변경할 수도 있습니다.



== S3 계정 설정을 수정합니다

S3 계정 설정 창에서 SANtricity 클라우드 커넥터 응용 프로그램에 대한 기존 S3 설정을 수정할 수 있습니다.

URL 또는 S3 버킷 레이블 설정을 수정할 때 SANtricity 클라우드 커넥터를 통해 구성된 기존 백업에 대한 액세스가 영향을 받는다는 점에 유의하십시오.

.단계
. 왼쪽 도구 모음에서 * 설정 > 구성 * 을 클릭합니다.
+
설정 - 구성 페이지가 표시됩니다.

. S3 계정 설정에 대한 * 설정 보기/편집 * 을 클릭합니다.
+
S3 계정 설정 페이지가 표시됩니다.

. URL 파일에 S3 클라우드 서비스의 URL을 입력합니다.
. 액세스 키 ID * 필드에 S3 대상의 액세스 ID를 입력합니다.
. 비밀 액세스 키 * 필드에 S3 대상의 액세스 키를 입력합니다.
. S3 버킷 이름 * 필드에 S3 타겟의 버킷 이름을 입력합니다.
. 필요한 경우 * 경로 스타일 액세스 사용 * 확인란을 선택합니다.
. Test Connection * 을 클릭하여 입력한 S3 자격 증명에 대한 연결을 확인합니다.
. 저장 * 을 클릭하여 수정 사항을 적용합니다.
+
수정된 S3 계정 설정이 적용됩니다.





== 스토리지 시스템을 관리합니다

스토리지 배열 관리 페이지의 SANtricity 클라우드 커넥터 호스트에 등록된 웹 서비스 프록시에서 스토리지 배열을 추가하거나 제거할 수 있습니다.

스토리지 배열 관리 페이지에는 SANtricity 클라우드 커넥터 호스트에 등록할 수 있는 웹 서비스 프록시의 스토리지 배열 목록이 표시됩니다.

.단계
. 왼쪽 도구 모음에서 * 설정 > 스토리지 배열 * 을 클릭합니다.
+
Settings - Storage Arrays(설정 - 스토리지 배열) 화면이 표시됩니다.

. SANtricity 클라우드 커넥터에 스토리지 어레이를 추가하려면 * 추가 * 를 클릭합니다.
+
.. Add Storage Arrays 창의 결과 목록에서 원하는 스토리지 배열 옆에 있는 각 확인란을 선택합니다.
.. 추가 * 를 클릭합니다.
+
선택한 스토리지 배열이 SANtricity 클라우드 커넥터에 추가되고 설정 - 스토리지 배열 화면의 결과 목록 섹션에 표시됩니다.



. 추가된 스토리지 배열에 대한 호스트를 수정하려면 Settings(설정) - Storage Arrays(스토리지 배열) 화면의 Result list(결과 목록) 섹션에서 라인 항목에 대해 * Edit(편집) * 를 클릭합니다.
+
.. Associated Host(연결된 호스트) 드롭다운 메뉴에서 스토리지 배열에 대해 원하는 호스트를 선택합니다.
.. 저장 * 을 클릭합니다.
+
선택한 호스트가 스토리지 배열에 할당됩니다.



. SANtricity 클라우드 커넥터 호스트에서 기존 스토리지 배열을 제거하려면 하단 결과 목록에서 원하는 스토리지 배열을 선택하고 * Remove * 를 클릭합니다.
+
.. 스토리지 배열 제거 확인 필드에 remove를 입력합니다.
.. 제거 * 를 클릭합니다.
+
선택한 스토리지 배열이 SANtricity 클라우드 커넥터 호스트에서 제거됩니다.







== 웹 서비스 프록시 설정을 수정합니다

웹 서비스 프록시 설정 창에서 SANtricity 클라우드 커넥터 응용 프로그램에 대한 기존 웹 서비스 프록시 설정을 수정할 수 있습니다.

SANtricity 클라우드 커넥터와 함께 사용되는 웹 서비스 프록시는 적절한 어레이가 추가되고 해당 암호가 설정되어 있어야 합니다.

.단계
. 왼쪽 도구 모음에서 * 메뉴: 설정 [구성] * 을 클릭합니다.
+
설정 - 구성 화면이 표시됩니다.

. 웹 서비스 프록시에 대한 * 설정 보기/편집 * 을 클릭합니다.
+
웹 서비스 프록시 설정 화면이 표시됩니다.

. URL 필드에 SANtricity 클라우드 커넥터에 사용되는 웹 서비스 프록시의 URL을 입력합니다.
. 사용자 이름 필드에 웹 서비스 프록시 연결의 사용자 이름을 입력합니다.
. 암호 필드에 웹 서비스 프록시 연결의 암호를 입력합니다.
. 입력한 웹 서비스 프록시 자격 증명에 대한 연결을 확인하려면 * 연결 테스트 * 를 클릭합니다.
. 저장 * 을 클릭하여 수정 사항을 적용합니다.




== SANtricity 클라우드 커넥터 암호를 변경합니다

암호 변경 화면에서 SANtricity 클라우드 커넥터 응용 프로그램의 암호를 변경할 수 있습니다.

.단계
. 왼쪽 도구 모음에서 * 메뉴: 설정 [구성] * 을 클릭합니다.
+
설정 - 구성 화면이 표시됩니다.

. SANtricity 클라우드 커넥터의 * 암호 변경 * 을 클릭합니다.
+
암호 변경 화면이 표시됩니다.

. 현재 암호 필드에 SANtricity 클라우드 커넥터 응용 프로그램의 현재 암호를 입력합니다.
. 새 암호 필드에 SANtricity 클라우드 커넥터 응용 프로그램의 새 암호를 입력합니다.
. 새 암호 확인 필드에 새 암호를 다시 입력합니다.
. 새 암호를 적용하려면 * 변경 * 을 클릭합니다.
+
수정된 암호는 SANtricity 클라우드 커넥터 응용 프로그램에 적용됩니다.


