---
permalink: cloud-connector/restore-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector restore, 
summary: SANtricity 클라우드 커넥터 응용 프로그램의 왼쪽 탐색 패널에서 복원 옵션에 액세스할 수 있습니다. 복원 옵션은 새 이미지 기반 또는 파일 기반 복원 작업을 만들 수 있는 복원 페이지를 표시합니다. 
---
= 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 클라우드 커넥터 응용 프로그램의 왼쪽 탐색 패널에서 복원 옵션에 액세스할 수 있습니다. 복원 옵션은 새 이미지 기반 또는 파일 기반 복원 작업을 만들 수 있는 복원 페이지를 표시합니다.

SANtricity 클라우드 커넥터는 작업 개념을 사용하여 E-Series 볼륨의 실제 복원을 수행합니다. 복원을 수행하기 전에 작업에 사용할 E-Series 볼륨을 확인해야 합니다. 복원을 위해 E-Series 볼륨을 SANtricity 클라우드 커넥터 호스트에 추가한 후 SANtricity 클라우드 커넥터 애플리케이션의 '복원' 페이지를 사용하여 복원을 생성 및 처리할 수 있습니다.


NOTE: SANtricity 클라우드 커넥터 애플리케이션에 나열된 백업 및 복원 작업에 대한 모든 타임스탬프는 현지 시간을 사용합니다.



== 새 이미지 기반 복원을 생성합니다

SANtricity 클라우드 커넥터 응용 프로그램의 복원 페이지에 있는 만들기 기능을 통해 새 이미지 기반 복원을 만들 수 있습니다.

SANtricity 클라우드 커넥터를 통해 이미지 기반 백업을 사용할 수 있는지 확인합니다.

.단계
. SANtricity 클라우드 커넥터 응용 프로그램의 복원 페이지에서 * 생성 * 을 클릭합니다.
+
Restore(복원) 창이 표시됩니다.

. 원하는 백업을 선택합니다.
. 다음 * 을 클릭합니다.
+
백업 지점 선택 페이지가 복원 창에 표시됩니다.

. 원하는 완료된 백업을 선택합니다.
. 다음 * 을 클릭합니다.
+
Restore(복원) 창에 Select Restore Target(대상 복원 선택) 페이지가 표시됩니다.

. 복원 볼륨을 선택하고 * 다음 * 을 클릭합니다.
+
Restore(복원) 창에 Review(검토) 페이지가 표시됩니다.

. 선택한 복원 작업을 검토하고 * Finish * 를 클릭합니다.
+
선택한 타겟 호스트 볼륨에 대한 복구가 시작되고 복구 페이지의 결과 목록 섹션에 작업 상태가 표시됩니다.





== 새 파일 기반 복구를 생성합니다

SANtricity 클라우드 커넥터 응용 프로그램의 복원 페이지에 있는 만들기 기능을 통해 새 파일 기반 복원을 만들 수 있습니다.

SANtricity 클라우드 커넥터를 통해 파일 기반 백업을 사용할 수 있는지 확인합니다.

.단계
. SANtricity 클라우드 커넥터 응용 프로그램의 복원 페이지에서 * 생성 * 을 클릭합니다.
+
Restore(복원) 창이 표시됩니다.

. Restore 창에서 원하는 파일 기반 백업을 선택합니다.
. 다음 * 을 클릭합니다.
+
백업 지점 선택 페이지가 복원 작업 생성 창에 표시됩니다.

. 백업 지점 선택 페이지에서 원하는 완료된 백업을 선택합니다.
. 다음 * 을 클릭합니다.
+
복구 창에 사용 가능한 파일 시스템 또는 폴더/파일 목록이 표시됩니다.

. 복원할 폴더 또는 파일을 선택하고 * 다음 * 을 클릭합니다.
+
Restore(복원) 창에 Select Restore Target(대상 복원 선택) 페이지가 표시됩니다.

. 복원 볼륨을 선택하고 * 다음 * 을 클릭합니다.
+
Restore(복원) 창에 Review(검토) 페이지가 표시됩니다.

. 선택한 복원 작업을 검토하고 * Finish * 를 클릭합니다.
+
선택한 타겟 호스트 볼륨에 대한 복구가 시작되고 복구 페이지의 결과 목록 섹션에 작업 상태가 표시됩니다.





== 복원을 삭제합니다

삭제 기능을 사용하여 복원 페이지의 결과 목록 섹션에서 선택한 복원 항목을 삭제할 수 있습니다.

완료, 실패 또는 취소 상태의 복원 작업이 있는지 확인합니다.

.단계
. 복원 페이지에서 * 삭제 * 를 클릭합니다.
+
Confirm Delete(삭제 확인) 창이 표시됩니다.

. 삭제 작업을 확인하려면 * 유형 삭제 * 필드에 삭제 를 입력합니다.
. 삭제 * 를 클릭합니다.
+

NOTE: 일시 중지된 복구는 삭제할 수 없습니다.

+
선택한 복원이 삭제됩니다.


