---
permalink: config-linux/fc-assign-volume-nvme-task.html 
sidebar: sidebar 
keywords: express linux configuration, assign volume, assign namespace, 
summary: 'I/O 작업에 사용할 수 있도록 호스트 또는 호스트 클러스터에 볼륨\(네임스페이스\)을 할당해야 합니다. 이 할당은 호스트 또는 호스트 클러스터에 스토리지 배열의 하나 이상의 네임스페이스에 대한 액세스 권한을 부여합니다.' 
---
= 볼륨을 할당합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I/O 작업에 사용할 수 있도록 호스트 또는 호스트 클러스터에 볼륨(네임스페이스)을 할당해야 합니다. 이 할당은 호스트 또는 호스트 클러스터에 스토리지 배열의 하나 이상의 네임스페이스에 대한 액세스 권한을 부여합니다.

볼륨을 할당할 때 다음 지침을 염두에 두십시오.

* 한 번에 하나의 호스트 또는 호스트 클러스터에만 볼륨을 할당할 수 있습니다.
* 할당된 볼륨은 스토리지 배열의 컨트롤러 간에 공유됩니다.
* 호스트 또는 호스트 클러스터에서 볼륨에 액세스하는 데 동일한 네임스페이스 ID(NSID)를 두 번 사용할 수 없습니다. 고유한 NSID를 사용해야 합니다.


다음과 같은 조건에서는 볼륨을 할당할 수 없습니다.

* 모든 볼륨이 할당됩니다.
* 볼륨이 이미 다른 호스트 또는 호스트 클러스터에 할당되어 있습니다.


다음과 같은 조건에서는 볼륨을 할당할 수 없습니다.

* 유효한 호스트 또는 호스트 클러스터가 없습니다.
* 모든 볼륨 할당이 정의되었습니다.


할당되지 않은 모든 볼륨이 표시되지만 DA(Data Assurance)를 사용하거나 사용하지 않는 호스트의 기능은 다음과 같이 적용됩니다.

* DA 지원 호스트의 경우 DA 사용 또는 DA 사용 안 함 볼륨을 선택할 수 있습니다.
* DA를 사용할 수 없는 호스트의 경우 DA를 사용할 수 있는 볼륨을 선택하면 호스트에 볼륨을 할당하기 전에 시스템에서 자동으로 볼륨의 DA를 해제해야 한다는 경고가 표시됩니다.


.단계
. 스토리지 [호스트] 메뉴를 선택합니다.
. 볼륨을 할당할 호스트 또는 호스트 클러스터를 선택한 다음 * 볼륨 할당 * 을 클릭합니다.
+
할당할 수 있는 모든 볼륨이 나열된 대화 상자가 나타납니다. 특정 볼륨을 쉽게 찾을 수 있도록 모든 열을 정렬하거나 * Filter * (필터 *) 상자에 원하는 항목을 입력할 수 있습니다.

. 할당할 각 볼륨 옆의 확인란을 선택하거나 표 머리글에서 확인란을 선택하여 모든 볼륨을 선택합니다.
. 작업을 완료하려면 * 배정 * 을 클릭하십시오.


볼륨이나 볼륨을 호스트 또는 호스트 클러스터에 성공적으로 할당한 후 시스템은 다음 작업을 수행합니다.

* 할당된 볼륨은 다음으로 사용 가능한 NSID를 받습니다. 호스트는 NSID를 사용하여 볼륨에 액세스합니다.
* 사용자 제공 볼륨 이름이 호스트에 연결된 볼륨 목록에 나타납니다.

