---
permalink: config-linux/fc-create-partition-file-task.html 
sidebar: sidebar 
keywords: partitions, file systems, express linux configuration, software configuration, linux host, 
summary: Linux 호스트가 처음 LUN을 검색할 때 새 LUN에 파티션 또는 파일 시스템이 없습니다. LUN을 사용하려면 먼저 포맷해야 합니다. 
---
= 파티션 및 파일 시스템을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 호스트가 처음 LUN을 검색할 때 새 LUN에 파티션이나 파일 시스템이 없으므로 LUN을 사용하려면 먼저 LUN을 포맷해야 합니다. 선택적으로 LUN에 파일 시스템을 생성할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 호스트에서 검색된 LUN입니다.
* 사용 가능한 디스크 목록입니다. 사용 가능한 디스크를 보려면 /dev/mapper 폴더에서 "ls" 명령을 실행합니다.


GPT(GUID Partition Table) 또는 MBR(Master Boot Record)을 사용하여 디스크를 기본 디스크로 초기화할 수 있습니다.

ext4 같은 파일 시스템으로 LUN을 포맷합니다. 일부 응용 프로그램에는 이 단계가 필요하지 않습니다.

.단계
. 'sanlun lun show -p' 명령을 실행하여 매핑된 디스크의 SCSI ID를 검색합니다.
+
SCSI ID는 3부터 시작하는 33자의 16진수 문자열입니다. 사용자 친화적인 이름이 활성화되면 장치 매퍼(Device Mapper)는 SCSI ID가 아닌 mpath로 디스크를 보고합니다.

+
[listing]
----
# sanlun lun show -p

                E-Series Array: ictm1619s01c01-SRP(60080e50002908b40000000054efb9d2)
                   Volume Name:
               Preferred Owner: Controller in Slot B
                 Current Owner: Controller in Slot B
                          Mode: RDAC (Active/Active)
                       UTM LUN: None
                           LUN: 116
                      LUN Size:
                       Product: E-Series
                   Host Device: mpathr(360080e50004300ac000007575568851d)
              Multipath Policy: round-robin 0
            Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host      controller                      controller
path      path       /dev/   host         target
state     type       node    adapter      port
--------- ---------- ------- ------------ ----------------------------------------------
up        secondary  sdcx    host14       A1
up        secondary  sdat    host10       A2
up        secondary  sdbv    host13       B1
----
. Linux OS 릴리스에 적합한 방법에 따라 새 파티션을 만듭니다.
+
일반적으로 디스크 파티션을 식별하는 문자는 SCSI ID(예: 숫자 1 또는 P3)에 추가됩니다.

+
[listing]
----
# parted -a optimal -s -- /dev/mapper/360080e5000321bb8000092b1535f887a mklabel
gpt mkpart primary ext4 0% 100%
----
. 파티션에 파일 시스템을 생성합니다.
+
파일 시스템을 생성하는 방법은 선택한 파일 시스템에 따라 다릅니다.

+
[listing]
----
# mkfs.ext4 /dev/mapper/360080e5000321bb8000092b1535f887a1
----
. 새 파티션을 마운트할 폴더를 생성합니다.
+
[listing]
----
# mkdir /mnt/ext4
----
. 파티션을 마운트합니다.
+
[listing]
----
# mount /dev/mapper/360080e5000321bb8000092b1535f887a1 /mnt/ext4
----

