---
permalink: config-linux/iscsi-configure-host-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 호스트 측에서 iSCSI 네트워킹을 구성합니다. 
---
= 호스트측 네트워킹을 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트측 네트워킹을 구성하려면 몇 가지 단계를 수행해야 합니다.

물리적 경로당 노드 세션 수 설정, 해당 iSCSI 서비스 설정, iSCSI 포트에 대한 네트워크 구성, iSCSI 얼굴 바인딩 생성 및 이니시에이터와 타겟 간의 iSCSI 세션 설정을 통해 호스트 측에서 iSCSI 네트워킹을 구성합니다.

대부분의 경우 받은 편지함 소프트웨어 - iSCSI CNA/NIC용 이니시에이터를 사용할 수 있습니다. 최신 드라이버, 펌웨어 및 BIOS는 다운로드할 필요가 없습니다. 을 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 코드 요구 사항을 결정합니다.

.단계
. /etc/iscsi/iscsid.conf 파일에서 ' node.session.nr_sessions` 변수를 확인하여 물리적 경로당 기본 세션 수를 확인합니다. 필요한 경우 기본 세션 수를 하나의 세션으로 변경합니다.
+
[listing]
----
node.session.nr_sessions = 1
----
. /etc/iscsi/iscsid.conf 파일의 node.session.timeo.replacement_timeout` 변수를 기본값인 120에서 20으로 변경합니다.
+
[listing]
----
node.session.timeo.replacement_timeout=20
----
. "iscsid" 및 "open-) iSCSI" 서비스가 부팅 및 활성화되어 있는지 확인합니다.
+
* Red Hat Enterprise Linux 7 및 8(RHEL 7 및 RHEL 8) *

+
[listing]
----
# systemctl start iscsi
# systemctl start iscsid
# systemctl enable iscsi
# systemctl enable iscsid
----
+
* SUSE Linux Enterprise Server 12 및 15(SLES 12 및 SLES 15) *

+
[listing]
----
# systemctl start iscsid.service
# systemctl enable iscsid.service
----
+
필요한 경우, "iscsiadm" 명령을 실행하기 전에 /etc/iscsi/iscsid.conf에서 node.startup=automatic"을 설정하여 재부팅 후 세션을 유지할 수 있습니다.

. 호스트 IQN 이니시에이터 이름을 가져옵니다. 이 이니시에이터 이름은 호스트를 스토리지에 구성하는 데 사용됩니다.
+
[listing]
----
# cat /etc/iscsi/initiatorname.iscsi
----
. iSCSI 포트에 대한 네트워크 구성:
+

NOTE: 공용 네트워크 포트 외에도 iSCSI 이니시에이터는 별도의 개인 세그먼트 또는 VLAN에 둘 이상의 NIC를 사용해야 합니다.

+
.. '#ifconfig-a' 명령을 사용하여 iSCSI 포트 이름을 확인합니다.
.. iSCSI 이니시에이터 포트의 IP 주소를 설정합니다. 이니시에이터 포트는 iSCSI 타겟 포트와 동일한 서브넷에 있어야 합니다.
+
[listing]
----
# vim /etc/sysconfig/network-scripts/ifcfg-<NIC port>
Edit:
BOOTPROTO=none
ONBOOT=yes
NM_CONTROLLED=no
Add:
IPADDR=192.168.xxx.xxx
NETMASK=255.255.255.0
----
+

NOTE: 두 iSCSI 이니시에이터 포트의 주소를 설정해야 합니다.

.. 네트워크 서비스를 다시 시작합니다.
+
[listing]
----
# systemctl restart network
----
.. Linux 서버가 iSCSI 대상 포트의 ping_all_을 수행할 수 있는지 확인합니다.


. iSCSI iface 바인딩 2개를 생성하여 iSCSI 인터페이스를 구성합니다.
+
[listing]
----
iscsiadm -m iface -I iface0 -o new
iscsiadm -m iface -I iface0 -o update -n iface.net_ifacename -v <NIC port1>
----
+
[listing]
----
iscsiadm -m iface -I iface1 -o new
iscsiadm -m iface -I iface1 -o update -n iface.net_ifacename -v <NIC port2>
----
+

NOTE: 인터페이스를 나열하려면 iscsiadm -m iface를 사용합니다.

. 이니시에이터와 타겟 간의 iSCSI 세션을 설정합니다(총 4개).
+
.. iSCSI 대상을 검색합니다. 다음 단계를 위해 워크시트에 IQN(각 검색과 동일함)을 저장합니다.
+
[listing]
----
iscsiadm -m discovery -t sendtargets -p 192.168.0.1:3260 -I iface0 -P 1
----
+

NOTE: IQN은 다음과 같습니다.

+
[listing]
----
iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
----
.. ifaces를 사용하여 iSCSI 이니시에이터와 iSCSI 타겟 간의 접속을 생성합니다.
+
[listing]
----
iscsiadm -m node -T iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
-p 192.168.0.1:3260 -I iface0 -l
----
.. 호스트에 설정된 iSCSI 세션을 나열합니다.
+
[listing]
----
# iscsiadm -m session
----



