---
permalink: config-linux/iscsi-configure-array-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 어레이 측에서 iSCSI 네트워킹을 구성합니다. 
---
= 스토리지 측 네트워킹 구성
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 시스템 관리자 GUI를 사용하여 어레이 측에서 iSCSI 네트워킹을 구성합니다.

.무엇을 &#8217;필요로 할거야
* 스토리지 어레이 컨트롤러 중 하나의 IP 주소 또는 도메인 이름입니다.
* 스토리지 어레이에 대한 적절한 보안 액세스를 위해 구성된 System Manager GUI, 즉 역할 기반 액세스 제어(RBAC) 또는 LDAP 및 디렉토리 서비스에 대한 암호입니다. 액세스 관리에 대한 자세한 내용은 SANtricity 시스템 관리자 온라인 도움말을 참조하십시오.


이 작업은 System Manager의 하드웨어 페이지에서 iSCSI 포트 구성에 액세스하는 방법을 설명합니다. 시스템 [설정 > iSCSI 포트 구성] 메뉴에서 구성에 액세스할 수도 있습니다.

.단계
. 브라우저에서 '+https://<DomainNameOrIPAddress>+` URL을 입력합니다
+
IPAddress는 스토리지 배열 컨트롤러 중 하나의 주소입니다.

+
구성되지 않은 어레이에서 SANtricity 시스템 관리자를 처음 열면 관리자 암호 설정 프롬프트가 나타납니다. 역할 기반 액세스 관리는 관리자, 지원, 보안 및 모니터링의 네 가지 로컬 역할을 구성합니다. 마지막 세 개의 역할에는 추측할 수 없는 임의의 암호가 있습니다. admin 역할의 암호를 설정한 후 admin 자격 증명을 사용하여 모든 암호를 변경할 수 있습니다. 4개의 로컬 사용자 역할에 대한 자세한 내용은 SANtricity System Manager 사용자 인터페이스에서 제공되는 온라인 도움말을 참조하십시오.

. 관리자 암호 설정 및 암호 확인 필드에 관리자 역할에 대한 System Manager 암호를 입력한 다음 * 암호 설정 * 을 클릭합니다.
+
구성된 풀, 볼륨 그룹, 워크로드 또는 알림이 없는 경우 설정 마법사가 시작됩니다.

. 설정 마법사를 닫습니다.
+
나중에 마법사를 사용하여 추가 설정 작업을 완료합니다.

. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * 쉘프 뒷면 표시 * 를 클릭합니다.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 구성할 iSCSI 포트가 있는 컨트롤러를 클릭합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. iSCSI 포트 구성 * 을 선택합니다.
+
iSCSI 포트 구성 대화 상자가 열립니다.

. 드롭다운 목록에서 구성할 포트를 선택한 후 * 다음 * 을 클릭합니다.
. 구성 포트 설정을 선택한 후 * 다음 * 을 클릭합니다.
+
모든 포트 설정을 보려면 대화 상자 오른쪽에 있는 * 추가 포트 설정 표시 * 링크를 클릭합니다.

+
|===
| 포트 설정 | 설명 


 a| 
이더넷 포트 속도를 구성했습니다
 a| 
원하는 속도를 선택합니다. 드롭다운 목록에 표시되는 옵션은 네트워크에서 지원할 수 있는 최대 속도(예: 10Gbps)에 따라 달라집니다.


NOTE: 컨트롤러에서 옵션으로 제공되는 25GB iSCSI 호스트 인터페이스 카드는 속도를 자동 협상하지 않습니다. 각 포트의 속도를 10Gb 또는 25Gb로 설정해야 합니다. 모든 포트는 동일한 속도로 설정되어야 합니다.



 a| 
IPv4 사용/IPv6 사용
 a| 
IPv4 및 IPv6 네트워크에 대한 지원을 활성화하려면 하나 또는 두 옵션을 모두 선택하십시오.



 a| 
TCP 수신 대기 포트(* 추가 포트 설정 표시 * 를 클릭하여 사용 가능)
 a| 
필요한 경우 새 포트 번호를 입력합니다.

수신 대기 포트는 컨트롤러가 호스트 iSCSI 초기자의 iSCSI 로그인을 수신 대기하기 위해 사용하는 TCP 포트 번호입니다. 기본 수신 대기 포트는 3260입니다. 3260 또는 49152와 65535 사이의 값을 입력해야 합니다.



 a| 
MTU 크기(* 추가 포트 설정 표시 * 를 클릭하여 사용 가능)
 a| 
필요한 경우 MTU(Maximum Transmission Unit)에 대한 새 크기를 바이트 단위로 입력합니다.

기본 MTU(Maximum Transmission Unit) 크기는 프레임당 1,500바이트입니다. 1500에서 9000 사이의 값을 입력해야 합니다.



 a| 
ICMP Ping 응답을 활성화합니다
 a| 
ICMP(Internet Control Message Protocol)를 활성화하려면 이 옵션을 선택합니다. 네트워크로 연결된 컴퓨터의 운영 체제는 이 프로토콜을 사용하여 메시지를 전송합니다. 이러한 ICMP 메시지는 호스트에 연결할 수 있는지 여부와 해당 호스트와 패킷을 주고 받는 데 걸리는 시간을 결정합니다.

|===
+
IPv4 사용 * 을 선택한 경우 * 다음 * 을 클릭하면 IPv4 설정을 선택할 수 있는 대화 상자가 열립니다. IPv6 사용 * 을 선택한 경우 * 다음 * 을 클릭하면 IPv6 설정을 선택할 수 있는 대화 상자가 열립니다. 두 옵션을 모두 선택한 경우 IPv4 설정에 대한 대화 상자가 먼저 열리고 * 다음 * 을 클릭하면 IPv6 설정에 대한 대화 상자가 열립니다.

. IPv4 및/또는 IPv6 설정을 자동 또는 수동으로 구성합니다. 모든 포트 설정을 보려면 대화 상자 오른쪽에 있는 * 추가 설정 표시 * 링크를 클릭합니다.
+
|===
| 포트 설정 | 설명 


 a| 
자동으로 구성을 가져옵니다
 a| 
구성을 자동으로 가져오려면 이 옵션을 선택합니다.



 a| 
수동으로 정적 설정을 지정합니다
 a| 
이 옵션을 선택한 다음 필드에 정적 주소를 입력합니다. IPv4의 경우 네트워크 서브넷 마스크 및 게이트웨이를 포함합니다. IPv6의 경우 라우팅 가능한 IP 주소와 라우터 IP 주소를 포함합니다.

|===
. 마침 * 을 클릭합니다.
. System Manager를 닫습니다.

