---
permalink: config-linux/iscsi-configure-multipath-software-task.html 
sidebar: sidebar 
keywords: multipath software for Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 물리적 경로 중 하나가 중단될 경우 스토리지 어레이에 대한 중복 경로를 제공하는 다중 경로 소프트웨어를 구성합니다. 
---
= E-Series-Linux(iSCSI)에서 다중 경로 소프트웨어 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에 대한 중복 경로를 제공하기 위해 다중 경로 소프트웨어를 구성할 수 있습니다.

.시작하기 전에
시스템에 필요한 패키지를 설치해야 합니다.

* RHEL(Red Hat) 호스트의 경우 "rpm -q device-mapper-multipath"를 실행하여 패키지가 설치되어 있는지 확인합니다.
* SLES 호스트의 경우 'rpm-q multipath-tools'를 실행하여 패키지가 설치되어 있는지 확인합니다.


운영 체제를 아직 설치하지 않은 경우 운영 체제 공급업체에서 제공한 매체를 사용하십시오.

.이 작업에 대해
물리적 경로 중 하나가 중단되는 경우 다중 경로 소프트웨어가 스토리지 배열에 대한 중복 경로를 제공합니다. 다중 경로 소프트웨어는 스토리지에 대한 활성 물리적 경로를 나타내는 단일 가상 장치를 운영 체제에 제공합니다. 또한 다중 경로 소프트웨어는 가상 장치를 업데이트하는 페일오버 프로세스를 관리합니다.

Linux 설치에 DM-MP(Device Mapper MultiPath) 툴을 사용합니다. 기본적으로 DM-MP는 RHEL 및 SLES에서 비활성화됩니다. 호스트에서 DM-MP 구성 요소를 활성화하려면 다음 단계를 수행하십시오.

.단계
. multipath.conf 파일이 아직 생성되지 않은 경우 '#touch/etc/multipath.conf' 명령을 실행합니다.
. multipath.conf 파일을 비워 두고 기본 다중 경로 설정을 사용합니다.
. 다중 경로 서비스를 시작합니다.
+
[listing]
----
# systemctl start multipathd
----
. uname -r 명령을 실행하여 커널 버전을 저장합니다.
+
[listing]
----
# uname -r
3.10.0-327.el7.x86_64
----
+
호스트에 볼륨을 할당할 때 이 정보를 사용합니다.

. 를 활성화합니다 `multipathd` 부팅 시 데몬
+
[listing]
----
systemctl enable multipathd
----
. /boot 디렉토리에서 "initramfs" 이미지 또는 "initrd" 이미지를 재생성합니다.
+
[listing]
----
dracut --force --add multipath
----
. 를 사용합니다 https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-manually.html["호스트를 수동으로 생성합니다"] 호스트가 정의되어 있는지 여부를 확인하는 온라인 도움말의 절차입니다. 각 호스트 유형 설정이 에서 수집한 커널 정보를 기반으로 하는지 확인합니다 <<step4,4단계>>.
+

NOTE: 자동 로드 밸런싱은 커널 3.9 이하를 실행하는 호스트에 매핑된 볼륨에 대해 비활성화됩니다.

. 호스트를 재부팅합니다.

