---
permalink: config-linux/nvme-ib-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: SANtricity System Manager에서 각 호스트를 정의하기 전에 호스트에서 타겟 컨트롤러 포트를 검색한 다음 NVMe 연결을 설정해야 합니다. 
---
= 호스트에서 스토리지를 검색하고 연결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager에서 각 호스트를 정의하기 전에 호스트에서 타겟 컨트롤러 포트를 검색한 다음 NVMe 연결을 설정해야 합니다.

.단계
. 다음 명령을 사용하여 모든 경로에 대해 NVMe-oF 타겟의 사용 가능한 서브시스템을 검색합니다.
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
이 명령에서 target_ip_address는 target 포트의 IP 주소입니다.

+

NOTE: "NVMe 검색" 명령은 호스트 액세스에 관계없이 하위 시스템의 모든 컨트롤러 포트를 검색합니다.

+
[listing]
----
# nvme discover  -t rdma -a 10.10.10.100
 Discovery Log Number of Records 2, Generation counter 0
 =====Discovery Log Entry 0======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  0
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 10.10.10.100
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
=====Discovery Log Entry 1======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  1
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 11.11.11.100
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
----
. 다른 모든 연결에도 1단계를 반복합니다.
. "NVMe connect -t RDMA -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period" 명령을 사용하여 첫 번째 경로에서 검색된 하위 시스템에 연결합니다
+

NOTE: 위의 명령은 재부팅 후에도 유지되지 않습니다. NVMe 연결을 재설정하기 위해서는 재부팅 후 NVMe connect 명령을 실행해야 한다.

+

NOTE: NVMe 연결은 시스템 재부팅 또는 컨트롤러의 연장 기간 동안 유지되지 않습니다.

+

NOTE: 호스트가 액세스할 수 없는 검색된 포트에 대한 연결이 설정되지 않았습니다.

+

NOTE: 이 명령을 사용하여 포트 번호를 지정하면 연결이 실패합니다. 기본 포트는 연결에 대해 설정된 유일한 포트입니다.

+

NOTE: 권장 대기열 길이 설정은 1024입니다. 다음 예제와 같이 ''-Q 1024' 명령줄 옵션을 사용하여 128의 기본 설정을 1024로 재정의합니다.

+

NOTE: 권장 컨트롤러 손실 시간 제한 시간(초)은 60분(3600초)입니다. 다음 예와 같이 '-l 3600' 명령줄 옵션을 사용하여 기본 설정인 600초를 3600초로 재정의합니다.

+
[listing]
----
# nvme connect -t rdma -a 10.10.10.100 -n  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. 현재 연결된 NVMe 장치의 목록을 보려면 "NVMe list" 명령을 사용하십시오. 아래 예에서는 nvme0n1입니다.
+
[listing]
----
 # nvme list

 Node          SN            Model             Namespace
 -------------------------------------------------------
 /dev/nvme0n1  021648023161  NetApp E-Series      1
----
+
[listing]
----
Usage                 Format           FW Rev
--------------------------------------------------------------
5.37 GB /5.37 GB      512 B + 0 B      0842XXXX
----
. 두 번째 경로에서 검색된 하위 시스템에 연결합니다.
+
[listing]
----
  # nvme connect -t rdma -a 11.11.11.100 -n  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. Linux 'lsblk' 및 'grep' 명령을 사용하여 각 블록 디바이스에 대한 추가 정보를 표시합니다.
+
[listing]
----
 # lsblk | grep nvme

 nvme0n1    259:0    0     5G  0 disk
 nvme1n1    259:0    0     5G  0 disk
----
. 현재 연결된 NVMe 장치의 새 목록을 보려면 "NVMe list" 명령을 사용하십시오. 아래 예에서는 nvme0n1, nvme0n1입니다.
+
[listing]
----
 # nvme list
 Node          SN            Model                   Namespace
 -------------------------------------------------------------
 /dev/nvme0n1  021648023161  NetApp E-Series          1
 /dev/nvme1n1  021648023161  NetApp E-Series          1
----
+
[listing]
----
Usage                 Format           FW Rev
--------------------------------------------------------------
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
----

