---
permalink: config-linux/nvme-fc-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: '안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.' 
---
= Linux 지원을 확인하고 제한 사항을 검토합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
첫 번째 단계에서는 Linux 구성이 지원되는지 확인하고 컨트롤러, 호스트 및 복구 제한도 검토해야 합니다.



== Linux 구성이 지원되는지 확인합니다

안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.

.단계
. 로 이동합니다 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 솔루션 검색 * 타일을 클릭합니다.
. 메뉴: 프로토콜 [SAN 호스트] 영역에서 * E-Series SAN 호스트 * 옆에 있는 * 추가 * 버튼을 클릭합니다.
. 검색 조건 구체화 보기 * 를 클릭합니다.
+
검색 조건 구체화 섹션이 표시됩니다. 이 섹션에서는 적용되는 프로토콜과 운영 체제, NetApp OS 및 호스트 다중 경로 드라이버와 같은 구성의 다른 기준을 선택할 수 있습니다.

. 구성에 대해 알고 있는 기준을 선택한 다음 어떤 호환 구성 요소가 적용되는지 확인합니다.
. 필요한 경우 도구에 규정된 운영 체제 및 프로토콜을 업데이트합니다.
+
선택한 구성에 대한 자세한 내용은 오른쪽 페이지 화살표를 클릭하여 지원되는 구성 보기 페이지에서 액세스할 수 있습니다.





== NVMe over FC의 제한 사항을 검토하십시오

NVMe over Fibre Channel을 사용하기 전에 컨트롤러, 호스트 및 복구 제한을 검토하십시오. 모든 제한 사항에 대한 최신 목록은 를 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].



=== 컨트롤러 제한

* NVMe over Fibre Channel은 EF300, EF600, EF570, E5700 컨트롤러에 대해 구성할 수 있습니다. 컨트롤러에 쿼드 32GB 호스트 포트가 있어야 합니다.
* 이 프로토콜은 32GB 이상의 물리적 메모리를 갖춘 EF300, EF600, EF570 또는 E5700 컨트롤러에만 사용할 수 있습니다. 일상 작업을 시작하는 동안 컨트롤러에 대한 최소 메모리 요구 사항이 충족되지 않으면 문제를 진단하는 데 도움이 되는 메시지가 표시됩니다.
* 단일 컨트롤러 구성은 지원되지 않습니다.
* 유일하게 지원되는 HIC(호스트 인터페이스 카드)는 4중 32Gb 파이버 채널 HIC입니다.




=== 호스트, 호스트 프로토콜 및 호스트 운영 체제 제한

전체 요구 사항 목록은 를 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].



=== 스토리지 및 재해 복구 제한 사항

* 비동기식 및 동기식 미러링은 지원되지 않습니다.
* 씬 프로비저닝(씬 볼륨 생성)은 지원되지 않습니다.

