---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: '안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.' 
---
= Linux 지원을 확인하고 제한 사항을 검토합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
첫 번째 단계에서는 Linux 구성이 지원되는지 확인하고 컨트롤러, 스위치, 호스트 및 복구 제한도 검토해야 합니다.



== Linux 구성이 지원되는지 확인합니다

안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.

.단계
. 로 이동합니다 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 솔루션 검색 * 타일을 클릭합니다.
. 메뉴: 프로토콜 [SAN 호스트] 영역에서 * E-Series SAN 호스트 * 옆에 있는 * 추가 * 버튼을 클릭합니다.
. 검색 조건 구체화 보기 * 를 클릭합니다.
+
검색 조건 구체화 섹션이 표시됩니다. 이 섹션에서는 적용되는 프로토콜과 운영 체제, NetApp OS 및 호스트 다중 경로 드라이버와 같은 구성의 다른 기준을 선택할 수 있습니다.

. 구성에 대해 알고 있는 기준을 선택한 다음 어떤 호환 구성 요소가 적용되는지 확인합니다.
. 필요한 경우 도구에 규정된 운영 체제 및 프로토콜을 업데이트합니다.
+
선택한 구성에 대한 자세한 내용은 오른쪽 페이지 화살표를 클릭하여 지원되는 구성 보기 페이지에서 액세스할 수 있습니다.





== NVMe over RoCE 제한 확인

NVMe over RoCE를 사용하기 전에 을(를) 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 최신 컨트롤러, 호스트 및 복구 제한 사항을 검토합니다.



=== 스위치 제한


NOTE: * 데이터 손실 위험. * NVMe over RoCE 환경에서 데이터 손실 위험을 제거하려면 스위치에서 우선순위 흐름 제어 또는 글로벌 일시 중지 제어를 활성화해야 합니다.



=== 스토리지 및 재해 복구 제한 사항

* 비동기식 및 동기식 미러링은 지원되지 않습니다.
* 씬 프로비저닝(씬 볼륨 생성)은 지원되지 않습니다.

