---
permalink: config-linux/nvme-roce-define-host-task.html 
sidebar: sidebar 
keywords: define Linux host, configure linux host, express linux configuration, linux host, 
summary: SANtricity 시스템 관리자를 사용하여 스토리지 배열에 데이터를 전송하는 호스트를 정의합니다. 호스트 정의는 스토리지 배열에 연결된 호스트를 알려 주는 단계 중 하나이며 볼륨에 대한 I/O 액세스를 허용하는 데 필요한 단계 중 하나입니다. 
---
= SANtricity System Manager-Linux(NVMe over RoCE)를 사용하여 호스트 생성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 시스템 관리자를 사용하여 스토리지 배열에 데이터를 전송하는 호스트를 정의합니다. 호스트 정의는 스토리지 배열에 연결된 호스트를 알려 주는 단계 중 하나이며 볼륨에 대한 I/O 액세스를 허용하는 데 필요한 단계 중 하나입니다.

.이 작업에 대해
호스트를 정의할 때 다음 지침을 염두에 두십시오.

* 호스트와 연결된 호스트 식별자 포트를 정의해야 합니다.
* 호스트에 할당된 시스템 이름과 동일한 이름을 제공해야 합니다.
* 선택한 이름이 이미 사용 중인 경우에는 이 작업이 성공하지 않습니다.
* 이름의 길이는 30자를 초과할 수 없습니다.


.단계
. 스토리지 [호스트] 메뉴를 선택합니다.
. MENU: Create [Host] 를 클릭합니다.
+
Create Host 대화 상자가 나타납니다.

. 필요에 따라 호스트 설정을 선택합니다.
+
|===
| 설정 | 설명 


 a| 
이름
 a| 
새 호스트의 이름을 입력합니다.



 a| 
호스트 운영 체제 유형입니다
 a| 
드롭다운 목록에서 다음 옵션 중 하나를 선택합니다.

** SANtricity 11.60 이상용 * Linux *
** * Linux DM-MP(커널 3.10 이상) * - SANtricity 11.60 이전 버전




 a| 
호스트 인터페이스 유형입니다
 a| 
사용할 호스트 인터페이스 유형을 선택합니다. 구성한 어레이에 사용 가능한 호스트 인터페이스 유형이 하나만 있는 경우 이 설정을 선택할 수 없습니다.



 a| 
호스트 포트
 a| 
다음 중 하나를 수행합니다.

** * I/O 인터페이스 * 를 선택합니다
+
호스트 포트가 로그인한 경우 목록에서 호스트 포트 식별자를 선택할 수 있습니다. 이 방법이 권장되는 방법입니다.

** * 수동 추가 *
+
호스트 포트가 로그인하지 않은 경우 호스트에서 /etc/NVMe/hostnqn을 보고 hostnqn 식별자를 찾아 호스트 정의에 연결합니다.

+
호스트 포트 식별자를 수동으로 입력하거나 /etc/NVMe/hostnqn 파일(한 번에 하나씩)에서 * 호스트 포트 * 필드로 복사/붙여넣기할 수 있습니다.

+
호스트와 연결하려면 한 번에 하나의 호스트 포트 식별자를 추가해야 하지만 호스트와 연결된 식별자를 계속 선택할 수 있습니다. 각 식별자는 * 호스트 포트 * 필드에 표시됩니다. 필요한 경우 옆에 있는 * X * 를 선택하여 식별자를 제거할 수도 있습니다.



|===
. Create * 를 클릭합니다.


.결과
호스트가 성공적으로 생성되면 SANtricity System Manager는 호스트에 대해 구성된 각 호스트 포트에 대한 기본 이름을 생성합니다.

기본 별칭은 "<Hostname_Port Number>"입니다. 예를 들어, 호스트 IPT에 대해 생성된 첫 번째 포트의 기본 별칭은 IPT_1입니다.
