---
permalink: config-linux/nvme-roce-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: SANtricity System Manager에서 각 호스트를 정의하기 전에 호스트에서 타겟 컨트롤러 포트를 검색한 다음 NVMe 연결을 설정해야 합니다. 
---
= 호스트에서 스토리지를 검색하고 연결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager에서 각 호스트를 정의하기 전에 호스트에서 타겟 컨트롤러 포트를 검색한 다음 NVMe 연결을 설정해야 합니다.

.단계
. 다음 명령을 사용하여 모든 경로에 대해 NVMe-oF 타겟의 사용 가능한 서브시스템을 검색합니다.
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
이 명령에서 target_ip_address는 target 포트의 IP 주소입니다.

+

NOTE: "NVMe 검색" 명령은 호스트 액세스에 관계없이 하위 시스템의 모든 컨트롤러 포트를 검색합니다.

+
[listing]
----
# nvme discover -t rdma -a 192.168.1.77
Discovery Log Number of Records 2, Generation counter 0
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.1.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.2.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
----
. 다른 모든 연결에도 1단계를 반복합니다.
. "NVMe connect -t RDMA -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period" 명령을 사용하여 첫 번째 경로에서 검색된 하위 시스템에 연결합니다
+

NOTE: 위에 나열된 명령은 재부팅 후에도 유지되지 않습니다. NVMe 연결을 재설정하기 위해서는 재부팅 후 NVMe connect 명령을 실행해야 한다.

+

NOTE: 호스트가 액세스할 수 없는 검색된 포트에 대한 연결이 설정되지 않았습니다.

+

NOTE: 이 명령을 사용하여 포트 번호를 지정하면 연결이 실패합니다. 기본 포트는 연결에 대해 설정된 유일한 포트입니다.

+

NOTE: 권장 대기열 길이 설정은 1024입니다. 다음 예제와 같이 ''-Q 1024' 명령줄 옵션을 사용하여 128의 기본 설정을 1024로 재정의합니다.

+

NOTE: 권장 컨트롤러 손실 시간 제한 시간(초)은 60분(3600초)입니다. 다음 예제와 같이 '-l 3600' 명령줄 옵션을 사용하여 기본 설정인 600초를 3600초로 재정의합니다.

+
[listing]
----
# nvme connect -t rdma -a 192.168.1.77 -n nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
# nvme connect -t rdma -a 192.168.2.77 -n nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
----
. 3단계를 반복하여 검색된 하위 시스템을 두 번째 경로에 연결합니다.

