---
permalink: config-linux/sas-configure-ip-address-dhcp-task.html 
sidebar: sidebar 
keywords: IP address, DHCP, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'DHCP(Dynamic Host Configuration Protocol)\ 를 사용하여 IP 주소를 제공합니다.' 
---
= DHCP를 사용하여 IP 주소를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 스테이션과 스토리지 어레이 간의 통신을 구성하려면 DHCP(Dynamic Host Configuration Protocol)를 사용하여 IP 주소를 제공합니다.

.시작하기 전에
다음 사항을 확인하십시오.

* 스토리지 관리 포트와 동일한 서브넷에 설치 및 구성된 DHCP 서버입니다.


.이 작업에 대해
각 스토리지 어레이에는 1개의 컨트롤러(단일) 또는 2개의 컨트롤러(이중)가 있으며, 각 컨트롤러에는 2개의 스토리지 관리 포트가 있습니다. 각 관리 포트에는 IP 주소가 할당됩니다.

다음 지침은 두 개의 컨트롤러가 있는 스토리지 배열(이중 구성)을 나타냅니다.

.단계
. 아직 연결하지 않은 경우 이더넷 케이블을 관리 스테이션과 각 컨트롤러(A 및 B)의 관리 포트 1에 연결하십시오.
+
DHCP 서버는 각 컨트롤러의 포트 1에 IP 주소를 할당합니다.

+

NOTE: 두 컨트롤러 중 하나에서 관리 포트 2를 사용하지 마십시오. 포트 2는 NetApp 기술 담당자가 사용하도록 예약되어 있습니다.

+

NOTE: 이더넷 케이블을 분리했다가 다시 연결하거나 스토리지 배열의 전원을 껐다가 켜면 DHCP는 IP 주소를 다시 할당합니다. 이 프로세스는 고정 IP 주소가 구성될 때까지 수행됩니다. 케이블을 분리하거나 배열의 전원을 껐다가 켜는 것을 피하는 것이 좋습니다.

+
스토리지 배열이 30초 이내에 DHCP 할당 IP 주소를 가져올 수 없는 경우, 다음의 기본 IP 주소가 설정됩니다:

+
** 컨트롤러 A, 포트 1: 169.254.128.101
** 컨트롤러 B, 포트 1: 169.254.128.102
** 서브넷 마스크: 255.255.0.0


. 각 컨트롤러 뒷면에서 MAC 주소 레이블을 찾은 다음 네트워크 관리자에게 각 컨트롤러의 포트 1에 대한 MAC 주소를 제공합니다.
+
네트워크 관리자는 각 컨트롤러의 IP 주소를 확인하기 위해 MAC 주소가 필요합니다. 브라우저를 통해 스토리지 시스템에 연결하려면 IP 주소가 필요합니다.


