---
permalink: maintenance-e2800/batteries-prepare-replace-task.html 
sidebar: sidebar 
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries 
summary: 양면 또는 단면 인쇄의 적절한 단계를 따라 E2800 배터리 교체를 준비합니다. 
---
= 배터리 교체 준비 - E2800
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
배터리 교체 준비 단계는 이중 구성(컨트롤러 2개) 또는 단일 구성(컨트롤러 1개)이 있는지 여부에 따라 다릅니다.

* 양면 인쇄 구성은 를 참조하십시오 <<컨트롤러를 오프라인(이중) 상태로 전환>>.
* 단면 구성은 를 참조하십시오 <<컨트롤러 쉘프 전원 끄기(단일)>>.


.시작하기 전에
* 사용 중인 볼륨이 없거나 이러한 볼륨을 사용하는 모든 호스트에 다중 경로 드라이버가 설치되어 있는지 확인합니다.
* 를 검토합니다 link:batteries-overview-requirements-concept.html["E2800 배터리 교체 요구 사항"].




== 컨트롤러를 오프라인(이중) 상태로 전환

이중 구성이 있는 경우 장애가 발생한 배터리를 안전하게 제거할 수 있도록 영향을 받는 컨트롤러를 오프라인으로 전환해야 합니다. 오프라인 상태로 전환하지 않는 컨트롤러는 온라인 상태여야 합니다(최적 상태).


NOTE: 스토리지 배열에 두 개의 컨트롤러가 있는 경우에만 이 작업을 수행합니다(이중 구성).

.단계
. SANtricity 시스템 관리자에서 Recovery Guru의 세부 정보를 검토하여 배터리에 문제가 있는지 확인하고 다른 항목을 먼저 해결하지 않도록 합니다.
. Recovery Guru의 세부 정보 영역에서 교체할 배터리를 확인합니다.
. SANtricity System Manager를 사용하여 스토리지 시스템의 구성 데이터베이스를 백업합니다.
+
컨트롤러를 제거할 때 문제가 발생하면 저장된 파일을 사용하여 구성을 복원할 수 있습니다. 시스템에서 RAID 구성 데이터베이스의 현재 상태를 저장합니다. 이 데이터베이스는 볼륨 그룹 및 컨트롤러의 디스크 풀에 대한 모든 데이터를 포함합니다.

+
** System Manager에서:
+
... 지원 [지원 센터 > 진단] 메뉴를 선택합니다.
... 구성 데이터 수집 * 을 선택합니다.
... 수집 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 * configurationData - <arrayName> - <DateTime>.7z * 라는 이름으로 저장됩니다.



** 또는 다음 CLI 명령을 사용하여 구성 데이터베이스를 백업할 수도 있습니다.
+
Save storageArray dbmDatabase sourceLocation = 온보드 contentType = 모든 파일 = "파일 이름";"



. SANtricity 시스템 관리자를 사용하여 스토리지 어레이에 대한 지원 데이터를 수집합니다.
+
컨트롤러를 제거할 때 문제가 발생하면 저장된 파일을 사용하여 문제를 해결할 수 있습니다. 시스템은 스토리지 어레이에 대한 인벤토리, 상태 및 성능 데이터를 단일 파일로 저장합니다.

+
.. 지원 [지원 센터 > 진단] 메뉴를 선택합니다.
.. 지원 데이터 수집 * 을 선택합니다.
.. 수집 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 * support-data.7z * 라는 이름으로 저장됩니다.



. 컨트롤러가 아직 오프라인 상태가 아닌 경우 SANtricity 시스템 관리자를 사용하여 오프라인 상태로 전환합니다.
+
** SANtricity 시스템 관리자:
+
... 하드웨어 * 를 선택합니다.
... 그래픽에 드라이브가 표시되면 * 쉘프 뒷면 표시 * 를 선택하여 컨트롤러를 표시합니다.
... 오프라인 상태로 설정할 컨트롤러를 선택합니다.
... 상황에 맞는 메뉴에서 * 오프라인 상태로 전환 * 을 선택하고 작업을 수행할지 확인합니다.
+

NOTE: 오프라인으로 전환하려고 하는 컨트롤러를 사용하여 SANtricity 시스템 관리자에 액세스하는 경우 SANtricity 시스템 관리자를 사용할 수 없음 메시지가 표시됩니다. 다른 컨트롤러를 사용하여 SANtricity 시스템 관리자에 자동으로 액세스하려면 * 대체 네트워크 연결 * 을 선택합니다.



** 또는 다음 CLI 명령을 사용하여 컨트롤러를 오프라인으로 전환할 수 있습니다.
+
컨트롤러 A: *'et controller[a] availability=offline'의 경우

+
* 컨트롤러 B: *'et controller[b] availability=offline'의 경우



. SANtricity 시스템 관리자가 컨트롤러의 상태를 오프라인으로 업데이트할 때까지 기다립니다.
. 로 이동합니다 link:batteries-remove-controller-canister-task.html["E2800 컨트롤러 캐니스터를 제거합니다"].
+

CAUTION: 상태가 업데이트되기 전에는 다른 작업을 시작하지 마십시오.





== 컨트롤러 쉘프 전원 끄기(단일)

단일 구성을 사용하는 경우 장애가 발생한 배터리를 안전하게 제거할 수 있도록 컨트롤러 쉘프의 전원을 끕니다.


NOTE: 스토리지 어레이에 하나의 컨트롤러(단일 구성)가 있는 경우에만 이 작업을 수행합니다.

.단계
. SANtricity System Manager를 사용하여 스토리지 시스템의 구성 데이터베이스를 백업합니다.
+
컨트롤러를 제거할 때 문제가 발생하면 저장된 파일을 사용하여 구성을 복원할 수 있습니다. 시스템에서 RAID 구성 데이터베이스의 현재 상태를 저장합니다. 이 데이터베이스는 볼륨 그룹 및 컨트롤러의 디스크 풀에 대한 모든 데이터를 포함합니다.

+
** System Manager에서:
+
... 지원 [지원 센터 > 진단] 메뉴를 선택합니다.
... 구성 데이터 수집 * 을 선택합니다.
... 수집 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 * configurationData - <arrayName> - <DateTime>.7z * 라는 이름으로 저장됩니다.



** 또는 다음 CLI 명령을 사용하여 구성 데이터베이스를 백업할 수도 있습니다.
+
Save storageArray dbmDatabase sourceLocation = 온보드 contentType = 모든 파일 = "파일 이름";"



. SANtricity 시스템 관리자를 사용하여 스토리지 어레이에 대한 지원 데이터를 수집합니다.
+
컨트롤러를 제거할 때 문제가 발생하면 저장된 파일을 사용하여 문제를 해결할 수 있습니다. 시스템은 스토리지 어레이에 대한 인벤토리, 상태 및 성능 데이터를 단일 파일로 저장합니다.

+
.. 지원 [지원 센터 > 진단] 메뉴를 선택합니다.
.. 지원 데이터 수집 * 을 선택합니다.
.. 수집 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 * support-data.7z * 라는 이름으로 저장됩니다.



. 스토리지 시스템과 접속된 모든 호스트 간에 입출력 작업이 발생하지 않도록 합니다. 예를 들어, 다음 단계를 수행할 수 있습니다.
+
.. 스토리지에서 호스트로 매핑된 LUN이 포함된 모든 프로세스를 중지합니다.
.. 스토리지에서 호스트로 매핑된 LUN에 데이터를 쓰는 애플리케이션이 없는지 확인합니다.
.. 스토리지의 볼륨과 연결된 모든 파일 시스템을 마운트 해제합니다.
+

NOTE: 호스트 I/O 작업을 중지하는 정확한 단계는 호스트 운영 체제 및 구성에 따라 달라지며, 이 지침은 다루지 않습니다. 사용자 환경에서 호스트 I/O 작업을 중지하는 방법을 모르는 경우 호스트를 종료하는 것이 좋습니다.

+

CAUTION: * 데이터 손실 가능성 * -- I/O 작업이 진행되는 동안 이 절차를 계속하면 데이터가 손실될 수 있습니다.



. 캐시 메모리의 데이터가 드라이브에 기록될 때까지 기다립니다.
+
캐시 데이터를 드라이브에 기록해야 하는 경우 컨트롤러 후면의 녹색 캐시 활성 LED가 켜집니다. 이 LED가 꺼질 때까지 기다려야 합니다.

. SANtricity 시스템 관리자의 홈 페이지에서 * 진행 중인 작업 보기 * 를 선택합니다.
. 다음 단계를 계속하기 전에 모든 작업이 완료되었는지 확인하십시오.
. 컨트롤러 쉘프의 두 전원 스위치를 끕니다.
. 컨트롤러 쉘프의 모든 LED가 꺼질 때까지 기다립니다.
. 로 이동합니다 link:batteries-remove-controller-canister-task.html["E2800 컨트롤러 캐니스터를 제거합니다"].

