---
permalink: maintenance-e2800/batteries-overview-requirements-concept.html 
sidebar: sidebar 
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries 
summary: E2800 배터리 교체 요구 사항 및 고려 사항을 검토합니다. 
---
= E2800 배터리 교체 요구 사항
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800 배터리를 교체하기 전에 요구 사항과 고려 사항을 검토하십시오.

각 컨트롤러 캐니스터에는 AC 전원에 장애가 발생할 경우 캐싱된 데이터를 보관하는 배터리가 포함되어 있습니다.



== Recovery Guru에서 알려줍니다

SANtricity 시스템 관리자의 Recovery Guru에서 다음 상태 중 하나를 보고하는 경우 영향을 받는 배터리를 교체해야 합니다.

* 배터리 고장
* 배터리 교체가 필요합니다


SANtricity 시스템 관리자에서 Recovery Guru의 세부 정보를 검토하여 배터리에 문제가 있는지 확인하고 다른 항목을 먼저 해결하지 않도록 합니다.



== 절차 개요

데이터를 보호하려면 장애가 발생한 배터리를 가능한 한 빨리 교체해야 합니다.

다음은 E2800 컨트롤러에서 배터리를 교체하는 데 필요한 단계를 간략히 설명합니다.

. 양면 또는 단면 구성의 적절한 단계에 따라 교체를 준비합니다.
. 컨트롤러 캐니스터를 제거합니다.
. 결함이 있는 배터리를 분리합니다.
. 새 배터리를 장착하십시오.
. 컨트롤러 캐니스터를 다시 설치합니다.
. 양면 또는 단면 구성의 적절한 단계에 따라 교체를 완료합니다.




== 이중 또는 단일 구성

배터리 교체 단계는 다음과 같이 1개 또는 2개의 컨트롤러가 있는지 여부에 따라 다릅니다.

|===
| 스토리지 어레이에 다음 기능이 있는 경우: | 필수 사항... 


 a| 
컨트롤러 2개(이중)
 a| 
. 컨트롤러를 오프라인으로 전환합니다.
. 컨트롤러 캐니스터를 제거합니다.
. 배터리를 교체합니다.
. 컨트롤러 캐니스터를 교체합니다.
. 컨트롤러를 온라인 상태로 전환합니다.




 a| 
단일 컨트롤러(단일)
 a| 
. 호스트 I/O 작업을 중지합니다.
. 컨트롤러 쉘프의 전원을 끕니다.
. 컨트롤러 캐니스터를 제거합니다.
. 배터리를 교체합니다.
. 컨트롤러 캐니스터를 교체합니다.
. 컨트롤러 쉘프에 전원을 공급합니다.


|===


== 배터리 교체 요구 사항

고장난 배터리를 교체할 계획이라면 다음이 필요합니다.

* 교체용 배터리
* ESD 밴드이거나 다른 정전기 방지 예방 조치를 취했습니다.
* 컨트롤러 캐니스터에 연결된 각 케이블을 식별하는 레이블입니다.
* 컨트롤러의 SANtricity 시스템 관리자에 액세스할 수 있는 브라우저가 있는 관리 스테이션. System Manager 인터페이스를 열려면 브라우저에서 컨트롤러의 도메인 이름 또는 IP 주소를 가리킵니다.

