---
permalink: maintenance-e2800/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E2800 replace HIC, E2800 replace host interface card, replacing E2800 HIC, E2800 replace HIC, adding E2800 HIC, upgrading E2800 HIC, E2800, E-Series, eseries 
summary: E2800 HIC 교체에 대한 요구사항을 검토합니다. 
---
= E2800 HIC 교체 요구 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800에서 HIC(호스트 인터페이스 카드)를 추가, 업그레이드 또는 교체하기 전에 요구사항 및 고려 사항을 검토하십시오.



== 절차 개요

HIC 교체 단계는 다음과 같이 컨트롤러 1~2개가 있는지 여부에 따라 다릅니다.

|===
| 스토리지 어레이에 다음 기능이 있는 경우: | 필수 사항... 


 a| 
컨트롤러 1개(E2812 또는 E2824 단일)
 a| 
. 호스트 I/O 작업을 중지합니다
. 컨트롤러 쉘프의 전원을 끕니다
. 컨트롤러 캐니스터를 제거합니다
. 배터리를 교체합니다
. 컨트롤러 캐니스터를 교체합니다
. 컨트롤러 쉘프에 전원을 공급합니다




 a| 
컨트롤러 2개(E2860, E2812 또는 E2824 이중)
 a| 
. 컨트롤러를 오프라인으로 전환합니다
. 컨트롤러 캐니스터를 제거합니다
. 배터리를 교체합니다
. 컨트롤러 캐니스터를 교체합니다
. 컨트롤러를 온라인 상태로 전환합니다


|===


== HIC 추가, 업그레이드 또는 교체 요구사항

HIC(호스트 인터페이스 카드)를 추가, 업그레이드 또는 교체하려는 경우 다음 요구사항을 염두에 두고 있어야 합니다.

* 이 절차에 대한 가동 중지 시간 유지 관리 기간을 예약했습니다. HIC를 설치할 때는 전원을 꺼야 하므로 이 절차를 성공적으로 완료할 때까지 스토리지 배열의 데이터에 액세스할 수 없습니다. (이중 구성에서는 두 컨트롤러가 전원을 켤 때 동일한 HIC 구성을 가져야 하기 때문입니다.)
* 스토리지 어레이에 하나 또는 두 개의 컨트롤러가 있는지 여부에 따라 하나 또는 두 개의 HIC가 있습니다. HIC는 컨트롤러와 호환되어야 합니다.
+
이중 구성(컨트롤러 2개)이 있는 경우 두 컨트롤러 캐니스터에 설치된 HIC는 동일해야 합니다. 일치하지 않는 HIC가 있으면 온라인 상태로 전환할 때 교체 HIC가 있는 컨트롤러가 잠깁니다.

* 새 호스트 포트를 연결하는 데 필요한 모든 케이블, 트랜시버, 스위치 및 HBA(호스트 버스 어댑터)가 있습니다.
+
호환 하드웨어에 대한 자세한 내용은 를 참조하십시오 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성 매트릭스"^] 또는 을 누릅니다 http://hwu.netapp.com/home.aspx["NetApp Hardware Universe를 참조하십시오"^].

* ESD 밴드를 가지고 있거나 다른 정전기 방지 예방 조치를 취했습니다.
* 1 십자 드라이버가 있습니다.
* 컨트롤러 캐니스터에 연결된 각 케이블을 식별하는 라벨이 있습니다.
* 컨트롤러의 SANtricity 시스템 관리자에 액세스할 수 있는 브라우저가 있는 관리 스테이션이 있습니다. System Manager 인터페이스를 열려면 브라우저에서 컨트롤러의 도메인 이름 또는 IP 주소를 가리킵니다.

