---
permalink: maintenance-e2800/index.html 
sidebar: sidebar 
keywords: E2800 maintenance, E2800 repair, replace E2800 components, replacing E2800 components, 
summary: E2800 구성 요소에 대한 유지 관리를 수행합니다. 
---
= 하드웨어-E2800 유지 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어에 대한 유지 관리 절차를 수행해야 할 수도 있습니다. E2800 시스템 구성 요소 유지 관리에 대한 절차는 이 섹션에 나와 있습니다.

이 섹션의 절차는 E2800 시스템이 E-Series 환경에 이미 구축되었다고 가정합니다.



== 시스템 구성 요소

E2800 스토리지 시스템의 경우, 다음 구성 요소에 대한 유지보수 절차를 수행할 수 있습니다.

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/batteries-overview-requirements-concept.html["배터리"]
 a| 
각 컨트롤러 캐니스터에는 AC 전원에 장애가 발생할 경우 캐싱된 데이터를 보관하는 배터리가 포함되어 있습니다.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/controllers-overview-supertask-concept.html["컨트롤러"]
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/canisters-overview-supertask-concept.html["캐니스터"]
 a| 
캐니스터는 3가지 유형, 즉 12-드라이브 또는 24-드라이브 컨트롤러 쉘프 또는 드라이브 쉘프에서 이중 전원을 공급하고 적절한 냉각 기능을 제공하는 전원 팬 캐니스터, 60-드라이브 컨트롤러 쉘프 또는 드라이브 쉘프의 전원 중복에 사용되는 전원 캐니스터, 60-드라이브 컨트롤러 쉘프 또는 드라이브 쉘프를 냉각하는 데 사용되는 팬 캐니스터를 지원합니다.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/drives-overview-supertask-concept.html["드라이브"]
 a| 
드라이브는 물리적 데이터 저장 매체를 제공하는 전자기 기계 장치입니다.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/hics-overview-supertask-concept.html["호스트 인터페이스 카드(HIC)"]
 a| 
HIC(호스트 인터페이스 카드)는 컨트롤러 캐니스터 내에 선택적으로 설치할 수 있습니다. E2800 컨트롤러에는 컨트롤러 카드 자체에 내장 호스트 포트와 HIC 옵션 중 호스트 포트가 포함되어 있습니다. 컨트롤러에 내장된 호스트 포트를 베이스보드 호스트 포트라고 합니다. HIC에 내장된 호스트 포트를 HIC 포트라고 합니다.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/hpp-overview-supertask-concept.html["호스트 포트 프로토콜입니다"]
 a| 
호환성과 통신을 설정할 수 있도록 호스트의 프로토콜을 다른 프로토콜로 변환할 수 있습니다.

|===