---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: SANtricity OS의 새로운 기능 
---
= SANtricity OS의 새로운 기능
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에서는 EF300, EF600, E2800/EF280 및 E5700/EF570 컨트롤러의 내장 관리를 위한 SANtricity OS 11.7의 새로운 기능에 대해 설명합니다.



== 버전 11.74의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
FIPS 140-3을 지원합니다
 a| 
이제 SAS 및 NVMe 기반 SSD의 특정 드라이브에서 FIPS 140-3이 지원됩니다. 드라이브가 모든 NVMe 기반이거나 모든 SAS 기반인 경우 FIPS 140-3단계 SSD 드라이브는 FIPS 140-2 레벨 SSD 드라이브와 함께 존재할 수 있습니다. 볼륨 그룹 및 디스크 풀에서 이러한 레벨을 혼합하여 사용할 경우 그룹 또는 풀이 낮은 보안 수준(140-2)으로 작동할 수 있습니다.



 a| 
MFA 및 SSH 지원
 a| 
SANtricity 버전 11.74 이상의 경우 원격 로그인 기능을 사용하면 사용자가 SSH 키 및/또는 SSH 암호를 입력하도록 요구하여 MFA(Multifactor Authorization)를 구성할 수 있습니다. 하드웨어 섹션의 메뉴 옵션이 * 원격 로그인 변경 * 에서 * 원격 로그인 구성(SSH) * 으로 변경되었습니다.



 a| 
액세스 토큰
 a| 
이 릴리스는 액세스 토큰을 생성하기 위한 새로운 기능을 포함합니다. 이러한 토큰을 사용하면 사용자 이름과 암호를 노출하지 않고 REST API 또는 CLI(Command Line Interface)로 인증할 수 있습니다. 이 기능은 액세스 관리 섹션에서 제공됩니다.

|===


== 버전 11.73의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
리소스 프로비저닝 및 DULBE 지원
 a| 
리소스 프로비저닝 기능 및 DULBE 드라이브 기능은 현재 이 릴리즈에서 완벽하게 지원됩니다. 리소스 프로비저닝된 볼륨에서 호스트 관련 UNMAP을 더 광범위하게 사용할 수 있도록 지원합니다.



 a| 
EF600 SAS(512e) 확장
 a| 
이 릴리즈에서는 EF600 스토리지 시스템의 SAS-3 엔클로저로의 확장을 지원합니다. 이 확장을 통해 4KiB 블록 NVMe SSD는 512e SAS SSD 및 HDD와 공존할 수 있습니다. 하지만 블록 크기가 다른 드라이브는 동일한 풀 또는 볼륨 그룹에서 구성할 수 없습니다.



 a| 
QLC SSD 지원
 a| 
이 릴리즈는 드라이브 펌웨어에 ONTAP 기능이 설정되어 있지만 전체 E-Series 관련 기능 세트가 없는 최신 세대 QLC SSD를 지원합니다. QLC 드라이브(NVMe만 해당)는 비용이 저렴하지만 쓰기 성능이 낮고 내구성 등급이 낮기 때문에 쓰기 집약적인 워크로드에 사용하면 안 됩니다.



 a| 
TLS 1.3 지원
 a| 
TLS 1.3은 이제 임베디드 관리에 지원됩니다. 이 지원은 System Manager 및 Embedded Web Services에 적용되며, 이를 활성화 또는 비활성화할 수 있습니다. (TLS 1.3 지원은 웹 서비스 프록시 및 Unified Manager의 이전 릴리스에 추가되었습니다.)



 a| 
최소 8 드라이브 RAID 1 DDP
 a| 
이 릴리스에서는 RAID 1 DDP에 풀에 최소 11개의 SSD가 필요하지 않습니다. 이제 최소 구성에서는 풀에 RAID 1 볼륨만 생성되는 경우 8 드라이브 SSD 풀을 허용합니다.



 a| 
EKMS 키 삭제
 a| 
이제 스토리지 관리자가 EKMS(외부 키 관리 서버)를 요청하여 이전 키를 삭제할 수 있습니다. 키 삭제는 설치된 드라이브에 새 키가 있는 후 키를 재키 처리하는 동안에만 수행됩니다.

|===


== 버전 11.72의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
SNMPv3 지원
 a| 
SNMPv3는 이제 설정 [알림] 메뉴에서 구성할 수 있는 알림 알림에 대해 지원됩니다. SNMPv3는 강력한 인증 및 데이터 암호화를 통해 보안을 제공합니다.



 a| 
여러 주요 서버에 키 복제 지원
 a| 
자체 암호화 드라이브의 외부 키 관리를 위해 외부 키 관리 생성 대화 상자에는 여러 키 서버를 추가하기 위한 새로운 옵션이 포함되어 있습니다.



 a| 
업데이트된 브라우저 버전
 a| 
System Manager의 최소 브라우저 버전이 업데이트되었습니다.

|===


== 버전 11.71의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
EF300 확장
| 이 릴리즈에서는 EF300 스토리지 시스템의 SAS-3 엔클로저로의 확장을 지원합니다. 이 확장을 통해 4KiB 블록 NVMe SSD는 512e SAS SSD 및 HDD와 공존할 수 있습니다. 하지만 블록 크기가 다른 드라이브는 동일한 풀 또는 볼륨 그룹에서 구성할 수 없습니다. 


 a| 
iSCSI 구성의 FEC 모드 옵션
 a| 
25GB iSCSI 호스트 인터페이스 카드를 사용하는 스토리지 어레이의 경우 iSCSI 포트를 구성할 때 FEC(Forward Error Correction) 모드를 설정하는 새로운 옵션을 사용할 수 있습니다.



 a| 
원격 스토리지 볼륨
 a| 
원격 스토리지 볼륨 옵션 기능을 사용하면 iSCSI 연결을 사용하여 원격 스토리지 시스템에서 로컬 E-Series 스토리지 시스템으로 볼륨을 가져올 수 있습니다. 원격 스토리지는 iSCSI를 통해 액세스할 수 있는 한 E-Series 시스템 또는 다른 스토리지 공급업체와 동일한 브랜드일 수 있습니다.



 a| 
non-FDE 드라이브에 대해 추가된 완전 삭제(지우기) 기능
 a| 
이제 드라이브 완전 삭제 기능에 FDE 드라이브가 아닌 드라이브가 포함되어 있습니다. Hardware(하드웨어) 페이지에서 Drive(드라이브) 컨텍스트 메뉴를 열고 "Erase(지우기)"를 선택할 수 있습니다(이전에는 "Secure Erase(보안 지우기)"를 선택함).



 a| 
이메일 알림을 위한 보안 연결
 a| 
암호화된 이메일 알림을 활성화하려면 선택적으로 발신 이메일(알림, ASUP 디스패치)을 구성하여 인증 자격 증명을 제공할 수 있습니다. 암호화 유형에는 SMTPS 및 STARTTLS가 있습니다.



 a| 
AutoSupport 추가 사항
 a| 
AutoSupport가 활성화되지 않은 경우 알림 영역에 경고가 나타납니다.



 a| 
Syslog 알림 형식 변경
 a| 
Syslog 경고 형식은 이제 RFC 5424를 지원합니다.

|===


== 버전 11.70의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
새로운 스토리지 시스템 모델 – EF300
 a| 
이번 릴리즈에는 EF300 경제적인 All-NVMe-Flash 스토리지 시스템이 도입되었습니다. EF300은 컨트롤러당 24개의 NVMe SSD 드라이브와 단일 호스트 인터페이스 카드(HIC)를 포함합니다. 지원되는 NVMe over Fabrics 호스트 인터페이스에는 NVMe over IB, NVMe over RoCE 및 NVMe over FC가 포함됩니다. 지원되는 SCSI 인터페이스에는 FC, iSER을 통한 IB 및 SRP를 통한 IB가 포함됩니다. Unified Manager에서 여러 EF300 스토리지 시스템과 기타 E-Series 스토리지 시스템을 보고 관리할 수 있습니다.



 a| 
새로운 리소스 프로비저닝 기능(EF300 및 EF600만 해당)
 a| 
EF300 및 EF600 스토리지 시스템의 새로운 리소스 프로비저닝 기능입니다. 리소스가 프로비저닝된 볼륨은 백그라운드 초기화 프로세스 없이 즉시 사용할 수 있습니다.



 a| 
512e 블록 크기 추가 옵션(EF300 및 EF600만 해당)
 a| 
EF300 및 EF600 스토리지 시스템의 경우 512바이트 또는 4KiB 블록 크기를 지원하도록 볼륨을 설정할 수 있습니다. iSCSI 호스트 인터페이스 및 VMware OS를 지원하기 위해 512e 기능이 추가되었습니다. 가능한 경우 System Manager에서는 적절한 기본값을 제안합니다.



 a| 
필요에 따라 AutoSupport 디스패치를 보내는 새로운 옵션입니다
 a| 
새로운 AutoSupport 디스패치 전송 기능을 사용하면 예약된 디스패치를 기다리지 않고 기술 지원 부서에 데이터를 보낼 수 있습니다. 이 옵션은 지원 센터의 AutoSupport 탭에서 사용할 수 있습니다.



 a| 
외부 키 관리 서버의 향상된 기능
 a| 
외부 키 관리 서버에 연결하는 기능은 다음과 같은 향상된 기능을 제공합니다.

* 백업 키 생성 기능을 사용하지 않습니다.
* 클라이언트 및 서버 인증서 외에 키 관리 서버에 대한 중간 인증서를 선택합니다.




 a| 
인증서 향상
 a| 
이 릴리스에서는 OpenSSL과 같은 외부 도구를 사용하여 CSR(인증서 서명 요청)을 생성할 수 있습니다. 이 경우 서명된 인증서와 함께 개인 키 파일을 가져와야 합니다.



 a| 
볼륨 그룹의 새로운 오프라인 초기화 기능
 a| 
볼륨 생성을 위해 System Manager에서는 새로 생성된 볼륨이 오프라인으로 초기화되도록 호스트 할당 단계를 건너뛰는 방법을 제공합니다. 이 기능은 SAS 드라이브의 RAID 볼륨 그룹(예: 동적 디스크 풀 또는 EF300 및 EF600 스토리지 시스템에 포함된 NVMe SSD 제외)에만 적용할 수 있습니다. 이 기능은 초기화가 백그라운드에서 실행되지 않고 사용량이 시작될 때 볼륨을 최대 성능으로 설정해야 하는 워크로드에 유용합니다.



 a| 
새로운 구성 데이터 수집 기능
 a| 
이 새로운 기능은 볼륨 그룹 및 디스크 풀에 대한 모든 데이터를 포함하는 컨트롤러의 RAID 구성 데이터를 저장합니다('Save storageArray dbmDatabase'에 대한 CLI 명령과 동일한 정보). 이 기능은 기술 지원을 위해 추가되었으며 지원 센터의 진단 탭에 있습니다.



 a| 
12개 드라이브 케이스에서 디스크 풀의 기본 보존 용량을 변경합니다
 a| 
이전에는 2개의 드라이브를 수용할 수 있는 충분한 보존(스페어) 용량을 갖춘 12개 드라이브 디스크 풀이 생성되었습니다. 이제 기본 풀은 단일 드라이브 장애를 처리하여 보다 비용 효율적인 소형 풀 기본값을 제공하도록 변경되었습니다.

|===