---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: SANtricity OS의 새로운 기능 
---
= SANtricity OS의 새로운 기능
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에서는 EF300, EF600, E2800/EF280 및 E5700/EF570 컨트롤러의 내장 관리를 위한 SANtricity OS 11.8의 새로운 기능에 대해 설명합니다.



== 버전 11.80의 새로운 기능

[cols="35h,~"]
|===
| 새로운 기능 | 설명 


 a| 
향상된 볼륨 패리티 검사
 a| 
이제 REST API 또는 CLI를 통해 볼륨 패리티 검사를 백그라운드 프로세스로 시작할 수 있습니다. 결과 패리티 검사는 스캔 작업을 완료하는 데 필요한 한 백그라운드에서 실행됩니다. 스캔 작업은 컨트롤러 재부팅 및 페일오버 작업에 영향을 줍니다.



 a| 
Unified Manager에 대한 SAML 지원
 a| 
Unified Manager는 이제 SAML(Security Assertion Markup Language)을 지원합니다. Unified Manager에 대해 SAML이 활성화된 경우 사용자는 ID 공급자에 대해 다중 요소 인증을 사용하여 사용자 인터페이스와 상호 작용해야 합니다. SAML이 Unified Manager에서 활성화된 후에는 IDP를 통해 요청을 인증하지 않고 REST API를 사용할 수 없습니다.



 a| 
자동 구성 기능
 a| 
이제 초기 어레이 설정을 위해 자동 구성 기능과 함께 사용할 볼륨 블록 크기 매개 변수를 설정하는 기능이 지원됩니다. 이 기능은 CLI에서만 "blocksize" 매개 변수로 사용할 수 있습니다.



 a| 
컨트롤러 펌웨어 암호화 서명
 a| 
컨트롤러 펌웨어가 암호로 서명됩니다. 서명은 초기 다운로드 및 각 컨트롤러 부팅 중에 검사됩니다. 최종 사용자에게 미치는 영향이 예상되지 않습니다. 서명은 CA에서 발급한 Extended Validation 인증서를 통해 백업됩니다.



 a| 
드라이브 펌웨어 암호화 서명
 a| 
드라이브 펌웨어가 암호로 서명되었습니다. 서명은 초기 다운로드 중에 확인되며 CA에서 발급한 Extended Validation 인증서를 통해 백업됩니다. 이제 드라이브 펌웨어 컨텐츠가 ZIP 파일로 전달되며, 여기에는 기존의 서명되지 않은 펌웨어와 새로 서명된 펌웨어가 포함됩니다. 사용자는 대상 시스템에서 실행 중인 코드의 릴리스 버전을 기반으로 적절한 파일을 선택해야 합니다.



 a| 
외부 키 서버 관리 - 인증서 키 크기
 a| 
새 기본 인증서 키 크기는 3072비트(2048비트)입니다. 최대 4096비트의 키 크기가 지원됩니다. 기본값이 아닌 키 크기를 지원하려면 NVSRAM 비트를 변경해야 합니다.

키 크기 선택 값은 다음과 같습니다.

* 기본값 = 0
* 길이 2048 = 1
* 길이 3072 = 2
* 길이 4096 = 3


SMcli를 통해 키 크기를 4096으로 변경하려면:

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

키 크기 조회:

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Disk Pool 기능 향상
 a| 
11.80 이상을 실행하는 컨트롤러로 생성된 디스크 풀은 _ 버전 0_pool과 달리 _ 버전 1_pool입니다. 버전 1_ 디스크 풀이 있으면 다운그레이드 작업이 제한됩니다.

디스크 풀의 버전은 스토리지 배열 프로파일에서 확인할 수 있습니다.



 a| 
최소 브라우저 요구 사항이 충족되지 않으면 System Manager 및 Unified Manager가 실행되지 않습니다
 a| 
System Manager 또는 Unified Manager를 실행하기 전에 브라우저의 최소 버전이 필요합니다. 다음은 지원되는 최소 버전입니다.

* Firefox 최소 버전 80
* Chrome 최소 버전 89
* 모서리 최소 버전 90
* Safari 최소 버전 14




 a| 
FIPS 140-3개 NVMe SSD 드라이브 지원
 a| 
이제 NetApp 인증 FIPS 140-3의 NVMe SSD 드라이브가 지원됩니다. 스토리지 어레이 프로필 및 System Manager에서 올바르게 식별됩니다.



 a| 
EF300 및 EF600에서 SSD 읽기 캐시 지원
 a| 
이제 SAS 확장 시 HDD를 사용하는 EF300 및 EF600 컨트롤러에서 SSD 읽기 캐시가 지원됩니다.



 a| 
EF300 및 EF600에서 iSCSI 및 파이버 채널 비동기 원격 미러링 지원
 a| 
이제 ARVM(비동기식 원격 미러링)이 NVMe 및 SAS 기반 볼륨을 사용하는 EF300 및 EF600 컨트롤러에서 지원됩니다.



 a| 
기본 트레이에 드라이브 없이 EF300 및 EF600 지원
 a| 
이제 기본 트레이에 NVMe 드라이브가 없는 EF300 및 EF600 컨트롤러 구성이 지원됩니다.



 a| 
모든 플랫폼에 대해 USB 포트가 비활성화되었습니다
 a| 
이제 모든 플랫폼에서 USB 포트가 비활성화되었습니다.

|===