---
permalink: getting-started/learn-terms-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, terms 
summary: E-Series에 사용된 용어에 대해 자세히 알아보십시오. 
---
= E-Series 용어에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E-Series에 사용된 용어에 대해 자세히 알아보십시오.

|===
| 기간 | 설명 


 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 기능을 구현합니다.



 a| 
이중/단일 구성
 a| 
Duplex는 스토리지 배열 내의 이중 컨트롤러 모듈 구성입니다. 단일 컨트롤러 모듈 구성은 Simplex입니다.



 a| 
HDD
 a| 
하드 디스크 드라이브(HDD)는 자기 코팅으로 회전하는 금속 플래터를 사용하는 데이터 저장 장치입니다.



 a| 
HIC
 a| 
HIC(호스트 인터페이스 카드)는 어레이를 호스트에 연결합니다. 컨트롤러 캐니스터 내에 선택적으로 설치할 수 있습니다.



 a| 
IB
 a| 
IB(InfiniBand)는 고성능 서버와 스토리지 시스템 간의 데이터 전송을 위한 통신 표준입니다.



 a| 
IOPS
 a| 
IOPS는 초당 입출력 작업입니다.



 a| 
미러링
 a| 
미러링은 지속적인 가용성을 보장하기 위해 데이터 볼륨을 별도의 스토리지 시스템에 복제하는 것입니다.



 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다.



 a| 
전원/팬 캐니스터
 a| 
전원/팬 캐니스터는 선반으로 미끄러지는 어셈블리입니다. 여기에는 전원 공급 장치 및 내장형 팬이 포함됩니다.



 a| 
랙 유닛(U)
 a| 
랙 유닛(U)은 44.50mm(1.75인치)로 정의된 측정 단위입니다.



 a| 
SAS를 참조하십시오
 a| 
SAS(Serial Attached SCSI)는 컨트롤러를 디스크 드라이브에 직접 연결하는 지점 간 직렬 프로토콜입니다.



 a| 
RoCE
 a| 
RoCE(RDMA over Converged Ethernet)는 이더넷 네트워크를 통한 RDMA(Remote Direct Memory Access)를 지원하는 네트워크 프로토콜입니다.



 a| 
쉘프
 a| 
쉘프는 캐비닛 또는 랙에 설치된 엔클로저입니다. 여기에는 스토리지 어레이의 하드웨어 구성 요소가 포함됩니다. 쉘프는 컨트롤러 쉘프와 드라이브 쉘프의 두 가지 유형이 있습니다. 컨트롤러 쉘프는 컨트롤러와 드라이브를 포함합니다. 드라이브 쉘프는 입/출력 모듈(IOM) 및 드라이브를 포함합니다.



 a| 
스냅샷
 a| 
스냅샷 이미지는 특정 시점에 캡처된 볼륨 데이터의 논리적 복사본입니다. 복원 지점과 마찬가지로 스냅샷 이미지를 통해 알려진 양호한 데이터 집합으로 롤백할 수 있습니다.



 a| 
SSD를 지원합니다
 a| 
SSD(Solid-State Disk)는 데이터를 영구적으로 저장하기 위해 솔리드 스테이트 메모리(플래시)를 사용하는 데이터 스토리지 장치입니다. SSD는 기존의 하드 드라이브를 에뮬레이트하며 하드 드라이브에서 사용하는 것과 동일한 인터페이스로 사용할 수 있습니다.



 a| 
스토리지 시스템
 a| 
스토리지 어레이에는 쉘프, 컨트롤러, 드라이브, 소프트웨어 및 펌웨어가 포함되어 있습니다.



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.



 a| 
워크로드
 a| 
워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 일부 애플리케이션의 경우 System Manager에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다.

|===