---
permalink: config-vmware/access-sam-setup-wizard-task.html 
sidebar: sidebar 
keywords: access System Manager vmware, express vmware configuration,software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: SANtricity 시스템 관리자의 설정 마법사를 사용하여 스토리지 배열을 구성합니다. 
---
= SANtricity System Manager - VMware를 사용하여 스토리지를 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열을 구성하려면 SANtricity System Manager에서 설치 마법사를 사용할 수 있습니다.

SANtricity 시스템 관리자는 각 컨트롤러에 내장된 웹 기반 인터페이스입니다. 사용자 인터페이스에 액세스하려면 브라우저에서 컨트롤러의 IP 주소를 가리킵니다. 설치 마법사를 사용하면 시스템 구성을 시작할 수 있습니다.

.시작하기 전에
다음 사항을 확인하십시오.

* 대역 외 관리.
* 다음 브라우저 중 하나가 포함된 SANtricity System Manager에 액세스하기 위한 관리 스테이션입니다.
+
|===
| 브라우저 | 최소 버전 


 a| 
Google Chrome
 a| 
89



 a| 
Microsoft Edge를 참조하십시오
 a| 
90



 a| 
Mozilla Firefox
 a| 
80



 a| 
사파리
 a| 
14

|===


.이 작업에 대해
iSCSI 사용자인 경우 iSCSI를 구성하는 동안 설정 마법사를 종료했는지 확인합니다.

System Manager를 열거나 브라우저를 새로 고치면 마법사가 자동으로 다시 시작되고, 다음 중 _ 개 이상의 조건이 충족됩니다.

* 풀 및 볼륨 그룹이 감지되지 않습니다.
* 감지된 워크로드가 없습니다.
* 알림이 구성되지 않았습니다.


설치 마법사가 자동으로 나타나지 않으면 기술 지원 부서에 문의하십시오.

.단계
. 브라우저에서 '+https://<DomainNameOrIPAddress>+` URL을 입력합니다
+
IPAddress는 스토리지 배열 컨트롤러 중 하나의 주소입니다.

+
구성되지 않은 어레이에서 SANtricity 시스템 관리자를 처음 열면 관리자 암호 설정 프롬프트가 나타납니다. 역할 기반 액세스 관리는 관리자, 지원, 보안 및 모니터링의 네 가지 로컬 역할을 구성합니다. 마지막 세 개의 역할에는 추측할 수 없는 임의의 암호가 있습니다. admin 역할의 암호를 설정한 후 admin 자격 증명을 사용하여 모든 암호를 변경할 수 있습니다. 4개의 로컬 사용자 역할에 대한 자세한 내용은 SANtricity System Manager 사용자 인터페이스에서 제공되는 온라인 도움말을 참조하십시오.

. 관리자 암호 설정 및 암호 확인 필드에 관리자 역할에 대한 System Manager 암호를 입력한 다음 * 암호 설정 * 을 클릭합니다.
+
구성된 풀, 볼륨 그룹, 워크로드 또는 알림이 없는 경우 설정 마법사가 시작됩니다.

. 설정 마법사를 사용하여 다음 작업을 수행합니다.
+
** * 하드웨어(컨트롤러 및 드라이브) 확인 * -- 스토리지 배열의 컨트롤러 및 드라이브 수를 확인합니다. 어레이에 이름을 할당합니다.
** * 호스트 및 운영 체제 확인 * -- 스토리지 배열이 액세스할 수 있는 호스트 및 운영 체제 유형을 확인합니다.
** * 풀 수락 * -- 빠른 설치 방법에 대해 권장되는 풀 구성을 수락합니다. 풀은 드라이브의 논리적 그룹입니다.
** * 경고 구성 * -- 스토리지 배열에 문제가 발생하면 System Manager가 자동 알림을 수신할 수 있도록 합니다.
** * AutoSupport 활성화 * -- 스토리지 어레이의 상태를 자동으로 모니터링하고 기술 지원 부서에 디스패치를 보냅니다.


. 볼륨을 아직 생성하지 않은 경우 Storage [Volumes > Create > Volume] 메뉴로 이동하여 생성합니다.
+

NOTE: EF300 및 EF600의 경우 VMware와의 호환성을 위해 블록 크기를 512바이트로 설정해야 합니다. 볼륨을 512바이트로 설정하는 방법에 대한 자세한 내용은 SANtricity 시스템 관리자 온라인 도움말을 참조하십시오.


