---
permalink: config-vmware/verify-vmware-config-support-task.html 
sidebar: sidebar 
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: VMware 구성이 지원되는지 확인합니다. 
---
= VMware 구성이 지원되는지 확인합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.

.단계
. 로 이동합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 솔루션 검색 * 타일을 클릭합니다.
. 메뉴: 프로토콜 [SAN 호스트] 영역에서 * E-Series SAN 호스트 * 옆에 있는 * 추가 * 버튼을 클릭합니다.
. 검색 조건 구체화 보기 * 를 클릭합니다.
+
검색 조건 구체화 섹션이 표시됩니다. 이 섹션에서는 적용되는 프로토콜과 운영 체제, NetApp OS 및 호스트 다중 경로 드라이버와 같은 구성의 다른 기준을 선택할 수 있습니다. 구성에 대해 알고 있는 기준을 선택한 다음 어떤 호환 구성 요소가 적용되는지 확인합니다. 필요한 경우 도구에 규정된 운영 체제 및 프로토콜을 업데이트합니다. 선택한 구성에 대한 자세한 내용은 오른쪽 페이지 화살표를 클릭하여 지원되는 구성 보기 페이지에서 액세스할 수 있습니다.

. 필요한 경우 표에 나열된 대로 운영 체제 및 프로토콜을 업데이트합니다.
+
|===
| 운영 체제 업데이트 | 프로토콜 | 프로토콜 관련 업데이트 


 a| 
** 적절한 기능과 지원 가능성을 보장하기 위해 즉시 사용 가능한 드라이버를 설치해야 할 수 있습니다. ESXi 셸이나 ESXi 호스트에 대한 원격 SSH 연결을 사용하여 HBA 드라이버를 설치할 수 있습니다. 이러한 방법 중 하나를 사용하여 호스트에 액세스하려면 ESXi 셸 및 SSH 액세스를 설정해야 합니다. ESXi 셸에 대한 자세한 내용은 ESXi에서 ESXi 셸 사용과 관련된 VMware 기술 자료 를 참조하십시오. 설치 명령에 대해서는 HBA 드라이버와 함께 제공되는 지침을 참조하십시오.
** 각 HBA 공급업체에는 부팅 코드 및 펌웨어를 업데이트하는 특정 방법이 있습니다. 이러한 방법 중 일부에는 vCenter 플러그인 사용 또는 ESXi 호스트에 CIM 공급자 설치가 포함될 수 있습니다. vCenter 플러그인을 사용하여 공급업체의 특정 HBA에 대한 정보를 얻을 수 있습니다. HBA 부트 코드 또는 펌웨어를 업데이트하는 데 필요한 지침과 소프트웨어를 얻으려면 공급업체 웹 사이트의 지원 섹션을 참조하십시오. 올바른 부팅 코드 또는 펌웨어를 얻으려면 _VMware 호환성 가이드_ 또는 HBA 공급업체 웹 사이트를 참조하십시오.

 a| 
FC
 a| 
호스트 버스 어댑터(HBA) 드라이버, 펌웨어 및 부트 코드



 a| 
iSCSI
 a| 
네트워크 인터페이스 카드(NIC) 드라이버, 펌웨어 및 부트 코드



 a| 
SAS를 참조하십시오
 a| 
호스트 버스 어댑터(HBA) 드라이버, 펌웨어 및 부트 코드

|===

