---
sidebar: sidebar 
permalink: vcenter-plugin/faq-storage-plugin-vcenter.html 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= vCenter용 SANtricity 스토리지 플러그인에 대한 FAQ
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 어떤 설정을 가져올까요?

설정 가져오기 기능은 하나의 스토리지 어레이에서 여러 스토리지 어레이로 구성을 로드하는 일괄 작업입니다.

이 작업 중에 가져오는 설정은 소스 스토리지 배열이 System Manager에 구성된 방식에 따라 다릅니다. 다음 설정을 여러 스토리지 어레이로 가져올 수 있습니다.

* * 이메일 경고 * -- 설정에는 메일 서버 주소와 경고 받는 사람의 이메일 주소가 포함됩니다.
* * Syslog alerts * -- 설정에는 syslog 서버 주소와 UDP 포트가 포함됩니다.
* SNMP 경고 * -- 설정에는 SNMP 서버에 대한 커뮤니티 이름과 IP 주소가 포함됩니다.
* * AutoSupport * -- 설정에는 별도 기능(기본 AutoSupport, AutoSupport OnDemand 및 원격 진단), 유지보수 윈도우, 제공 방법, 및 발송 일정을 참조하십시오.
* * 디렉토리 서비스 * -- 구성에는 LDAP(Lightweight Directory Access Protocol) 서버의 도메인 이름 및 URL과 LDAP 서버의 사용자 그룹에 대한 스토리지 배열의 사전 정의된 역할에 대한 매핑이 포함됩니다.
* * 스토리지 구성 * -- 구성에는 볼륨(일반 및 비리포지토리 볼륨만), 볼륨 그룹, 풀 및 핫 스페어 드라이브 할당이 포함됩니다.
* * 시스템 설정 * -- 구성에는 볼륨에 대한 미디어 스캔 설정, 컨트롤러에 대한 SSD 캐시, 자동 로드 밸런싱(호스트 연결 보고 제외)이 포함됩니다.




== 내 스토리지 어레이가 모두 표시되지 않는 이유는 무엇입니까?

설정 가져오기 작업 중에 일부 스토리지 배열을 대상 선택 대화 상자에서 사용하지 못할 수 있습니다.

다음과 같은 이유로 스토리지 어레이가 나타나지 않을 수 있습니다.

* 펌웨어 버전이 8.50 미만입니다.
* 스토리지 배열이 오프라인입니다.
* 시스템이 해당 어레이와 통신할 수 없습니다(예: 어레이에 인증서, 암호 또는 네트워킹 문제가 있음).




== 이러한 볼륨이 워크로드와 관련이 없는 이유는 무엇입니까?

CLI(Command Line Interface)를 사용하여 볼륨을 생성했거나 다른 스토리지 어레이에서 마이그레이션(가져오기/내보내기)한 경우 볼륨은 워크로드에 연결되지 않습니다.



== 선택한 워크로드가 볼륨 생성에 어떤 영향을 미칩니까?

볼륨을 생성하는 동안 작업 부하 사용에 대한 정보를 묻는 메시지가 표시됩니다. 시스템에서는 이 정보를 사용하여 최적의 볼륨 구성을 생성합니다. 이 구성은 필요에 따라 편집할 수 있습니다. 선택적으로 볼륨 생성 순서에서 이 단계를 건너뛸 수 있습니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

* * 응용 프로그램별 * -- 응용 프로그램별 작업 부하를 사용하여 볼륨을 생성할 때 응용 프로그램 작업 부하 I/O와 응용 프로그램 인스턴스의 다른 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시와 같은 볼륨 특성은 자동으로 권장 사항이며 다음과 같은 애플리케이션 유형에 대해 생성되는 워크로드에 최적화되어 있습니다.
+
** Microsoft SQL Server를 참조하십시오
** Microsoft Exchange Server를 참조하십시오
** 비디오 감시 애플리케이션
** VMware ESXi(가상 머신 파일 시스템과 함께 사용할 볼륨용)
+
볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.



* * 기타(또는 특정 볼륨 생성을 지원하지 않는 애플리케이션) * -- 다른 워크로드는 볼륨 구성을 사용하며, 특정 애플리케이션과 연결되지 않은 워크로드를 생성하려는 경우 또는 스토리지 어레이에서 사용하려는 애플리케이션에 대한 내장 최적화가 없는 경우 수동으로 지정해야 합니다. 볼륨 추가/편집 대화 상자를 사용하여 볼륨 구성을 수동으로 지정해야 합니다.




== 내 볼륨, 호스트 또는 호스트 클러스터가 모두 표시되지 않는 이유는 무엇입니까?

DA 지원 기본 볼륨이 있는 스냅샷 볼륨은 DA(Data Assurance) 기능이 지원되지 않는 호스트에 할당할 수 없습니다. DA를 사용할 수 없는 호스트에 스냅샷 볼륨을 할당하기 전에 기본 볼륨에서 DA를 비활성화해야 합니다.

스냅샷 볼륨을 할당할 호스트에 대한 다음 지침을 고려하십시오.

* DA를 사용할 수 없는 입출력 인터페이스를 통해 스토리지 시스템에 접속된 호스트의 경우 DA를 사용할 수 없습니다.
* DA를 사용할 수 없는 호스트 구성원이 하나 이상 있는 경우 호스트 클러스터를 DA를 사용할 수 없습니다.



NOTE: 스냅샷과 연결된 볼륨(정합성 보장 그룹, 스냅샷 그룹, 스냅샷 이미지 및 스냅샷 볼륨), 볼륨 복제본에서는 DA를 비활성화할 수 없습니다. 있습니다. 기본 볼륨에서 DA를 비활성화하기 전에 관련된 모든 예약 용량 및 스냅샷 객체를 삭제해야 합니다.



== 선택한 워크로드를 삭제할 수 없는 이유는 무엇입니까?

이 워크로드는 CLI(Command Line Interface)를 사용하여 생성되거나 다른 스토리지 어레이에서 마이그레이션(가져오기/내보내기)된 볼륨 그룹으로 구성됩니다. 따라서 이 워크로드의 볼륨은 애플리케이션별 워크로드와 연결되지 않으므로 워크로드를 삭제할 수 없습니다.



== 애플리케이션별 워크로드를 사용하면 스토리지 어레이를 관리하는 데 어떤 도움이 됩니까?

애플리케이션별 워크로드의 볼륨 특성에 따라 스토리지 어레이의 구성 요소와 워크로드가 상호 작용하는 방식이 결정되며, 지정된 구성에서 환경의 성능을 파악하는 데 도움이 됩니다.

애플리케이션은 SQL Server 또는 Exchange와 같은 소프트웨어입니다. 각 애플리케이션을 지원할 워크로드를 하나 이상 정의합니다. 일부 애플리케이션의 경우, 시스템은 스토리지를 최적화하는 볼륨 구성을 자동으로 권장합니다. 볼륨 구성에는 I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시 같은 특성이 포함됩니다.



== 확장된 용량을 인식하려면 어떻게 해야 합니까?

볼륨의 용량을 늘릴 경우 호스트에서 즉시 볼륨 용량 증가를 인식하지 못할 수 있습니다.

대부분의 운영 체제는 볼륨 확장이 시작된 후 확장된 볼륨 용량을 인식하고 자동으로 확장합니다. 그러나 일부는 그렇지 않을 수도 있습니다. OS에서 확장된 볼륨 용량을 자동으로 인식하지 못하는 경우 디스크 재검색 또는 재부팅을 수행해야 할 수 있습니다.

볼륨 용량을 확장한 후에는 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다.

자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.



== 나중에 호스트 할당 선택 항목을 언제 사용하시겠습니까?

볼륨 생성 프로세스의 속도를 높이려면 새로 생성된 볼륨이 오프라인으로 초기화되도록 호스트 할당 단계를 건너뛸 수 있습니다.

새로 생성된 볼륨을 초기화해야 합니다. 시스템은 두 가지 모드(즉시 사용 가능한 형식(iaf) 백그라운드 초기화 프로세스 또는 오프라인 프로세스) 중 하나를 사용하여 이러한 모드를 초기화할 수 있습니다.

볼륨을 호스트에 매핑하면 해당 그룹의 초기화 볼륨이 백그라운드 초기화로 강제로 전환됩니다. 이 백그라운드 초기화 프로세스를 사용하면 동시 호스트 입출력이 허용되므로 시간이 오래 걸릴 수 있습니다.

볼륨 그룹의 볼륨 중 어느 것도 매핑되지 않은 경우 오프라인 초기화가 수행됩니다. 오프라인 프로세스는 백그라운드 프로세스보다 훨씬 빠릅니다.



== 호스트 블록 크기 요구 사항에 대해 알아야 할 내용은 무엇입니까?

EF300 및 EF600 시스템의 경우 512바이트 또는 4KiB 블록 크기("섹터 크기"라고도 함)를 지원하도록 볼륨을 설정할 수 있습니다. 볼륨을 생성하는 동안 올바른 값을 설정해야 합니다. 가능한 경우 시스템은 적절한 기본값을 제안합니다.

볼륨 블록 크기를 설정하기 전에 다음 제한 사항 및 지침을 읽으십시오.

* 일부 운영 체제와 가상 머신(현재 VMware 등)에는 512바이트 블록 크기가 필요하며 4KiB를 지원하지 않으므로 볼륨을 생성하기 전에 호스트 요구 사항을 알아야 합니다. 일반적으로 볼륨을 4KiB 블록 크기로 설정하여 최상의 성능을 얻을 수 있지만 호스트에서 4KiB(또는 "4Kn") 블록을 허용하는지 확인합니다.
* 풀 또는 볼륨 그룹에 대해 선택하는 드라이브 유형에 따라 지원되는 볼륨 블록 크기가 다음과 같이 결정됩니다.
+
** 512바이트 블록에 쓰는 드라이브를 사용하여 볼륨 그룹을 생성하는 경우 512바이트 블록의 볼륨만 생성할 수 있습니다.
** 4KiB 블록에 쓰는 드라이브를 사용하여 볼륨 그룹을 생성하는 경우 512바이트 또는 4KiB 블록으로 볼륨을 생성할 수 있습니다.


* 어레이에 iSCSI 호스트 인터페이스 카드가 있는 경우 모든 볼륨은 볼륨 그룹 블록 크기와 관계없이 512바이트 블록으로 제한됩니다. 이는 특정 하드웨어 구현 때문입니다.
* 블록 크기를 설정한 후에는 변경할 수 없습니다. 블록 크기를 변경해야 하는 경우 볼륨을 삭제하고 다시 생성해야 합니다.




== 호스트 클러스터를 생성해야 하는 이유는 무엇입니까?

동일한 볼륨 세트에 대한 액세스를 공유하는 호스트가 2개 이상인 경우 호스트 클러스터를 생성해야 합니다. 일반적으로 개별 호스트에는 볼륨 액세스를 조정하기 위해 클러스터링 소프트웨어가 설치되어 있습니다.



== 어떤 호스트 운영 체제 유형이 올바른지 어떻게 알 수 있습니까?

호스트 운영 체제 유형 필드에는 호스트의 운영 체제가 들어 있습니다. 드롭다운 목록에서 권장 호스트 유형을 선택할 수 있습니다.

드롭다운 목록에 표시되는 호스트 유형은 스토리지 어레이 모델 및 펌웨어 버전에 따라 다릅니다. 가장 최신 버전은 가장 일반적인 옵션을 먼저 표시하며, 이 옵션이 가장 적절할 가능성이 높습니다. 이 목록의 모양은 옵션이 완전히 지원됨을 의미하지는 않습니다.


NOTE: 호스트 지원에 대한 자세한 내용은 를 참조하십시오 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].

다음 호스트 유형 중 일부가 목록에 나타날 수 있습니다.

|===
| 호스트 운영 체제 유형입니다 | 운영 체제(OS) 및 다중 경로 드라이버 


| Linux DM-MP(커널 3.10 이상) | 3.10 이상의 커널과 함께 장치 매퍼 다중 경로 페일오버 솔루션을 사용하여 Linux 운영 체제를 지원합니다. 


| VMware ESXi | VMware 기본 제공 스토리지 어레이 유형 정책 모듈 SATP_ALUA를 사용하여 NMP(Native Multipathing Plug-in) 아키텍처를 실행하는 VMware ESXi 운영 체제를 지원합니다. 


| Windows(클러스터형 또는 비클러스터형) | ATTO 다중 경로 드라이버를 실행하지 않는 Windows 클러스터 또는 클러스터링되지 않은 구성을 지원합니다. 


| ATTO 클러스터(모든 운영 체제) | ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 모든 클러스터 구성을 지원합니다. 


| Linux(Veritas DMP) | Veritas DMP 다중 경로 솔루션을 사용하여 Linux 운영 체제를 지원합니다. 


| Linux(ATTO) | ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Linux 운영 체제를 지원합니다. 


| Mac OS | ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Mac OS 버전을 지원합니다. 


| Windows(ATTO) | ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Windows 운영 체제를 지원합니다. 


| IBM SVC | IBM SAN Volume Controller 구성을 지원합니다. 


| 공장 출하 시 기본값 | 스토리지 배열의 초기 시작용으로 예약되어 있습니다. 호스트 운영 체제 유형이 출하 시 기본값으로 설정되어 있는 경우 연결된 호스트에서 실행 중인 호스트 운영 체제 및 다중 경로 드라이버에 맞게 변경합니다. 


| Linux DM-MP(커널 3.9 이상) | 3.9 이하의 커널과 함께 장치 매퍼 다중 경로 장애 조치 솔루션을 사용하여 Linux 운영 체제를 지원합니다. 


| Window Clustered(더 이상 사용되지 않음) | 호스트 운영 체제 유형이 이 값으로 설정되어 있으면 Windows(클러스터형 또는 비클러스터형) 설정을 대신 사용합니다. 
|===


== 호스트 포트를 호스트에 일치시키려면 어떻게 해야 합니까?

호스트를 수동으로 생성하는 경우 먼저 호스트에서 사용할 수 있는 적절한 HBA(호스트 버스 어댑터) 유틸리티를 사용하여 호스트에 설치된 각 HBA와 연결된 호스트 포트 식별자를 확인해야 합니다.

이 정보가 있는 경우 Create Host 대화 상자에 제공된 목록에서 스토리지 배열에 로그인한 호스트 포트 식별자를 선택합니다.


CAUTION: 생성 중인 호스트에 대해 적절한 호스트 포트 식별자를 선택해야 합니다. 잘못된 호스트 포트 식별자를 연결하면 다른 호스트에서 이 데이터에 의도하지 않은 액세스가 발생할 수 있습니다.



== 기본 클러스터는 무엇입니까?

기본 클러스터는 기본 클러스터에 할당된 볼륨에 대한 액세스 권한을 얻기 위해 스토리지 배열에 로그인한 연결되지 않은 호스트 포트 식별자를 허용하는 시스템 정의 엔티티입니다.

연결되지 않은 호스트 포트 식별자는 특정 호스트와 논리적으로 연결되지 않지만 호스트에 물리적으로 설치되어 스토리지 배열에 로그인하는 호스트 포트입니다.


NOTE: 호스트가 스토리지 배열의 특정 볼륨에 특정 액세스 권한을 가지도록 하려면 기본 클러스터를 사용하지 않아야 합니다. 대신 호스트 포트 식별자를 해당 호스트에 연결해야 합니다. 이 작업은 Create Host(호스트 생성) 작업 중에 수동으로 수행할 수 있습니다. 그런 다음 개별 호스트 또는 호스트 클러스터에 볼륨을 할당합니다.

외부 스토리지 환경이 모든 호스트 및 스토리지 배열에 연결된 모든 로그인 호스트 포트 식별자를 모든 볼륨에 액세스할 수 있도록 허용하는 특수한 경우에만 기본 클러스터를 사용해야 합니다(모든 액세스 모드). 호스트를 스토리지 시스템 또는 사용자 인터페이스에 특별히 알려주지 않습니다.

처음에는 CLI(Command Line Interface)를 통해 기본 클러스터에만 볼륨을 할당할 수 있습니다. 그러나 기본 클러스터에 볼륨을 한 개 이상 할당한 후에는 이 개체(기본 클러스터라고 함)가 사용자 인터페이스에 표시되며, 여기에서 이 엔터티를 관리할 수 있습니다.



== 중복 검사란?

중복 검사는 풀 또는 볼륨 그룹의 볼륨에 있는 데이터가 일관되는지 여부를 확인합니다. 이중화 데이터는 풀 또는 볼륨 그룹의 드라이브 중 하나에 장애가 발생할 경우 교체 드라이브에 대한 정보를 빠르게 재구성하는 데 사용됩니다.

한 번에 하나의 풀 또는 볼륨 그룹에서만 이 검사를 수행할 수 있습니다. 볼륨 중복 검사는 다음 작업을 수행합니다.

* RAID 3 볼륨, RAID 5 볼륨 또는 RAID 6 볼륨의 데이터 블록을 검색한 다음 각 블록의 중복 정보를 확인합니다. (RAID 3은 명령줄 인터페이스를 사용하는 볼륨 그룹에만 할당할 수 있습니다.)
* RAID 1 미러링 드라이브의 데이터 블록을 비교합니다.
* 데이터가 컨트롤러 펌웨어와 일치하지 않는 것으로 확인되면 중복 오류를 반환합니다.



NOTE: 동일한 풀 또는 볼륨 그룹에서 중복 검사를 즉시 실행하면 오류가 발생할 수 있습니다. 이 문제를 방지하려면 동일한 풀 또는 볼륨 그룹에서 다른 중복 검사를 실행하기 전에 1-2분 정도 기다리십시오.



== 보존 용량이란?

Preservation capacity는 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량(드라이브 수)입니다.

풀이 생성되면 시스템은 풀의 드라이브 수에 따라 기본 보존 용량을 자동으로 예약합니다.

풀은 재구성 중에 보존 용량을 사용하지만 볼륨 그룹은 동일한 목적으로 핫 스페어 드라이브를 사용합니다. 보존 용량 방법은 재구성을 더 빠르게 수행할 수 있도록 핫 스페어 드라이브에 비해 향상된 기능입니다. 보존 용량은 핫 스페어 드라이브의 경우 드라이브 하나가 아닌 풀의 여러 드라이브에 분산되므로 드라이브 한 개의 속도나 가용성에 의해 제한되지 않습니다.



== 애플리케이션에 가장 적합한 RAID 레벨은 무엇입니까?

볼륨 그룹의 성능을 최대화하려면 적절한 RAID 레벨을 선택해야 합니다.

볼륨 그룹에 액세스하는 응용 프로그램의 읽기 및 쓰기 비율을 알면 적절한 RAID 레벨을 결정할 수 있습니다. 성능 페이지를 사용하여 이러한 비율을 얻습니다.



=== RAID 레벨 및 애플리케이션 성능

RAID는 수준이라는 일련의 구성을 사용하여 드라이브에서 사용자 및 중복 데이터를 기록하고 검색하는 방법을 결정합니다. 각 RAID 레벨은 서로 다른 성능 기능을 제공합니다. RAID 5 및 RAID 6 구성의 탁월한 읽기 성능 때문에 읽기 비율이 높은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨을 사용하여 잘 수행됩니다.

읽기 백분율(쓰기 집약적)이 낮은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨에서 제대로 작동하지 않습니다. 성능 저하는 컨트롤러가 RAID 5 볼륨 그룹 또는 RAID 6 볼륨 그룹의 드라이브에 데이터 및 중복 데이터를 기록하는 방식으로 인해 발생합니다.

다음 정보를 기반으로 RAID 레벨을 선택합니다.



==== RAID 0

* 설명: *

* 비중복, 스트라이핑 모드
* RAID 0은 볼륨 그룹의 모든 드라이브에 데이터를 스트라이핑합니다.


* 데이터 보호 기능: *

* 고가용성 요구 사항에 대해서는 RAID 0을 권장하지 않습니다. RAID 0은 중요하지 않은 데이터에 적합합니다.
* 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨이 실패하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* RAID 레벨 0에는 최소 하나의 드라이브가 필요합니다.
* RAID 0 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다.
* 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




==== RAID 1 또는 RAID 10

* 설명: *

* 스트라이핑/미러 모드


* 작동 방식: *

* RAID 1은 디스크 미러링을 사용하여 두 개의 중복 디스크에 동시에 데이터를 씁니다.
* RAID 10은 드라이브 스트라이핑을 사용하여 미러링된 드라이브 쌍의 집합에 걸쳐 데이터를 스트라이핑합니다.


* 데이터 보호 기능: *

* RAID 1 및 RAID 10은 고성능과 최상의 데이터 가용성을 제공합니다.
* RAID 1 및 RAID 10은 드라이브 미러링을 사용하여 한 드라이브에서 다른 드라이브로 정확하게 복사합니다.
* 드라이브 쌍의 드라이브 중 하나에 장애가 발생하면 스토리지 어레이가 데이터 또는 서비스의 손실 없이 다른 드라이브로 즉시 전환할 수 있습니다.
* 단일 드라이브 장애로 인해 관련 볼륨의 성능이 저하됩니다. 미러 드라이브를 통해 데이터에 액세스할 수 있습니다.
* 볼륨 그룹의 드라이브 쌍 장애로 인해 연결된 모든 볼륨이 장애가 발생하고 데이터 손실이 발생할 수 있습니다.


* 드라이브 번호 요구 사항: *

* RAID 1에는 사용자 데이터용 드라이브 1개와 미러링된 데이터용 드라이브 1개 등 최소 2개의 드라이브가 필요합니다.
* 드라이브를 4개 이상 선택하면 사용자 데이터를 위한 드라이브 2개와 미러링된 데이터를 위한 드라이브 2개 등 RAID 10이 볼륨 그룹 전체에 자동으로 구성됩니다.
* 볼륨 그룹에 짝수의 드라이브가 있어야 합니다. 드라이브 수가 짝수이고 할당되지 않은 드라이브가 일부 있는 경우 * Pools & Volume Groups * 로 이동하여 볼륨 그룹에 드라이브를 추가하고 작업을 재시도하십시오.
* RAID 1 및 RAID 10 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다. 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




==== RAID 5

* 설명: *

* 높은 I/O 모드.


* 작동 방식: *

* 사용자 데이터 및 중복 정보(패리티)는 드라이브에 스트라이핑됩니다.
* 하나의 드라이브에 해당하는 용량이 중복 정보에 사용됩니다.


* 데이터 보호 기능 *

* RAID 5 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하됩니다. 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
* RAID 5 볼륨 그룹에서 두 개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* 볼륨 그룹에 최소 3개의 드라이브가 있어야 합니다.
* 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.




==== RAID 6

* 설명: *

* 높은 I/O 모드.


* 작동 방식: *

* 사용자 데이터 및 중복 정보(이중 패리티)는 드라이브에 스트라이핑됩니다.
* 두 드라이브의 동일한 용량이 중복 정보에 사용됩니다.


* 데이터 보호 기능: *

* RAID 6 볼륨 그룹에서 하나 또는 두 개의 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하되지만 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
* RAID 6 볼륨 그룹에서 3개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* 볼륨 그룹에 최소 5개의 드라이브가 있어야 합니다.
* 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.



NOTE: 풀의 RAID 레벨은 변경할 수 없습니다. 사용자 인터페이스는 풀을 RAID 6으로 자동 구성합니다.



=== RAID 레벨 및 데이터 보호

RAID 1, RAID 5 및 RAID 6은 드라이브 미디어에 중복 데이터를 기록하여 내결함성을 제공합니다. 중복 데이터는 데이터 사본(미러링)이거나 데이터에서 파생된 오류 정정 코드일 수 있습니다. 드라이브 장애가 발생할 경우 중복 데이터를 사용하여 교체 드라이브에 대한 정보를 빠르게 재구성할 수 있습니다.

단일 볼륨 그룹에서 단일 RAID 레벨을 구성합니다. 해당 볼륨 그룹의 모든 중복 데이터는 볼륨 그룹 내에 저장됩니다. 볼륨 그룹의 용량은 구성원 드라이브의 총 용량에서 중복 데이터를 위해 예약된 용량을 뺀 값입니다. 중복성에 필요한 용량은 사용된 RAID 레벨에 따라 다릅니다.



== 일부 드라이브가 표시되지 않는 이유는 무엇입니까?

Add Capacity 대화 상자에서 기존 풀 또는 볼륨 그룹에 용량을 추가하는 데 일부 드라이브를 사용할 수 없습니다.

드라이브는 다음과 같은 이유로 적합하지 않습니다.

* 드라이브를 할당하지 않고 안전하게 사용할 수 없어야 합니다. 다른 풀, 다른 볼륨 그룹에 이미 속해 있거나 핫 스페어로 구성된 드라이브는 사용할 수 없습니다. 드라이브 할당이 취소되었지만 보안이 설정된 경우 해당 드라이브를 수동으로 지워야 사용할 수 있습니다.
* 최적화되지 않은 상태의 드라이브는 해당되지 않습니다.
* 드라이브 용량이 너무 작으면 대상에서 제외됩니다.
* 드라이브 미디어 유형은 풀 또는 볼륨 그룹 내에서 일치해야 합니다. 다음을 혼합할 수 없습니다.
+
** 솔리드 스테이트 디스크(SSD)가 장착된 하드 디스크 드라이브(HDD)
** SAS 드라이브를 포함한 NVMe
** 512바이트 및 4KiB 볼륨 블록 크기의 드라이브


* 풀 또는 볼륨 그룹에 모든 보안 가능 드라이브가 포함되어 있는 경우 비보안 가능 드라이브가 표시되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 FIPS(Federal Information Processing Standards) 드라이브가 포함되어 있는 경우 비 FIPS 드라이브가 나열되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 DA(Data Assurance) 가능 드라이브가 포함되어 있고 풀 또는 볼륨 그룹에 하나 이상의 DA 지원 볼륨이 있는 경우, DA를 사용할 수 없는 드라이브는 사용할 수 없으므로 해당 풀 또는 볼륨 그룹에 추가할 수 없습니다. 그러나 풀 또는 볼륨 그룹에 DA 지원 볼륨이 없는 경우 DA를 사용할 수 없는 드라이브를 해당 풀 또는 볼륨 그룹에 추가할 수 있습니다. 이러한 드라이브를 혼합하려는 경우 DA 지원 볼륨을 생성할 수 없습니다.



NOTE: 새 드라이브를 추가하거나 풀 또는 볼륨 그룹을 삭제하여 스토리지 시스템에서 용량을 늘릴 수 있습니다.



== 보존 용량을 늘릴 수 없는 이유는 무엇입니까?

사용 가능한 모든 용량에 볼륨을 생성한 경우 보존 용량을 늘릴 수 없습니다.

Preservation capacity는 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량(드라이브 수)입니다. 풀이 생성되면 시스템은 풀의 드라이브 수에 따라 기본 보존 용량을 자동으로 예약합니다. 사용 가능한 모든 용량에 볼륨을 생성한 경우 드라이브를 추가하거나 볼륨을 삭제하여 풀에 용량을 추가하지 않으면 보존 용량을 늘릴 수 없습니다.

풀 및 볼륨 그룹에서 보존 용량을 변경할 수 있습니다. 편집할 풀을 선택합니다. 설정 보기/편집 * 을 클릭한 다음 * 설정 * 탭을 선택합니다.


NOTE: 보존 용량은 풀의 드라이브에 실제 보존 용량이 분산되어 있더라도 여러 드라이브로 지정됩니다.



== Data Assurance란 무엇입니까?

DA(Data Assurance)는 T10 PI(보호 정보) 표준을 구현하여 I/O 경로를 통해 데이터가 전송될 때 발생할 수 있는 오류를 확인하고 수정하여 데이터 무결성을 향상합니다.

일반적으로 Data Assurance 기능을 사용하면 컨트롤러와 드라이브 사이의 입출력 경로 부분을 확인할 수 있습니다. DA 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다.

이 기능을 활성화하면 스토리지 배열은 볼륨의 각 데이터 블록에 오류 검사 코드(순환 중복 검사 또는 CRC라고도 함)를 추가합니다. 데이터 블록이 이동된 후 스토리지 배열은 이러한 CRC 코드를 사용하여 전송 중에 오류가 발생했는지 확인합니다. 잠재적으로 손상된 데이터는 디스크에 기록되거나 호스트에 반환되지 않습니다. DA 기능을 사용하려면 새 볼륨을 생성할 때 DA를 지원하는 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 * DA * 옆에 * Yes * 가 표시됨).

DA가 가능한 입출력 인터페이스를 사용하여 이러한 DA 지원 볼륨을 호스트에 할당해야 합니다. DA를 지원할 수 있는 I/O 인터페이스로는 파이버 채널, SAS, iSCSI over TCP/IP, NVMe/FC, NVMe/IB, InfiniBand를 통한 NVMe/RoCE 및 iSER(RDMA/IB용 iSCSI 확장) DA는 InfiniBand를 통한 SRP에서 지원되지 않습니다.



== FDE/FIPS 보안이란 무엇입니까?

FDE/FIPS 보안이란 읽기 중에 고유 암호화 키를 사용하여 데이터를 암호화하고 해독하는 동안 데이터를 보호하는 보안 가능 드라이브를 말합니다.

이러한 보안 가능 드라이브는 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. FIPS 드라이브는 인증 테스트를 거쳤습니다.


NOTE: FIPS 지원이 필요한 볼륨의 경우 FIPS 드라이브만 사용합니다. 볼륨 그룹 또는 풀에서 FIPS 및 FDE 드라이브를 혼합하면 모든 드라이브가 FDE 드라이브로 처리됩니다. 또한 FDE 드라이브는 All-FIPS 볼륨 그룹 또는 풀에서 스페어로 추가하거나 사용할 수 없습니다.



== 보안 기능(드라이브 보안)이란 무엇입니까?

드라이브 보안은 스토리지 어레이에서 제거할 때 보안이 설정된 드라이브의 데이터에 대한 무단 액세스를 방지하는 기능입니다.

이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.



== 모든 SSD Cache 통계를 보고 해석하려면 어떻게 해야 합니까?

SSD Cache에 대한 공칭 통계 및 세부 통계를 볼 수 있습니다.

공칭 통계는 상세 통계의 하위 집합입니다. 자세한 통계는 모든 SSD 통계를 .csv 파일로 내보낼 때만 볼 수 있습니다. 통계를 검토 및 해석할 때는 통계의 조합을 통해 일부 해석이 파생된다는 점을 염두에 두십시오.



=== 공칭 통계

SSD 캐시 통계를 보려면 * 관리 * 페이지로 이동하십시오. 메뉴: Provisioning [Configure Pools & Volume Groups]를 선택합니다. 통계를 보려는 SSD Cache를 선택한 다음 menu:More [View Statistics](추가 [통계 보기])를 선택합니다. 공칭 통계는 SSD 캐시 통계 보기 대화 상자에 표시됩니다.


NOTE: EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.

이 목록에는 상세 통계의 하위 집합인 공칭 통계가 포함됩니다.



=== 자세한 통계

세부 통계는 공칭 통계와 추가 통계로 구성됩니다. 이러한 추가 통계는 공칭 통계와 함께 저장되지만, 공칭 통계와 달리 SSD 캐시 통계 보기 대화 상자에 표시되지 않습니다. 통계를 .csv 파일로 내보낸 후에만 자세한 통계를 볼 수 있습니다.

세부 통계는 공칭 통계 다음에 나열됩니다.



== 선반 손실 방지 및 서랍 손실 방지란 무엇입니까?

쉘프 손실 보호 및 드로어 손실 보호는 단일 쉘프 또는 드로어에 장애가 발생해도 데이터 액세스를 유지할 수 있는 풀 및 볼륨 그룹의 속성입니다.



=== 선반 손실 방지

쉘프는 드라이브 또는 드라이브와 컨트롤러를 포함합니다. 쉘프 손실 방지: 단일 드라이브 쉘프로 통신이 두절되는 경우 풀 또는 볼륨 그룹의 볼륨에서 데이터에 액세스할 수 있습니다. 예를 들어, 통신 장애가 발생할 경우 드라이브 쉘프에 대한 전원 공급이 중단되거나 두 I/O 모듈(IOM)이 모두 실패할 수 있습니다.


NOTE: 풀 또는 볼륨 그룹에서 드라이브가 이미 장애가 발생한 경우에는 쉘프 손실 보호가 보장되지 않습니다. 이 경우, 드라이브 쉘프와 풀 또는 볼륨 그룹의 다른 드라이브에 액세스하지 못하면 데이터가 손실됩니다.

쉘프 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

|===
| 레벨 | 쉘프 손실 방지 기준 | 필요한 최소 쉘프 수입니다 


| 수영장 | 풀은 5개 이상의 쉘프의 드라이브를 포함해야 하며 각 쉘프에 동일한 수의 드라이브가 있어야 합니다. 셸프 손실 보호는 고용량 셸프에는 적용되지 않습니다. 시스템에 고용량 셸프가 포함되어 있는 경우 문서함 손실 보호 를 참조하십시오. | 5 


| RAID 6 | 볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다. | 3 


| RAID 3 또는 RAID 5 | 볼륨 그룹의 각 드라이브는 별도의 쉘프에 있습니다. | 3 


| RAID 1 | RAID 1 쌍의 각 드라이브는 별도의 쉘프에 있어야 합니다. | 2 


| RAID 0 | 선반 손실 보호를 달성할 수 없습니다. | 해당 없음 
|===


=== 서랍 손실 방지

드라이브 액세스를 위해 서랍식 용지함은 셸프의 구획 중 하나입니다. 고용량 쉘프에만 서랍이 있습니다. 드로어 손실 보호는 단일 드로어와의 통신이 완전히 손실되는 경우 풀 또는 볼륨 그룹의 볼륨에 있는 데이터에 액세스할 수 있도록 보장합니다. 통신 손실의 예로는 드로어에 대한 전원 손실 또는 드로어 내 내부 구성 요소의 고장이 있습니다.


CAUTION: 풀 또는 볼륨 그룹에서 드라이브에 장애가 이미 발생한 경우에는 드로어 손실 보호가 보장되지 않습니다. 이 경우 드로어(풀 또는 볼륨 그룹의 다른 드라이브)에 액세스하지 못하게 되면 데이터가 손실됩니다.

드로어 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

|===
| 레벨 | 서랍 손실 방지 기준 | 필요한 최소 드로어 수입니다 


| 수영장 | 풀 후보는 모든 드로어의 드라이브를 포함해야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다. 풀에는 5개 이상의 서랍에서 나온 드라이브가 포함되어야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다. 60-드라이브 쉘프는 15, 20, 25, 30, 35, 40, 45, 50, 55 또는 60개 드라이브. 초기 생성 후 풀에 5의 배수로 증분을 추가할 수 있습니다. | 5 


| RAID 6 | 볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다. | 3 


| RAID 3 또는 5 | 볼륨 그룹의 각 드라이브는 별도의 드로어에 있습니다 | 3 


| RAID 1 | 미러링된 쌍의 각 드라이브는 별도의 드로어에 위치해야 합니다. | 2 


| RAID 0 | 문서함 손실 방지를 달성할 수 없습니다. | 해당 없음 
|===


== 선반 및 서랍 손실 방지를 어떻게 유지합니까?

풀 또는 볼륨 그룹의 쉘프 및 드로어 손실 보호를 유지하려면 다음 표에 나와 있는 기준을 사용하십시오.

|===
| 레벨 | 선반/서랍 손실 방지 기준 | 필요한 최소 쉘프/서랍 수 


| 수영장 | 쉘프의 경우 풀에는 단일 쉘프에 2개 이상의 드라이브가 없어야 합니다. 드로어의 경우 풀에는 각 드로어의 드라이브 수가 동일해야 합니다. | 6 서랍용 쉘프 5의 경우 


| RAID 6 | 볼륨 그룹은 단일 쉘프 또는 서랍에 2개 이상의 드라이브를 포함하지 않습니다. | 3 


| RAID 3 또는 RAID 5 | 볼륨 그룹의 각 드라이브는 별도의 쉘프 또는 드로어에 있습니다. | 3 


| RAID 1 | 미러링된 쌍의 각 드라이브는 별도의 쉘프 또는 드로어에 위치해야 합니다. | 2 


| RAID 0 | 선반/서랍 손실 방지를 달성할 수 없습니다. | 해당 없음 
|===

NOTE: 풀 또는 볼륨 그룹에서 드라이브가 이미 장애가 발생한 경우에는 쉘프/드로어 손실 보호가 유지되지 않습니다. 이 경우, 드라이브 쉘프 또는 드로어에 액세스하지 못하게 되고 결과적으로 풀 또는 볼륨 그룹의 다른 드라이브가 데이터 손실을 유발합니다.



== 풀의 최적화 용량은 얼마입니까?

SSD 드라이브는 용량의 일부가 할당되지 않은 경우 수명이 더 길고 쓰기 성능이 극대화됩니다.

풀과 연결된 드라이브의 경우 할당되지 않은 용량은 풀의 보존 용량, 사용 가능한 용량(볼륨에서 사용하지 않는 용량) 및 추가 최적화 용량으로 남겨 둔 사용 가능한 용량의 일부로 구성됩니다. 추가 최적화 용량은 사용 가능한 용량을 줄여 최적화 용량을 최소화하므로 볼륨 생성에 사용할 수 없습니다.

풀을 생성할 때 성능, 드라이브 마모 수명 및 가용 용량의 균형을 제공하는 권장 최적화 용량이 생성됩니다. Pool Settings(풀 설정) 대화 상자에 있는 Additional Optimization Capacity(추가 최적화 용량) 슬라이더를 사용하여 풀의 최적화 용량을 조정할 수 있습니다. 슬라이더를 조정하면 사용 가능한 용량을 희생하여 더 나은 성능과 드라이브 마모 수명을 얻을 수 있고, 성능과 드라이브 마모 수명을 희생하여 사용 가능한 추가 용량을 확보할 수 있습니다.


NOTE: 추가 최적화 용량 슬라이더는 EF600 및 EF300 스토리지 시스템에서만 사용할 수 있습니다.



== 볼륨 그룹의 최적화 용량은 무엇입니까?

SSD 드라이브는 용량의 일부가 할당되지 않은 경우 수명이 더 길고 쓰기 성능이 극대화됩니다.

볼륨 그룹과 연결된 드라이브의 경우 할당되지 않은 용량은 볼륨 그룹의 사용 가능한 용량(볼륨에서 사용하지 않는 용량)과 최적화 용량으로 남겨 둔 사용 가능한 용량의 일부로 구성됩니다. 추가 최적화 용량은 사용 가능한 용량을 줄여 최적화 용량을 최소화하므로 볼륨 생성에 사용할 수 없습니다.

볼륨 그룹이 생성되면 성능, 드라이브 마모 수명 및 가용 용량의 균형을 제공하는 권장 최적화 용량이 생성됩니다. 볼륨 그룹 설정 대화 상자의 추가 최적화 용량 슬라이더를 사용하여 볼륨 그룹의 최적화 용량을 조정할 수 있습니다. 슬라이더를 조정하면 사용 가능한 용량을 희생하여 더 나은 성능과 드라이브 마모 수명을 얻을 수 있고, 성능과 드라이브 마모 수명을 희생하여 사용 가능한 추가 용량을 확보할 수 있습니다.


NOTE: 추가 최적화 용량 슬라이더는 EF600 및 EF300 스토리지 시스템에서만 사용할 수 있습니다.



== 리소스 프로비저닝 기능은 무엇입니까?

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다. 이에 비해 기존의 일반 볼륨에서는 Data Assurance 보호 정보 필드를 초기화하고 각 RAID 스트라이프에서 데이터 및 RAID 패리티를 일관되게 만들기 위해 백그라운드 볼륨 초기화 작업 중에 모든 드라이브 블록이 매핑되거나 할당됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Logical Block Error Enable) 오류 복구 기능을 지원합니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 또한 호스트는 NVMe Dataset Management 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.



== 리소스 프로비저닝된 볼륨 기능에 대해 알아야 할 내용은 무엇입니까?

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.


NOTE: 현재 리소스 프로비저닝 기능을 사용할 수 없습니다. 일부 보기에서는 구성 요소가 리소스 프로비저닝 가능 상태로 보고될 수 있지만 나중에 업데이트할 때 다시 활성화될 때까지 리소스 프로비저닝된 볼륨을 생성하는 기능이 비활성화되었습니다.



=== 리소스가 프로비저닝된 볼륨

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다. 이에 비해 기존의 일반 볼륨에서는 Data Assurance 보호 정보 필드를 초기화하고 각 RAID 스트라이프에서 데이터 및 RAID 패리티를 일관되게 만들기 위해 백그라운드 볼륨 초기화 작업 중에 모든 드라이브 블록이 매핑되거나 할당됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Logical Block Error Enable) 오류 복구 기능을 지원합니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 또한 호스트는 NVMe Dataset Management 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.



=== 기능 활성화 및 비활성화

드라이브가 DULBE를 지원하는 시스템에서는 리소스 프로비저닝이 기본적으로 사용됩니다. 풀 및 볼륨 그룹에서 기본 설정을 해제할 수 있습니다. 리소스 프로비저닝을 해제하는 작업은 기존 볼륨에 대해 영구적으로 수행되므로 되돌릴 수 없습니다. 즉, 이러한 볼륨 그룹 및 풀에 대해 리소스 프로비저닝을 다시 설정할 수 없습니다.

그러나 새로 생성한 모든 볼륨에 대해 리소스 프로비저닝을 다시 활성화하려면 설정 [시스템] 메뉴에서 다시 활성화할 수 있습니다. 리소스 프로비저닝을 다시 설정하면 새로 생성한 볼륨 그룹 및 풀만 영향을 받습니다. 기존 볼륨 그룹 및 풀은 변경되지 않습니다. 필요한 경우 설정 [시스템] 메뉴에서 자원 프로비저닝을 다시 비활성화할 수도 있습니다.



== 내부 보안 키와 외부 보안 키 관리의 차이점은 무엇입니까?

드라이브 보안 기능을 구현할 때 스토리지 배열에서 보안 지원 드라이브를 제거할 때 내부 보안 키 또는 외부 보안 키를 사용하여 데이터를 잠글 수 있습니다.

보안 키는 문자열을 말합니다. 이 문자열은 스토리지 어레이에서 보안이 설정된 드라이브와 컨트롤러 간에 공유됩니다. 내부 키는 컨트롤러의 영구 메모리에 유지됩니다. 외부 키는 KMIP(Key Management Interoperability Protocol)를 사용하여 별도의 키 관리 서버에 유지됩니다.



== 보안 키를 생성하기 전에 알아야 할 사항은 무엇입니까?

보안 키는 스토리지 시스템 내의 컨트롤러 및 보안 지원 드라이브에서 공유됩니다. 스토리지 배열에서 보안 지원 드라이브를 제거하면 보안 키가 무단 액세스로부터 데이터를 보호합니다.

다음 방법 중 하나를 사용하여 보안 키를 만들고 관리할 수 있습니다.

* 컨트롤러의 영구 메모리에서 내부 키 관리.
* 외부 키 관리 서버의 외부 키 관리.




== 내부 키 관리

내부 키는 컨트롤러의 영구 메모리에서 액세스할 수 없는 위치에 유지 및 "숨김"됩니다. 내부 보안 키를 생성하기 전에 다음을 수행해야 합니다.

. 스토리지 배열에 보안 가능 드라이브를 설치합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
. 드라이브 보안 기능이 활성화되어 있는지 확인합니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.


그런 다음 식별자 및 암호 구문을 정의하는 내부 보안 키를 만들 수 있습니다. 식별자는 보안 키와 연결된 문자열이며, 컨트롤러와 키에 연결된 모든 드라이브에 저장됩니다. 암호 구문은 백업을 위해 보안 키를 암호화하는 데 사용됩니다. 작업을 마치면 보안 키가 컨트롤러에 액세스할 수 없는 위치에 저장됩니다. 그런 다음 보안이 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.



=== 외부 키 관리

외부 키는 KMIP(Key Management Interoperability Protocol)를 사용하여 별도의 키 관리 서버에 유지됩니다. 외부 보안 키를 만들기 전에 다음을 수행해야 합니다.

. 스토리지 배열에 보안 가능 드라이브를 설치합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
. 드라이브 보안 기능이 활성화되어 있는지 확인합니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오
. 서명된 클라이언트 인증서 파일을 가져옵니다. 클라이언트 인증서가 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP 요청을 신뢰할 수 있습니다.
+
.. 먼저 CSR(Client Certificate Signing Request)을 완료하고 다운로드합니다. 설정 [인증서 > 키 관리 > CSR 완료] 메뉴로 이동합니다.
.. 그런 다음 키 관리 서버에서 신뢰할 수 있는 CA로부터 서명된 클라이언트 인증서를 요청합니다. (다운로드한 CSR 파일을 사용하여 키 관리 서버에서 클라이언트 인증서를 생성하고 다운로드할 수도 있습니다.)
.. 클라이언트 인증서 파일이 있는 경우 해당 파일을 System Manager에 액세스할 호스트에 복사합니다.


. 키 관리 서버에서 인증서 파일을 가져온 다음 System Manager에 액세스하는 호스트에 해당 파일을 복사합니다. 키 관리 서버 인증서는 키 관리 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다. 키 관리 서버에 루트, 중간 또는 서버 인증서를 사용할 수 있습니다.


그런 다음 외부 키를 생성하여 키 관리 서버의 IP 주소와 KMIP 통신에 사용되는 포트 번호를 정의할 수 있습니다. 이 프로세스 중에 인증서 파일도 로드합니다. 작업을 마치면 입력한 자격 증명을 사용하여 시스템이 키 관리 서버에 연결됩니다. 그런 다음 보안이 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.



== 암호문을 정의해야 하는 이유는 무엇입니까?

암호 구문은 로컬 관리 클라이언트에 저장된 보안 키 파일을 암호화하고 해독하는 데 사용됩니다. 암호 구문이 없으면 보안 키를 해독할 수 없으며 다른 스토리지 배열에 다시 설치한 경우 보안 활성 드라이브에서 데이터의 잠금을 해제하는 데 사용할 수 없습니다.
