---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-array-discovery.html 
keywords: discover arrays vCenter plugin, discover storage resources Plugin for vCenter, resolve certificates vCenter plugin 
summary: Plugin for vCenter 인터페이스를 사용하여 네트워크에 있는 어레이의 IP 주소를 검색합니다. 
---
= 플러그인에서 스토리지 시스템을 검색합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
스토리지 리소스를 표시하고 관리하려면 vCenter용 Storage Plugin 인터페이스를 사용하여 네트워크에 있는 어레이의 IP 주소를 검색해야 합니다.



== 1단계: 검색할 네트워크 주소를 입력합니다

.시작하기 전에
* 어레이 컨트롤러의 네트워크 IP 주소(또는 주소 범위)를 알아야 합니다.
* 스토리지 배열이 올바르게 설정 및 구성되어 있어야 하며 스토리지 배열 로그인 자격 증명(사용자 이름 및 암호)을 알고 있어야 합니다.


.단계
. 관리 페이지에서 * 추가/검색 * 을 선택합니다.
+
네트워크 주소 범위 입력 대화 상자가 나타납니다.

. 다음 중 하나를 수행합니다.
+
** 하나의 어레이를 검색하려면 * 단일 스토리지 어레이 검색 * 라디오 버튼을 선택한 다음 스토리지 어레이에 있는 컨트롤러 중 하나의 IP 주소를 입력합니다.
** 여러 스토리지 어레이를 검색하려면 * 네트워크 범위 내의 모든 스토리지 배열 검색 * 라디오 버튼을 선택한 다음 시작 네트워크 주소와 끝 네트워크 주소를 입력하여 로컬 하위 네트워크를 검색합니다.


. 검색 시작 * 을 클릭합니다.
+
검색 프로세스가 시작되면 검색된 스토리지 시스템이 대화 상자에 표시됩니다. 검색 프로세스를 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
관리 가능한 어레이가 검색되지 않으면 스토리지 어레이가 네트워크에 올바르게 연결되어 있고 할당된 주소가 범위 내에 있는지 확인합니다. 추가/검색 페이지로 돌아가려면 * New Discovery Parameters * 를 클릭합니다.

. 관리 도메인에 추가할 스토리지 배열 옆의 확인란을 선택합니다.
+
시스템은 관리 도메인에 추가할 각 스토리지에 대해 자격 증명 검사를 수행합니다. 계속하기 전에 신뢰할 수 없는 인증서의 문제를 해결해야 할 수 있습니다.

. 마법사의 다음 단계로 진행하려면 * Next * (다음 *)를 클릭합니다.
+
스토리지 배열에 유효한 인증서가 있는 경우 로 이동합니다 <<Step 3: Provide passwords>>.

+
스토리지 배열에 유효한 인증서가 없는 경우 자체 서명된 인증서 확인 대화 상자가 나타납니다. 로 이동합니다 <<Step 2: Resolve untrusted certificates during discovery>>.

+
CA 서명 인증서를 가져오려면 검색 마법사에서 취소하고 왼쪽 패널에서 * 인증서 관리 * 를 클릭합니다. 자세한 지침은 온라인 도움말을 참조하십시오.





== 2단계: 검색 중에 신뢰할 수 없는 인증서를 해결합니다

검색 프로세스를 진행하기 전에 인증서 문제를 해결해야 합니다.

. 자체 서명된 인증서 확인 대화 상자가 열리면 신뢰할 수 없는 인증서에 대해 표시되는 정보를 검토합니다. 자세한 내용을 보려면 표의 맨 끝에 있는 줄임표를 클릭하고 팝업 메뉴에서 * 보기 * 를 선택하십시오.
. 다음 중 하나를 수행합니다.
+
** 검색된 스토리지 배열에 대한 접속을 신뢰할 수 있는 경우 * Next * (다음 *)를 클릭한 다음 * Yes * (예 *)를 클릭하여 확인하고 마법사의 다음 대화 상자로 이동합니다. 자체 서명된 인증서가 신뢰할 수 있는 것으로 표시되고 스토리지 배열이 플러그인에 추가됩니다.
** 스토리지 배열에 대한 연결을 신뢰하지 않는 경우, * Cancel * 을 선택하고 각 스토리지 배열의 보안 인증서 전략을 확인한 후 추가하십시오.


. 마법사의 다음 단계로 진행하려면 * Next * (다음 *)를 클릭합니다.




== 3단계: 암호를 입력합니다

검색을 위한 마지막 단계로 관리 도메인에 추가할 스토리지 배열에 대한 암호를 입력해야 합니다.

. 검색된 각 스토리지 시스템의 필드에 관리자 암호를 입력합니다.
. 마침 * 을 클릭합니다.
+
시스템이 지정된 스토리지 어레이에 연결하는 데 몇 분 정도 걸릴 수 있습니다. 프로세스가 완료되면 스토리지 어레이가 관리 도메인에 추가되고 선택한 그룹에 연결됩니다(지정된 경우).


