---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-provisioning.html 
keywords: create volumes vCenter plugin, provision Plugin for vCenter, vCenter plugin storage provisioning, vCenter plugin host 
summary: Plugin for vCenter를 사용하여 볼륨을 생성하고 호스트에 볼륨을 할당한 다음 볼륨을 데이터 저장소에 할당합니다. 
---
= 플러그인에서 스토리지를 프로비저닝합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
스토리지를 프로비저닝하려면 볼륨을 생성하고 호스트에 볼륨을 할당한 다음 볼륨을 데이터 저장소에 할당합니다.



== 1단계: 볼륨 생성

볼륨은 스토리지 어레이에서 스토리지 공간을 관리하고 구성하는 데이터 컨테이너입니다. 스토리지 배열에서 사용 가능한 스토리지 용량에서 볼륨을 생성하여 시스템 리소스를 구성할 수 있습니다. "볼륨"의 개념은 빠른 액세스를 위해 파일을 구성하기 위해 컴퓨터의 폴더/디렉토리를 사용하는 것과 비슷합니다.

볼륨은 호스트에서 볼 수 있는 유일한 데이터 계층입니다. SAN 환경에서는 볼륨이 LUN(논리 유닛 번호)에 매핑됩니다. 이러한 LUN은 스토리지 시스템에서 지원하는 하나 이상의 호스트 액세스 프로토콜을 사용하여 액세스할 수 있는 사용자 데이터를 저장합니다.

.단계
. 관리 페이지에서 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Manage Volumes](볼륨 관리)를 선택합니다.
. 메뉴: Create [Volumes](볼륨 생성)를 선택합니다.
+
호스트 선택 대화 상자가 나타납니다.

. 드롭다운 목록에서 볼륨을 할당할 특정 호스트 또는 호스트 클러스터를 선택하거나 나중에 호스트 또는 호스트 클러스터를 할당하도록 선택합니다.
. 선택한 호스트 또는 호스트 클러스터에 대한 볼륨 생성 순서를 계속하려면 * 다음 * 을 클릭합니다.
+
워크로드 선택 대화 상자가 나타납니다. 워크로드에는 유사한 특성의 볼륨이 포함되어 있으며 이 볼륨은 워크로드가 지원하는 애플리케이션의 유형에 따라 최적화됩니다. 워크로드를 정의하거나 기존 워크로드를 선택할 수 있습니다.

. 다음 중 하나를 수행합니다.
+
** 기존 워크로드에 대한 볼륨 생성 * 옵션을 선택한 다음 드롭다운 목록에서 워크로드를 선택합니다.
** 새 작업 부하 생성 * 옵션을 선택하여 지원되는 응용 프로그램 또는 “기타” 응용 프로그램에 대한 새 작업 부하를 정의한 다음 다음 다음 단계를 수행합니다.
+
... 드롭다운 목록에서 새 워크로드를 생성할 애플리케이션의 이름을 선택합니다. 이 스토리지 배열에서 사용하려는 애플리케이션이 나열되지 않은 경우 "기타" 항목 중 하나를 선택합니다.
... 생성할 워크로드의 이름을 입력합니다.




. 다음 * 을 클릭합니다. 워크로드가 지원되는 애플리케이션 유형과 연결되어 있는 경우 요청된 정보를 입력하고, 그렇지 않으면 다음 단계로 이동합니다.
+
볼륨 추가/편집 대화 상자가 나타납니다. 이 대화 상자에서는 적합한 풀 또는 볼륨 그룹에서 볼륨을 생성합니다. 해당하는 각 풀 및 볼륨 그룹에 사용 가능한 드라이브 수와 총 사용 가능한 용량이 나타납니다. 일부 애플리케이션별 워크로드의 경우, 해당되는 각 풀 또는 볼륨 그룹은 제안된 볼륨 구성을 기준으로 제안된 용량을 표시하고 남은 사용 가능 용량을 GiB 단위로 표시합니다. 다른 워크로드의 경우 제안된 용량은 풀 또는 볼륨 그룹에 볼륨을 추가하고 보고된 용량을 지정할 때 나타납니다.

. 볼륨 추가를 시작하기 전에 다음 표의 지침을 읽으십시오.
+
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
여유 용량
 a| 
볼륨이 풀 또는 볼륨 그룹에서 생성되기 때문에 선택한 풀 또는 볼륨 그룹에 충분한 가용 용량이 있어야 합니다.



 a| 
DA(Data Assurance)
 a| 
DA 지원 볼륨을 생성하려면 사용하려는 호스트 연결이 DA를 지원해야 합니다.

** DA 지원 볼륨을 생성하려면 DA를 지원하는 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "DA" 옆에 * Yes * 가 표시됨).
** DA 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다. DA 보호 기능은 컨트롤러를 통해 드라이브로 데이터가 전송될 때 발생할 수 있는 오류를 검사하고 수정합니다. 새 볼륨에 대해 DA 가능 풀 또는 볼륨 그룹을 선택하면 오류가 감지되고 수정됩니다.
** 스토리지 시스템의 컨트롤러에 있는 호스트 접속 중 하나라도 DA를 지원하지 않으면 연결된 호스트가 DA 지원 볼륨의 데이터에 액세스할 수 없습니다.




 a| 
드라이브 보안
 a| 
보안이 설정된 볼륨을 생성하려면 스토리지 배열에 대한 보안 키를 생성해야 합니다.

** 보안이 설정된 볼륨을 생성하려면 보안이 가능한 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "보안 가능" 옆에 * 예 * 가 표시됨).
** 드라이브 보안 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다. 보안 가능 드라이브는 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 보안이 설정된 드라이브는 쓰기 중에 데이터를 암호화하고 읽기 중에 고유 암호화 키를 사용하여 데이터를 해독합니다.
** 풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.




 a| 
리소스 프로비저닝
 a| 
리소스 프로비저닝된 볼륨을 만들려면 모든 드라이브가 DULBE(할당 취소 또는 기록되지 않은 논리적 블록 오류) 옵션이 있는 NVMe 드라이브여야 합니다.

|===
. 이전 단계에서 "기타" 또는 애플리케이션별 워크로드를 선택했는지 여부에 따라 다음 작업 중 하나를 선택합니다.
+
** * 기타 * – 하나 이상의 볼륨을 생성하는 데 사용할 각 풀 또는 볼륨 그룹에서 * 새 볼륨 추가 * 를 클릭합니다.
** * 애플리케이션별 워크로드 * – * 다음 * 을 클릭하여 선택한 워크로드에 대해 시스템 권장 볼륨 및 특성을 수락하거나 * 볼륨 편집 * 을 클릭하여 선택한 워크로드에 대해 시스템 권장 볼륨 및 특성을 변경, 추가 또는 삭제합니다.
+
다음 필드가 나타납니다.

+
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
볼륨 이름
 a| 
볼륨 생성 시퀀스 중에 볼륨에 기본 이름이 할당됩니다. 기본 이름을 그대로 사용하거나 볼륨에 저장된 데이터의 유형을 나타내는 추가 설명을 제공할 수 있습니다.



 a| 
보고된 용량
 a| 
새 볼륨의 용량과 사용할 용량 단위(MiB, GiB 또는 TiB)를 정의합니다. 일반 볼륨의 경우 최소 용량은 1MiB이고 최대 용량은 풀 또는 볼륨 그룹에 있는 드라이브의 수와 용량에 따라 결정됩니다. 풀의 용량은 4GiB 단위로 할당됩니다. 4GiB의 배수에 포함되지 않은 용량은 할당되지만 사용할 수 없습니다. 전체 용량을 사용할 수 있도록 용량을 4GiB 단위로 지정합니다. 사용할 수 없는 용량이 있는 경우, 볼륨을 다시 얻을 수 있는 유일한 방법은 볼륨의 용량을 늘리는 것입니다.



 a| 
볼륨 유형
 a| 
"애플리케이션별 워크로드"를 선택한 경우 볼륨 유형 필드가 나타납니다. 애플리케이션별 워크로드를 위해 생성된 볼륨 유형을 나타냅니다.



 a| 
볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
볼륨에 대해 생성할 수 있는 블록 크기를 표시합니다.

*** 512 ~ 512바이트
*** 4K – 4,096바이트




 a| 
세그먼트 크기
 a| 
에는 볼륨 그룹의 볼륨에만 표시되는 세그먼트 크기 조정 설정이 나와 있습니다. 세그먼트 크기를 변경하여 성능을 최적화할 수 있습니다.

* 허용된 세그먼트 크기 전환 * – 시스템이 허용되는 세그먼트 크기 전환을 결정합니다. 현재 세그먼트 크기에서 잘못 전환되는 세그먼트 크기는 드롭다운 목록에서 사용할 수 없습니다. 허용되는 전이는 일반적으로 현재 세그먼트 크기의 두 배 또는 절반입니다. 예를 들어 현재 볼륨 세그먼트 크기가 32KiB인 경우 16KiB 또는 64KiB의 새 볼륨 세그먼트 크기가 허용됩니다.

* SSD 캐시 사용 볼륨 * – SSD 캐시 사용 볼륨에 대해 4KiB 세그먼트 크기를 지정할 수 있습니다. 작은 블록 입출력 작업을 처리하는 SSD Cache 지원 볼륨(예: 16KiB 입출력 블록 크기 이하)에 대해서만 4KiB 세그먼트 크기를 선택해야 합니다. 대규모 블록 순차적 작업을 처리하는 SSD Cache 지원 볼륨의 세그먼트 크기로 4KiB를 선택하면 성능에 영향을 미칠 수 있습니다.

* 세그먼트 크기를 변경하는 시간 * – 볼륨의 세그먼트 크기를 변경하는 시간은 다음 변수에 따라 다릅니다.

*** 호스트로부터의 I/O 로드
*** 볼륨의 수정 우선 순위입니다
*** 볼륨 그룹의 드라이브 수입니다
*** 드라이브 채널 수입니다
*** 스토리지 어레이 컨트롤러의 처리 능력


볼륨의 세그먼트 크기를 변경하면 I/O 성능에 영향을 미치지만 데이터를 계속 사용할 수 있습니다.



 a| 
보안 가능
 a| 
* 예 * 는 풀 또는 볼륨 그룹의 드라이브가 암호화 가능한 경우에만 "보안 가능" 옆에 표시됩니다. 드라이브 보안은 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 이 옵션은 드라이브 보안 기능이 설정되어 있고 스토리지 배열에 대한 보안 키가 설정된 경우에만 사용할 수 있습니다. 풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.



| DA | * 예 * 는 풀 또는 볼륨 그룹의 드라이브가 DA(Data Assurance)를 지원하는 경우에만 "DA" 옆에 표시됩니다. DA는 전체 스토리지 시스템에서 데이터 무결성을 높입니다. DA를 사용하면 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 스토리지 어레이에서 확인할 수 있습니다. 새 볼륨에 DA를 사용하면 오류가 감지됩니다. 
|===


. 선택한 응용 프로그램에 대한 볼륨 생성 순서를 계속하려면 * 다음 * 을 클릭합니다.
. 마지막 단계에서는 생성하려는 볼륨의 요약을 검토하고 필요한 내용을 변경합니다. 변경하려면 * 뒤로 * 를 클릭합니다. 볼륨 구성이 만족스러우면 * 마침 * 을 클릭합니다.




== 2단계: 호스트 액세스를 생성하고 볼륨을 할당합니다

호스트를 자동으로 또는 수동으로 생성할 수 있습니다.

* * 자동 * -- SCSI 기반(NVMe-oF 아님) 호스트의 자동 호스트 생성이 HCA(Host Context Agent)에 의해 시작됩니다. HCA는 스토리지 배열에 연결된 각 호스트에 설치할 수 있는 유틸리티입니다. HCA가 설치된 각 호스트는 I/O 경로를 통해 구성 정보를 스토리지 어레이 컨트롤러로 푸시합니다. 호스트 정보에 따라 컨트롤러는 자동으로 호스트와 관련 호스트 포트를 생성하고 호스트 유형을 설정합니다. 필요한 경우 호스트 구성을 추가로 변경할 수 있습니다. HCA가 자동 감지를 수행한 후 호스트는 다음 속성을 사용하여 자동으로 구성됩니다.
+
** 호스트의 시스템 이름에서 파생된 호스트 이름입니다.
** 호스트와 연결된 호스트 식별자 포트입니다.
** 호스트의 호스트 운영 체제 유형입니다.





NOTE: Linux 및 Windows용 호스트 컨텍스트 에이전트 소프트웨어는 에서 사용할 수 있습니다 https://mysupport.netapp.com/site/downloads["NetApp 지원 - 다운로드"^].


NOTE: 호스트는 독립 실행형 호스트로 생성되지만 HCA는 호스트 클러스터를 자동으로 생성하거나 추가하지 않습니다.

* * 수동 * – 수동 호스트 생성 중에 호스트 포트 식별자를 목록에서 선택하거나 수동으로 입력하여 연결합니다. 호스트를 생성한 후 볼륨에 대한 액세스를 공유하려는 경우 호스트에 볼륨을 할당하거나 호스트 클러스터에 추가할 수 있습니다.




=== HCA를 사용하여 호스트를 자동으로 검색합니다

HCA(Host Context Agent)에서 호스트를 자동으로 검색한 다음 정보가 올바른지 확인할 수 있습니다.

.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. 스토리지 [호스트] 메뉴를 선택합니다.
+
이 표에는 자동으로 생성된 호스트가 나열됩니다.

. HCA에서 제공하는 정보(이름, 호스트 유형, 호스트 포트 식별자)가 올바른지 확인합니다.
. 정보를 변경해야 하는 경우 호스트를 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.




=== 호스트를 수동으로 생성합니다

.시작하기 전에
다음 지침을 읽으십시오.

* 사용자 환경 내에 이미 스토리지 시스템을 추가하거나 검색한 상태여야 합니다.
* 호스트와 연결된 호스트 식별자 포트를 정의해야 합니다.
* 호스트에 할당된 시스템 이름과 동일한 이름을 제공해야 합니다.
* 선택한 이름이 이미 사용 중인 경우에는 이 작업이 성공하지 않습니다.
* 이름의 길이는 30자를 초과할 수 없습니다.


.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. MENU: Create [Host] 를 클릭합니다.
+
Create Host 대화 상자가 나타납니다.

. 필요에 따라 호스트 설정을 선택합니다.
+
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
새 호스트의 이름을 입력합니다.



 a| 
호스트 운영 체제 유형입니다
 a| 
드롭다운 목록에서 새 호스트에서 실행 중인 운영 체제를 선택합니다.



 a| 
호스트 인터페이스 유형입니다
 a| 
(선택 사항) 스토리지 배열에서 지원되는 호스트 인터페이스 유형이 두 개 이상인 경우 사용할 호스트 인터페이스 유형을 선택합니다.



 a| 
호스트 포트
 a| 
다음 중 하나를 수행합니다.

** * I/O 인터페이스 선택 * -- 일반적으로 호스트 포트는 로그인되어 있고 드롭다운 목록에서 사용할 수 있어야 합니다. 목록에서 호스트 포트 식별자를 선택할 수 있습니다.
** * 수동 추가 * -- 호스트 포트 식별자가 목록에 표시되지 않으면 호스트 포트가 로그인되어 있지 않은 것입니다. HBA 유틸리티 또는 iSCSI 이니시에이터 유틸리티를 사용하여 호스트 포트 식별자를 찾아 호스트에 연결할 수 있습니다.


호스트 포트 식별자를 수동으로 입력하거나 유틸리티에서 호스트 포트 필드로 복사/붙여 넣을 수 있습니다(한 번에 하나씩).

호스트와 연결하려면 한 번에 하나의 호스트 포트 식별자를 선택해야 하지만 호스트와 연결된 식별자를 계속 선택할 수 있습니다. 각 식별자는 호스트 포트 필드에 표시됩니다. 필요한 경우 옆에 있는 * X * 를 선택하여 식별자를 제거할 수도 있습니다.



 a| 
CHAP 이니시에이터 암호를 설정합니다
 a| 
(선택 사항) iSCSI IQN을 사용하여 호스트 포트를 선택하거나 수동으로 입력한 경우, CHAP(Challenge Handshake Authentication Protocol)를 사용하여 인증하기 위해 스토리지 배열에 액세스를 시도하는 호스트가 필요한 경우 * Set CHAP initiator secret * 확인란을 선택합니다. 선택하거나 수동으로 입력한 각 iSCSI 호스트 포트에 대해 다음을 수행합니다.

** CHAP 인증을 위해 각 iSCSI 호스트 이니시에이터에 설정된 것과 동일한 CHAP 암호를 입력합니다. 상호 CHAP 인증(호스트가 스토리지 어레이에서 자체적으로 유효성을 검사할 수 있도록 하는 양방향 인증)을 사용하는 경우, 초기 설정 시 또는 설정을 변경하여 스토리지 배열에 대한 CHAP 암호를 설정해야 합니다.
** 호스트 인증이 필요하지 않은 경우 필드를 비워 둡니다.


현재 사용되는 유일한 iSCSI 인증 방법은 CHAP입니다.

|===
. Create * 를 클릭합니다.
. 호스트 정보를 업데이트해야 하는 경우 테이블에서 호스트를 선택하고 * 설정 보기/편집 * 을 클릭합니다.
+
호스트가 성공적으로 생성된 후 시스템은 호스트에 대해 구성된 각 호스트 포트(사용자 레이블)의 기본 이름을 생성합니다. 기본 별칭은 "<Hostname_Port Number>"입니다. 예를 들어, 호스트 IPT에 대해 생성된 첫 번째 포트의 기본 별칭은 "ipt_1"입니다.

. 다음으로, I/O 작업에 사용할 수 있도록 호스트 또는 호스트 클러스터에 볼륨을 할당해야 합니다. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. 볼륨을 할당할 호스트 또는 호스트 클러스터를 선택한 다음 * 볼륨 할당 * 을 클릭합니다.
+
할당할 수 있는 모든 볼륨이 나열된 대화 상자가 나타납니다. 특정 볼륨을 쉽게 찾을 수 있도록 열을 정렬하거나 필터 상자에 원하는 항목을 입력할 수 있습니다.

. 할당할 각 볼륨 옆의 확인란을 선택하거나 표 머리글에서 확인란을 선택하여 모든 볼륨을 선택합니다.
. 작업을 완료하려면 * 배정 * 을 클릭하십시오.
+
시스템은 다음 작업을 수행합니다.

+
** 할당된 볼륨은 다음으로 사용 가능한 LUN 번호를 받습니다. 호스트는 LUN 번호를 사용하여 볼륨을 액세스합니다.
** 사용자 제공 볼륨 이름이 호스트에 연결된 볼륨 목록에 나타납니다. 해당하는 경우 공장 구성 액세스 볼륨이 호스트와 연결된 볼륨 목록에도 표시됩니다.






== 3단계: vSphere Client에서 데이터 저장소를 생성합니다

vSphere Client에서 데이터 저장소를 생성하려면 VMware Doc Center에서 다음 항목을 참조하십시오.

* https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-7EB0CE06-02DD-4B31-85C7-E54993CC06DC.html["vSphere Client에서 VMFS 데이터 저장소를 생성합니다"^]




=== 볼륨 용량을 늘려 기존 데이터 저장소의 용량을 늘립니다

풀 또는 볼륨 그룹에서 사용할 수 있는 가용 용량을 사용하여 볼륨의 보고된 용량(호스트에 보고된 용량)을 늘릴 수 있습니다.

.시작하기 전에
다음을 확인합니다.

* 볼륨의 연결된 풀 또는 볼륨 그룹에서 충분한 가용 용량을 사용할 수 있습니다.
* 볼륨은 최적이며 수정 상태가 아닙니다.
* 볼륨에서 사용 중인 핫 스페어 드라이브가 없습니다. (볼륨 그룹의 볼륨에만 적용됩니다.)



NOTE: 볼륨 용량 증가는 특정 운영 체제에서만 지원됩니다. LUN 확장을 지원하지 않는 호스트 운영 체제에서 볼륨 용량을 늘릴 경우 확장된 용량을 사용할 수 없으며 원래 볼륨 용량을 복원할 수 없습니다.

.단계
. vSphere Client 내에서 플러그인으로 이동합니다.
. 플러그인 내에서 원하는 스토리지 배열을 선택합니다.
. Provisioning * 을 클릭하고 * Manage Volumes * 를 선택합니다.
. 용량을 늘릴 볼륨을 선택한 다음 * 용량 증가 * 를 선택합니다.
+
용량 증가 확인 대화 상자가 나타납니다.

. 계속하려면 * 예 * 를 선택하십시오.
+
보고된 용량 증가 대화 상자가 나타납니다.

+
이 대화 상자에는 볼륨의 현재 보고된 용량과 볼륨의 연결된 풀 또는 볼륨 그룹에서 사용 가능한 가용 용량이 표시됩니다.

. 보고된 용량을 현재 사용 가능한 보고된 용량에 추가하려면 * 보고 용량 증가... * 상자를 사용합니다. 용량 값을 변경하여 메비바이트(MiB), 기비바이트(GiB) 또는 테비바이트(TiB)로 표시할 수 있습니다.
. 증가 * 를 클릭합니다.
. 선택한 볼륨에 대해 현재 실행 중인 용량 증가 작업의 진행 상황에 대한 최근 작업 창을 봅니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
. 볼륨 용량이 완료되면 다음 항목에 설명된 대로 VMFS 크기를 수동으로 늘려야 합니다.
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["vSphere Client에서 VMFS 데이터 저장소 용량을 늘립니다"^]






=== 볼륨을 추가하여 기존 데이터 저장소의 용량을 늘립니다

. 볼륨을 추가하여 데이터 저장소의 용량을 늘릴 수 있습니다. 의 단계를 따릅니다 <<1단계: 볼륨 생성>>.
. 그런 다음 원하는 호스트에 볼륨을 할당하여 데이터 저장소의 용량을 늘립니다. 다음 항목을 참조하십시오.
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["vSphere Client에서 VMFS 데이터 저장소 용량을 늘립니다"^]



