---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: vCenter용 SANtricity 스토리지 플러그인을 설치합니다. 
---
= vCenter용 Storage Plugin을 설치합니다
:hardbreaks:
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter용 Storage Plugin을 설치하고 플러그인 등록을 확인할 수 있습니다.



== 설치 사전 요구 사항을 검토합니다

시스템이 다음 요구사항을 충족하는지 확인하십시오.

* VMware vCenter Server Appliance 지원 버전: 6.7U3J, 7.0U1 또는 7. 0U2
* NetApp SANtricity OS 버전: 11.60.2 이상
* 지원되는 애플리케이션 호스트 버전: Windows 2016 또는 Windows 2019
* 호스트 시스템의 CPU 요구 사항:
+
** 시스템 메모리: 1.5GB
** 스토리지 공간: 275MB + 200MB(로깅)






== 플러그인 소프트웨어를 설치합니다

플러그인 소프트웨어를 설치하려면:

. 설치 관리자 파일을 응용 프로그램 서버로 사용할 호스트에 복사한 다음 설치 프로그램을 다운로드한 폴더에 액세스합니다.
. 설치 파일을 두 번 클릭합니다.
+
'S antricity_storage_vcenterplugin-windows_x64--nn.nn.nn.nnnn.exe'

+
위 파일 이름에서 ' nn.nn.nn.nnnn'은 버전 번호를 나타냅니다.

. 설치가 시작되면 화면에 나타나는 지침을 따릅니다.
+
설치하는 동안 일부 구성 매개 변수를 입력하라는 메시지가 표시됩니다.

+
.. 첫 번째 화면에서 소프트웨어에 사용할 언어를 선택하고 * 확인 * 을 클릭합니다.
.. 소개 화면에서 * 다음 * 을 클릭합니다.
.. 저작권 화면에서 * 다음 * 을 클릭합니다.
.. 사용권 계약 화면에서 약관에 동의하는 확인란을 선택한 후 * 다음 * 을 클릭합니다.
.. 소프트웨어를 설치할 폴더를 선택한 후 * 다음 * 을 클릭합니다.
.. 플러그인과 스토리지 배열 간에 인증서 유효성 검사를 적용하려면 인증서 유효성 검사 화면에서 확인란을 선택한 상태로 유지합니다. 이렇게 하면 스토리지 배열 인증서가 플러그인에 대해 신뢰되도록 확인됩니다. 인증서를 신뢰할 수 없는 경우 플러그인에 인증서를 추가할 수 없습니다. 인증서 유효성 검사를 재정의하려면 자체 서명된 인증서를 사용하여 모든 스토리지 어레이를 플러그인에 추가할 수 있도록 확인란을 선택 취소합니다. 다음 * 을 클릭합니다.
+
인증서에 대한 자세한 내용은 플러그인 인터페이스에서 사용할 수 있는 온라인 도움말을 참조하십시오.

.. HTTPS 웹 서비스 포트 화면에서 기본값을 8445로 그대로 두거나 필요한 경우 포트 번호를 변경합니다. 다음 * 을 클릭합니다.
.. 사전 설치 요약 화면에서 * 다음 * 을 클릭하여 파일을 설치합니다.
.. Webserver Started 메시지가 나타나면 * OK * 를 클릭하여 설치를 완료합니다.
.. 완료 * 를 클릭합니다.
+

NOTE: 필요한 경우 설치 후 인증서 유효성 검사 및 웹 서비스 포트 설정을 변경할 수 있습니다. 설치 디렉터리에서 wsconfig.xml 파일을 엽니다. 스토리지 배열에서 인증서 유효성 검사를 제거하려면 env 키 trust.all.arrays를 true로 변경합니다. 웹 서비스 포트를 변경하려면 'slport' 값을 0에서 65535 사이의 원하는 포트 값으로 수정합니다. 사용된 포트 번호가 다른 프로세스에 바인딩되어 있지 않은지 확인합니다. 완료되면 변경 사항을 저장하고 플러그인 웹 서버를 다시 시작합니다. 플러그인을 vCSA에 등록한 후 플러그인 웹 서버의 포트 값이 변경되면 vCSA가 변경된 포트에서 플러그인 웹서버로 통신하도록 플러그인을 등록 취소하고 다시 등록해야 합니다.



. services.msc * 명령을 실행하여 응용 프로그램 서버가 성공적으로 설치되었는지 확인합니다.
. VCP(Application Server) 서비스 * vCenter * 용 NetApp SANtricity 스토리지 플러그인 이 설치되어 있고 서비스가 시작되었는지 확인합니다.




== vCenter Server Appliance에 플러그인을 등록합니다

플러그인 소프트웨어가 설치되면 vCSA에 플러그인을 등록합니다.


NOTE: 플러그인은 한 번에 하나의 vCSA에만 등록할 수 있습니다. 다른 vCSA에 등록하려면 현재 vCSA에서 플러그인 등록을 해제하고 애플리케이션 호스트에서 제거해야 합니다. 그런 다음 플러그인을 다시 설치하고 다른 vCSA에 등록할 수 있습니다.

. 명령줄을 통해 프롬프트를 열고 다음 디렉토리로 이동합니다.
+
"<설치 디렉토리>\vcenter-register\bin"

. vcenter-register.bat * 파일: 'vcenter-register.bat^ - action registerPlugin^ - vcenter Hostname <vcenter FQDN>^ - username <Administrator username>^'을 실행합니다
. 스크립트가 성공했는지 확인합니다.


로그는 "%install_dir%/working/logs/vc-registration.log"에 저장됩니다.



== 플러그인 등록을 확인합니다

플러그인을 설치하고 등록 스크립트를 실행한 후 플러그인이 vCenter Server Appliance에 성공적으로 등록되었는지 확인합니다.

. vCenter Server Appliance에 대한 vSphere Client를 엽니다.
. 메뉴 표시줄에서 Administrator[Client Plugins] 메뉴를 선택합니다.
. vCenter용 SANtricity 스토리지 플러그인이 * Enabled * 로 표시되는지 확인합니다.
+
응용 프로그램 서버와 통신할 수 없다는 오류 메시지와 함께 플러그인이 사용 안 함 으로 표시되면 응용 프로그램 서버에 대해 정의된 포트 번호가 사용 중인 방화벽을 통과할 수 있도록 설정되어 있는지 확인합니다. 기본 애플리케이션 서버 TCP(Transmission Control Protocol) 포트 번호는 8445입니다.


