---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-the-settings-for-a-host.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 호스트 또는 호스트 클러스터의 이름, 호스트 운영 체제 유형 및 관련 호스트 클러스터를 변경할 수 있습니다. 
---
= 호스트의 설정을 변경합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
호스트 또는 호스트 클러스터의 이름, 호스트 운영 체제 유형 및 관련 호스트 클러스터를 변경할 수 있습니다.

.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. 편집할 호스트를 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
현재 호스트 설정을 보여주는 대화 상자가 나타납니다.

. 호스트 속성을 변경하려면 * 속성 * 탭이 선택되어 있는지 확인한 다음 필요에 따라 설정을 변경합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
사용자가 제공한 호스트 이름을 변경할 수 있습니다. 호스트 이름을 지정해야 합니다.



 a| 
연결된 호스트 클러스터입니다
 a| 
다음 옵션 중 하나를 선택할 수 있습니다.

** * 없음 * -- 호스트가 독립 실행형 호스트로 유지됩니다. 호스트가 호스트 클러스터에 연결되어 있는 경우 시스템은 클러스터에서 호스트를 제거합니다.
** * <호스트 클러스터> * -- 시스템이 호스트를 선택한 클러스터에 연결합니다.




 a| 
호스트 운영 체제 유형입니다
 a| 
정의한 호스트에서 실행 중인 운영 체제의 유형을 변경할 수 있습니다.

|===
====
. 포트 설정을 변경하려면 * 호스트 포트 * 탭을 클릭한 다음 필요에 따라 설정을 변경합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
호스트 포트
 a| 
다음 옵션 중 하나를 선택할 수 있습니다.

** * Add * -- Add를 사용하여 새 호스트 포트 식별자를 호스트에 연결합니다. 호스트 포트 식별자 이름의 길이는 호스트 인터페이스 기술에 의해 결정됩니다. Fibre Channel 및 Infiniband 호스트 포트 식별자 이름은 16자여야 합니다. iSCSI 호스트 포트 식별자 이름은 최대 223자입니다. 포트는 고유해야 합니다. 이미 구성된 포트 번호는 허용되지 않습니다.
** * 삭제 * -- 호스트 포트 식별자를 제거(연결 해제)하려면 삭제를 사용합니다. 삭제 옵션은 호스트 포트를 물리적으로 제거하지 않습니다. 이 옵션은 호스트 포트와 호스트 간의 연결을 제거합니다. 호스트 버스 어댑터 또는 iSCSI 이니시에이터를 제거하지 않는 한, 호스트 포트는 컨트롤러에서 계속 인식됩니다.



CAUTION: 호스트 포트 식별자를 삭제하면 이 호스트와 더 이상 연결되지 않습니다. 또한 호스트는 이 호스트 포트 식별자를 통해 할당된 볼륨에 대한 액세스 권한을 상실합니다.



 a| 
라벨
 a| 
포트 레이블 이름을 변경하려면 * 편집 * 아이콘(연필)을 클릭합니다. 포트 레이블 이름은 고유해야 합니다. 이미 구성된 레이블 이름은 허용되지 않습니다.



 a| 
CHAP 암호
 a| 
iSCSI 호스트에만 표시됩니다. 이니시에이터(iSCSI 호스트)의 CHAP 암호를 설정하거나 변경할 수 있습니다. 시스템은 CHAP(Challenge Handshake Authentication Protocol) 방법을 사용하여 초기 링크 중에 대상 및 초기자의 ID를 확인합니다. 인증은 CHAP 암호라는 공유 보안 키를 기반으로 합니다.

|===
====
. 저장 * 을 클릭합니다.

