---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-settings-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: '설정 가져오기 기능은 단일 스토리지 배열(소스)의 설정을 여러 배열(대상)에 복제할 수 있는 배치 작업입니다.' 
---
= 설정 가져오기 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
설정 가져오기 기능은 단일 스토리지 배열(소스)의 설정을 vCenter용 Storage Plugin의 여러 스토리지(대상)로 복제할 수 있는 일괄 작업입니다.



== 가져올 수 있는 설정입니다

다음 구성을 한 어레이에서 다른 어레이로 가져올 수 있습니다.

* * Alerts * -- e-메일, syslog 서버 또는 SNMP 서버를 사용하여 중요한 이벤트를 관리자에게 보내는 경고 방법입니다.
* * AutoSupport * -- 스토리지 어레이의 상태를 모니터링하고 자동 디스패치를 기술 지원 부서에 보내는 기능입니다.
* * 디렉터리 서비스 * -- LDAP(Lightweight Directory Access Protocol) 서버 및 디렉터리 서비스(예: Microsoft의 Active Directory)를 통해 관리되는 사용자 인증 방법입니다.
* * 시스템 설정 * -- 다음과 관련된 구성:
+
** 볼륨에 대한 미디어 스캔 설정입니다
** SSD 설정
** 자동 로드 밸런싱(호스트 연결 보고 포함 안 함)


* * 스토리지 구성 * -- 다음과 관련된 구성:
+
** 볼륨(일반 및 비리포지토리 볼륨만 해당)
** 볼륨 그룹 및 풀
** 핫 스페어 드라이브 할당






== 구성 워크플로우

설정을 가져오려면 다음 워크플로를 따릅니다.

. 소스로 사용할 스토리지 배열에서 System Manager를 사용하여 설정을 구성합니다.
. 타겟으로 사용할 스토리지 어레이에서 System Manager를 사용하여 구성을 백업합니다.
. 플러그인 인터페이스에서 * 관리 * 페이지로 이동하여 설정을 가져옵니다.
. 작업 페이지에서 설정 가져오기 작업의 결과를 검토합니다.




== 스토리지 구성 복제 요구 사항

스토리지 시스템 간에 스토리지 구성을 가져오기 전에 요구 사항 및 지침을 검토하십시오.



=== 쉘프

* 컨트롤러가 상주하는 쉘프는 소스 및 타겟 어레이에서 동일해야 합니다.
* 소스 및 타겟 스토리지에서 쉘프 ID가 동일해야 합니다.
* 확장 쉘프가 동일한 드라이브 유형으로 동일한 슬롯에 설치되어야 합니다(구성에서 드라이브를 사용하는 경우, 사용되지 않은 드라이브의 위치는 중요하지 않음).




=== 컨트롤러

* 컨트롤러 유형은 소스와 대상 어레이 간에 다를 수 있지만 RBOD 케이스 유형은 동일해야 합니다.
* 호스트의 DA 기능을 포함한 HIC는 소스와 타겟 스토리지 간에 동일해야 합니다.
* 양면 인쇄에서 단면 인쇄로 가져오는 것은 지원되지 않지만 단면 인쇄에서 양면 인쇄로 가져오는 것은 허용됩니다.
* FDE 설정은 가져오기 프로세스에 포함되지 않습니다.




=== 상태

* 타겟 스토리지가 최적 상태여야 합니다.
* 소스 스토리지가 최적 상태가 아니어야 합니다.




=== 스토리지

* 타겟의 볼륨 용량이 소스보다 큰 경우 소스 스토리지와 타겟 스토리지 간에 드라이브 용량이 다를 수 있습니다. (타겟 스토리지에는 복제 작업에 의해 볼륨으로 완전히 구성되지 않는 더 큰 최신 용량 드라이브가 있을 수 있습니다.)
* 소스 스토리지에서 64TB 이상의 디스크 풀 볼륨으로 인해 타겟의 가져오기 프로세스가 실행되지 않습니다.

