---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-manually.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 설정이 자동 풀 구성에 대한 요구 사항을 충족하지 않는 경우 풀을 수동으로 생성할 수 있습니다. 풀은 논리적으로 그룹화된 드라이브 집합입니다. 
---
= 풀을 수동으로 생성합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
설정이 자동 풀 구성에 대한 요구 사항을 충족하지 않는 경우 풀을 수동으로 생성할 수 있습니다. 풀은 논리적으로 그룹화된 드라이브 집합입니다.

.시작하기 전에
* 드라이브 유형(HDD 또는 SSD)이 동일한 드라이브가 최소 11개 이상 있어야 합니다.
* 쉘프 손실 방지 기능을 사용하려면 풀을 구성하는 드라이브가 6개 이상의 서로 다른 드라이브 쉘프에 있어야 하며, 단일 드라이브 쉘프에 드라이브가 2개 이상 없어야 합니다.
* 드로어 손실 방지 기능을 사용하려면 풀을 구성하는 드라이브가 5개 이상의 서로 다른 드로어에 있어야 하며 풀에는 각 드로어의 드라이브 셸프가 동일한 수만큼 포함되어 있어야 합니다.
* EF600 또는 EF300 스토리지 어레이를 구성할 때는 각 컨트롤러가 처음 12개 슬롯에서 동일한 수의 드라이브와 마지막 12개 슬롯에서 동일한 수의 드라이브를 액세스할 수 있는지 확인하십시오. 이 구성을 사용하면 컨트롤러가 드라이브 측 PCIe 버스를 보다 효과적으로 사용할 수 있습니다. 풀을 생성하려면 스토리지 배열의 모든 드라이브를 사용해야 합니다.


풀을 생성하는 동안 드라이브 유형, 보안 기능, DA(Data Assurance) 기능, 쉘프 손실 보호, 서랍 손실 보호와 같은 특성을 확인합니다.

EF600 및 EF300 스토리지 어레이의 경우 리소스 프로비저닝과 볼륨 블록 크기도 설정에 포함됩니다.

.단계
. 관리 페이지에서 풀의 스토리지 시스템을 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. MENU: Create [Pool] 를 클릭합니다.
+
풀 생성 대화 상자가 나타납니다.

. 풀의 이름을 입력합니다.
. (선택 사항) 스토리지 배열에 둘 이상의 드라이브 유형이 있는 경우 사용할 드라이브 유형을 선택합니다.
+
결과 테이블에는 생성할 수 있는 모든 풀이 나열됩니다.

. 다음 특성을 기준으로 사용할 풀 후보를 선택한 다음 * Create * 를 클릭합니다.
+
.필드 세부 정보
====
[cols="25h,~"]
|===
| 특징 | 사용 


 a| 
사용 가능한 용량
 a| 
에는 GiB 단위의 풀 후보 가용 용량이 나와 있습니다. 애플리케이션 스토리지 요구 사항에 맞는 용량을 갖춘 풀 후보를 선택합니다. 보존(스페어) 용량도 풀 전체에 분산되며 가용 용량에 포함되지 않습니다.



 a| 
총 드라이브 수
 a| 
에는 풀 후보 드라이브에서 사용 가능한 드라이브 수가 나와 있습니다. 시스템은 보존 용량을 위해 가능한 한 많은 드라이브를 자동으로 예약합니다(풀에 있는 6개 드라이브마다 시스템이 보존 용량을 위해 1개의 드라이브를 예약합니다). 드라이브 장애가 발생하면 보존 용량이 재구성 데이터를 저장하는 데 사용됩니다.



 a| 
드라이브 블록 크기(EF300 및 EF600만 해당)
 a| 
에서는 풀의 드라이브가 쓸 수 있는 블록 크기(섹터 크기)를 보여 줍니다. 다음과 같은 값이 포함될 수 있습니다.

** 512--512바이트 섹터 크기
** 4k--4,096바이트 섹터 크기




 a| 
보안 가능
 a| 
풀 대상이 전체 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있는 전체 보안 가능 드라이브로 구성되어 있는지 여부를 나타냅니다.

** 드라이브 보안으로 풀을 보호할 수 있지만 이 기능을 사용하려면 모든 드라이브가 안전해야 합니다.
** FDE 전용 풀을 생성하려면 Secure-Capable 열에서 * Yes-FDE * 를 찾습니다. FIPS 전용 풀을 생성하려면 * Yes-FIPS * 또는 * Yes-FIPS(Mixed) * 를 찾습니다. "혼합"은 140-3단계 드라이브와 140-3단계 드라이브의 혼합을 나타냅니다. 이러한 수준을 혼합하여 사용하는 경우 풀이 낮은 보안 수준(140-2)에서 작동할 수 있습니다.
** 보안 기능이 있거나 그렇지 않거나 보안 수준이 혼합된 드라이브로 구성된 풀을 생성할 수 있습니다. 풀의 드라이브에 보안 기능이 지원되지 않는 드라이브가 포함되어 있으면 풀을 안전하게 설정할 수 없습니다.




 a| 
보안을 활성화하시겠습니까?
 a| 
에서는 보안 가능 드라이브를 사용하여 드라이브 보안 기능을 활성화하는 옵션을 제공합니다. 풀이 보안 기능이 있고 보안 키를 만든 경우 확인란을 선택하여 보안을 설정할 수 있습니다.


NOTE: 활성화된 후 드라이브 보안을 제거하는 유일한 방법은 풀을 삭제하고 드라이브를 지우는 것입니다.



 a| 
DA 가능
 a| 
이 풀 대상에 대해 DA(Data Assurance)를 사용할 수 있는지 여부를 나타냅니다. DA는 컨트롤러를 통해 드라이브로 데이터가 전송될 때 발생할 수 있는 오류를 검사하고 수정합니다. DA를 사용하려면 DA를 지원하는 풀을 선택합니다. 이 옵션은 DA 기능이 활성화된 경우에만 사용할 수 있습니다. 풀에는 DA를 사용할 수 있거나 DA를 사용할 수 없는 드라이브가 포함될 수 있지만 이 기능을 사용하려면 모든 드라이브가 DA를 지원해야 합니다.



 a| 
리소스 프로비저닝 가능(EF300 및 EF600만 해당)
 a| 
이 풀 대상에 대해 리소스 프로비저닝을 사용할 수 있는지 여부를 표시합니다. 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.



 a| 
선반 손실 방지
 a| 
쉘프 손실 방지 기능이 사용 가능한지 여부를 표시합니다. 쉘프 손실 방지: 단일 드라이브 쉘프의 전체 통신 장애가 발생할 경우 풀 내의 볼륨 데이터에 액세스할 수 있도록 보장합니다.



 a| 
서랍 손실 방지
 a| 
드로어 손실 보호가 사용 가능한지 여부를 표시합니다. 이 보호 기능은 드로어가 포함된 드라이브 쉘프를 사용하는 경우에만 제공됩니다. 드로어 손실 방지 기능은 드라이브 쉘프의 단일 드로어에서 전체 통신 장애가 발생할 경우 풀 내의 볼륨 데이터에 액세스할 수 있도록 보장합니다.



 a| 
지원되는 볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
에는 풀의 볼륨에 대해 생성할 수 있는 블록 크기가 나와 있습니다.

** 512n -- 512바이트 네이티브
** 512e -- 512바이트가 에뮬레이트됨
** 4k--4,096바이트.


|===
====

