---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-access.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: vCenter용 Storage Plugin을 사용하여 스토리지를 관리하려면 네트워크에서 각 호스트를 검색 또는 정의해야 합니다. 
---
= 호스트 액세스를 생성합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter용 Storage Plugin을 사용하여 스토리지를 관리하려면 네트워크에서 각 호스트를 검색 또는 정의해야 합니다.

호스트를 생성하면 스토리지 시스템에 대한 접속 및 볼륨에 대한 입출력 액세스를 제공하는 호스트 매개 변수를 정의할 수 있습니다.

호스트 구성 페이지에서 * 설정 보기/편집 * 을 선택하여 HCA(Host Context Agent)에서 호스트를 자동으로 검색한 다음 정보가 올바른지 확인할 수 있습니다. 그러나 HCA는 지원되는 모든 운영 체제에서 사용할 수 없으며 호스트를 수동으로 생성해야 합니다.

호스트를 생성할 때 다음 지침을 염두에 두십시오.

* 호스트와 연결된 호스트 식별자 포트를 정의해야 합니다.
* 호스트에 할당된 시스템 이름과 동일한 이름을 제공해야 합니다.
* 선택한 이름이 이미 사용 중인 경우에는 이 작업이 성공하지 않습니다.
* 이름의 길이는 30자를 초과할 수 없습니다.


.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. MENU: Create [Host] 를 클릭합니다.
+
Create Host 대화 상자가 나타납니다.

. 필요에 따라 호스트 설정을 선택합니다.
+
.필드 세부 정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
새 호스트의 이름을 입력합니다.



 a| 
호스트 운영 체제 유형입니다
 a| 
드롭다운 목록에서 새 호스트에서 실행 중인 운영 체제를 선택합니다.



 a| 
호스트 인터페이스 유형입니다
 a| 
(선택 사항) 스토리지 배열에서 지원되는 호스트 인터페이스 유형이 두 개 이상인 경우 사용할 호스트 인터페이스 유형을 선택합니다.



 a| 
호스트 포트
 a| 
다음 중 하나를 수행합니다.

** * I/O 인터페이스 선택 * -- 일반적으로 호스트 포트는 로그인되어 있고 드롭다운 목록에서 사용할 수 있어야 합니다. 목록에서 호스트 포트 식별자를 선택할 수 있습니다.
** * 수동 추가 * -- 호스트 포트 식별자가 목록에 표시되지 않으면 호스트 포트가 로그인되어 있지 않은 것입니다. HBA 유틸리티 또는 iSCSI 이니시에이터 유틸리티를 사용하여 호스트 포트 식별자를 찾아 호스트에 연결할 수 있습니다. 호스트 포트 식별자를 수동으로 입력하거나 유틸리티에서 호스트 포트 필드로 복사/붙여 넣을 수 있습니다(한 번에 하나씩). 호스트와 연결하려면 한 번에 하나의 호스트 포트 식별자를 선택해야 하지만 호스트와 연결된 식별자를 계속 선택할 수 있습니다. 각 식별자는 호스트 포트 필드에 표시됩니다. 필요한 경우 옆에 있는 * X * 를 선택하여 식별자를 제거할 수도 있습니다.




 a| 
CHAP 이니시에이터 암호를 설정합니다
 a| 
(선택 사항) iSCSI IQN을 사용하여 호스트 포트를 선택하거나 수동으로 입력한 경우, CHAP(Challenge Handshake Authentication Protocol)를 사용하여 인증하기 위해 스토리지 배열에 액세스를 시도하는 호스트를 요구하려면 “Set CHAP initiator secret(CHAP 초기자 암호 설정)” 확인란을 선택합니다. 선택하거나 수동으로 입력한 각 iSCSI 호스트 포트에 대해 다음을 수행합니다.

** CHAP 인증을 위해 각 iSCSI 호스트 이니시에이터에 설정된 것과 동일한 CHAP 암호를 입력합니다. 상호 CHAP 인증(호스트가 스토리지 어레이에서 자체적으로 유효성을 검사할 수 있도록 하는 양방향 인증)을 사용하는 경우, 초기 설정 시 또는 설정을 변경하여 스토리지 배열에 대한 CHAP 암호를 설정해야 합니다.
** 호스트 인증이 필요하지 않은 경우 필드를 비워 둡니다. 현재 사용되는 유일한 iSCSI 인증 방법은 CHAP입니다.


|===
====
. Create * 를 클릭합니다.
. 호스트 정보를 업데이트해야 하는 경우 테이블에서 호스트를 선택하고 * 설정 보기/편집 * 을 클릭합니다.


호스트가 성공적으로 생성된 후 시스템은 호스트에 대해 구성된 각 호스트 포트(사용자 레이블)의 기본 이름을 생성합니다. 기본 별칭은 "<Hostname_Port Number>"입니다. 예를 들어, 호스트 IPT에 대해 생성된 첫 번째 포트의 기본 별칭은 "ipt_1"입니다.

I/O 작업에 사용할 수 있도록 볼륨을 호스트에 할당해야 합니다. 로 이동합니다 link:vc-olh-assign-volumes-to-hosts.html["호스트에 볼륨을 할당합니다"].
