---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-check-volume-redundancy.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 풀 또는 볼륨 그룹의 볼륨에서 이중화를 확인하여 해당 볼륨의 데이터가 일관되는지 확인할 수 있습니다. 이중화 데이터는 풀 또는 볼륨 그룹의 드라이브 중 하나에 장애가 발생할 경우 교체 드라이브에 대한 정보를 빠르게 재구성하는 데 사용됩니다. 
---
= 볼륨 중복성을 확인합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기술 지원의 지침이나 Recovery Guru의 지시에 따라 풀 또는 볼륨 그룹의 볼륨에서 이중화를 확인하여 해당 볼륨의 데이터가 일관되는지 여부를 결정할 수 있습니다.

이중화 데이터는 풀 또는 볼륨 그룹의 드라이브 중 하나에 장애가 발생할 경우 교체 드라이브에 대한 정보를 빠르게 재구성하는 데 사용됩니다.

.시작하기 전에
* 풀 또는 볼륨 그룹의 상태가 최적이어야 합니다.
* 풀 또는 볼륨 그룹에 진행 중인 볼륨 수정 작업이 없어야 합니다.
* RAID 0에는 데이터 중복성이 없으므로 RAID 0을 제외한 모든 RAID 수준에서 이중화를 확인할 수 있습니다. 풀은 RAID 6로만 구성됩니다.



NOTE: Recovery Guru에서 지시하고 기술 지원의 지침에 따라 볼륨 중복성을 확인해야 합니다.

.이 작업에 대해
한 번에 하나의 풀 또는 볼륨 그룹에서만 이 검사를 수행할 수 있습니다. 볼륨 중복 검사는 다음 작업을 수행합니다.

* RAID 3 볼륨, RAID 5 볼륨 또는 RAID 6 볼륨의 데이터 블록을 검사하고 각 블록의 중복 정보를 확인합니다. (RAID 3은 명령줄 인터페이스를 사용하는 볼륨 그룹에만 할당할 수 있습니다.)
* RAID 1 미러링 드라이브의 데이터 블록을 비교합니다.
* 컨트롤러 펌웨어가 데이터가 일치하지 않는 것으로 판단할 경우 중복 오류를 반환합니다.



NOTE: 동일한 풀 또는 볼륨 그룹에서 중복 검사를 즉시 실행하면 오류가 발생할 수 있습니다. 이 문제를 방지하려면 동일한 풀 또는 볼륨 그룹에서 다른 중복 검사를 실행하기 전에 1-2분 정도 기다리십시오.

.단계
. 관리 페이지에서 풀 또는 볼륨 그룹이 있는 스토리지 어레이를 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. Uncommon Tasks [Check volume redundancy] 메뉴를 선택합니다.
+
Check Redundancy 대화상자가 나타납니다.

. 확인할 볼륨을 선택한 다음 check 를 입력하여 이 작업을 수행할지 확인합니다.
. 확인 * 을 클릭합니다.
+
볼륨 중복 검사 작업이 시작됩니다. 풀 또는 볼륨 그룹의 볼륨은 대화 상자의 테이블 상단에서 시작하여 순차적으로 스캔됩니다. 이러한 작업은 각 볼륨을 스캔할 때 수행됩니다.

+
** 볼륨 테이블에서 볼륨이 선택됩니다.
** 이중화 체크 상태가 Status 열에 표시됩니다.
** 미디어 또는 패리티 오류가 발생하면 검사가 중지되고 오류가 보고됩니다. 다음 표에는 이중화 검사 상태에 대한 자세한 정보가 나와 있습니다.


+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 상태 | 설명 


| 보류 중 | 이 볼륨이 스캔되는 첫 번째 볼륨이며, 시작을 클릭하여 중복 검사를 시작하지 않았습니다. 또는 - 풀 또는 볼륨 그룹의 다른 볼륨에서 중복 검사 작업이 수행되고 있습니다. 


| 확인 중입니다 | 볼륨이 중복 검사를 진행 중입니다. 


| 통과 | 볼륨이 중복 검사를 통과했습니다. 이중화 정보에서 불일치를 감지하지 못했습니다. 


| 실패했습니다 | 볼륨이 중복 검사에 실패했습니다. 이중화 정보에서 불일치가 발견되었습니다. 


| 미디어 오류입니다 | 드라이브 미디어에 결함이 있어 읽을 수 없습니다. Recovery Guru에 표시되는 지침을 따릅니다. 


| 패리티 오류입니다 | 패리티는 데이터의 특정 부분에 대해 있어서는 안 되는 것이 아닙니다. 패리티 오류는 잠재적으로 심각하며 영구적인 데이터 손실을 일으킬 수 있습니다. 
|===
====
. 풀 또는 볼륨 그룹의 마지막 볼륨을 선택한 후 * Done * 을 클릭합니다.

