---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-media-scan-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 미디어 검사는 볼륨의 모든 데이터 및 중복 정보를 검사하는 백그라운드 작업입니다. 하나 이상의 볼륨에 대한 미디어 스캔 설정을 활성화 또는 비활성화하거나 스캔 기간을 변경하려면 이 옵션을 사용합니다. 
---
= 볼륨에 대한 미디어 스캔 설정을 변경합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
미디어 검사는 볼륨의 모든 데이터 및 중복 정보를 검사하는 백그라운드 작업입니다. 하나 이상의 볼륨에 대한 미디어 스캔 설정을 활성화 또는 비활성화하거나 스캔 기간을 변경하려면 이 옵션을 사용합니다.

다음 사항을 이해합니다.

* 미디어 스캔은 스캔 용량 및 스캔 기간에 따라 일정한 속도로 계속 실행됩니다. 백그라운드 스캔은 우선 순위가 더 높은 백그라운드 작업(예: 재구성)에 의해 일시적으로 중단될 수 있지만 동일한 일정한 속도로 재개됩니다.
* 스토리지 배열 및 해당 볼륨에 대해 미디어 검사 옵션이 활성화된 경우에만 볼륨이 스캔됩니다. 해당 볼륨에 대해서도 중복 검사가 활성화된 경우 볼륨에 중복성이 있는 경우 볼륨의 중복 정보가 데이터와 일관되는지 검사합니다. 중복성 검사를 통한 미디어 검사는 각 볼륨을 만들 때 기본적으로 활성화됩니다.
* 스캔 중에 복구할 수 없는 매체 오류가 발생하면 중복 정보를 사용하여 데이터가 복구됩니다(가능한 경우).
+
예를 들어, 이중화 정보는 최적의 RAID 5 볼륨 또는 최적의 RAID 6 볼륨에서 사용할 수 있으며 하나의 드라이브에만 장애가 있습니다. 복구 불가능한 오류가 중복 정보를 사용하여 복구할 수 없는 경우 데이터 블록이 읽을 수 없는 섹터 로그에 추가됩니다. 수정 가능한 미디어 오류와 수정 불가능한 미디어 오류가 모두 이벤트 로그에 보고됩니다.

* 중복 검사가 데이터와 중복 정보 간의 불일치를 발견하면 이벤트 로그에 보고됩니다.


미디어 검사는 애플리케이션에서 자주 읽지 않는 디스크 블록의 미디어 오류를 감지하고 복구합니다. 따라서 드라이브 장애가 발생할 경우 볼륨 그룹 또는 풀에 있는 다른 드라이브의 데이터 및 이중화 정보를 사용하여 장애가 발생한 드라이브의 데이터가 재구성되므로 데이터 손실을 방지할 수 있습니다.

다음 작업을 수행할 수 있습니다.

* 전체 스토리지 어레이에 대한 백그라운드 미디어 검사를 설정하거나 해제합니다
* 전체 스토리지 배열의 스캔 기간을 변경합니다
* 하나 이상의 볼륨에 대한 미디어 스캔을 활성화 또는 비활성화합니다
* 하나 이상의 볼륨에 대한 중복 검사를 활성화 또는 비활성화합니다


.단계
. 관리 페이지에서 미디어 스캔 설정을 변경할 볼륨이 포함된 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Manage Volumes](볼륨 관리)를 선택합니다.
. 임의의 볼륨을 선택한 다음 MENU: More [Change media scan settings](메뉴: 추가 [미디어 스캔 설정 변경])를 선택합니다.
+
드라이브 미디어 검색 설정 변경 대화 상자가 나타납니다. 스토리지 배열의 모든 볼륨이 이 대화 상자에 나타납니다.

. 미디어 스캔을 활성화하려면 * 다음 과정을 통해 미디어 스캔 * 확인란을 선택합니다. 미디어 스캔 확인란을 비활성화하면 모든 미디어 스캔 설정이 일시 중단됩니다.
. 미디어 검사를 실행할 일 수를 지정합니다.
. 미디어 스캔을 수행하려는 각 볼륨에 대해 * Media Scan * (미디어 스캔 *) 확인란을 선택합니다. 시스템은 미디어 스캔을 실행하도록 선택한 각 볼륨에 대해 Redundancy Check(이중화 확인) 옵션을 활성화합니다. 중복성 검사를 수행하지 않을 개별 볼륨이 있는 경우 * Redundancy Check *(중복성 검사 *) 확인란을 선택 취소합니다.
. 저장 * 을 클릭합니다.


선택한 내용에 따라 백그라운드 미디어 검사에 변경 사항이 적용됩니다.
