---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-view-status.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Storage Plugin for vCenter 또는 vSphere Client에서 시스템 상태를 봅니다 
---
= 상태를 봅니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Storage Plugin for vCenter 또는 vSphere Client에서 시스템 상태를 볼 수 있습니다.

. vSphere Client 내에서 플러그인을 엽니다.
. 다음 패널에서 상태를 봅니다.
+
** * 스토리지 배열 상태 * -- * Manage - All * 패널로 이동합니다. 검색된 각 배열에 대해 이 행은 상태 열을 제공합니다.
** * 작업 진행 중 * -- 측면 패널에서 * 작업 * 을 클릭하여 설정 가져오기와 같은 장기 실행 작업을 모두 봅니다. Provisioning 드롭다운에서 장기 실행 작업을 볼 수도 있습니다. 진행 중인 작업 대화 상자에 나열된 각 작업에 대해 완료 비율과 작업을 완료하는 데 남은 예상 시간이 표시됩니다. 경우에 따라 작업을 중지하거나 우선 순위가 높거나 낮은 위치에 놓을 수 있습니다. 필요한 경우 작업 열의 링크를 사용하여 작업의 우선 순위를 중지하거나 변경합니다.





CAUTION: 특히 작업을 중지할 때 대화 상자에 제공된 모든 주의 텍스트를 읽습니다.

플러그인에 대해 나타날 수 있는 작업은 다음 표에 나와 있습니다. System Manager 인터페이스에 추가 작업도 표시될 수 있습니다.

|===
| 작동 | 작업의 가능한 상태입니다 | 수행할 수 있는 작업 


| 볼륨 생성(64TiB보다 큰 일반 풀 볼륨만 해당) | 진행 중입니다 | 없음 


| 볼륨 삭제(64TiB보다 큰 일반 풀 볼륨만 해당) | 진행 중입니다 | 없음 


| 풀 또는 볼륨 그룹에 용량을 추가합니다 | 진행 중입니다 | 없음 


| 볼륨의 RAID 레벨을 변경합니다 | 진행 중입니다 | 없음 


| 풀의 용량을 줄입니다 | 진행 중입니다 | 없음 


| 풀 볼륨에 대한 즉시 사용 가능 형식(iaf) 작업에 남아 있는 시간을 확인합니다 | 진행 중입니다 | 없음 


| 볼륨 그룹의 데이터 중복성을 확인합니다 | 진행 중입니다 | 없음 


| 볼륨을 초기화합니다 | 진행 중입니다 | 없음 


| 볼륨의 용량을 늘립니다 | 진행 중입니다 | 없음 


| 볼륨의 세그먼트 크기를 변경합니다 | 진행 중입니다 | 없음 
|===