---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 호스트가 스토리지의 스토리지를 액세스할 수 있도록 볼륨이라는 데이터 컨테이너를 생성할 수 있습니다. 
---
= 프로비저닝 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter용 저장소 플러그인에서 볼륨이라는 데이터 컨테이너를 생성하여 호스트가 스토리지의 저장소에 액세스할 수 있도록 할 수 있습니다.



== 볼륨 유형 및 특성

볼륨은 스토리지 어레이에서 스토리지 공간을 관리하고 구성하는 데이터 컨테이너입니다.

스토리지 배열에서 사용 가능한 스토리지 용량에서 볼륨을 생성하여 시스템 리소스를 구성할 수 있습니다. "볼륨"의 개념은 빠른 액세스를 위해 파일을 구성하기 위해 컴퓨터의 폴더/디렉토리를 사용하는 것과 비슷합니다.

볼륨은 호스트에서 볼 수 있는 유일한 데이터 계층입니다. SAN 환경에서는 볼륨이 LUN(논리 유닛 번호)에 매핑됩니다. 이러한 LUN은 FC, iSCSI 및 SAS를 비롯한 스토리지 어레이에서 지원하는 하나 이상의 호스트 액세스 프로토콜을 사용하여 액세스할 수 있는 사용자 데이터를 저장합니다.

풀 또는 볼륨 그룹의 각 볼륨은 어떤 유형의 데이터가 저장되어 있는지 기준으로 고유한 개별 특성을 가질 수 있습니다. 이러한 특징에는 다음이 포함됩니다.

* * 세그먼트 크기 * -- 세그먼트는 스토리지 어레이가 스트라이프의 다음 드라이브(RAID 그룹)로 이동하기 전에 드라이브에 저장되는 데이터의 양(KB)입니다. 세그먼트 크기는 볼륨 그룹의 용량과 같거나 그보다 작습니다. 세그먼트 크기가 고정되어 풀의 경우 변경할 수 없습니다.
* * 용량 * -- 풀 또는 볼륨 그룹에서 사용 가능한 용량을 사용하여 볼륨을 생성합니다. 볼륨을 생성하기 전에 풀 또는 볼륨 그룹이 이미 있어야 하며 볼륨을 생성할 수 있는 충분한 가용 용량이 있어야 합니다.
* * 컨트롤러 소유권 * -- 모든 스토리지 어레이에는 하나 또는 두 개의 컨트롤러가 있을 수 있습니다. 단일 컨트롤러 어레이에서 단일 컨트롤러로 볼륨의 워크로드를 관리할 수 있습니다. 이중 컨트롤러 어레이에서 볼륨에는 볼륨을 "소유"하는 기본 컨트롤러(A 또는 B)가 있습니다. 이중 컨트롤러 구성에서는 컨트롤러 간에 워크로드가 이동할 때 자동 로드 밸런싱 기능을 사용하여 볼륨 소유권을 자동으로 조정하여 로드 밸런싱 문제를 해결합니다. 자동 로드 밸런싱은 자동화된 I/O 워크로드 밸런싱을 제공하고 호스트에서 들어오는 I/O 트래픽을 두 컨트롤러 간에 동적으로 관리 및 밸런싱합니다.
* * 볼륨 할당 * -- 볼륨을 생성할 때 또는 나중에 호스트에 볼륨에 대한 액세스를 제공할 수 있습니다. 모든 호스트 액세스는 LUN(Logical Unit Number)을 통해 관리됩니다. 호스트는 다시 볼륨에 할당된 LUN을 감지합니다. 여러 호스트에 볼륨을 할당하는 경우 클러스터링 소프트웨어를 사용하여 모든 호스트에서 볼륨을 사용할 수 있는지 확인합니다.
+
호스트 유형에는 호스트가 액세스할 수 있는 볼륨 수에 대한 특정 제한이 있을 수 있습니다. 특정 호스트에서 사용할 볼륨을 생성할 때 이 제한 사항을 염두에 두십시오.

* * 리소스 프로비저닝 * -- EF600 또는 EF300 스토리지 어레이의 경우 백그라운드 초기화 프로세스 없이 즉시 볼륨을 사용하도록 지정할 수 있습니다. 리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다.
* * 설명적 이름 * - - - 어떤 이름을 원하든 볼륨의 이름을 지정할 수 있지만 이름을 설명하는 것이 좋습니다.


볼륨 생성 중에 각 볼륨에 용량이 할당되며 이름, 세그먼트 크기(볼륨 그룹만 해당), 컨트롤러 소유권 및 볼륨-호스트 할당이 할당됩니다. 볼륨 데이터는 필요에 따라 컨트롤러 전체에서 자동으로 로드 밸런싱됩니다.



== 볼륨에 대한 용량입니다

스토리지 배열의 드라이브는 데이터의 물리적 스토리지 용량을 제공합니다. 데이터 저장을 시작하려면 먼저 할당된 용량을 풀 또는 볼륨 그룹이라고 하는 논리적 구성 요소로 구성해야 합니다. 이러한 스토리지 객체를 사용하여 스토리지 배열의 데이터를 구성, 저장, 유지 및 보존할 수 있습니다.



=== 생성 및 확장 용량

풀 또는 볼륨 그룹의 할당되지 않은 용량 또는 사용 가능한 용량에서 볼륨을 생성할 수 있습니다.

* 할당되지 않은 용량에서 볼륨을 생성할 경우 풀 또는 볼륨 그룹과 볼륨을 동시에 생성할 수 있습니다.
* 사용 가능한 용량에서 볼륨을 생성하는 경우 이미 존재하는 풀 또는 볼륨 그룹에 추가 볼륨을 생성하고 있습니다. 볼륨 용량을 확장한 후 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.



NOTE: 플러그인 인터페이스에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다.



=== 볼륨에 대해 보고된 용량입니다

볼륨의 보고된 용량은 할당된 물리적 스토리지 용량과 같습니다. 물리적 스토리지 용량의 전체 양이 있어야 합니다. 물리적으로 할당된 공간은 호스트에 보고된 공간과 같습니다.

일반적으로 볼륨의 보고된 용량을 볼륨이 커질 것으로 생각되는 최대 용량으로 설정합니다. 볼륨은 애플리케이션에 예측 가능하고 우수한 성능을 제공합니다. 이는 생성 시 모든 가용 용량이 예약되고 할당되기 때문입니다.



=== 용량 제한

볼륨의 최소 용량은 1MiB이고 최대 용량은 풀 또는 볼륨 그룹에 있는 드라이브의 수와 용량에 따라 결정됩니다.

볼륨에 대해 보고된 용량을 늘릴 경우 다음 지침을 염두에 두십시오.

* 최대 3개의 소수 자릿수(예: 65.375GiB)를 지정할 수 있습니다.
* 용량은 볼륨 그룹에서 사용할 수 있는 최대값보다 작거나 같아야 합니다. 볼륨을 생성할 때 DSS(동적 세그먼트 크기) 마이그레이션에 일부 추가 용량이 사전 할당됩니다. DSS 마이그레이션은 볼륨의 세그먼트 크기를 변경할 수 있는 소프트웨어의 기능입니다.
* 2TiB보다 큰 볼륨은 일부 호스트 운영 체제에서 지원됩니다(보고된 최대 용량은 호스트 운영 체제에 의해 결정됨). 실제로 일부 호스트 운영 체제는 최대 128TiB 볼륨을 지원합니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.




== 애플리케이션별 워크로드

볼륨을 생성할 때 특정 애플리케이션에 대한 스토리지 어레이 구성을 사용자 지정할 워크로드를 선택합니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

볼륨을 생성하는 동안 작업 부하 사용에 대한 질문에 답하라는 메시지가 표시됩니다. 예를 들어 Microsoft Exchange용 볼륨을 만드는 경우 필요한 메일박스 수, 평균 메일박스 용량 요구 사항, 원하는 데이터베이스 복제본 수를 묻는 메시지가 표시됩니다. 시스템에서는 이 정보를 사용하여 최적의 볼륨 구성을 생성합니다. 이 구성은 필요에 따라 편집할 수 있습니다. 선택적으로 볼륨 생성 순서에서 이 단계를 건너뛸 수 있습니다.



=== 워크로드의 유형입니다

두 가지 유형의 워크로드, 즉 애플리케이션별 워크로드와 기타 워크로드를 생성할 수 있습니다.

* * 응용 프로그램별 * -- 응용 프로그램별 작업 부하를 사용하여 볼륨을 생성할 때 응용 프로그램 작업 부하 I/O와 응용 프로그램 인스턴스의 다른 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시와 같은 볼륨 특성은 자동으로 권장 사항이며 다음과 같은 애플리케이션 유형에 대해 생성되는 워크로드에 최적화되어 있습니다.
+
** Microsoft SQL Server를 참조하십시오
** Microsoft Exchange Server를 참조하십시오
** 비디오 감시 애플리케이션
** VMware ESXi(가상 머신 파일 시스템과 함께 사용할 볼륨용)
+
볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.



* * 기타(또는 특정 볼륨 생성을 지원하지 않는 애플리케이션) * -- 다른 워크로드는 볼륨 구성을 사용하며, 특정 애플리케이션과 연결되지 않은 워크로드를 생성하려는 경우 또는 스토리지 어레이에서 사용하려는 애플리케이션에 대한 최적화 기능이 시스템에 내장되어 있지 않은 경우 수동으로 지정해야 합니다. 볼륨 추가/편집 대화 상자를 사용하여 볼륨 구성을 수동으로 지정해야 합니다.




=== 애플리케이션 및 워크로드 뷰

애플리케이션 및 워크로드를 보려면 System Manager를 시작합니다. 이 인터페이스를 통해 다음과 같은 몇 가지 방법으로 애플리케이션별 워크로드와 관련된 정보를 볼 수 있습니다.

* Volumes(볼륨) 타일에서 Applications & Workload(애플리케이션 및 워크로드) 탭을 선택하여 워크로드별로 그룹화된 스토리지 어레이의 볼륨과 워크로드가 연결된 애플리케이션 유형을 볼 수 있습니다.
* 성능 타일에서 애플리케이션 및 워크로드 탭을 선택하여 논리적 객체에 대한 성능 메트릭(지연 시간, IOPS 및 MBs)을 볼 수 있습니다. 오브젝트는 애플리케이션 및 관련 워크로드별로 그룹화됩니다. 이 성능 데이터를 정기적으로 수집하면 기준 측정을 설정하고 추세를 분석할 수 있습니다. 이렇게 하면 I/O 성능과 관련된 문제를 조사하는 데 도움이 됩니다.

