---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 호스트에서 액세스할 수 있는 하나 이상의 볼륨에 대해 볼륨 그룹을 생성할 수 있습니다. 
---
= 볼륨 그룹을 생성합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
호스트에서 액세스할 수 있는 하나 이상의 볼륨에 대해 볼륨 그룹을 생성할 수 있습니다. 볼륨 그룹은 RAID 레벨 및 용량과 같은 공유 특성을 가진 볼륨의 컨테이너입니다.

다음 지침을 검토하십시오.

* 할당되지 않은 드라이브가 하나 이상 필요합니다.
* 단일 볼륨 그룹에 포함할 수 있는 드라이브 용량에 제한이 있습니다. 이러한 제한은 호스트 유형에 따라 다릅니다.
* 쉘프/서랍 손실 보호를 활성화하려면 최소 3개의 쉘프 또는 서랍에 있는 드라이브를 사용하는 볼륨 그룹을 생성해야 합니다. 단, RAID 1을 사용하는 경우는 예외입니다. 여기서 두 개의 쉘프/서랍이 최소값이 됩니다.
* EF600 또는 EF300 스토리지 어레이를 구성할 때는 각 컨트롤러가 처음 12개 슬롯에서 동일한 수의 드라이브와 마지막 12개 슬롯에서 동일한 수의 드라이브를 액세스할 수 있는지 확인하십시오. 이 구성을 사용하면 컨트롤러가 드라이브 측 PCIe 버스를 보다 효과적으로 사용할 수 있습니다. 현재 시스템은 볼륨 그룹을 생성할 때 Advanced(고급) 기능에서 드라이브를 선택할 수 있습니다.


선택한 RAID 레벨이 볼륨 그룹의 결과 용량에 미치는 영향을 검토합니다.

* RAID 1을 선택한 경우 미러링된 쌍이 선택되었는지 확인하기 위해 한 번에 두 개의 드라이브를 추가해야 합니다. 4개 이상의 드라이브를 선택하면 미러링 및 스트라이핑(RAID 10 또는 RAID 1+0이라고 함)이 수행됩니다.
* RAID 5를 선택한 경우 최소 3개의 드라이브를 추가하여 볼륨 그룹을 만들어야 합니다.
* RAID 6을 선택한 경우 최소 5개의 드라이브를 추가하여 볼륨 그룹을 생성해야 합니다.


볼륨 그룹을 생성하는 동안 드라이브 수, 보안 기능, DA(Data Assurance) 기능, 쉘프 손실 보호, 서랍 손실 보호와 같은 그룹 특성을 확인합니다.

EF600 및 EF300 스토리지 어레이의 설정에는 리소스 프로비저닝, 드라이브 블록 크기, 볼륨 블록 크기도 포함됩니다.


NOTE: 대용량 드라이브를 사용하고 여러 컨트롤러에 볼륨을 분산할 수 있으므로 볼륨 그룹당 둘 이상의 볼륨을 생성하는 것이 스토리지 용량을 사용하고 데이터를 보호하는 좋은 방법입니다.

.단계
. 관리 페이지에서 볼륨 그룹의 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. 메뉴 [Volume group](볼륨 그룹)을 클릭합니다.
+
Create Volume Group 대화상자가 나타납니다.

. 볼륨 그룹의 이름을 입력합니다.
. 데이터 스토리지 및 보호 요구사항에 가장 적합한 RAID 레벨을 선택합니다. 볼륨 그룹 후보 테이블이 나타나고 선택한 RAID 레벨을 지원하는 후보만 표시됩니다.
. (선택 사항) 스토리지 배열에 둘 이상의 드라이브 유형이 있는 경우 사용할 드라이브 유형을 선택합니다.
+
볼륨 그룹 후보 테이블이 나타나고 선택한 드라이브 유형과 RAID 레벨을 지원하는 후보만 표시됩니다.

. (선택 사항) 자동 방법 또는 수동 방법을 선택하여 볼륨 그룹에서 사용할 드라이브를 정의할 수 있습니다. 자동 방법이 기본 선택 항목입니다.
+

CAUTION: 드라이브 중복성과 최적의 드라이브 구성을 이해하는 전문가가 아니라면 수동 방법을 사용하지 마십시오.

+
드라이브를 수동으로 선택하려면 * Manually select drives (advanced) * 링크를 클릭합니다. 클릭하면 자동으로 드라이브 선택(고급) * 으로 변경됩니다.

+
Manual(수동) 방법을 사용하면 볼륨 그룹을 구성하는 특정 드라이브를 선택할 수 있습니다. 할당되지 않은 특정 드라이브를 선택하여 필요한 용량을 확보할 수 있습니다. 스토리지 배열에 다른 미디어 유형 또는 다른 인터페이스 유형의 드라이브가 포함된 경우, 단일 드라이브 유형에 대해 구성되지 않은 용량만 선택하여 새 볼륨 그룹을 생성할 수 있습니다.

. 표시된 드라이브 특성에 따라 볼륨 그룹에서 사용할 드라이브를 선택한 다음 * Create * 를 클릭합니다.


표시되는 드라이브 특성은 자동 방법 또는 수동 방법을 선택했는지 여부에 따라 달라집니다. 자세한 내용은 SANtricity 시스템 관리자 설명서를 참조하십시오. https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["볼륨 그룹을 생성합니다"^].
