---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-add-capacity-to-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 드라이브를 추가하여 기존 풀 또는 볼륨 그룹의 사용 가능한 용량을 확장합니다. 
---
= vCenter용 SANtricity 스토리지 플러그인에서 풀 또는 볼륨 그룹에 용량을 추가합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
드라이브를 추가하여 기존 풀 또는 볼륨 그룹에서 사용 가능한 용량을 확장할 수 있습니다.

.시작하기 전에
* 드라이브가 최적 상태여야 합니다.
* 드라이브는 드라이브 유형(HDD 또는 SSD)이 동일해야 합니다.
* 풀 또는 볼륨 그룹이 Optimal 상태여야 합니다.
* 풀 또는 볼륨 그룹에 모든 보안 가능 드라이브가 포함되어 있는 경우, 보안 가능 드라이브의 암호화 기능을 계속 사용할 수 있는 안전한 드라이브만 추가합니다.


보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.

.이 작업에 대해
이 작업에서는 풀 또는 볼륨 그룹에 포함할 가용 용량을 추가할 수 있습니다. 이 여유 용량을 사용하여 추가 볼륨을 생성할 수 있습니다. 이 작업 중에 볼륨의 데이터에 액세스할 수 있습니다.

풀의 경우 한 번에 최대 60개의 드라이브를 추가할 수 있습니다. 볼륨 그룹의 경우 한 번에 최대 2개의 드라이브를 추가할 수 있습니다. 최대 드라이브 수보다 많은 드라이브를 추가해야 하는 경우 이 절차를 반복합니다. 풀은 스토리지 배열의 최대 제한보다 많은 드라이브를 포함할 수 없습니다.


NOTE: 드라이브를 추가하면 보존 용량을 늘려야 할 수 있습니다. 확장 작업 후 예약된 용량을 늘리는 것이 좋습니다.


NOTE: DA를 지원하지 않는 풀 또는 볼륨 그룹에 용량을 추가할 수 있는 DA(Data Assurance)를 사용하지 마십시오. 풀 또는 볼륨 그룹은 DA 가능 드라이브의 기능을 활용할 수 없습니다. 이 상황에서는 DA를 사용할 수 없는 드라이브를 사용하는 것이 좋습니다.

.단계
. 관리 페이지에서 풀 또는 볼륨 그룹이 있는 스토리지 어레이를 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. 드라이브를 추가할 풀 또는 볼륨 그룹을 선택한 다음 * 용량 추가 * 를 클릭합니다.
+
용량 추가 대화 상자가 나타납니다. 풀 또는 볼륨 그룹과 호환되는 할당되지 않은 드라이브만 나타납니다.

. 용량을 추가할 드라이브 선택... * 에서 기존 풀 또는 볼륨 그룹에 추가할 드라이브를 하나 이상 선택합니다.
+
컨트롤러 펌웨어는 위에 나열된 최상의 옵션을 사용하여 할당되지 않은 드라이브를 정렬합니다. 풀 또는 볼륨 그룹에 추가된 총 사용 가능 용량이 * 선택한 총 용량 * 의 목록 아래에 표시됩니다.

+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
쉘프
 a| 
드라이브의 쉘프 위치를 나타냅니다.



 a| 
베이
 a| 
드라이브의 베이 위치를 나타냅니다



 a| 
용량(GiB)
 a| 
드라이브 용량을 나타냅니다.

** 가능하면 풀 또는 볼륨 그룹의 현재 드라이브 용량과 동일한 용량을 가진 드라이브를 선택합니다.
** 용량이 더 작은 할당되지 않은 드라이브를 추가해야 하는 경우 현재 풀 또는 볼륨 그룹에 있는 각 드라이브의 가용 용량이 줄어듭니다. 따라서 드라이브 용량은 풀 또는 볼륨 그룹에서 동일합니다.
** 용량이 더 큰 할당되지 않은 드라이브를 추가해야 하는 경우, 추가하는 할당되지 않은 드라이브의 가용 용량이 줄어들기 때문에 풀 또는 볼륨 그룹의 드라이브 현재 용량과 일치하게 됩니다.




 a| 
보안 가능
 a| 
드라이브가 안전한지 여부를 나타냅니다.

** 드라이브 보안 기능을 사용하여 풀 또는 볼륨 그룹을 보호할 수 있지만 이 기능을 사용하려면 모든 드라이브가 안전해야 합니다.
** 보안 기능이 있는 드라이브와 비보안 가능 드라이브를 혼합하여 풀 또는 볼륨 그룹을 생성할 수 있지만 드라이브 보안 기능을 활성화할 수는 없습니다.
** 모든 보안 가능 드라이브가 있는 풀 또는 볼륨 그룹은 암호화 기능을 사용하지 않는 경우에도 스페어링 또는 확장을 위한 비보안 가능 드라이브를 수락할 수 없습니다.
** 보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. FIPS 드라이브는 수준 140-3이고 수준 140-3은 상위 수준의 보안일 수 있습니다. 140-3단계 드라이브와 140-3단계 드라이브를 혼합하여 선택하면 풀 또는 볼륨 그룹이 더 낮은 보안 수준(140-2)에서 작동합니다.




 a| 
DA 가능
 a| 
드라이브가 DA(Data Assurance)를 지원하는지 여부를 나타냅니다.

** DA(Data Assurance)가 지원되지 않는 드라이브를 사용하여 DA 가능 풀 또는 볼륨 그룹에 용량을 추가하는 것은 권장되지 않습니다. 풀 또는 볼륨 그룹에는 더 이상 DA 기능이 없으며 풀 또는 볼륨 그룹 내에서 새로 생성된 볼륨에 대해 DA를 활성화하는 옵션이 더 이상 제공되지 않습니다.
** DA(Data Assurance)가 지원되지 않는 풀 또는 볼륨 그룹에 용량을 추가할 수 있는 드라이브를 사용하는 것은 권장되지 않습니다. 풀 또는 볼륨 그룹이 DA 가능 드라이브의 기능을 활용할 수 없기 때문입니다(드라이브 속성이 일치하지 않음). 이 상황에서는 DA를 사용할 수 없는 드라이브를 사용하는 것이 좋습니다.




 a| 
DULBE 가능
 a| 
드라이브에 DULBE(Logical Block Error) 할당 해제 또는 미기록 해제 옵션이 있는지 여부를 나타냅니다. DULBE는 EF300 또는 EF600 스토리지 어레이가 리소스 프로비저닝된 볼륨을 지원할 수 있도록 NVMe 드라이브에 대한 옵션입니다.

|===
====
. 추가 * 를 클릭합니다.
+
풀 또는 볼륨 그룹에 드라이브를 추가하는 경우 풀 또는 볼륨 그룹에 다음 속성 중 하나 이상이 없는 드라이브를 선택하면 확인 대화 상자가 나타납니다.

+
** 선반 손실 방지
** 서랍 손실 방지
** 전체 디스크 암호화 기능
** Data Assurance입니다
** DULBE 기능


. 계속하려면 * 예 * 를 클릭하고, 그렇지 않으면 * 취소 * 를 클릭합니다.


.결과
할당되지 않은 드라이브를 풀 또는 볼륨 그룹에 추가한 후에는 추가 드라이브를 포함하기 위해 풀 또는 볼륨 그룹의 각 볼륨에 있는 데이터가 재배포됩니다.
