---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-remove-capacity.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 드라이브를 제거하여 기존 풀 또는 SSD Cache의 용량을 줄일 수 있습니다. 
---
= 용량을 제거합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
드라이브를 제거하여 기존 풀 또는 SSD Cache의 용량을 줄일 수 있습니다.

드라이브를 제거한 후에는 풀 또는 SSD Cache의 각 볼륨에 있는 데이터가 나머지 드라이브에 재배포됩니다. 제거된 드라이브는 할당되지 않고 해당 용량은 스토리지 어레이의 총 사용 가능 용량의 일부가 됩니다.

.이 작업에 대해
용량을 제거할 때 다음 지침을 따르십시오.

* SSD Cache를 먼저 삭제하지 않으면 SSD Cache의 마지막 드라이브를 제거할 수 없습니다.
* 풀의 드라이브 수를 11개 미만으로 줄일 수는 없습니다.
* 한 번에 최대 12개의 드라이브를 제거할 수 있습니다. 12개 이상의 드라이브를 제거해야 하는 경우 이 절차를 반복합니다.
* 데이터가 풀 또는 SSD Cache의 나머지 드라이브에 재분배된 경우, 데이터를 포함할 풀 또는 SSD Cache에 사용 가능한 용량이 충분하지 않으면 드라이브를 제거할 수 없습니다.


다음은 성능에 영향을 미칠 수 있는 잠재적 영향입니다.

* 풀 또는 SSD Cache에서 드라이브를 제거하면 볼륨 성능이 저하될 수 있습니다.
* 풀 또는 SSD Cache에서 용량을 제거할 때는 보존 용량이 사용되지 않습니다. 하지만 풀 또는 SSD Cache에 남아 있는 드라이브 수에 따라 보존 용량이 줄어들 수 있습니다.


다음은 보안 가능 드라이브에 미치는 영향입니다.

* 보안 기능이 없는 마지막 드라이브를 제거하면 모든 보안 가능 드라이브가 풀에 남아 있습니다. 이 경우 풀에 대한 보안을 설정할 수 있는 옵션이 제공됩니다.
* DA(Data Assurance)를 지원하지 않는 마지막 드라이브를 제거하면 모든 DA 가능 드라이브가 풀에 남아 있습니다.
* 풀에서 생성한 새 볼륨은 DA를 사용할 수 있습니다. 기존 볼륨을 DA로 사용하려면 볼륨을 삭제한 다음 다시 생성해야 합니다.


.단계
. 관리 페이지에서 스토리지 배열을 선택합니다.
+
메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.

. 풀 또는 SSD Cache를 선택한 다음 MENU: More [Remove capacity]([용량 제거]) 를 클릭합니다.
+
용량 제거 대화 상자가 나타납니다.

. 목록에서 하나 이상의 드라이브를 선택합니다.
+
목록에서 드라이브를 선택하거나 선택 취소하면 선택한 총 용량 필드가 업데이트됩니다. 이 필드에는 선택한 드라이브를 제거한 후 결과로 표시되는 풀 또는 SSD Cache의 총 용량이 표시됩니다.

. 제거 * 를 클릭한 다음 드라이브 제거 여부를 확인합니다.


.결과
풀 또는 SSD Cache에서 새로 축소된 용량이 Pools and Volume Groups 뷰에 반영됩니다.
