---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-pools-and-volume-group-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: '스토리지 용량을 할당하려면 스토리지 어레이에서 사용할 HDD(하드 디스크 드라이브) 또는 SSD(Solid State Disk) 드라이브가 포함될 풀 또는 볼륨 그룹을 생성합니다.' 
---
= 풀 및 볼륨 그룹 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter용 저장소 플러그인에서 스토리지를 프로비저닝하려면 스토리지 배열에서 사용할 HDD(하드 디스크 드라이브) 또는 SSD(Solid State Disk) 드라이브가 포함될 풀 또는 볼륨 그룹을 만듭니다.



== 프로비저닝

물리적 하드웨어는 논리적 구성 요소로 프로비저닝되므로 데이터를 구성하고 쉽게 검색할 수 있습니다. 지원되는 그룹 유형에는 두 가지가 있습니다.

* 풀
* 볼륨 그룹


풀 및 볼륨 그룹은 스토리지 어레이에서 최상위 스토리지 단위이며, 드라이브 용량을 관리 가능한 여러 사업부로 나눕니다. 이러한 논리적 사업부 내에는 데이터가 저장되는 개별 볼륨 또는 LUN이 있습니다.

스토리지 시스템을 구축할 때 첫 번째 단계는 다음을 통해 사용 가능한 드라이브 용량을 다양한 호스트에 제공하는 것입니다.

* 용량이 충분한 풀 또는 볼륨 그룹 생성
* 성능 요구 사항을 충족하는 데 필요한 드라이브 수를 풀 또는 볼륨 그룹에 추가
* 특정 비즈니스 요구 사항을 충족하기 위해 원하는 RAID 보호 수준(볼륨 그룹을 사용하는 경우)을 선택합니다


동일한 스토리지 시스템에 풀 또는 볼륨 그룹이 있을 수 있지만 드라이브가 둘 이상의 풀 또는 볼륨 그룹에 속할 수는 없습니다. 그런 다음 호스트에게 입출력에 대해 제공되는 볼륨이 풀 또는 볼륨 그룹의 공간을 사용하여 생성됩니다.



== 풀

풀은 물리적 하드 디스크 드라이브를 대용량 스토리지 공간에 통합하여 RAID 보호 기능을 강화하도록 설계되었습니다. 풀은 풀에 할당된 총 드라이브 수에서 많은 가상 RAID 세트를 생성하고 모든 참여 드라이브에 데이터를 균등하게 분산시킵니다. 드라이브가 손실되거나 추가되면 시스템은 모든 활성 드라이브에 걸쳐 데이터를 동적으로 재조정합니다.

풀은 또 다른 RAID 레벨로 작동하며, 기본 RAID 아키텍처를 가상화하여 재구축, 드라이브 확장, 드라이브 손실 처리 등의 작업을 수행할 때 성능과 유연성을 최적화합니다. 시스템은 8+2 구성(데이터 디스크 8개 + 패리티 디스크 2개)에서 RAID 레벨을 6으로 자동 설정합니다.



=== 드라이브 일치

풀에서 사용할 HDD 또는 SSD 중 하나를 선택할 수 있지만 볼륨 그룹과 마찬가지로 풀의 모든 드라이브에서 동일한 기술을 사용해야 합니다. 컨트롤러는 자동으로 포함할 드라이브를 선택하므로 선택한 기술에 필요한 드라이브의 수가 충분한지 확인해야 합니다.



=== 장애가 발생한 드라이브 관리

풀에는 최소 11개의 드라이브 용량이 있지만 드라이브 장애가 발생할 경우 여유 용량을 위해 1개의 드라이브 용량이 예약됩니다. 이 여유 용량을 "보존 용량"이라고 합니다.

풀을 생성할 때 비상 사용을 위해 특정 용량이 보존됩니다. 이 용량은 여러 드라이브의 관점에서 표현되지만 실제 구현은 전체 드라이브 풀에 분산됩니다. 기본 보존 용량은 풀의 드라이브 수를 기준으로 합니다.

풀을 생성한 후에는 보존 용량 값을 더 많이 또는 더 적은 용량으로 변경하거나 보존 용량(0개 드라이브의 값)을 사용하지 않도록 설정할 수 있습니다. 보존할 수 있는 최대 용량(드라이브 수로 표시)은 10이지만 풀의 총 드라이브 수에 따라 사용 가능한 용량이 더 적을 수 있습니다.



== 볼륨 그룹

볼륨 그룹은 스토리지 시스템에서 볼륨에 용량을 할당하는 방법을 정의합니다. 디스크 드라이브는 RAID 그룹으로 구성되고 볼륨은 RAID 그룹의 드라이브에 상주합니다. 따라서 볼륨 그룹 구성 설정은 그룹에 속한 드라이브와 사용되는 RAID 레벨을 식별합니다.

볼륨 그룹을 생성할 때 컨트롤러는 그룹에 포함할 드라이브를 자동으로 선택합니다. 그룹의 RAID 레벨을 수동으로 선택해야 합니다. 볼륨 그룹의 용량은 선택한 드라이브 수의 합계에 해당 용량을 곱한 값입니다.



=== 드라이브 일치

크기와 성능을 위해서는 볼륨 그룹의 드라이브와 일치해야 합니다. 볼륨 그룹에 더 작은 드라이브와 더 큰 드라이브가 있으면 모든 드라이브가 가장 작은 용량 크기로 인식됩니다. 볼륨 그룹에 더 느리고 빠른 드라이브가 있으면 모든 드라이브가 가장 느린 속도로 인식됩니다. 이러한 요인은 스토리지 시스템의 성능과 전체 용량에 영향을 줍니다.

다양한 드라이브 기술(HDD 및 SSD 드라이브)을 혼합할 수 없습니다. RAID 3, 5 및 6은 최대 30개의 드라이브로 제한됩니다. RAID 1 및 RAID 10은 미러링을 사용하므로 이러한 볼륨 그룹에는 동일한 수의 디스크가 있어야 합니다.



=== 장애가 발생한 드라이브 관리

볼륨 그룹은 볼륨 그룹에 포함된 RAID 1/10, RAID 3, RAID 5 또는 RAID 6 볼륨에서 드라이브에 장애가 발생할 경우 핫 스페어 드라이브를 대기 상태로 사용합니다. 핫 스페어 드라이브에는 데이터가 없으며 스토리지 어레이에 또 다른 수준의 중복성이 추가됩니다.

스토리지 배열의 드라이브에 오류가 발생하면 물리 스왑 없이 핫 스페어 드라이브가 장애가 발생한 드라이브로 자동 대체됩니다. 드라이브에 오류가 발생할 때 핫 스페어 드라이브를 사용할 수 있는 경우 컨트롤러는 중복 데이터를 사용하여 오류가 발생한 드라이브에서 핫 스페어 드라이브로 데이터를 재구성합니다.



== 풀 또는 볼륨 그룹을 사용할지 여부를 결정합니다



=== 풀을 선택합니다

* 더 빠른 드라이브 리빌드 및 단순화된 스토리지 관리 또는 높은 수준의 랜덤 워크로드가 필요한 경우
* 풀을 구성하는 드라이브 집합에 각 볼륨의 데이터를 무작위로 분산하려는 경우 풀의 RAID 레벨 또는 풀의 볼륨을 설정하거나 변경할 수 없습니다. 풀은 RAID 레벨 6을 사용합니다.




=== 볼륨 그룹을 선택합니다

* 최대 시스템 대역폭이 필요한 경우 스토리지 설정을 조정할 수 있고 워크로드가 매우 순차적입니다.
* RAID 레벨을 기반으로 드라이브에 데이터를 배포하려는 경우 볼륨 그룹을 생성할 때 RAID 레벨을 지정할 수 있습니다.
* 볼륨 그룹을 구성하는 드라이브 세트를 통해 각 볼륨의 데이터를 순차적으로 쓰려는 경우



NOTE: 풀은 볼륨 그룹과 함께 존재할 수 있으므로 스토리지 어레이에는 풀과 볼륨 그룹이 모두 포함될 수 있습니다.



== 자동 및 수동 풀 생성

스토리지 구성에 따라 시스템에서 자동으로 풀을 생성하도록 허용하거나 직접 풀을 생성할 수 있습니다. 풀은 논리적으로 그룹화된 드라이브 집합입니다.

풀을 생성 및 관리하기 전에 풀을 자동으로 생성하는 방법과 풀을 수동으로 생성해야 하는 시기에 대한 다음 섹션을 검토하십시오.



=== 자동 작성

시스템에서 스토리지 시스템에서 할당되지 않은 용량을 감지하면 스토리지 시스템에서 할당되지 않은 용량을 감지하면 자동 풀 생성이 시작됩니다. 하나 이상의 풀을 생성하거나 기존 풀에 할당되지 않은 용량을 추가하라는 메시지가 자동으로 표시됩니다.

자동 풀 생성은 다음 조건 중 하나가 참일 때 발생합니다.

* 스토리지 시스템에 풀이 없으며 새 풀을 생성할 수 있는 유사한 드라이브가 충분히 있습니다.
* 풀이 하나 이상 있는 스토리지 배열에 새 드라이브가 추가됩니다. 풀의 각 드라이브는 동일한 드라이브 유형(HDD 또는 SSD)이어야 하며 용량이 같아야 합니다. 다음 작업을 완료하라는 메시지가 표시됩니다.
* 이러한 유형의 드라이브 수가 충분한 경우 단일 풀을 생성합니다.
* 할당되지 않은 용량이 서로 다른 드라이브 유형으로 구성된 경우 여러 풀을 생성합니다.
* 스토리지 배열에 풀이 이미 정의되어 있는 경우 기존 풀에 드라이브를 추가하고 동일한 드라이브 유형의 새 드라이브를 풀에 추가합니다.
* 동일한 드라이브 유형의 드라이브를 기존 풀에 추가하고 다른 드라이브 유형을 사용하여 새 드라이브 유형이 다른 경우 다른 풀을 생성합니다.




=== 수동 생성

자동 생성에서 최적의 구성을 확인할 수 없는 경우 풀을 수동으로 생성할 수 있습니다. 이 상황은 다음 이유 중 하나로 발생할 수 있습니다.

* 새 드라이브를 둘 이상의 풀에 추가할 수 있습니다.
* 하나 이상의 새 풀 후보가 셸프 손실 방지 또는 드로어 손실 방지 기능을 사용할 수 있습니다.
* 현재 풀 후보 중 하나 이상이 셸프 손실 방지 또는 드로어 손실 보호 상태를 유지할 수 없습니다. 스토리지 어레이에 여러 애플리케이션이 있고 동일한 드라이브 리소스를 두고 경합하지 않으려는 경우에도 풀을 수동으로 생성할 수 있습니다. 이 경우 하나 이상의 애플리케이션에 대해 더 작은 풀을 수동으로 생성하는 것이 좋습니다. 데이터를 분산할 볼륨이 많은 대규모 풀에 워크로드를 할당하는 대신 하나 또는 두 개의 볼륨만 할당할 수 있습니다. 특정 애플리케이션의 워크로드 전용으로 별도의 풀을 수동으로 생성하면 스토리지 시스템의 운영 속도가 빨라질 수 있고 경합이 줄어듭니다.

