---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 이름 및 RAID 레벨을 포함하여 볼륨 그룹의 설정을 편집합니다. 
---
= vCenter용 SANtricity 스토리지 플러그인에서 볼륨 그룹에 대한 구성 설정을 변경합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이름 및 RAID 레벨을 포함하여 볼륨 그룹의 설정을 편집할 수 있습니다.

.시작하기 전에
볼륨 그룹에 액세스하는 응용 프로그램의 성능 요구 사항을 수용하기 위해 RAID 레벨을 변경하는 경우 다음 필수 구성 요소를 충족해야 합니다.

* 볼륨 그룹이 Optimal(최적) 상태여야 합니다.
* 새 RAID 레벨로 변환하려면 볼륨 그룹에 충분한 용량이 있어야 합니다.


.단계
. 관리 페이지에서 볼륨 그룹이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. 편집할 볼륨 그룹을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
볼륨 그룹 설정 대화 상자가 나타납니다.

. 설정 * 탭을 선택한 다음 볼륨 그룹 설정을 적절하게 편집합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
볼륨 그룹의 사용자 제공 이름을 변경할 수 있습니다. 볼륨 그룹의 이름을 지정해야 합니다.



 a| 
RAID 레벨
 a| 
드롭다운 메뉴에서 새 RAID 레벨을 선택합니다.

** * RAID 0 스트라이핑* -- 고성능을 제공하지만 데이터 중복성을 제공하지 않습니다. 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨이 실패하고 모든 데이터가 손실됩니다. 스트라이핑 RAID 그룹은 두 개 이상의 드라이브를 하나의 대용량 논리 드라이브로 결합합니다.
** * RAID 1 미러링 * -- 고성능 및 최고의 데이터 가용성을 제공하며 중요한 데이터를 기업 또는 개인 차원에서 저장하는 데 적합합니다. 한 드라이브의 내용을 미러링된 쌍의 두 번째 드라이브에 자동으로 미러링하여 데이터를 보호합니다. 단일 드라이브 장애 시 보호 기능을 제공합니다.
** * RAID 10 스트라이핑/미러링* -- RAID 0(스트라이핑)과 RAID 1(미러링)의 조합을 제공하며, 4개 이상의 드라이브를 선택할 때 가능합니다. RAID 10은 고성능 및 내결함성이 필요한 데이터베이스와 같은 대용량 트랜잭션 애플리케이션에 적합합니다.
** * RAID 5 * -- 일반적인 I/O 크기가 작고 읽기 작업이 많은 다중 사용자 환경(예: 데이터베이스 또는 파일 시스템 스토리지)에 적합합니다.
** * RAID 6 * -- RAID 5 이상의 이중화 보호가 필요하지만 높은 쓰기 성능이 필요하지 않은 환경에 적합합니다. RAID 3은 CLI(Command Line Interface)를 사용하여 볼륨 그룹에만 할당할 수 있습니다. RAID 레벨을 변경하면 이 작업이 시작된 후에는 취소할 수 없습니다. 변경 중에는 데이터를 계속 사용할 수 있습니다.




 a| 
용량 최적화(EF600 어레이만 해당)
 a| 
볼륨 그룹이 생성되면 사용 가능한 용량과 성능 및 드라이브 마모 수명 간의 균형을 제공하는 권장 최적화 용량이 생성됩니다. 사용 가능한 용량 증가를 희생하여 성능 및 드라이브 마모 수명을 개선하려면 슬라이더를 오른쪽으로 이동하거나 성능 및 드라이브 마모 수명을 연장하여 사용 가능한 용량을 늘리기 위해 슬라이더를 왼쪽으로 이동하면 이러한 균형을 조정할 수 있습니다. SSD 드라이브는 용량의 일부가 할당되지 않은 경우 수명이 더 길고 쓰기 성능이 극대화됩니다. 볼륨 그룹과 연결된 드라이브의 경우 할당되지 않은 용량은 그룹의 사용 가능한 용량(볼륨에서 사용하지 않는 용량)과 추가 최적화 용량으로 남겨 둔 사용 가능한 용량의 일부로 구성됩니다. 추가 최적화 용량은 사용 가능한 용량을 줄여 최적화 용량을 최소화하므로 볼륨 생성에 사용할 수 없습니다.

|===
====
. 저장 * 을 클릭합니다.


RAID 레벨 변경으로 인해 용량이 줄어들거나, 볼륨 중복성이 손실되거나, 쉘프/드로어 손실 보호가 손실되면 확인 대화 상자가 나타납니다. 계속하려면 * 예 * 를 선택하고, 그렇지 않으면 * 아니요 * 를 클릭합니다.

.결과
볼륨 그룹의 RAID 레벨을 변경하면 플러그인은 볼륨 그룹을 구성하는 모든 볼륨의 RAID 레벨을 변경합니다. 작업 중에 성능이 약간 영향을 받을 수 있습니다.
