---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-consolidate-free-capacity-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 통합 가용 용량 옵션을 사용하여 선택한 볼륨 그룹에서 기존 가용 익스텐트를 통합합니다. 이 작업을 수행하면 볼륨 그룹의 최대 가용 용량에서 추가 볼륨을 생성할 수 있습니다. 
---
= 볼륨 그룹의 여유 용량을 통합합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
통합 가용 용량 옵션을 사용하여 선택한 볼륨 그룹에서 기존 가용 익스텐트를 통합합니다. 이 작업을 수행하면 볼륨 그룹의 최대 가용 용량에서 추가 볼륨을 생성할 수 있습니다.

.시작하기 전에
* 볼륨 그룹에는 사용 가능한 용량 영역이 하나 이상 포함되어야 합니다.
* 볼륨 그룹의 모든 볼륨이 온라인 상태이고 최적 상태여야 합니다.
* 볼륨의 세그먼트 크기 변경과 같은 볼륨 수정 작업이 진행 중이지 않아야 합니다.


.이 작업에 대해
작업을 시작한 후에는 취소할 수 없습니다. 통합 작업 중에도 데이터에 계속 액세스할 수 있습니다.

다음 방법 중 하나를 사용하여 통합 가용 용량 대화 상자를 시작할 수 있습니다.

* 볼륨 그룹에 대해 사용 가능한 용량 영역이 하나 이상 감지되면 알림 영역의 홈 페이지에 가용 용량 통합 권장 사항이 나타납니다. 무료 용량 통합 * 링크를 클릭하여 대화 상자를 시작합니다.
* 다음 작업에 설명된 대로 Pools & Volume Groups 페이지에서 Consolidate Free Capacity 대화 상자를 시작할 수도 있습니다.


.여유 용량 영역에 대해 자세히 알아보십시오
[%collapsible]
====
사용 가능한 용량 영역은 볼륨 삭제 또는 볼륨 생성 중 사용 가능한 모든 용량을 사용하지 않함으로 인해 발생할 수 있는 사용 가능한 용량입니다. 하나 이상의 사용 가능한 용량 영역이 있는 볼륨 그룹에서 볼륨을 생성할 때 볼륨의 용량은 해당 볼륨 그룹에서 가장 큰 사용 가능한 용량 영역으로 제한됩니다. 예를 들어, 볼륨 그룹의 사용 가능한 용량이 총 15GiB이고 사용 가능한 최대 용량 영역이 10GiB인 경우 생성할 수 있는 최대 볼륨은 10GiB입니다.

볼륨 그룹에 여유 용량을 통합하여 쓰기 성능을 향상할 수 있습니다. 호스트가 파일을 쓰기, 수정 및 삭제할 때 볼륨 그룹의 사용 가능한 용량이 시간 경과에 따라 조각화됩니다. 결국 가용 용량은 단일 연속 블록에 위치하지 않고 볼륨 그룹 전체에 작은 조각으로 분산됩니다. 이로 인해 호스트가 사용 가능한 무료 클러스터 범위에 맞게 새 파일을 조각으로 써야 하기 때문에 파일 조각화가 더욱 심해집니다.

선택한 볼륨 그룹에 여유 용량을 통합하면 호스트가 새 파일을 쓸 때마다 파일 시스템 성능이 향상됩니다. 또한 통합 프로세스를 통해 새 파일이 나중에 조각화되는 것을 방지할 수 있습니다.

====
.단계
. 관리 페이지에서 볼륨 그룹이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. 통합할 여유 용량이 있는 볼륨 그룹을 선택한 다음, Uncommon Tasks [Consolidate volume group free capacity] 메뉴를 선택합니다.
+
여유 용량 통합 대화 상자가 나타납니다.

. 이 작업을 수행하려면 '통합'을 입력하십시오.
. 통합 * 을 클릭합니다.


.결과
시스템은 볼륨 그룹의 여유 용량 영역을 이후 스토리지 구성 작업을 위해 인접한 하나의 용량으로 통합(조각 모음)하기 시작합니다.

.작업을 마친 후
탐색 사이드바에서 * Operations * 를 선택하여 통합 가용 용량 작업의 진행률을 확인합니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
