---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-initialize-volumes.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 볼륨을 수동으로 초기화하여 특정 장애 조건에서 복구합니다. 
---
= 볼륨 초기화
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
볼륨이 처음 생성될 때 자동으로 초기화됩니다. 그러나 Recovery Guru는 특정 장애 조건에서 복구하기 위해 볼륨을 수동으로 초기화하도록 조언할 수 있습니다.

이 옵션은 기술 지원 부서의 안내에 따라서만 사용할 수 있습니다. 초기화할 볼륨을 하나 이상 선택할 수 있습니다.

.시작하기 전에
* 모든 I/O 작업이 중지되었습니다.
* 초기화하려는 볼륨의 모든 디바이스 또는 파일 시스템은 마운트 해제해야 합니다.
* 볼륨이 최적 상태이며 볼륨에서 수정 작업이 진행 중이지 않습니다. * 주의: * 작업을 시작한 후에는 취소할 수 없습니다. 모든 볼륨 데이터가 지워집니다. Recovery Guru에서 그렇게 하도록 조언하지 않는 한 이 작업을 수행하지 마십시오. 이 절차를 시작하기 전에 기술 지원 부서에 문의하십시오.


.이 작업에 대해
볼륨을 초기화할 때 볼륨은 WWN, 호스트 할당, 할당된 용량 및 예약된 용량 설정을 유지합니다. 또한 동일한 DA(Data Assurance) 설정 및 보안 설정을 유지합니다.

다음 유형의 볼륨을 초기화할 수 없습니다.

* 스냅샷 볼륨의 기본 볼륨입니다
* 미러 관계의 운영 볼륨입니다
* 미러 관계의 보조 볼륨입니다
* 볼륨 복사본의 소스 볼륨입니다
* 볼륨 복사본의 타겟 볼륨입니다
* 이미 초기화가 진행 중인 볼륨입니다


이 절차는 풀 또는 볼륨 그룹에서 생성된 표준 볼륨에만 적용됩니다.

.단계
. 관리 페이지에서 초기화할 볼륨이 포함된 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Manage Volumes](볼륨 관리)를 선택합니다.
. 임의의 볼륨을 선택한 다음 menu:More [Initialize volumes](추가 [볼륨 초기화])를 선택합니다.
+
볼륨 초기화 대화 상자가 나타납니다. 스토리지 배열의 모든 볼륨이 이 대화 상자에 나타납니다.

. 초기화하려는 볼륨을 하나 이상 선택하고 작업을 수행할지 확인합니다.


.결과
시스템은 다음 작업을 수행합니다.

* 초기화된 볼륨에서 모든 데이터를 지웁니다.
* 블록 인덱스를 지웁니다. 이로 인해 기록되지 않은 블록이 0으로 채워진 것처럼 읽힙니다(볼륨이 완전히 비어 있는 것처럼 보임).


이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
