---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-automatically.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 시스템에서 할당되지 않은 드라이브 11개 이상을 감지하거나 기존 풀에 적합한 할당되지 않은 드라이브 1개를 감지하면 자동으로 풀을 생성할 수 있습니다. 
---
= 풀을 자동으로 생성합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
시스템에서 할당되지 않은 드라이브 11개 이상을 감지하거나 기존 풀에 적합한 할당되지 않은 드라이브 1개를 감지하면 자동으로 풀을 생성할 수 있습니다. 풀은 논리적으로 그룹화된 드라이브 집합입니다.

다음 조건 중 하나가 참일 경우 풀 자동 구성 대화 상자를 시작할 수 있습니다.

* 드라이브 유형이 유사한 기존 풀에 추가할 수 있는 할당되지 않은 드라이브가 하나 이상 감지되었습니다.
* 할당되지 않은 11개 이상의 드라이브가 감지되었습니다. 이 드라이브는 새 풀을 생성하는 데 사용할 수 있습니다(드라이브 유형이 서로 다른 기존 풀에 추가할 수 없는 경우).


자동 풀 생성을 사용하여 스토리지 어레이에서 할당되지 않은 모든 드라이브를 하나의 풀로 쉽게 구성하고 기존 풀에 드라이브를 추가할 수 있습니다.

다음 사항에 유의하십시오.

* 스토리지 배열에 드라이브를 추가하면 시스템에서 드라이브를 자동으로 감지하고 드라이브 유형 및 현재 구성에 따라 단일 풀 또는 다중 풀을 생성하라는 메시지를 표시합니다.
* 풀이 이전에 정의된 경우 시스템에서 호환 가능한 드라이브를 기존 풀에 추가하는 옵션을 자동으로 표시합니다. 새 드라이브를 기존 풀에 추가하면 시스템에서 자동으로 새 용량에 데이터를 재분배하며, 여기에는 추가한 새 드라이브가 포함됩니다.
* EF600 또는 EF300 스토리지 어레이를 구성할 때는 각 컨트롤러가 처음 12개 슬롯에서 동일한 수의 드라이브와 마지막 12개 슬롯에서 동일한 수의 드라이브를 액세스할 수 있는지 확인하십시오. 이 구성을 사용하면 컨트롤러가 드라이브 측 PCIe 버스를 보다 효과적으로 사용할 수 있습니다. 풀을 생성하려면 스토리지 배열의 모든 드라이브를 사용해야 합니다.


.단계
. 관리 페이지에서 풀의 스토리지 시스템을 선택합니다.
. 메뉴: Provisioning [Configure Pools and Volume Groups]를 선택합니다.
. 메뉴 선택: More [Launch pool auto-configuration](추가 [풀 자동 구성 시작])
+
결과 테이블에는 새 풀, 드라이브가 추가된 기존 풀 또는 둘 다 나열됩니다. 새 풀의 이름은 기본적으로 일련 번호로 지정됩니다.

+
시스템에서 다음 작업을 수행합니다.

+
** 동일한 드라이브 유형(HDD 또는 SSD)의 드라이브 수가 충분하고 용량이 유사한 경우 단일 풀을 생성합니다.
** 할당되지 않은 용량이 서로 다른 드라이브 유형으로 구성된 경우 여러 풀을 생성합니다.
** 스토리지 배열에 풀이 이미 정의되어 있는 경우 기존 풀에 드라이브를 추가하고 동일한 드라이브 유형의 새 드라이브를 풀에 추가합니다.
** 동일한 드라이브 유형의 드라이브를 기존 풀에 추가하고 다른 드라이브 유형을 사용하여 새 드라이브 유형이 다른 경우 다른 풀을 생성합니다.


. 새 풀의 이름을 변경하려면 * 편집 * 아이콘(연필)을 클릭합니다.
. 풀의 추가 특성을 보려면 커서를 위에 놓거나 Details 아이콘(페이지)을 누릅니다.
+
드라이브 유형, 보안 기능, 데이터 보증(DA) 기능, 쉘프 손실 보호, 서랍 손실 보호에 대한 정보가 나타납니다.

+
EF600 및 EF300 스토리지 어레이의 경우 리소스 프로비저닝 및 볼륨 블록 크기에 대한 설정도 표시됩니다.

. Accept * 를 클릭합니다.

