---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 이름, 호스트 할당, 세그먼트 크기, 수정 우선순위, 캐싱 등과 같은 볼륨 설정을 등. 
---
= 볼륨의 설정을 변경합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이름, 호스트 할당, 세그먼트 크기, 수정 우선순위, 캐싱 등과 같은 볼륨 설정을 변경할 수 있습니다. 등.

.시작하기 전에
변경할 볼륨이 최적 상태인지 확인합니다.

.단계
. 관리 페이지에서 변경할 볼륨이 포함된 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Manage Volumes](볼륨 관리)를 선택합니다.
. 변경할 볼륨을 선택한 다음 * 설정 보기/편집 * 을 선택합니다.
+
볼륨 설정 대화 상자가 나타납니다. 선택한 볼륨의 구성 설정이 이 대화 상자에 나타납니다.

. 볼륨의 이름과 호스트 할당을 변경하려면 * Basic * 탭을 선택합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
볼륨의 이름을 표시합니다. 현재 이름이 더 이상 의미가 없거나 적용할 수 없는 경우 볼륨의 이름을 변경합니다.



 a| 
용량
 a| 
선택한 볼륨에 대해 보고되고 할당된 용량을 표시합니다.



 a| 
풀/볼륨 그룹입니다
 a| 
풀 또는 볼륨 그룹의 이름과 RAID 레벨을 표시합니다. 풀 또는 볼륨 그룹이 보안이 가능하고 보안이 설정된 상태인지 여부를 나타냅니다.



 a| 
호스트
 a| 
볼륨 할당을 표시합니다. I/O 작업을 위해 액세스할 수 있도록 볼륨을 호스트 또는 호스트 클러스터에 할당합니다. 이 할당은 호스트 또는 호스트 클러스터에 특정 볼륨 또는 스토리지 배열의 여러 볼륨에 대한 액세스 권한을 부여합니다.

** * Assigned to * -- 선택한 볼륨에 대한 액세스 권한이 있는 호스트 또는 호스트 클러스터를 식별합니다.
** * LUN * -- 논리 단위 번호(LUN)는 호스트가 볼륨에 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다. 각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.


NVMe 인터페이스의 경우 이 열에는 네임스페이스 ID가 표시됩니다. 네임스페이스는 블록 액세스를 위해 포맷된 NVM 스토리지입니다. 스토리지 배열의 볼륨과 관련된 SCSI의 논리 유닛과 유사합니다. 네임스페이스 ID는 네임스페이스에 대한 NVMe 컨트롤러의 고유 식별자이며 1에서 255 사이의 값으로 설정할 수 있습니다. SCSI의 LUN(Logical Unit Number)과 유사합니다.



 a| 
식별자
 a| 
선택한 볼륨의 식별자를 표시합니다.

** WWID(World Wide Identifier)입니다. 볼륨의 고유한 16진수 식별자입니다.
** 확장 고유 식별자(EUI)입니다. 볼륨의 EUI-64 식별자입니다.
** 하위 시스템 식별자(SSID)입니다. 볼륨의 스토리지 배열 하위 시스템 식별자입니다.


|===
====
. 풀 또는 볼륨 그룹의 볼륨에 대한 추가 구성 설정을 변경하려면 * 고급 * 탭을 선택합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
애플리케이션 및 워크로드 정보
 a| 
볼륨 생성 중에 애플리케이션별 워크로드 또는 기타 워크로드를 생성할 수 있습니다. 해당하는 경우 선택한 볼륨에 대한 워크로드 이름, 애플리케이션 유형 및 볼륨 유형이 표시됩니다. 필요한 경우 워크로드 이름을 변경할 수 있습니다.



 a| 
서비스 품질 설정
 a| 
* 영구적으로 데이터 무결성 보장 * 사용 안 함 -- 이 설정은 볼륨이 DA(Data Assurance)를 사용하는 경우에만 나타납니다. DA는 컨트롤러를 통해 드라이브로 데이터가 전송될 때 발생할 수 있는 오류를 검사하고 수정합니다. 선택한 볼륨에서 DA를 영구적으로 비활성화하려면 이 옵션을 사용합니다. 비활성화하면 이 볼륨에서 DA를 다시 활성화할 수 없습니다. * 사전 읽기 중복 검사 활성화 * -- 이 설정은 볼륨이 일반 볼륨인 경우에만 나타납니다. 사전 읽기 이중화 검사는 읽기 수행 시 볼륨의 데이터가 일관되는지 여부를 결정합니다. 이 기능이 활성화된 볼륨은 컨트롤러 펌웨어에 의해 데이터가 일치하지 않는 것으로 확인되면 읽기 오류를 반환합니다.



 a| 
컨트롤러 소유권
 a| 
볼륨의 소유 또는 기본 컨트롤러로 지정된 컨트롤러를 정의합니다. 컨트롤러 소유권은 매우 중요하며 신중하게 계획해야 합니다. 전체 I/O에 대해 컨트롤러를 최대한 균형 조정해야 합니다.



 a| 
세그먼트 크기 조정
 a| 
에는 볼륨 그룹의 볼륨에 대해서만 표시되는 세그먼트 크기 조정 설정이 나와 있습니다. 세그먼트 크기를 변경하여 성능을 최적화할 수 있습니다. * 허용된 세그먼트 크기 전환 * -- 시스템이 허용되는 세그먼트 크기 전환을 결정합니다. 현재 세그먼트 크기에서 잘못 전환되는 세그먼트 크기는 드롭다운 목록에서 사용할 수 없습니다. 허용되는 전이는 일반적으로 현재 세그먼트 크기의 두 배 또는 절반입니다. 예를 들어 현재 볼륨 세그먼트 크기가 32KiB인 경우 16KiB 또는 64KiB의 새 볼륨 세그먼트 크기가 허용됩니다. * SSD 캐시 사용 볼륨 * -- SSD 캐시 사용 볼륨에 대해 4KiB 세그먼트 크기를 지정할 수 있습니다. 작은 블록 입출력 작업을 처리하는 SSD Cache 지원 볼륨(예: 16KiB 입출력 블록 크기 이하)에 대해서만 4KiB 세그먼트 크기를 선택해야 합니다. 대규모 블록 순차적 작업을 처리하는 SSD Cache 지원 볼륨의 세그먼트 크기로 4KiB를 선택하면 성능에 영향을 미칠 수 있습니다. * 세그먼트 크기를 변경하는 시간. * 볼륨의 세그먼트 크기를 변경하는 시간은 다음 변수에 따라 다릅니다.

** 호스트로부터의 I/O 로드
** 볼륨의 수정 우선 순위입니다
** 볼륨 그룹의 드라이브 수입니다
** 드라이브 채널 수입니다
** 스토리지 어레이 컨트롤러의 처리 능력


볼륨의 세그먼트 크기를 변경하면 I/O 성능에 영향을 미치지만 데이터를 계속 사용할 수 있습니다.



 a| 
수정 우선 순위
 a| 
에는 볼륨 그룹의 볼륨에 대해서만 표시되는 수정 우선 순위 설정이 나와 있습니다. 수정 우선순위는 시스템 성능과 관련하여 볼륨 수정 작업에 할당되는 처리 시간을 정의합니다. 시스템 성능에 영향을 미칠 수 있지만 볼륨 수정 우선 순위를 높일 수 있습니다. 슬라이더 막대를 이동하여 우선 순위 수준을 선택합니다. * 수정 우선 순위 비율 * - 최저 우선 순위 비율은 시스템 성능에 도움이 되지만 수정 작업은 더 오래 걸립니다. 가장 높은 우선 순위의 경우 수정 작업에 도움이 되지만 시스템 성능이 저하될 수 있습니다.



 a| 
캐싱
 a| 
에는 볼륨의 전체 I/O 성능에 영향을 미치기 위해 변경할 수 있는 캐싱 설정이 나와 있습니다.



 a| 
SSD 캐시
 a| 
EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다. 에는 SSD 캐시 설정이 나와 있습니다. 이 설정은 호환 볼륨에서 읽기 전용 성능을 향상하는 방법으로 활성화할 수 있습니다. 볼륨은 동일한 드라이브 보안 및 데이터 보증 기능을 공유하는 경우 호환됩니다. SSD Cache 기능은 하나 또는 여러 개의 SSD(Solid State Disk)를 사용하여 읽기 캐시를 구현합니다. SSD의 읽기 시간이 더 빨라지므로 애플리케이션 성능이 향상됩니다. 읽기 캐시가 스토리지 배열에 있기 때문에, 캐시는 스토리지 배열을 사용하는 모든 응용 프로그램에서 공유됩니다. 캐시하려는 볼륨을 선택한 다음 캐싱은 자동으로 이루어지며 동적 볼륨입니다.

|===
====
. 저장 * 을 클릭합니다.


.결과
선택한 사항에 따라 볼륨 설정이 변경됩니다.
