---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-santricity-os.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 최신 소프트웨어 및 NVSRAM으로 하나 이상의 스토리지 어레이를 업그레이드하여 모든 최신 기능과 버그 수정을 확인할 수 있습니다. 
---
= SANtricity OS를 업그레이드합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
최신 소프트웨어 및 NVSRAM으로 하나 이상의 스토리지 어레이를 업그레이드하여 모든 최신 기능과 버그 수정을 확인할 수 있습니다. 컨트롤러 NVSRAM은 컨트롤러의 기본 설정을 지정하는 컨트롤러 파일입니다.

다음을 확인합니다.

* 플러그인이 실행 중인 호스트 시스템에서 최신 SANtricity OS 파일을 사용할 수 있습니다.
* 소프트웨어 업그레이드를 지금 또는 나중에 활성화할지 여부를 알 수 있습니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.
+
** * 시간 * -- 소프트웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 부하가 더 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 OS 소프트웨어를 테스트할 수 있습니다.





CAUTION: * 데이터 손실 또는 스토리지 배열 손상 위험 * -- 업그레이드 중에 스토리지 배열을 변경하지 마십시오. 스토리지 어레이에 대한 전원을 유지합니다.

.단계
. 스토리지 어레이에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버를 사용하지 않는 경우 스토리지 어레이에 대한 I/O 작업을 중지하여 응용 프로그램 오류를 방지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.
. 기본 보기에서 * 관리 * 를 선택한 다음 업그레이드할 스토리지 어레이를 하나 이상 선택합니다.
. 업그레이드 센터 [업그레이드 > SANtricity OS > 소프트웨어]를 선택합니다.
+
SANtricity OS 소프트웨어 업그레이드 페이지가 나타납니다.

. 지원 사이트에서 로컬 컴퓨터로 최신 SANtricity OS 소프트웨어 패키지를 다운로드합니다.
+
.. 소프트웨어 저장소에 새 파일 추가 를 클릭합니다
.. 최신 SANtricity OS 다운로드를 찾기 위한 링크를 클릭합니다.
.. 최신 릴리스 다운로드 * 링크를 클릭합니다.
.. 나머지 지침에 따라 OS 파일과 NVSRAM 파일을 로컬 컴퓨터에 다운로드합니다.
+

NOTE: 버전 8.42 이상에서는 디지털 서명된 펌웨어가 필요합니다. 서명되지 않은 펌웨어를 다운로드하려고 하면 오류가 표시되고 다운로드가 중단됩니다.



. 컨트롤러를 업그레이드하는 데 사용할 OS 소프트웨어 파일과 NVSRAM 파일을 선택합니다.
+
.. 드롭다운에서 로컬 시스템으로 다운로드한 OS 파일을 선택합니다.
+
여러 개의 파일을 사용할 수 있는 경우 파일이 최신 날짜부터 가장 오래된 날짜순으로 정렬됩니다.

+

NOTE: 소프트웨어 리포지토리는 플러그인과 관련된 모든 소프트웨어 파일을 나열합니다. 사용할 파일이 표시되지 않으면 * 소프트웨어 리포지토리에 새 파일 추가 * 링크를 클릭하여 추가할 OS 파일이 있는 위치를 찾을 수 있습니다.

.. NVSRAM 파일 선택 * 드롭다운에서 사용할 컨트롤러 파일을 선택합니다.
+
파일이 여러 개 있는 경우 파일이 최신 날짜부터 가장 오래된 날짜순으로 정렬됩니다.



. Compatible Storage Array 표에서 선택한 OS 소프트웨어 파일과 호환되는 스토리지 배열을 검토한 다음 업그레이드할 스토리지를 선택합니다.
+
** 관리 보기에서 선택했으며 선택한 펌웨어 파일과 호환되는 스토리지 배열은 기본적으로 호환 가능한 스토리지 배열 테이블에서 선택됩니다.
** 선택한 펌웨어 파일로 업데이트할 수 없는 스토리지 배열은 * 호환되지 않음 * 상태로 표시된 호환 가능한 스토리지 배열 테이블에서 선택할 수 없습니다.


. (선택 사항) 소프트웨어 파일을 활성화하지 않고 스토리지 어레이로 전송하려면 * OS 소프트웨어를 스토리지 어레이로 전송, 스테이징으로 표시 및 나중에 활성화 * 확인란을 선택합니다.
. 시작 * 을 클릭합니다.
. 지금 활성화할지 아니면 나중에 활성화할지 여부에 따라 다음 중 하나를 수행합니다.
+
** 업그레이드하려는 어레이에 제안된 OS 소프트웨어 버전을 전송하려면 "전송"을 입력하고 * 전송 * 을 클릭합니다. 전송된 소프트웨어를 활성화하려면 업그레이드 센터 [스테이징된 SANtricity OS 소프트웨어 활성화] 메뉴를 선택합니다.
** 업그레이드를 선택한 어레이에서 제안된 OS 소프트웨어 버전을 전송 및 활성화하려면 "업그레이드"를 입력하고 * 업그레이드 * 를 클릭합니다.
+
시스템은 업그레이드를 위해 선택한 각 스토리지 어레이로 소프트웨어 파일을 전송한 다음 재부팅을 시작하여 해당 파일을 활성화합니다.

+
업그레이드 작업 중에 다음 작업이 수행됩니다.

** 업그레이드 전 상태 점검이 업그레이드 프로세스의 일부로 실행됩니다. 업그레이드 전 상태 점검을 통해 모든 스토리지 시스템 구성 요소를 평가하여 업그레이드를 진행할 수 있는지 확인합니다.
** 스토리지 배열에 대한 상태 검사에 실패하면 업그레이드가 중지됩니다. 줄임표(…)를 클릭할 수 있습니다. 그리고 * 로그 저장 * 을 선택하여 오류를 검토합니다. 상태 점검 오류를 재정의하도록 선택한 다음 * 계속 * 을 클릭하여 업그레이드를 진행할 수도 있습니다.
** 업그레이드 전 상태 점검 후 업그레이드 작업을 취소할 수 있습니다.


. (선택 사항) 업그레이드가 완료되면 줄임표(…)를 클릭하여 특정 스토리지 배열에 대해 업그레이드된 항목 목록을 볼 수 있습니다. 그런 다음 * 로그 저장 * 을 선택합니다.
+
이 파일은 브라우저의 다운로드 폴더에 'upgrade_log-<date>'라는 이름으로 저장됩니다. Json'이라고 합니다.


