---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-use-ca-signed-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Storage Plugin for vCenter를 호스팅하는 관리 시스템에 안전하게 액세스할 수 있도록 CA 서명 인증서를 받아서 가져옵니다. 
---
= CA 서명 인증서를 사용합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Storage Plugin for vCenter를 호스팅하는 관리 시스템에 안전하게 액세스하기 위해 CA 서명 인증서를 얻고 가져올 수 있습니다.

CA 서명 인증서를 사용하는 절차는 3단계로 구성됩니다.

* <<Step 1: Complete a CSR file>>.
* <<Step 2: Submit CSR file>>.
* <<Step 3: Import management certificates>>.




== 1단계: CSR 파일을 완료합니다

먼저 인증서 서명 요청(CSR) 파일을 생성해야 합니다. 이 파일은 사용자의 조직과 플러그인이 실행 중인 호스트 시스템을 식별합니다. 또는 OpenSSL과 같은 도구를 사용하여 CSR 파일을 생성하고 로 건너뛸 수 있습니다 <<Step 2: Submit CSR file>>.

.단계
. 인증서 관리 * 를 선택합니다.
. 관리 * 탭에서 * CSR 완료 * 를 선택합니다.
. 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** * 조직 * -- 회사 또는 조직의 전체 법적 이름. Inc. 또는 Corp.와 같은 접미사를 포함합니다
** * 조직 단위(선택 사항) * -- 인증서를 처리하는 조직의 사업부입니다.
** * 시/군/구 * -- 호스트 시스템이나 업무가 위치한 도시.
** * 주/지역(선택 사항) * -- 호스트 시스템 또는 비즈니스가 위치한 주 또는 지역입니다.
** * 국가 ISO 코드 * -- 미국 등 해당 국가의 2자리 ISO(International Organization for Standardization) 코드입니다.


. 플러그인이 실행되고 있는 호스트 시스템에 대한 다음 정보를 입력합니다.
+
** * 공통 이름 * -- 플러그인이 실행되고 있는 호스트 시스템의 IP 주소 또는 DNS 이름입니다. 이 주소가 올바른지 확인합니다. 입력한 주소와 정확히 일치해야 브라우저에서 플러그인에 액세스할 수 있습니다. http:// 또는 https://를 포함하지 마십시오. DNS 이름은 와일드카드로 시작할 수 없습니다.
** * 대체 IP 주소 * -- 공통 이름이 IP 주소인 경우 호스트 시스템에 대한 추가 IP 주소 또는 별칭을 선택적으로 입력할 수 있습니다. 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다.
** * 대체 DNS 이름 * -- 공통 이름이 DNS 이름이면 호스트 시스템에 대한 추가 DNS 이름을 입력합니다. 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다. 대체 DNS 이름이 없지만 첫 번째 필드에 DNS 이름을 입력한 경우 여기에 해당 이름을 복사합니다. DNS 이름은 와일드카드로 시작할 수 없습니다.


. 호스트 정보가 올바른지 확인합니다. 그렇지 않으면 CA에서 반환된 인증서를 가져오려고 할 때 실패합니다.
. 마침 * 을 클릭합니다.




== 2단계: CSR 파일을 제출합니다

CSR(인증서 서명 요청) 파일을 생성한 후 생성된 CSR 파일을 CA에 전송하여 플러그인을 호스팅하는 시스템에 대한 서명된 관리 인증서를 받습니다.

E-Series 시스템에는 .pem, .crt, .cer 또는 .key 파일 형식을 포함하는 서명된 인증서에 대한 PEM 형식(Base64 ASCII 인코딩)이 필요합니다.

.단계
. 다운로드한 CSR 파일을 찾습니다.
+
다운로드의 폴더 위치는 브라우저에 따라 다릅니다.

. CSR 파일을 CA(예: VeriSign 또는 DigiCert)에 제출하고 서명된 인증서를 PEM 형식으로 요청합니다.



CAUTION: CSR 파일을 CA에 제출한 후 다른 CSR 파일을 다시 생성하지 마십시오.

CSR을 생성할 때마다 시스템은 개인 키 및 공개 키 쌍을 생성합니다. 공개 키는 CSR의 일부이며 개인 키는 시스템의 키 저장소에 보관됩니다. 서명된 인증서를 받아서 가져오면 시스템에서 개인 키와 공개 키가 모두 원래 쌍이 되도록 합니다. 키가 일치하지 않으면 서명된 인증서가 작동하지 않으므로 CA에서 새 인증서를 요청해야 합니다.



== 3단계: 관리 인증서를 가져옵니다

CA(인증 기관)에서 서명된 인증서를 받은 후 플러그인이 설치된 호스트 시스템으로 인증서를 가져옵니다.

.시작하기 전에
* CA의 서명된 인증서가 있어야 합니다. 이러한 파일에는 루트 인증서, 하나 이상의 중간 인증서 및 서버 인증서가 포함됩니다.
* CA가 체인 인증서 파일(예: .p7b 파일)을 제공한 경우, 루트 인증서, 하나 이상의 중간 인증서 및 서버 인증서 등 개별 파일에 체인 파일의 압축을 풀어야 합니다. Windows certmgr 유틸리티를 사용하여 파일의 압축을 풀 수 있습니다(마우스 오른쪽 단추를 클릭하고 All Tasks(모든 작업) [Export(내보내기)] 메뉴를 선택합니다). base-64 인코딩이 권장됩니다. 내보내기가 완료되면 체인의 각 인증서 파일에 대해 CER 파일이 표시됩니다.
* 플러그인이 실행 중인 호스트 시스템에 인증서 파일을 복사해야 합니다.


.단계
. 인증서 관리 * 를 선택합니다.
. 관리 * 탭에서 * 가져오기 * 를 선택합니다.
+
인증서 파일을 가져올 수 있는 대화 상자가 열립니다.

. 찾아보기 * 를 클릭하여 먼저 루트 및 중간 인증서 파일을 선택한 다음 서버 인증서를 선택합니다. 외부 도구에서 CSR을 생성한 경우 CSR과 함께 생성된 개인 키 파일도 가져와야 합니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 가져오기 * 를 클릭합니다.


파일이 업로드되고 검증됩니다. 인증서 정보가 인증서 관리 페이지에 표시됩니다.
