---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-are-some-drives-not-showing-up.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Add Capacity 대화 상자에서 기존 풀 또는 볼륨 그룹에 용량을 추가하는 데 일부 드라이브를 사용할 수 없습니다. 
---
= 일부 드라이브가 표시되지 않는 이유는 무엇입니까?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Add Capacity 대화 상자에서 기존 풀 또는 볼륨 그룹에 용량을 추가하는 데 일부 드라이브를 사용할 수 없습니다.

드라이브는 다음과 같은 이유로 적합하지 않습니다.

* 드라이브를 할당하지 않고 안전하게 사용할 수 없어야 합니다. 다른 풀, 다른 볼륨 그룹에 이미 속해 있거나 핫 스페어로 구성된 드라이브는 사용할 수 없습니다. 드라이브 할당이 취소되었지만 보안이 설정된 경우 해당 드라이브를 수동으로 지워야 사용할 수 있습니다.
* 최적화되지 않은 상태의 드라이브는 해당되지 않습니다.
* 드라이브 용량이 너무 작으면 대상에서 제외됩니다.
* 드라이브 미디어 유형은 풀 또는 볼륨 그룹 내에서 일치해야 합니다. 다음을 혼합할 수 없습니다.
+
** 솔리드 스테이트 디스크(SSD)가 장착된 하드 디스크 드라이브(HDD)
** SAS 드라이브를 포함한 NVMe
** 512바이트 및 4KiB 볼륨 블록 크기의 드라이브


* 풀 또는 볼륨 그룹에 모든 보안 가능 드라이브가 포함되어 있는 경우 비보안 가능 드라이브가 표시되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 FIPS(Federal Information Processing Standards) 드라이브가 포함되어 있는 경우 비 FIPS 드라이브가 나열되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 DA(Data Assurance) 가능 드라이브가 포함되어 있고 풀 또는 볼륨 그룹에 하나 이상의 DA 지원 볼륨이 있는 경우, DA를 사용할 수 없는 드라이브는 사용할 수 없으므로 해당 풀 또는 볼륨 그룹에 추가할 수 없습니다. 그러나 풀 또는 볼륨 그룹에 DA 지원 볼륨이 없는 경우 DA를 사용할 수 없는 드라이브를 해당 풀 또는 볼륨 그룹에 추가할 수 있습니다. 이러한 드라이브를 혼합하려는 경우 DA 지원 볼륨을 생성할 수 없습니다.



NOTE: 새 드라이브를 추가하거나 풀 또는 볼륨 그룹을 삭제하여 스토리지 시스템에서 용량을 늘릴 수 있습니다.
