---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 두 개 이상의 호스트에서 동일한 볼륨에 대한 I/O 액세스가 필요한 경우 호스트 클러스터를 생성할 수 있습니다. 
---
= 호스트 클러스터를 생성합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
두 개 이상의 호스트에서 동일한 볼륨에 대한 I/O 액세스가 필요한 경우 호스트 클러스터를 생성할 수 있습니다.

호스트 클러스터를 생성할 때는 다음 지침을 염두에 두십시오.

* 클러스터를 생성하는 데 사용할 수 있는 호스트가 두 개 이상 없으면 이 작업이 시작되지 않습니다.
* 호스트 클러스터의 호스트는 서로 다른 운영 체제(이기종)를 가질 수 있습니다.
* 호스트 클러스터의 NVMe 호스트는 비 NVMe 호스트와 혼합하여 사용할 수 없습니다.
* DA(Data Assurance) 지원 볼륨을 생성하려면 사용하려는 호스트 연결이 DA를 지원해야 합니다.
+
스토리지 시스템의 컨트롤러에 있는 호스트 접속 중 하나라도 DA를 지원하지 않으면 연결된 호스트가 DA 지원 볼륨의 데이터에 액세스할 수 없습니다.

* 선택한 이름이 이미 사용 중인 경우에는 이 작업이 성공하지 않습니다.
* 이름의 길이는 30자를 초과할 수 없습니다.


.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. 메뉴 선택: Create [Host cluster](호스트 클러스터 생성)를 선택합니다.
+
Create Host Cluster 대화상자가 나타납니다.

. 호스트 클러스터에 대한 설정을 적절히 선택합니다.
+
|===
| 설정 | 설명 


| 이름 | 새 호스트 클러스터의 이름을 입력합니다. 


| 볼륨 액세스를 공유할 호스트를 선택합니다 | 드롭다운 목록에서 두 개 이상의 호스트를 선택합니다. 호스트 클러스터에 아직 포함되지 않은 호스트만 목록에 표시됩니다. 
|===
. Create * 를 클릭합니다.
+
선택한 호스트가 서로 다른 DA(Data Assurance) 기능을 가진 인터페이스 유형에 연결된 경우 호스트 클러스터에서 DA를 사용할 수 없다는 메시지가 포함된 대화 상자가 나타납니다. 이 비가용성은 DA 지원 볼륨을 호스트 클러스터에 추가하지 못하도록 합니다. 계속하려면 * 예 * 를 선택하고 취소하려면 * 아니요 * 를 선택합니다.

+
DA는 전체 스토리지 시스템에서 데이터 무결성을 높입니다. DA를 사용하면 호스트와 드라이브 간에 데이터가 이동할 때 발생할 수 있는 오류를 스토리지 시스템에서 확인할 수 있습니다. 새 볼륨에 DA를 사용하면 오류가 감지됩니다.



새 호스트 클러스터가 아래 행에 할당된 호스트와 함께 테이블에 나타납니다.

I/O 작업에 사용할 수 있도록 볼륨을 호스트 클러스터에 할당해야 합니다. 로 이동합니다 link:vc-olh-assign-volumes-to-hosts.html["호스트에 볼륨을 할당합니다"].
