---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 같은 유형의 여러 스토리지 배열에 대한 SANtricity 소프트웨어 및 NVSRAM 업그레이드를 관리할 수 있습니다. 
---
= 업그레이드 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter용 스토리지 플러그인에서 같은 유형의 여러 스토리지 어레이에 대한 SANtricity 소프트웨어 및 NVSRAM 업그레이드를 관리할 수 있습니다.



== 워크플로우 업그레이드

다음 단계에서는 소프트웨어 업그레이드를 수행하기 위한 높은 수준의 워크플로우를 제공합니다.

. 지원 사이트에서 최신 SANtricity OS 파일을 다운로드합니다(지원 페이지에서 링크 제공). 관리 호스트 시스템(브라우저에서 플러그인에 액세스하는 호스트)에 파일을 저장한 다음 파일의 압축을 풉니다.
. 플러그인에서 SANtricity OS 소프트웨어 파일과 NVSRAM 파일을 리포지토리(파일이 저장되는 서버 영역)에 로드할 수 있습니다.
. 저장소에 파일이 로드되면 업그레이드에 사용할 파일을 선택할 수 있습니다. SANtricity OS 소프트웨어 업그레이드 페이지에서 OS 소프트웨어 파일과 NVSRAM 파일을 선택합니다. 소프트웨어 파일을 선택하면 호환되는 스토리지 배열 목록이 이 페이지에 표시됩니다. 그런 다음 새 소프트웨어로 업그레이드할 스토리지 어레이를 선택합니다. (호환되지 않는 어레이는 선택할 수 없습니다.)
. 그런 다음 즉시 소프트웨어 전송 및 활성화를 시작하거나 나중에 활성화할 파일을 준비하도록 선택할 수 있습니다. 업그레이드 프로세스 중에 플러그인은 다음 작업을 수행합니다.
+
** 스토리지 배열의 상태 점검을 수행하여 업그레이드가 완료되지 못할 수 있는 조건이 있는지 확인합니다. 상태 확인에 실패한 어레이가 있으면 해당 특정 어레이를 건너뛰고 다른 어레이를 계속 업그레이드할 수 있습니다. 또는 전체 프로세스를 중지하고 통과하지 못한 어레이의 문제를 해결할 수 있습니다.
** 각 컨트롤러로 업그레이드 파일을 전송합니다.
** 컨트롤러를 재부팅하고 한 번에 하나의 컨트롤러인 새 OS 소프트웨어를 활성화합니다. 활성화 중에 기존 OS 파일이 새 파일로 대체됩니다.





NOTE: 나중에 소프트웨어가 활성화되도록 지정할 수도 있습니다.



== 업그레이드 고려 사항

여러 스토리지 시스템을 업그레이드하기 전에 계획의 일환으로 주요 고려 사항을 검토하십시오.



=== 현재 버전

검색된 각 스토리지 배열에 대한 vCenter용 저장소 플러그인 의 관리 페이지에서 현재 SANtricity OS 소프트웨어 버전을 볼 수 있습니다. 이 버전은 SANtricity OS 소프트웨어 열에 표시됩니다. 각 행에서 OS 버전을 클릭하면 컨트롤러 펌웨어 및 NVSRAM 정보가 팝업 대화 상자에 표시됩니다.



=== 업그레이드가 필요한 기타 구성 요소

업그레이드 프로세스 중에 호스트가 컨트롤러와 올바르게 상호 작용할 수 있도록 호스트의 다중 경로/페일오버 드라이버 또는 HBA 드라이버를 업그레이드해야 할 수도 있습니다. 호환성 정보는 을 참조하십시오 link:https://imt.netapp.com/matrix/["상호 운용성 매트릭스 툴"^].



=== 듀얼 컨트롤러

스토리지 어레이에 2개의 컨트롤러가 포함되어 있고 다중 경로 드라이버가 설치되어 있는 경우, 업그레이드가 진행되는 동안 스토리지 어레이에서 I/O를 계속 처리할 수 있습니다. 업그레이드 중에 다음 프로세스가 발생합니다.

. 컨트롤러 A는 모든 LUN을 컨트롤러 B로 페일오버합니다
. 컨트롤러 A에서 업그레이드가 발생합니다
. 컨트롤러 A는 LUN과 모든 컨트롤러 B의 LUN을 백업합니다.
. 컨트롤러 B에서 업그레이드가 발생합니다


업그레이드가 완료된 후 컨트롤러 간에 볼륨을 수동으로 재배포하여 볼륨이 올바른 소유 컨트롤러로 돌아가도록 해야 할 수 있습니다.
