---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-shelf-loss-protection-and-drawer-loss-protection.html 
keywords:  
summary:  
---
= 선반 손실 방지 및 서랍 손실 방지란 무엇입니까?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
쉘프 손실 보호 및 드로어 손실 보호는 단일 쉘프 또는 드로어에 장애가 발생해도 데이터 액세스를 유지할 수 있는 풀 및 볼륨 그룹의 속성입니다.



=== 선반 손실 방지

쉘프는 드라이브 또는 드라이브와 컨트롤러를 포함합니다. 쉘프 손실 방지: 단일 드라이브 쉘프로 통신이 두절되는 경우 풀 또는 볼륨 그룹의 볼륨에서 데이터에 액세스할 수 있습니다. 예를 들어, 통신 장애가 발생할 경우 드라이브 쉘프에 대한 전원 공급이 중단되거나 두 I/O 모듈(IOM)이 모두 실패할 수 있습니다.


NOTE: 풀 또는 볼륨 그룹에서 드라이브가 이미 장애가 발생한 경우에는 쉘프 손실 보호가 보장되지 않습니다. 이 경우, 드라이브 쉘프와 풀 또는 볼륨 그룹의 다른 드라이브에 액세스하지 못하면 데이터가 손실됩니다.

쉘프 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

|===
| 레벨 | 쉘프 손실 방지 기준 | 필요한 최소 쉘프 수입니다 


| 수영장 | 풀은 5개 이상의 쉘프의 드라이브를 포함해야 하며 각 쉘프에 동일한 수의 드라이브가 있어야 합니다. 셸프 손실 보호는 고용량 셸프에는 적용되지 않습니다. 시스템에 고용량 셸프가 포함되어 있는 경우 문서함 손실 보호 를 참조하십시오. | 5 


| RAID 6 | 볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다. | 3 


| RAID 3 또는 RAID 5 | 볼륨 그룹의 각 드라이브는 별도의 쉘프에 있습니다. | 3 


| RAID 1 | RAID 1 쌍의 각 드라이브는 별도의 쉘프에 있어야 합니다. | 2 


| RAID 0 | 선반 손실 보호를 달성할 수 없습니다. | 해당 없음 
|===


=== 서랍 손실 방지

드라이브 액세스를 위해 서랍식 용지함은 셸프의 구획 중 하나입니다. 고용량 쉘프에만 서랍이 있습니다. 드로어 손실 보호는 단일 드로어와의 통신이 완전히 손실되는 경우 풀 또는 볼륨 그룹의 볼륨에 있는 데이터에 액세스할 수 있도록 보장합니다. 통신 손실의 예로는 드로어에 대한 전원 손실 또는 드로어 내 내부 구성 요소의 고장이 있습니다.


CAUTION: 풀 또는 볼륨 그룹에서 드라이브에 장애가 이미 발생한 경우에는 드로어 손실 보호가 보장되지 않습니다. 이 경우 드로어(풀 또는 볼륨 그룹의 다른 드라이브)에 액세스하지 못하게 되면 데이터가 손실됩니다.

드로어 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

|===
| 레벨 | 서랍 손실 방지 기준 | 필요한 최소 드로어 수입니다 


| 수영장 | 풀 후보는 모든 드로어의 드라이브를 포함해야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다. 풀에는 5개 이상의 서랍에서 나온 드라이브가 포함되어야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다. 60-드라이브 쉘프는 15, 20, 25, 30, 35, 40, 45, 50, 55 또는 60개 드라이브. 초기 생성 후 풀에 5의 배수로 증분을 추가할 수 있습니다. | 5 


| RAID 6 | 볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다. | 3 


| RAID 3 또는 5 | 볼륨 그룹의 각 드라이브는 별도의 드로어에 있습니다 | 3 


| RAID 1 | 미러링된 쌍의 각 드라이브는 별도의 드로어에 위치해야 합니다. | 2 


| RAID 0 | 문서함 손실 방지를 달성할 수 없습니다. | 해당 없음 
|===