---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-host-creation-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: vCenter용 Storage Plugin을 사용하여 스토리지를 관리하려면 네트워크에서 각 호스트를 검색 또는 정의해야 합니다. 
---
= 호스트 생성 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter용 Storage Plugin을 사용하여 스토리지를 관리하려면 네트워크에서 각 호스트를 검색 또는 정의해야 합니다. 호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



== 자동 및 수동 호스트 생성

호스트를 생성하는 것은 스토리지 어레이가 호스트에 연결된 호스트를 파악하고 볼륨에 대한 I/O 액세스를 허용하는 데 필요한 단계 중 하나입니다. 호스트를 자동 또는 수동으로 생성할 수 있습니다.

* * 자동 * -- SCSI 기반(NVMe-oF 아님) 호스트의 자동 호스트 생성이 HCA(Host Context Agent)에 의해 시작됩니다. HCA는 스토리지 배열에 연결된 각 호스트에 설치할 수 있는 유틸리티입니다. HCA가 설치된 각 호스트는 I/O 경로를 통해 구성 정보를 스토리지 어레이 컨트롤러로 푸시합니다. 호스트 정보에 따라 컨트롤러는 자동으로 호스트와 관련 호스트 포트를 생성하고 호스트 유형을 설정합니다. 필요한 경우 호스트 구성을 추가로 변경할 수 있습니다. HCA가 자동 감지를 수행한 후 호스트는 다음 속성을 사용하여 자동으로 구성됩니다.
+
** 호스트의 시스템 이름에서 파생된 호스트 이름입니다.
** 호스트와 연결된 호스트 식별자 포트입니다.
** 호스트의 호스트 운영 체제 유형입니다.





NOTE: 호스트는 독립 실행형 호스트로 생성되지만 HCA는 호스트 클러스터를 자동으로 생성하거나 추가하지 않습니다.

* * 수동 * -- 수동 호스트 생성 중에 호스트 포트 식별자를 목록에서 선택하거나 수동으로 입력하여 연결합니다. 호스트를 생성한 후 볼륨에 대한 액세스를 공유하려는 경우 호스트에 볼륨을 할당하거나 호스트 클러스터에 추가할 수 있습니다.




== 볼륨이 할당되는 방법입니다

호스트에서 볼륨에 I/O를 보내려면 볼륨을 할당해야 합니다. 볼륨을 생성할 때 호스트 또는 호스트 클러스터를 선택하거나 나중에 호스트 또는 호스트 클러스터에 볼륨을 할당할 수 있습니다. 호스트 클러스터는 호스트 그룹입니다. 호스트 클러스터를 생성하여 동일한 볼륨을 여러 호스트에 쉽게 할당할 수 있습니다.

호스트에 볼륨을 할당할 수 있는 유연성이 있으므로 특정 스토리지 요구 사항을 충족할 수 있습니다.

* * 호스트 클러스터의 일부가 아닌 독립 실행형 호스트 * -- 개별 호스트에 볼륨을 할당할 수 있습니다. 볼륨은 한 호스트에서만 액세스할 수 있습니다.
* * 호스트 클러스터 * -- 호스트 클러스터에 볼륨을 할당할 수 있습니다. 호스트 클러스터의 모든 호스트에서 볼륨에 액세스할 수 있습니다.
* * 호스트 클러스터 내의 호스트 * -- 호스트 클러스터의 일부인 개별 호스트에 볼륨을 할당할 수 있습니다. 호스트가 호스트 클러스터의 일부이더라도 호스트 클러스터의 다른 호스트가 아닌 개별 호스트에서만 볼륨에 액세스할 수 있습니다.


볼륨이 생성되면 LUN(논리 유닛 번호)이 자동으로 할당됩니다. LUN은 I/O 작업 중 호스트와 컨트롤러 사이의 주소 역할을 합니다. 볼륨이 생성된 후 LUN을 변경할 수 있습니다.
