---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-resolve-untrusted-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: '스토리지 배열에서 자체 서명된 인증서를 가져오거나 신뢰할 수 있는 타사에서 발급한 CA(인증 기관) 인증서를 가져와 신뢰할 수 없는 인증서를 해결합니다.' 
---
= vCenter용 SANtricity 스토리지 플러그인에서 신뢰할 수 없는 인증서를 해결합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
인증서 페이지에서는 스토리지 배열에서 자체 서명된 인증서를 가져오거나 신뢰할 수 있는 타사에서 발급한 CA(인증 기관) 인증서를 가져와 신뢰할 수 없는 인증서를 확인할 수 있습니다.

.시작하기 전에
CA 서명 인증서를 가져오려면 다음을 확인합니다.

* 스토리지 배열의 각 컨트롤러에 대한 인증서 서명 요청(.csr 파일)을 생성하여 CA로 보냈습니다.
* CA가 신뢰할 수 있는 인증서 파일을 반환했습니다.
* 인증서 파일은 로컬 시스템에서 사용할 수 있습니다.


.이 작업에 대해
신뢰할 수 없는 인증서는 스토리지 배열이 플러그인에 대한 보안 연결을 설정하려고 시도하지만 연결이 보안으로 확인하지 못할 때 발생합니다. 다음 중 하나라도 해당되는 경우 신뢰할 수 있는 CA 인증서를 추가로 설치해야 할 수 있습니다.

* 최근에 스토리지 배열을 추가했습니다.
* 하나 이상의 인증서가 만료되었거나 해지되었습니다.
* 하나 이상의 인증서에 루트 또는 중간 인증서가 없습니다.


.단계
. 인증서 관리 * 를 선택합니다.
. 신뢰할 수 있는 * 탭을 선택합니다.
+
이 페이지에는 스토리지 배열에 대해 보고된 모든 인증서가 표시됩니다.

. [인증서] 가져오기 메뉴를 선택하여 CA 인증서를 가져오거나 메뉴: 자체 서명된 [스토리지 배열 인증서] 가져오기 를 선택하여 자체 서명된 인증서를 가져옵니다.
. 보기를 제한하려면 * Show certificates that are... * filtering 필드를 사용하거나 열 머리글 중 하나를 클릭하여 인증서 행을 정렬할 수 있습니다.
. 대화 상자에서 인증서를 선택한 다음 * 가져오기 * 를 클릭합니다.
+
인증서가 업로드 및 검증됩니다.


