---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다. 
---
= 리소스 프로비저닝된 볼륨 기능에 대해 알아야 할 내용은 무엇입니까?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.


NOTE: 현재 리소스 프로비저닝 기능을 사용할 수 없습니다. 일부 보기에서는 구성 요소가 리소스 프로비저닝 가능 상태로 보고될 수 있지만 나중에 업데이트할 때 다시 활성화될 때까지 리소스 프로비저닝된 볼륨을 생성하는 기능이 비활성화되었습니다.



== 리소스가 프로비저닝된 볼륨

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다. 이에 비해 기존의 일반 볼륨에서는 Data Assurance 보호 정보 필드를 초기화하고 각 RAID 스트라이프에서 데이터 및 RAID 패리티를 일관되게 만들기 위해 백그라운드 볼륨 초기화 작업 중에 모든 드라이브 블록이 매핑되거나 할당됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Logical Block Error Enable) 오류 복구 기능을 지원합니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 또한 호스트는 NVMe Dataset Management 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.



== 기능 활성화 및 비활성화

드라이브가 DULBE를 지원하는 시스템에서는 리소스 프로비저닝이 기본적으로 사용됩니다. 풀 및 볼륨 그룹에서 기본 설정을 해제할 수 있습니다. 리소스 프로비저닝을 해제하는 작업은 기존 볼륨에 대해 영구적으로 수행되므로 되돌릴 수 없습니다. 즉, 이러한 볼륨 그룹 및 풀에 대해 리소스 프로비저닝을 다시 설정할 수 없습니다.

그러나 새로 생성한 모든 볼륨에 대해 리소스 프로비저닝을 다시 활성화하려면 설정 [시스템] 메뉴에서 다시 활성화할 수 있습니다. 리소스 프로비저닝을 다시 설정하면 새로 생성한 볼륨 그룹 및 풀만 영향을 받습니다. 기존 볼륨 그룹 및 풀은 변경되지 않습니다. 필요한 경우 설정 [시스템] 메뉴에서 자원 프로비저닝을 다시 비활성화할 수도 있습니다.
