---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-activate-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 소프트웨어 파일을 보다 편리하게 활성화할 수 있습니다. 
---
= 스테이징된 OS 소프트웨어를 활성화합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
소프트웨어 파일을 즉시 활성화하거나 더 편리한 시간이 될 때까지 기다릴 수 있습니다. 이 절차에서는 나중에 소프트웨어 파일을 활성화하도록 선택한 것으로 가정합니다.

.이 작업에 대해
펌웨어 파일을 활성화하지 않고 전송할 수 있습니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.

* * 시간 * -- 소프트웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 부하가 더 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 재부팅되고 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
* * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.



NOTE: 활성화 프로세스가 시작된 후에는 중지할 수 없습니다.

.단계
. 기본 보기에서 * 관리 * 를 선택합니다. 필요한 경우 페이지 맨 위에서 * Status * 열을 클릭하여 "OS Upgrade(활성화 대기 중)" 상태의 모든 스토리지 어레이를 정렬합니다.
. 소프트웨어를 활성화할 스토리지 어레이를 하나 이상 선택한 다음 메뉴: 업그레이드 센터 [스테이징된 SANtricity 소프트웨어 활성화] 를 선택합니다.
+
업그레이드 작업 중에 다음 작업이 수행됩니다.

+
** 업그레이드 전 상태 점검이 활성화 프로세스의 일부로 실행됩니다. 업그레이드 전 상태 점검을 통해 모든 스토리지 시스템 구성 요소를 평가하여 활성화를 진행할 수 있는지 확인합니다.
** 스토리지 배열에 대한 상태 검사에 실패하면 활성화가 중지됩니다. 줄임표(…)를 클릭할 수 있습니다. 그리고 * 로그 저장 * 을 선택하여 오류를 검토합니다. 상태 점검 오류를 재정의하도록 선택한 다음 * 계속 * 을 클릭하여 활성화를 계속 진행할 수도 있습니다.
** 업그레이드 전 상태 점검 후 활성화 작업을 취소할 수 있습니다.
+
업그레이드 전 상태 점검이 성공적으로 완료되면 활성화가 발생합니다. 활성화하는 데 걸리는 시간은 스토리지 배열 구성과 활성화 중인 구성 요소에 따라 달라집니다.



. (선택 사항) 활성화가 완료된 후 줄임표(…)를 클릭하여 특정 스토리지 배열에 대해 활성화된 항목 목록을 볼 수 있습니다. 그런 다음 * 로그 저장 * 을 선택합니다.
+
파일은 브라우저의 Downloads 폴더에 "activate_log-<date>"라는 이름으로 저장됩니다. Json'이라고 합니다.


