---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-raid-level-is-best-for-my-application.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 볼륨 그룹의 성능을 최대화하려면 적절한 RAID 레벨을 선택해야 합니다. 
---
= 애플리케이션에 가장 적합한 RAID 레벨은 무엇입니까?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
볼륨 그룹의 성능을 최대화하려면 적절한 RAID 레벨을 선택해야 합니다.

볼륨 그룹에 액세스하는 응용 프로그램의 읽기 및 쓰기 비율을 알면 적절한 RAID 레벨을 결정할 수 있습니다. 성능 페이지를 사용하여 이러한 비율을 얻습니다.



== RAID 레벨 및 애플리케이션 성능

RAID는 수준이라는 일련의 구성을 사용하여 드라이브에서 사용자 및 중복 데이터를 기록하고 검색하는 방법을 결정합니다. 각 RAID 레벨은 서로 다른 성능 기능을 제공합니다. RAID 5 및 RAID 6 구성의 탁월한 읽기 성능 때문에 읽기 비율이 높은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨을 사용하여 잘 수행됩니다.

읽기 백분율(쓰기 집약적)이 낮은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨에서 제대로 작동하지 않습니다. 성능 저하는 컨트롤러가 RAID 5 볼륨 그룹 또는 RAID 6 볼륨 그룹의 드라이브에 데이터 및 중복 데이터를 기록하는 방식으로 인해 발생합니다.

다음 정보를 기반으로 RAID 레벨을 선택합니다.



=== RAID 0

* 설명: *

* 비중복, 스트라이핑 모드
* RAID 0은 볼륨 그룹의 모든 드라이브에 데이터를 스트라이핑합니다.


* 데이터 보호 기능: *

* 고가용성 요구 사항에 대해서는 RAID 0을 권장하지 않습니다. RAID 0은 중요하지 않은 데이터에 적합합니다.
* 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨이 실패하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* RAID 레벨 0에는 최소 하나의 드라이브가 필요합니다.
* RAID 0 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다.
* 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




=== RAID 1 또는 RAID 10

* 설명: *

* 스트라이핑/미러 모드


* 작동 방식: *

* RAID 1은 디스크 미러링을 사용하여 두 개의 중복 디스크에 동시에 데이터를 씁니다.
* RAID 10은 드라이브 스트라이핑을 사용하여 미러링된 드라이브 쌍의 집합에 걸쳐 데이터를 스트라이핑합니다.


* 데이터 보호 기능: *

* RAID 1 및 RAID 10은 고성능과 최상의 데이터 가용성을 제공합니다.
* RAID 1 및 RAID 10은 드라이브 미러링을 사용하여 한 드라이브에서 다른 드라이브로 정확하게 복사합니다.
* 드라이브 쌍의 드라이브 중 하나에 장애가 발생하면 스토리지 어레이가 데이터 또는 서비스의 손실 없이 다른 드라이브로 즉시 전환할 수 있습니다.
* 단일 드라이브 장애로 인해 관련 볼륨의 성능이 저하됩니다. 미러 드라이브를 통해 데이터에 액세스할 수 있습니다.
* 볼륨 그룹의 드라이브 쌍 장애로 인해 연결된 모든 볼륨이 장애가 발생하고 데이터 손실이 발생할 수 있습니다.


* 드라이브 번호 요구 사항: *

* RAID 1에는 사용자 데이터용 드라이브 1개와 미러링된 데이터용 드라이브 1개 등 최소 2개의 드라이브가 필요합니다.
* 드라이브를 4개 이상 선택하면 사용자 데이터를 위한 드라이브 2개와 미러링된 데이터를 위한 드라이브 2개 등 RAID 10이 볼륨 그룹 전체에 자동으로 구성됩니다.
* 볼륨 그룹에 짝수의 드라이브가 있어야 합니다. 드라이브 수가 짝수이고 할당되지 않은 드라이브가 일부 있는 경우 * Pools & Volume Groups * 로 이동하여 볼륨 그룹에 드라이브를 추가하고 작업을 재시도하십시오.
* RAID 1 및 RAID 10 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다. 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




=== RAID 5

* 설명: *

* 높은 I/O 모드.


* 작동 방식: *

* 사용자 데이터 및 중복 정보(패리티)는 드라이브에 스트라이핑됩니다.
* 하나의 드라이브에 해당하는 용량이 중복 정보에 사용됩니다.


* 데이터 보호 기능 *

* RAID 5 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하됩니다. 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
* RAID 5 볼륨 그룹에서 두 개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* 볼륨 그룹에 최소 3개의 드라이브가 있어야 합니다.
* 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.




=== RAID 6

* 설명: *

* 높은 I/O 모드.


* 작동 방식: *

* 사용자 데이터 및 중복 정보(이중 패리티)는 드라이브에 스트라이핑됩니다.
* 두 드라이브의 동일한 용량이 중복 정보에 사용됩니다.


* 데이터 보호 기능: *

* RAID 6 볼륨 그룹에서 하나 또는 두 개의 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하되지만 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
* RAID 6 볼륨 그룹에서 3개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* 드라이브 번호 요구 사항: *

* 볼륨 그룹에 최소 5개의 드라이브가 있어야 합니다.
* 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.



NOTE: 풀의 RAID 레벨은 변경할 수 없습니다. 사용자 인터페이스는 풀을 RAID 6으로 자동 구성합니다.



== RAID 레벨 및 데이터 보호

RAID 1, RAID 5 및 RAID 6은 드라이브 미디어에 중복 데이터를 기록하여 내결함성을 제공합니다. 중복 데이터는 데이터 사본(미러링)이거나 데이터에서 파생된 오류 정정 코드일 수 있습니다. 드라이브 장애가 발생할 경우 중복 데이터를 사용하여 교체 드라이브에 대한 정보를 빠르게 재구성할 수 있습니다.

단일 볼륨 그룹에서 단일 RAID 레벨을 구성합니다. 해당 볼륨 그룹의 모든 중복 데이터는 볼륨 그룹 내에 저장됩니다. 볼륨 그룹의 용량은 구성원 드라이브의 총 용량에서 중복 데이터를 위해 예약된 용량을 뺀 값입니다. 중복성에 필요한 용량은 사용된 RAID 레벨에 따라 다릅니다.
