---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-management-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 추가/검색 기능을 사용하여 조직의 네트워크에서 관리할 스토리지 어레이를 찾아서 추가합니다. 
---
= 스토리지 관리 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Add/Discover 기능을 사용하여 vCenter용 Storage 플러그인에서 관리할 스토리지 시스템을 찾아 추가합니다. 관리 페이지에서 검색된 이러한 스토리지에 대한 새 암호를 이름 변경, 제거 및 제공할 수도 있습니다.



== 스토리지 검색 시 고려 사항

플러그인이 스토리지 리소스를 표시하고 관리하려면 조직의 네트워크에서 관리할 스토리지 어레이를 검색해야 합니다. 단일 어레이 또는 여러 어레이를 검색하고 추가할 수 있습니다.



=== 제공합니다

여러 어레이를 검색하도록 선택한 경우 네트워크 IP 주소 범위를 입력한 다음 시스템이 해당 범위의 각 IP 주소에 대한 개별 연결을 시도합니다. 성공적으로 도달한 스토리지 배열이 플러그인에 표시되면 이를 관리 도메인에 추가할 수 있습니다.



=== 단일 스토리지 어레이

단일 어레이를 검색하도록 선택한 경우 스토리지 어레이에 있는 컨트롤러 중 하나의 IP 주소를 입력한 다음 해당 어레이를 관리 도메인에 추가합니다.


NOTE: 플러그인은 컨트롤러에 할당된 범위 내에서 단일 IP 주소 또는 IP 주소만 검색하여 표시합니다. 이 단일 IP 주소 또는 IP 주소 범위를 벗어나는 컨트롤러에 할당된 대체 컨트롤러 또는 IP 주소가 있는 경우 플러그인이 컨트롤러를 검색 또는 표시하지 않습니다. 그러나 스토리지 배열을 추가하면 연결된 모든 IP 주소가 검색되어 관리 보기에 표시됩니다.



=== 사용자 자격 증명

추가할 각 스토리지 배열에 대해 관리자 암호를 제공해야 합니다.



=== 인증서

검색 프로세스의 일부로 검색된 스토리지 시스템이 신뢰할 수 있는 소스의 인증서를 사용하고 있는지 확인합니다. 시스템은 브라우저를 사용하여 에서 설정하는 모든 연결에 대해 두 가지 유형의 인증서 기반 인증을 사용합니다.

* * 신뢰할 수 있는 인증서 * -- 하나 이상의 컨트롤러 인증서가 만료되었거나 해지되었거나 체인에 인증서가 없는 경우 인증 기관에서 제공하는 신뢰할 수 있는 인증서를 추가로 설치해야 할 수 있습니다.
* * 자체 서명된 인증서 * -- 어레이도 자체 서명된 인증서를 사용할 수 있습니다. 서명된 인증서를 가져오지 않고 어레이를 검색할 경우 플러그인은 자체 서명된 인증서를 수락할 수 있는 추가 단계를 제공합니다. 스토리지 배열의 자체 서명된 인증서가 신뢰할 수 있는 것으로 표시되고 스토리지 배열이 플러그인에 추가됩니다. 스토리지 배열에 대한 연결을 신뢰하지 않는 경우, 스토리지 배열을 플러그인에 추가하기 전에 * Cancel * 을 선택하고 스토리지 배열의 보안 인증서 전략을 확인합니다.




== 스토리지 배열 상태입니다

vCenter용 Storage Plugin을 열면 각 스토리지 배열과의 통신이 설정되고 각 스토리지 배열의 상태가 표시됩니다.

Manage-All * 페이지에서 스토리지 배열의 상태 및 스토리지 배열 연결 상태를 볼 수 있습니다.

|===
| 상태 | 를 나타냅니다 


| 최적 | 스토리지 배열이 Optimal(최적) 상태에 있습니다. 인증서 문제가 없으며 암호가 유효합니다. 


| 암호가 잘못되었습니다 | 잘못된 스토리지 배열 암호가 제공되었습니다. 


| 신뢰할 수 없는 인증서입니다 | HTTPS 인증서가 자체 서명되어 있고 가져오지 않았거나 인증서가 CA 서명되었으며 루트 및 중간 CA 인증서를 가져오지 않았기 때문에 스토리지 배열과의 연결을 하나 이상 신뢰할 수 없습니다. 


| 주의가 필요합니다 | 스토리지 어레이에 문제가 있어 수정하려면 스토리지 시스템의 개입이 필요합니다. 


| 잠금 | 스토리지 배열이 잠김 상태에 있습니다. 


| 알 수 없음 | 스토리지 배열에 연결된 적이 없습니다. 이 문제는 플러그인이 시작되고 아직 스토리지 어레이와 연결되지 않았거나 스토리지 어레이가 오프라인 상태이며 플러그인을 시작한 이후 연락이 되지 않은 경우에 발생할 수 있습니다. 


| 오프라인 | 이전에 플러그인이 스토리지 어레이에 연결했지만 지금은 모든 연결이 끊어졌습니다. 
|===


== 플러그인 인터페이스와 System Manager의 비교

스토리지 배열의 기본 운영 작업에 vCenter용 저장소 플러그인 을 사용할 수 있습니다. 그러나 플러그인에서 사용할 수 없는 작업을 수행하기 위해 System Manager를 시작해야 하는 경우가 있습니다.

System Manager는 이더넷 관리 포트를 통해 네트워크에 연결되는 스토리지 어레이 컨트롤러에 내장된 애플리케이션입니다. System Manager에는 모든 어레이 기반 기능이 포함되어 있습니다.

다음 표를 참조하여 특정 스토리지 어레이 작업에 플러그인 인터페이스나 System Manager 인터페이스를 사용할 수 있는지 여부를 결정할 수 있습니다.

|===
| 기능 | 플러그인 인터페이스 | System Manager 인터페이스 


| 여러 스토리지 시스템의 그룹에 대한 배치 작업 | 예 | 아니요 작업은 단일 어레이에서 수행됩니다. 


| SANtricity OS 펌웨어의 업그레이드 | 예. 일괄 작업에서 하나 이상의 어레이 | 예. 단일 스토리지 전용. 


| 한 어레이에서 여러 어레이로 설정을 가져옵니다 | 예 | 아니요 


| 호스트 및 호스트 클러스터 관리(볼륨 생성, 할당, 업데이트 및 삭제) | 예 | 예 


| 풀 및 볼륨 그룹 관리(생성, 업데이트, 보안 활성화 및 삭제) | 예 | 예 


| 볼륨 관리(생성, 크기 조정, 업데이트 및 삭제) | 예 | 예 


| SSD Cache 관리(생성, 업데이트 및 삭제) | 예 | 예 


| 미러링 및 스냅샷 관리 | 아니요 | 예 


| 하드웨어 관리(컨트롤러 상태 보기, 포트 연결 구성, 컨트롤러 오프라인, 핫 스페어 활성화, 드라이브 지우기, 등) | 아니요 | 예 


| 알림(e-메일, SNMP, syslog) 관리 | 아니요 | 예 


| 보안 키 관리 | 아니요 | 예 


| 컨트롤러의 인증서 관리 | 아니요 | 예 


| 컨트롤러의 액세스 관리(LDAP, SAML 등) | 아니요 | 예 


| AutoSupport 관리 | 아니요 | 예 
|===