---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-directory-services-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 한 스토리지 어레이에서 다른 스토리지 어레이로 디렉토리 서비스 구성을 가져옵니다. 
---
= vCenter용 SANtricity 스토리지 플러그인에서 디렉토리 서비스 설정을 가져옵니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
한 스토리지 어레이에서 다른 스토리지 어레이로 디렉토리 서비스 구성을 가져올 수 있습니다. 이 배치 작업은 네트워크에서 여러 어레이를 구성해야 하는 시간을 절약합니다.

.시작하기 전에
다음을 확인합니다.

* 디렉토리 서비스는 소스로 사용할 스토리지 어레이에 대한 System Manager(메뉴: 설정 [액세스 관리])에서 구성됩니다.
* 대상 스토리지 배열에 대한 기존 구성은 System Manager(시스템 설정) [System(시스템) > Save Storage Array Configuration(스토리지 배열 구성 저장)] 메뉴에서 백업됩니다.
* 에서 스토리지 구성을 복제하는 데 필요한 요구 사항을 검토했습니다 link:vc-olh-import-settings-overview.html["설정 가져오기 개요"].


.이 작업에 대해
가져온 설정에는 LDAP(Lightweight Directory Access Protocol) 서버의 도메인 이름과 URL, LDAP 서버의 사용자 그룹에 대한 매핑과 스토리지 배열의 사전 정의된 역할에 대한 URL이 포함됩니다.

.단계
. 관리 페이지에서 작업 [설정 가져오기]를 클릭합니다.
+
설정 가져오기 마법사가 열립니다.

. 설정 선택 대화 상자에서 * 디렉터리 서비스 * 를 선택한 후 * 다음 * 을 클릭합니다.
+
소스 스토리지를 선택할 수 있는 대화 상자가 열립니다.

. 소스 선택 대화 상자에서 가져올 설정이 있는 배열을 선택하고 * 다음 * 을 클릭합니다.
. 대상 선택 대화 상자에서 새 설정을 받을 하나 이상의 배열을 선택합니다.
+

NOTE: 8.50 미만의 펌웨어를 사용하는 스토리지 어레이는 선택할 수 없습니다. 또한 플러그인이 해당 어레이와 통신할 수 없는 경우(예: 오프라인이거나 인증서, 암호 또는 네트워킹 문제가 있는 경우) 이 대화 상자에 어레이가 표시되지 않습니다.

. 마침 * 을 클릭합니다.
+
작업 페이지에는 가져오기 작업의 결과가 표시됩니다. 작업이 실패하면 해당 행을 클릭하여 자세한 정보를 볼 수 있습니다.



.결과
이제 타겟 스토리지 시스템이 소스 스토리지와 동일한 디렉토리 서비스로 구성됩니다.
