---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-redistribute-volumes.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 볼륨을 재배포하여 볼륨을 기본 컨트롤러 소유자에게 다시 옮깁니다 
---
= vCenter용 SANtricity 스토리지 플러그인에서 볼륨을 재배포합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
볼륨을 재배포하여 볼륨을 기본 컨트롤러 소유자에게 다시 옮깁니다. 일반적으로 다중 경로 드라이버는 호스트 및 스토리지 어레이 사이의 데이터 경로에 문제가 발생할 경우 원하는 컨트롤러 소유자로부터 볼륨을 이동합니다.

.시작하기 전에
* 재배포하려는 볼륨이 사용 중이 아니거나 입출력 오류가 발생합니다.
* 재배포하려는 볼륨을 사용하는 모든 호스트에 다중 경로 드라이버가 설치되어 있거나 I/O 오류가 발생합니다. 호스트에 다중 경로 드라이버 없이 볼륨을 재배포하려는 경우, 애플리케이션 오류를 방지하기 위해 재배포가 진행되는 동안 볼륨에 대한 모든 I/O 작업을 중지해야 합니다.


.이 작업에 대해
대부분의 호스트 다중 경로 드라이버는 기본 컨트롤러 소유자에 대한 경로의 각 볼륨에 액세스를 시도합니다. 그러나 이 기본 경로를 사용할 수 없게 되면 호스트의 다중 경로 드라이버가 대체 경로로 페일오버됩니다. 이 페일오버로 볼륨 소유권이 대체 컨트롤러로 변경될 수 있습니다. 페일오버를 발생시키는 조건을 해결한 후 일부 호스트는 자동으로 볼륨 소유권을 기본 컨트롤러 소유자로 다시 이동하지만 경우에 따라 볼륨을 수동으로 재분산해야 할 수 있습니다.

.단계
. 관리 페이지에서 재배포할 볼륨이 포함된 스토리지 어레이를 선택합니다.
. 메뉴: Provisioning [Manage Volumes](볼륨 관리)를 선택합니다.
. 메뉴 선택: More [Redistribute volumes](추가 [볼륨 재배포])
+
Redistribute Volumes 대화상자가 나타납니다. 기본 컨트롤러 소유자가 현재 소유자와 일치하지 않는 스토리지 배열의 모든 볼륨이 이 대화 상자에 나타납니다.

. 재배포할 볼륨을 하나 이상 선택하고 작업을 수행할지 확인합니다.


.결과
선택한 볼륨이 기본 컨트롤러 소유자로 이동하거나 Redistribute Volumes Unnessary(볼륨 재분산 불필요) 대화 상자가 나타날 수 있습니다.
