---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-host-or-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 호스트 또는 호스트 클러스터를 제거하여 볼륨이 더 이상 해당 호스트에 연결되지 않도록 할 수 있습니다. 
---
= 호스트 또는 호스트 클러스터를 삭제합니다
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
호스트 또는 호스트 클러스터를 제거하여 볼륨이 더 이상 해당 호스트에 연결되지 않도록 할 수 있습니다.

호스트 또는 호스트 클러스터를 삭제할 때는 다음 지침을 염두에 두십시오.

* 특정 볼륨 할당이 삭제되고 연결된 볼륨을 새 할당에 사용할 수 있습니다.
* 호스트가 고유한 특정 할당이 있는 호스트 클러스터의 일부인 경우 호스트 클러스터에는 영향이 없습니다. 그러나 호스트가 다른 할당이 없는 호스트 클러스터의 일부인 경우 호스트 클러스터와 기타 연결된 호스트 또는 호스트 포트 식별자는 기본 할당을 상속합니다.
* 호스트와 연결된 모든 호스트 포트 식별자는 정의되지 않습니다.


.단계
. 관리 페이지에서 호스트 연결이 있는 스토리지 배열을 선택합니다.
. 메뉴: Provisioning [Configure Hosts](호스트 구성)를 선택합니다.
+
호스트 구성 페이지가 열립니다.

. 삭제할 호스트 또는 호스트 클러스터를 선택하고 * Delete * 를 클릭합니다.
+
확인 대화 상자가 나타납니다.

. 작업을 수행할지 확인한 다음 * 삭제 * 를 클릭합니다.


호스트를 삭제한 경우 시스템은 다음 작업을 수행합니다.

* 호스트를 삭제하고 해당하는 경우 호스트 클러스터에서 제거합니다.
* 할당된 볼륨에 대한 액세스를 제거합니다.
* 연결된 볼륨을 할당되지 않은 상태로 반환합니다.
* 호스트와 연결된 모든 호스트 포트 식별자를 연결되지 않은 상태로 반환합니다. 호스트 클러스터를 삭제한 경우 시스템은 다음 작업을 수행합니다.
+
** 호스트 클러스터와 관련 호스트(있는 경우)를 삭제합니다.
** 할당된 볼륨에 대한 액세스를 제거합니다.
** 연결된 볼륨을 할당되지 않은 상태로 반환합니다.
** 호스트와 연결된 모든 호스트 포트 식별자를 연결되지 않은 상태로 반환합니다.



