---
permalink: maintenance-e5700/batteries-intro-concept.html 
sidebar: sidebar 
keywords: E5700 battery, repair E5700 battery, replace E5700 battery, failed E5700 battery 
summary: E5700 배터리 교체 요구사항 및 고려사항 검토 
---
= E5700 배터리 교체 요구사항
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E5700 배터리를 교체하기 전에 요구사항 및 고려 사항을 검토하십시오.

각 컨트롤러 캐니스터에는 AC 전원에 장애가 발생할 경우 캐싱된 데이터를 보관하는 배터리가 포함되어 있습니다.



== Recovery Guru에서 알려줍니다

SANtricity 시스템 관리자의 Recovery Guru에서 다음 상태 중 하나를 보고하는 경우 영향을 받는 배터리를 교체해야 합니다.

* 배터리 고장
* 배터리 교체가 필요합니다


SANtricity 시스템 관리자에서 Recovery Guru의 세부 정보를 검토하여 배터리에 문제가 있는지 확인하고 다른 항목을 먼저 해결하지 않도록 합니다.



== 절차 개요

데이터를 보호하려면 장애가 발생한 배터리를 가능한 한 빨리 교체해야 합니다.

다음은 E5700 컨트롤러(E5724, EF570 또는 E5760의 배터리 교체 단계에 대한 개요입니다.

. 컨트롤러를 오프라인으로 전환합니다(양면 인쇄만 해당).
. 컨트롤러 캐니스터를 제거합니다.
. 배터리를 교체합니다.
. 컨트롤러 캐니스터를 교체합니다.
. 컨트롤러를 온라인 상태로 전환합니다(양면 인쇄만 해당).




== 요구 사항

고장난 배터리를 교체할 계획이라면 다음이 필요합니다.

* 교체용 배터리
* ESD 밴드이거나 다른 정전기 방지 예방 조치를 취했습니다.
* 컨트롤러 캐니스터에 연결된 각 케이블을 식별하는 레이블입니다.
* 컨트롤러의 SANtricity 시스템 관리자에 액세스할 수 있는 브라우저가 있는 관리 스테이션. System Manager 인터페이스를 열려면 브라우저에서 컨트롤러의 도메인 이름 또는 IP 주소를 가리킵니다.
+
선택적으로 CLI(Command Line Interface)를 사용하여 일부 절차를 수행할 수 있습니다. CLI에 액세스할 수 없는 경우 다음 중 하나를 수행할 수 있습니다.

+
** * SANtricity 시스템 관리자용(버전 11.60 이상) * -- System Manager에서 CLI 패키지(zip 파일)를 다운로드합니다. 설정 [시스템 > 추가 기능 > 명령줄 인터페이스] 메뉴로 이동합니다. 그러면 DOS C: 프롬프트와 같은 운영 체제 프롬프트에서 CLI 명령을 실행할 수 있습니다.
** * SANtricity 스토리지 관리자/EMW(엔터프라이즈 관리 창) * -- 빠른 안내서의 지침에 따라 소프트웨어를 다운로드하고 설치합니다. EMW에서 도구 [스크립트 실행] 메뉴를 선택하여 CLI 명령을 실행할 수 있습니다.



