---
permalink: maintenance-ef50-ef80/controller-replace-complete-replacement.html 
sidebar: sidebar 
keywords: ef50, ef80, how to complete the controller replacement process 
summary: EF50 또는 EF80 스토리지 시스템의 컨트롤러 교체를 완료하려면 스토리지 시스템 펌웨어가 최신 상태인지 확인하고, 볼륨이 소유자에게 반환되었는지 확인하고, 시스템 지원 데이터를 수집한 다음, 고장난 부품을 NetApp에 반환하십시오. 
---
= 컨트롤러 교체 완료 - EF50 및 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF50 또는 EF80 스토리지 시스템의 컨트롤러 교체를 완료하려면 최신 버전의 SANtricity OS가 설치되어 있는지 확인하고, 볼륨이 소유 컨트롤러로 반환되었는지 확인하고, 시스템 지원 데이터를 수집한 다음, 고장난 부품을 NetApp에 반환하십시오.



== 1단계: SANtricity OS의 최신 버전을 확인하고, 볼륨 소유권을 검증하고, 지원 데이터를 수집합니다

SANtricity System Manager를 사용하여 최신 버전의 SANtricity OS가 설치되어 있는지 확인하고, 모든 볼륨이 소유 컨트롤러로 반환되었는지 확인하고, 작업을 재개할 수 있도록 지원 데이터를 수집하십시오.

.단계
. 스토리지 시스템에 최신 버전의 SANtricity OS가 설치되어 있는지 확인하십시오.
+
.. *Support* > *Upgrade Center*를 선택합니다
.. 필요한 경우 최신 버전을 설치합니다.


. 모든 볼륨이 소유 컨트롤러로 반환되었는지 확인합니다.
+
[cols="1,2"]
|===
| 만약... | 그런 다음... 


 a| 
Recovery Guru가 있으며 볼륨이 기본 경로에 있지 않음(소유 컨트롤러로 반환되지 않음)을 나타냅니다
 a| 
.. * Storage * > * Volumes * > * More * 를 선택하고 드롭다운 메뉴에서 * Redistribute volumes * 를 선택하여 소유 컨트롤러에 볼륨을 재분배합니다.
.. Recovery Guru가 있는지 확인하고 볼륨이 기본 경로에 없다고 여전히 표시되는지 확인하여 모든 볼륨이 소유 컨트롤러로 재배포되었는지 확인하십시오.



NOTE: 볼륨이 여전히 소유 컨트롤러로 반환되지 않으면 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]에 문의하십시오.



 a| 
Recovery Guru가 없습니다(모든 볼륨이 소유 컨트롤러로 반환된 것으로 보입니다)
 a| 
모든 볼륨이 소유 컨트롤러로 반환되었는지 확인하려면 * Storage * > * Volumes * > * More * 를 선택하고 드롭다운 메뉴에서 * Change volume ownership * 을 선택하여 볼륨 소유자를 확인하십시오.

|===
. 스토리지 시스템에 대한 지원 데이터 수집:
+
.. 지원 * > * 지원 센터 * > * 진단 * 을 선택합니다.
.. 지원 데이터 수집 * 을 선택합니다.
.. *Collect*를 선택합니다.
+
파일은 브라우저의 다운로드 폴더에 * support-data.7z * 라는 이름으로 저장됩니다.







== 2단계: 고장난 부품을 NetApp에 반환합니다

키트에 동봉된 RMA 지침에 따라 고장난 부품을 NetApp으로 반송하십시오. 자세한 내용은  https://mysupport.netapp.com/site/info/rma["부품 반품 및 교체"] 페이지를 참조하십시오.

.다음 단계
컨트롤러 교체가 완료되었습니다. 일반 작업을 다시 시작할 수 있습니다.
