= 
:allow-uri-read: 


.단계
. 다음 단계는 장애가 발생한 컨트롤러가 IP 주소에 DHCP를 사용했는지 여부에 따라 달라집니다.
+
[cols="1,2"]
|===
| 만약... | 그런 다음... 


 a| 
손상된 컨트롤러는 IP 주소에 DHCP를 사용하지 않았습니다
 a| 
교체 컨트롤러는 제거한 손상된 컨트롤러의 IP 주소를 사용합니다.

다음 단계로 이동합니다.



 a| 
손상된 컨트롤러가 IP 주소에 DHCP를 사용했습니다
 a| 
네트워크 관리자에게 손상된 컨트롤러의 DNS/네트워크 및 IP 주소를 교체 컨트롤러의 MAC 주소와 연결하도록 요청하십시오.

|===
. SANtricity System Manager를 사용하여 컨트롤러를 온라인 상태로 전환하십시오.
+
.. 컨트롤러를 표시하려면 *Hardware* > *Controllers and components*를 선택하십시오.
.. 교체한 컨트롤러를 선택하여 해당 콘텐츠 메뉴를 표시합니다.
.. *온라인으로 주문하기*를 선택합니다.


. 컨트롤러가 부팅되는 동안 컨트롤러 LED를 확인하여 다른 컨트롤러와의 통신이 다시 설정되었는지 확인하십시오.
+
** 황색 주의 LED가 계속 켜져 있습니다.
** 호스트 인터페이스에 따라 호스트 링크 LED가 켜지거나 깜박이거나 꺼질 수 있습니다.


. 컨트롤러가 다시 온라인 상태가 되면 Recovery Guru에서 NVSRAM 불일치가 보고되는지 확인합니다.
+
NVSRAM 불일치가 보고되면 다음 SMcli 명령을 사용하여 NVSRAM을 업그레이드하십시오.  `-k` 매개 변수는 어레이가 https 보안이 아닌 경우 필요합니다.

+
[listing]
----
SMcli <controller A IP> <controller B IP> -u admin -p <password> -k -c "download storageArray NVSRAM file=\"C:\Users\testuser\Downloads\NVSRAM .dlp file>\" forceDownload=TRUE;"
----
+

NOTE: SMcli 명령을 완료할 수 없는 경우  https://www.netapp.com/company/contact-us/support/["NetApp 지원"^]에 문의하거나  https://mysupport.netapp.com["NetApp Support 사이트"^]에 로그인하여 케이스를 생성하십시오.

. 스토리지 시스템의 상태가 최적인지, 그리고 컨트롤러의 주의 LED가 꺼져 있는지 확인하십시오.
+
상태가 최적이 아니거나 주의 LED가 켜져 있는 경우 모든 케이블이 올바르게 연결되었는지, 컨트롤러가 제대로 설치되었는지 확인하십시오. 필요한 경우 컨트롤러를 제거한 후 다시 설치하십시오.

+

NOTE: 문제를 해결할 수 없는 경우 https://www.netapp.com/company/contact-us/support/["NetApp 지원"^]에 문의하십시오.


