---
permalink: maintenance-ef600/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: EF300, EF600, EF300C, EF600C, replace HIC, replace HIC, host interface card failed, HIC failure 
summary: EF300 또는 EF600 HIC를 교체하기 전에 요구사항 및 고려사항을 검토하십시오. 
---
= EF300 또는 EF600 HIC 업그레이드 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300, EF600, EF300C 또는 EF600C 어레이에서 호스트 인터페이스 카드(HIC)를 업그레이드하거나 교체하기 전에 다음 요구사항을 검토하십시오.

* 이 절차에 대한 가동 중지 시간 유지 관리 기간을 예약했습니다. 이 절차를 성공적으로 완료할 때까지 스토리지 배열의 데이터에 액세스할 수 없습니다. 두 컨트롤러의 전원이 켜져 있을 때 동일한 HIC 구성을 가져야 하므로 HIC 구성을 변경할 때는 전원이 꺼져 있어야 합니다. 일치하지 않는 HIC가 있으면 온라인 상태로 전환할 때 교체 HIC가 있는 컨트롤러가 잠깁니다.
* 새 호스트 포트를 연결하는 데 필요한 모든 케이블, 트랜시버, 스위치 및 HBA(호스트 버스 어댑터)가 있습니다.
+
호환 하드웨어에 대한 자세한 내용은 를 참조하십시오 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성 매트릭스"^] 또는 을 누릅니다 http://hwu.netapp.com/home.aspx["NetApp Hardware Universe를 참조하십시오"^].

* ESD 밴드를 가지고 있거나 다른 정전기 방지 예방 조치를 취했습니다.
* 1 십자 드라이버가 있습니다.
* 컨트롤러 캐니스터에 연결된 각 케이블을 식별하는 라벨이 있습니다.
* 컨트롤러의 SANtricity 시스템 관리자에 액세스할 수 있는 브라우저가 있는 관리 스테이션. System Manager 인터페이스를 열려면 브라우저에서 컨트롤러의 도메인 이름 또는 IP 주소를 가리킵니다.
* HIC를 일부 교체 또는 업그레이드하려면 호스트 포트 프로토콜 변환이 필요할 수 있습니다. 의 지침을 따릅니다 xref:hpp-change-supertask-task.html[EF300 또는 EF600의 호스트 프로토콜 변경] 참조하십시오.
* EF300 컨트롤러는 호스트 연결을 위해 HIC 포트 2를 HIC로 채워야 합니다.

