---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Windows Express용 Windows Unified Host Utilities를 설치합니다. 
---
= E-Series-Windows에서 Linux 유니파이드 호스트 유틸리티를 설치 및 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows Unified Host Utilities 툴을 사용하면 호스트 컴퓨터를 NetApp 스토리지 시스템에 연결하고 호스트 컴퓨터에서 필요한 매개 변수를 설정할 수 있습니다. 또한 NetApp 스토리지를 사용하면 최상의 읽기/쓰기 성능을 위해 적절한 디스크 시간 초과를 설정할 수 있습니다.


NOTE: 자세한 내용은 에서 _Windows 호스트 유틸리티 설치 안내서, _를 참조하십시오 http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["NetApp 설명서: 호스트 유틸리티"^].

.단계
. 를 사용합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 설치할 Unified Host Utilities의 적절한 버전을 확인합니다.
+
지원되는 각 구성 내의 열에 버전이 나열됩니다.

. 에서 Unified Host Utilities를 다운로드합니다 http://mysupport.netapp.com["NetApp 지원"^].
+

NOTE: SANtricity 저장소 관리자 설치 프로그램을 사용하여 이 유틸리티 패키지를 설치할 수 없습니다.

+

NOTE: 또는 SMcli 명령을 사용할 수 있습니다 `-identifyDevices` Unified Host Utility 툴과 동일한 기능을 수행합니다. SMcli는 SANtricity OS에 포함되어 있으며 SANtricity System Manager를 통해 다운로드할 수 있습니다. SANtricity System Manager를 통해 SMcli를 다운로드하는 방법에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["SANtricity System Manager 온라인 도움말에서 CLI(Command Line Interface) 항목을 다운로드하십시오"^].


