---
permalink: config-windows/verify-windows-config-support-task.html 
sidebar: sidebar 
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Windows 구성이 지원되는지 확인합니다. 
---
= Windows 구성이 지원되는지 확인합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
안정적인 운영을 보장하기 위해 구축 계획을 생성한 다음 NetApp 상호 운용성 매트릭스 툴(IMT) 을 사용하여 전체 구성이 지원되는지 확인하십시오.

.단계
. 로 이동합니다 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].
. 스토리지 솔루션 검색 * 타일을 클릭합니다.
. 메뉴: 프로토콜 [SAN 호스트] 영역에서 * E-Series SAN 호스트 * 옆에 있는 * 추가 * 버튼을 클릭합니다.
. 검색 조건 구체화 보기 * 를 클릭합니다.
+
검색 조건 구체화 섹션이 표시됩니다. 이 섹션에서는 적용되는 프로토콜과 운영 체제, NetApp OS 및 호스트 다중 경로 드라이버와 같은 구성의 다른 기준을 선택할 수 있습니다. 구성에 대해 알고 있는 기준을 선택한 다음 어떤 호환 구성 요소가 적용되는지 확인합니다. 필요한 경우 도구에 규정된 운영 체제 및 프로토콜을 업데이트합니다. 선택한 구성에 대한 자세한 내용은 오른쪽 페이지 화살표를 클릭하여 지원되는 구성 보기 페이지에서 액세스할 수 있습니다.

. 필요한 경우 표에 나열된 대로 운영 체제 및 프로토콜을 업데이트합니다.
+
|===
| 운영 체제 업데이트 | 프로토콜 | 프로토콜 관련 업데이트 


 a| 
적절한 기능과 지원 가능성을 보장하기 위해 즉시 사용 가능한 드라이버를 설치해야 할 수 있습니다.

각 HBA 공급업체에는 부팅 코드 및 펌웨어를 업데이트하는 특정 방법이 있습니다. HBA 부트 코드 및 펌웨어를 업데이트하는 데 필요한 지침과 소프트웨어를 얻으려면 공급업체 웹 사이트의 지원 섹션을 참조하십시오.
 a| 
FC
 a| 
호스트 버스 어댑터(HBA) 드라이버, 펌웨어 및 부트 코드



 a| 
iSCSI
 a| 
네트워크 인터페이스 카드(NIC) 드라이버, 펌웨어 및 부트 코드.



 a| 
SAS를 참조하십시오
 a| 
호스트 버스 어댑터(HBA) 드라이버, 펌웨어 및 부트 코드

|===

