---
permalink: upgrade-controllers/complete-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, vendor ID, upgrade status, upgrade validate 
summary: 컨트롤러 쉘프의 전원을 켜고 컨트롤러 소프트웨어 버전을 검증하여 컨트롤러 업그레이드를 완료합니다. 그런 다음 지원 데이터를 수집하고 작업을 재개할 수 있습니다. 
---
= 컨트롤러 업그레이드를 완료합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 쉘프의 전원을 켜고 컨트롤러 소프트웨어 버전을 검증하여 컨트롤러 업그레이드를 완료합니다. 그런 다음 지원 데이터를 수집하고 작업을 재개할 수 있습니다.

이중 컨트롤러 드라이브 트레이에서 컨트롤러를 업그레이드하는 경우 모든 단계를 반복하여 두 번째 컨트롤러에 대한 업그레이드를 완료합니다.



== 1단계: 컨트롤러 전원을 켭니다

컨트롤러 쉘프가 올바로 작동하는지 확인하려면 컨트롤러 쉘프의 전원을 켜십시오.

.단계
. 컨트롤러 드라이브 트레이에 연결된 각 드라이브 트레이 뒤쪽에 있는 전원 스위치를 켭니다
. 드라이브가 회전할 때까지 2분 정도 기다립니다.
. 컨트롤러 드라이브 트레이 후면에 있는 전원 스위치를 켭니다
. 전원 켜기 프로세스가 완료될 때까지 3분 정도 기다립니다.
. E2800 또는 E5700 컨트롤러에 대한 전체 컨트롤러 교체를 수행하는 경우 드라이브 보안 시나리오에 따라 다음 절차 중 하나를 진행하십시오.
+
|===
| 전체 컨트롤러 교체 유형 | 절차 및 사전 요구 사항 


 a| 
모든 비보안 드라이브, 외부 또는 내부 키 관리
 a| 
다음 단계를 진행합니다.



 a| 
보안 및 비보안 드라이브 혼합, 내부 키 관리
 a| 
먼저 내부 보안 키를 생성한 다음 보안 키를 수동으로 가져와 보안 드라이브의 잠금을 해제해야 합니다. 드라이브의 잠금이 해제되면 드라이브에 액세스할 수 있습니다.

.. 내부 보안 키를 생성합니다
.. 내부 키 관리 및 하나 이상의 드라이브가 고정된 컨트롤러 교체




 a| 
모든 보안 드라이브, 내부 키 관리
 a| 
내부 키 관리 및 하나 이상의 드라이브가 고정된 컨트롤러 교체



 a| 
보안 및 비보안 드라이브 혼합, 외부 키 관리
 a| 
다음 단계를 진행합니다.

컨트롤러 교체를 수행하면 컨트롤러가 자동으로 외부 키 관리 서버와 재동기화되고 드라이브가 잠금 해제되고 액세스할 수 있게 됩니다.


NOTE: 내부 키 관리 기능이 있는 혼합 보안 드라이브의 컨트롤러 교체를 수행한 후 7세그먼트 디스플레이 잠금 코드 'L5'를 받는 경우 기술 지원 부서에 문의하십시오.



 a| 
모든 보안 드라이브, 외부 키 관리, 컨트롤러 교체 절차를 위해 일시적으로 내부 키 관리로 전환했습니다
 a| 
먼저 내부 키 관리 절차를 사용하여 보안 드라이브의 잠금을 해제해야 합니다. 드라이브의 잠금을 해제한 후 스토리지 배열에 대한 새 외부 보안 키를 생성하여 외부 키 관리로 다시 전환합니다.

.. 내부 키 관리 및 하나 이상의 드라이브가 고정된 컨트롤러 교체
.. 외부 보안 키를 만듭니다




 a| 
모든 보안 드라이브, 외부 키 관리, 컨트롤러 교체 절차를 위해 일시적으로 내부 키 관리로 전환하지는 않았습니다
 a| 
외부 키 관리 및 모든 드라이브가 보호되는 컨트롤러로 바꿉니다

|===




== 2단계: 컨트롤러 및 트레이 상태를 확인합니다

LED 및 스토리지 관리 소프트웨어를 사용하여 컨트롤러 및 트레이 상태를 확인할 수 있습니다.

.단계
. 컨트롤러 A의 LED를 확인하여 올바르게 부팅되는지 확인합니다.
+
재부팅 중 호스트 링크 서비스 작업 필요 LED가 녹색으로 바뀝니다. 7세그먼트 디스플레이에는 OS+SD+블랭크 시퀀스가 표시되어 컨트롤러가 일일 시작(SOD) 처리를 수행하고 있음을 나타냅니다.

+
컨트롤러 재부팅이 성공적으로 완료되면 7세그먼트 디스플레이에 두 번째 컨트롤러의 7세그먼트 디스플레이에 일치하는 트레이 ID가 표시됩니다. 그런 다음 스토리지 관리 소프트웨어를 사용하여 새 컨트롤러 캐니스터를 검색할 수 있습니다.

. 컨트롤러-드라이브 트레이의 서비스 조치 필요 LED 중 하나라도 _ ON _ 이거나 컨트롤러 서비스 조치 필요 LED가 _ ON _ 인 경우:
+
.. 컨트롤러 캐니스터가 올바르게 설치되어 있고 모든 케이블이 올바르게 장착되어 있는지 확인합니다. 필요한 경우 컨트롤러 캐니스터를 다시 설치합니다.
.. 컨트롤러 드라이브 트레이의 서비스 조치 필요 LED와 컨트롤러 서비스 조치 필요 LED를 다시 확인하십시오. 문제가 해결되지 않으면 기술 지원 부서에 문의하십시오.


. 이중 구성의 경우 컨트롤러 B에 대해 1단계부터 2단계까지 반복합니다
. 상태 표시등과 스토리지 관리 소프트웨어를 사용하여 스토리지 어레이에 있는 모든 트레이의 상태를 확인합니다. 구성 요소의 주의 상태가 필요하면 Recovery Guru를 사용하여 문제를 해결하십시오. 문제가 해결되지 않으면 기술 지원 부서에 문의하십시오.




== 3단계: 컨트롤러 소프트웨어 버전 확인

새 컨트롤러가 올바른 운영 체제(컨트롤러 펌웨어) 레벨 및 NVSRAM으로 실행되고 있는지 확인해야 합니다.

.단계
. 다음 중 하나를 수행합니다.
+
** SANtricity 11.30 및 컨트롤러 펌웨어 8.30을 지원하지 않는 컨트롤러로 업그레이드하는 경우, 새 컨트롤러에서 실행되는 버전이 원래 컨트롤러에서 마지막으로 실행되었던 버전과 일치하는지 확인하십시오. 일반적으로 이전 컨트롤러에서 지원하는 최신 릴리즈입니다. 필요한 경우 새 컨트롤러에 적절한 버전을 설치합니다.
** SANtricity 11.30 및 컨트롤러 펌웨어 8.30을 실행하는 컨트롤러로 업그레이드하는 경우 새 컨트롤러의 전원을 켠 후 최신 NVSRAM을 다운로드하여 설치하십시오.


. 컨트롤러 업그레이드에 프로토콜 변경(예: Fibre Channel에서 iSCSI로)이 포함되어 있고 스토리지 배열에 대해 이미 정의된 호스트가 있는 경우 새 호스트 포트를 호스트와 연결합니다.
+
.. System Manager에서 Storage [Hosts] 메뉴를 선택합니다.
.. 포트를 연결할 호스트를 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
현재 호스트 설정을 보여주는 대화 상자가 나타납니다.

.. 호스트 포트 * 탭을 클릭합니다.
+
대화 상자에 현재 호스트 포트 식별자가 표시됩니다.

.. 각 호스트와 연결된 호스트 포트 식별자 정보를 업데이트하려면 이전 호스트 어댑터의 호스트 포트 ID를 새 호스트 어댑터의 새 호스트 포트 ID로 교체하십시오.
.. 각 호스트에 대해 d 단계를 반복합니다.
.. 저장 * 을 클릭합니다.


+
호환 하드웨어에 대한 자세한 내용은 를 참조하십시오 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성 매트릭스"^] 및.

. 헤드스왑을 준비하는 동안 모든 씬 볼륨에 대해 Write Back Caching을 사용하지 않도록 설정한 경우 Write Back Caching을 다시 사용하도록 설정합니다.
+
.. System Manager에서 Storage [Volumes] 메뉴를 선택합니다.
.. 임의의 볼륨을 선택한 다음 MENU: More [Change cache settings](추가 [캐시 설정 변경])를 선택합니다.
+
캐시 설정 변경 대화 상자가 나타납니다. 스토리지 배열의 모든 볼륨이 이 대화 상자에 나타납니다.

.. 기본 * 탭을 선택하고 읽기 캐싱 및 쓰기 캐싱 설정을 변경합니다.
.. 저장 * 을 클릭합니다.


. 헤드스왑을 준비하는 동안 SAML이 비활성화된 경우 SAML을 다시 활성화합니다.
+
.. System Manager에서 설정 [액세스 관리] 메뉴를 선택합니다.
.. SAML * 탭을 선택한 다음 페이지의 지침을 따릅니다.


. GUI 또는 CLI를 사용하여 스토리지 어레이에 대한 지원 데이터를 수집합니다.
+
** System Manager 또는 Storage Manager의 Array Management Window를 사용하여 스토리지 어레이의 지원 번들을 수집하고 저장합니다.
+
*** System Manager에서 지원 [지원 센터 > 진단 탭] 메뉴를 선택합니다. 그런 다음 * 지원 데이터 수집 * 을 선택하고 * 수집 * 을 클릭합니다.
*** Array Management Window 도구 모음에서 Monitor [Health > Collect Support Data Manually] 메뉴를 선택합니다. 그런 다음 이름을 입력하고 지원 번들을 저장할 시스템의 위치를 지정합니다.
+
이 파일은 브라우저의 다운로드 폴더에 'upport-data.7z'라는 이름으로 저장됩니다.

+
선반에 서랍이 있는 경우 해당 셸프의 진단 데이터는 "tray-component-state-capture.7z"라는 별도의 압축 파일에 보관됩니다



** CLI를 이용하여 'Save storageArray supportData' 명령어를 실행하여 스토리지 배열에 대한 종합적인 지원 데이터를 수집한다.
+

NOTE: 지원 데이터를 수집하면 스토리지 시스템의 성능에 일시적으로 영향을 줄 수 있습니다.



. 스토리지 어레이 구성의 변경 사항에 대해 NetApp 기술 지원 부서에 알립니다.
+
.. 에서 기록한 컨트롤러 드라이브 트레이의 일련 번호를 가져옵니다 xref:prepare-upgrade-controllers-task.adoc[컨트롤러 업그레이드를 준비합니다].
.. NetApp Support 사이트 에 로그인합니다 http://mysupport.netapp.com/eservice/assistant["mysupport.netapp.com/eservice/assistant"^].
.. 범주 1 * 의 드롭다운 목록에서 * 제품 등록 * 을 선택합니다.
.. ** Comments** 텍스트 상자에 다음 텍스트를 입력하여 컨트롤러-드라이브 트레이의 일련 번호를 일련 번호로 대체합니다.
+
'일련 번호: 일련 번호에 대한 경고를 작성하십시오. 알림 이름은 "E-Series 업그레이드"여야 합니다. 알림 텍스트는 다음과 같이 표시되어야 합니다

+
``주의: 이 시스템의 컨트롤러는 원래 구성에서 업그레이드되었습니다. 교체 컨트롤러를 주문하기 전에 컨트롤러 구성을 확인하고 시스템이 업그레이드되었음을 디스패치에 알립니다.

.. 양식 하단의 * 제출 * 버튼을 클릭합니다.




컨트롤러 업그레이드로 인해 공급업체 ID가 LSI에서 NetApp로 변경되는 경우, 로 이동하십시오 link:remount-volumes-lsi-task.html["공급업체를 LSI에서 NetApp로 변경한 후 볼륨을 다시 마운트합니다"]그렇지 않으면 컨트롤러 업그레이드가 완료되고 정상 운영을 다시 시작할 수 있습니다.
