---
permalink: upgrade-controllers/install-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, installing new controller, install new controller, install battery, installing battery, install controller canister 
summary: 이전 컨트롤러를 제거한 후에는 컨트롤러 드라이브 트레이에 새 컨트롤러를 설치할 수 있습니다 
---
= 새 컨트롤러를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전 컨트롤러를 제거한 후에는 컨트롤러 드라이브 트레이에 새 컨트롤러를 설치할 수 있습니다

컨트롤러 드라이브 트레이의 각 컨트롤러에 대해 다음 단계를 수행하십시오 이중 컨트롤러 드라이브 트레이에서 컨트롤러를 업그레이드하는 경우 모든 단계를 반복하여 두 번째 컨트롤러 캐니스터를 설치합니다.

.무엇을 &#8217;필요로 할거야
* ESD 밴드나 기타 정전기 방지 조치를 취하십시오.
* 원래 컨트롤러 캐니스터에서 나온 배터리 또는 주문한 새 배터리입니다.
* 새 컨트롤러 캐니스터




== 1단계: 배터리를 설치합니다

원래 컨트롤러 캐니스터에서 분리한 배터리 또는 주문한 새 배터리를 설치합니다.

.단계
. 새 컨트롤러 캐니스터의 포장을 풀고 이동식 덮개가 위를 향하도록 평평하고 정전기가 없는 표면에 설치합니다.
. 덮개 단추를 누르고 덮개를 밀어 분리합니다.
. 배터리 슬롯이 사용자를 향하도록 컨트롤러 캐니스터의 방향을 맞춥니다.
. 컨트롤러 모델에 따라 다음 중 하나를 수행합니다.
+
** E2600 또는 E2700 컨트롤러 모델:
+
... 배터리 회로 보드를 새 컨트롤러 캐니스터 앞쪽으로 밀어 삽입합니다.
... 나비나사를 조여 새 컨트롤러 캐니스터 카드에 배터리 회로 보드를 고정합니다.
... 상단 래치 커버가 딸깍 소리가 날 때까지 밀어넣어 새 컨트롤러 캐니스터의 상단 덮개를 다시 설치합니다.
+
래치가 제자리에 고정되면 래치 하단이 섀시의 금속 슬롯에 후크됩니다.



** 기타 컨트롤러 모델의 경우:
+
... 새 컨트롤러 캐니스터에 배터리를 삽입합니다.
+
새 캐니스터의 벽에 있는 리벳 아래에 유지되도록 배터리를 캐니스터 안으로 밀어 넣습니다.

... 잠금 핸들을 45도 각도로 유지하면서 배터리 하단의 커넥터를 캐니스터의 커넥터에 맞춥니다.
... 딸깍 소리가 날 때까지 배터리를 아래로 누르고 잠금 핸들을 위로 움직여 컨트롤러 배터리를 컨트롤러 케이스에 고정합니다.
+

TIP: 컨트롤러 배터리가 E5XX 컨트롤러 드라이브 트레이에 올바르게 장착되었는지 확인하려면 컨트롤러 배터리를 밀어 빼낸 후 다시 삽입해야 할 수 있습니다. 딸깍 소리가 날 때, 그리고 핸들을 움직일 때 잠금 핸들이 똑바로 선 위치에서 움직이지 않을 때 안전합니다.

... 상단 래치 커버가 딸깍 소리가 날 때까지 밀어넣어 새 컨트롤러 캐니스터의 상단 덮개를 다시 설치합니다.
+
래치가 제자리에 고정되면 래치 하단이 섀시의 금속 슬롯에 후크됩니다.





. 컨트롤러 캐니스터를 뒤집어 배터리가 올바르게 설치되었는지 확인합니다.




== 2단계: 새 컨트롤러 캐니스터 설치

새 컨트롤러 캐니스터를 컨트롤러 쉘프에 설치합니다.

.단계
. 새 컨트롤러 캐니스터를 완전히 컨트롤러 드라이브 트레이에 밀어 넣습니다 분리 레버를 컨트롤러 캐니스터 중앙을 향해 돌려 제자리에 고정시킵니다.
. 새 컨트롤러 캐니스터에 파이버 채널 HIC 또는 InfiniBand HIC가 있으면 SFP+ 트랜시버(파이버 채널) 또는 QSFP+ 트랜시버(InfiniBand)를 컨트롤러 캐니스터에 설치하고 호스트 케이블을 다시 연결합니다.
+
업그레이드와 관련된 HIC에 따라 기존 컨트롤러 캐니스터에서 분리한 SFP+ 트랜시버 또는 QSFP+ 트랜시버를 재사용할 수 있습니다.

. 컨트롤러 드라이브 트레이와 드라이브 트레이 사이의 모든 케이블을 다시 연결합니다.
+
드라이브 케이블 연결 구성이 이전 컨트롤러와 동일한 경우 케이블에 연결한 레이블을 사용하여 케이블을 올바르게 다시 연결합니다.

+

NOTE: 이전 모델에서 E2700 컨트롤러로 업그레이드하는 경우, 드라이브 케이블 연결 구성이 이전 컨트롤러에 사용된 구성과 다를 수 있습니다.



E2800 및 E5700 컨트롤러를 업그레이드하고 드라이브 보안 기능을 활성화한 경우 로 이동합니다 link:upgrade-unlock-drives-task.html["드라이브 잠금을 해제합니다"]. 그렇지 않으면 로 이동합니다 link:complete-upgrade-controllers-task.html["컨트롤러 업그레이드를 완료합니다"].
