---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: E-Series 컨트롤러의 업그레이드 및 교체에 대한 요구사항을 검토하십시오. 
---
= 업그레이드 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러를 업그레이드하기 전에 다음 고려 사항을 검토하십시오.


NOTE: 각 E-Series 컨트롤러에 대해 지원되는 구성에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["E-Series 하드웨어 개요"] 참조하십시오.



== 하드웨어 및 펌웨어 요구 사항

* * 이중 및 단일 컨트롤러 업그레이드 *
+
이중 컨트롤러 드라이브 트레이의 경우 두 컨트롤러를 모두 교체합니다. 단일 컨트롤러 드라이브 트레이의 경우 하나의 컨트롤러를 교체합니다. 두 경우 모두 컨트롤러 드라이브 트레이의 전원을 꺼야 합니다 따라서 교체를 완료할 때까지 스토리지 배열의 데이터에 액세스할 수 없습니다.

* * 트레이 및 선반 *
+
E-Series 컨트롤러 쉘프가 포함된 스토리지 어레이는 일반적으로 SANtricity System Manager 사용자 인터페이스를 통해 관리됩니다.

* * 컨트롤러 배터리 *
+
새 컨트롤러는 배터리가 설치되지 않은 상태로 배송됩니다. 가능한 경우 기존 컨트롤러에서 배터리를 분리한 다음 새 컨트롤러에 배터리를 설치해야 합니다. 그러나 일부 컨트롤러 업그레이드의 경우 이전 컨트롤러의 배터리가 새 컨트롤러와 호환되지 않습니다. 이러한 경우 새 컨트롤러와 함께 배터리를 주문해야 하며, 이러한 작업을 시작하기 전에 배터리를 사용할 수 있어야 합니다.

* * 동기 미러링 및 비동기 미러링 *
+
스토리지 배열이 동기 미러링에 참여하는 경우 운영 사이트와 원격 사이트 간에 iSCSI 또는 파이버 채널 연결만 지원됩니다. 새 컨트롤러의 HIC(호스트 인터페이스 카드) 구성에 iSCSI 또는 파이버 채널 연결이 포함되지 않으면 동기식 미러링이 지원되지 않습니다.

+
비동기 미러링의 경우 로컬 스토리지 배열과 원격 스토리지 배열은 서로 다른 버전의 펌웨어를 실행할 수 있습니다. 지원되는 최소 펌웨어 버전은 SANtricity 펌웨어 버전 7.84입니다.




NOTE: E4000 컨트롤러의 경우 미러링은 파이버 채널 연결에서만 지원됩니다.

* * 스토리지 객체 제한 *
+
컨트롤러를 미드레인지 모델에서 엔트리 레벨 모델로 변경하는 경우(예: 5x00 모델에서 2x00 모델로 변경), 새로운 스토리지 어레이 구성은 기존 구성에 비해 스토리지 관리 소프트웨어에서 일부 스토리지 오브젝트(예: 볼륨)의 수를 줄입니다. 이전 구성이 스토리지 오브젝트 제한을 초과하지 않는지 확인해야 합니다.

+
자세한 내용은 을 http://hwu.netapp.com/home.aspx["Hardware Universe"^] 참조하십시오.

* * 최신 모델로 업그레이드 *
+
새 모델로 업그레이드하기 위해 컨트롤러를 교체하는 경우 현재 스토리지 어레이에는 새 모델을 지원하지 않는 프리미엄 기능이 설치되어 있을 수 있습니다.

+
E-Series 컨트롤러를 업그레이드할 때 새 컨트롤러에서 지원되지 않는 스토리지 어레이에 사용된 프리미엄 기능을 비활성화해야 합니다.

* * 액세스 볼륨을 사용한 대역 내 관리 *
+
** E4000은 액세스 볼륨을 사용하는 대역내 관리를 지원하지 않습니다.
+
E4000 컨트롤러로 업그레이드하기 전에 정의된 모든 호스트 및 호스트 클러스터에서 액세스 볼륨의 매핑을 해제합니다.







== 업그레이드 호환성

각 스토리지 어레이 모델에 대해 지원되는 업그레이드 경로를 검토합니다.

[role="tabbed-block"]
====
.E4000 컨트롤러 업그레이드 호환성
--
[cols="h,d,d,d"]
|===
| 업그레이드 경로 | 배터리 | 기능 지원 | SAS-3 쉘프 


| E2800에서 E4000까지 모두 지원합니다  a| 
새 배터리를 주문합니다.
 a| 
* E4000은 ARVM iSCSI를 지원하지 않습니다
* E4000 베이스보드 포트는 iSCSI 전용이며 FC로 변경할 수 없습니다
* E4000은 300개의 드라이브만 지원할 수 있습니다
* E4000은 512개의 볼륨만 지원할 수 있습니다
* E4000은 SAS 구성을 지원하지 않습니다
* E4000은 원격 저장소 볼륨을 지원하지 않습니다
* E4000은 액세스 볼륨을 사용하는 대역내 관리를 지원하지 않습니다.

 a| 
E4000 컨트롤러는 SAS-3 쉘프를 사용해야 합니다.



| E5700에서 E4000까지  a| 
새 배터리를 주문합니다.
 a| 
* E4000은 ARVM iSCSI를 지원하지 않습니다
* E4000 베이스보드 포트는 iSCSI 전용이며 FC로 변경할 수 없습니다
* E4000은 300개의 드라이브만 지원할 수 있습니다
+
** E5700은 최대 480개의 드라이브를 지원할 수 있습니다


* E4000은 512개의 볼륨만 지원할 수 있습니다
+
** E5700은 최대 2048개의 볼륨을 지원할 수 있습니다


* InfiniBand 호스트 인터페이스 카드를 지원하지 않습니다
* E4000은 SAS 구성을 지원하지 않습니다
* E4000은 원격 저장소 볼륨을 지원하지 않습니다
* E4000은 액세스 볼륨을 사용하는 대역내 관리를 지원하지 않습니다.

 a| 
E4000 컨트롤러는 SAS-3 쉘프를 사용해야 합니다.

|===
--
.EF600 및 EF300 컨트롤러 업그레이드 호환성
--
[cols="h,d,d,d"]
|===
| 업그레이드 경로 | 배터리 | 기능 지원 | SAS-3 쉘프 


| EF600에서 EF600으로 전환, 다른 호스트 인터페이스 카드 사용  a| 
이전 배터리를 다시 사용합니다.
 a| 
* 씬 프로비저닝된 볼륨은 지원되지 않습니다
* 동기식 미러링을 지원하지 않음

| EF600 컨트롤러는 SAS-3 쉘프를 사용해야 합니다. 


| EF300에서 EF600으로 업그레이드  a| 
이전 배터리를 다시 사용합니다.
 a| 
* 씬 프로비저닝된 볼륨은 지원되지 않습니다
* 동기식 미러링을 지원하지 않음

 a| 
EF600 컨트롤러는 SAS-3 쉘프를 사용해야 합니다.

|===
--
.레거시 컨트롤러 업그레이드 호환성
--
[cols="h,d,d,d,d"]
|===
| 업그레이드 경로 | 배터리 | 공급업체 ID입니다 | 기능 지원 | SAS-3 쉘프 


| E2x00에서 E2x00까지  a| 
이전 배터리를 다시 사용합니다.
 a| 
추가 단계가 필요합니다.
 a| 
E2700에서는 기존 스냅샷이 지원되지 않습니다.
 a| 
E2800 컨트롤러는 SAS-2 쉘프에 배치하면 안 됩니다.



| E2x00에서 E5x00까지  a| 
새 배터리를 주문합니다.
 a| 
E2600에서 E5500 또는 E5600으로 업그레이드하거나 E2700에서 E5400으로 업그레이드할 경우 추가 단계가 필요합니다.
 a| 
* 기존 스냅샷은 E5500 또는 E5600에서 지원되지 않습니다.
* 기존 RVM(원격 볼륨 미러링)은 iSCSI HIC가 있는 E5500 또는 E5600에서 지원되지 않습니다.
* iSCSI HIC가 있는 E5500 또는 E5600에서는 Data Assurance가 지원되지 않습니다.
* E5700 컨트롤러는 SAS-2 선반에 배치할 수 없습니다.

 a| 
E5400, E5500 및 E5600 컨트롤러는 SAS-3 쉘프에 장착되지 않아야 합니다.



| E5x00에서 E2x00까지  a| 
새 배터리를 주문합니다.
 a| 
E5500 또는 E5600에서 E2600으로 업그레이드하거나 E5400에서 E2700으로 업그레이드할 경우 추가 단계가 필요합니다.
 a| 
E2700에서는 기존 스냅샷이 지원되지 않습니다.
 a| 
5400, E5500 및 E5600 컨트롤러는 SAS-3 쉘프에 장착되지 않아야 합니다.



| E5x00에서 E5x00까지  a| 
이전 배터리를 다시 사용합니다.
 a| 
E5400에서 E5500 또는 E5600으로 업그레이드할 때 추가 단계 필요
 a| 
* 기존 스냅샷은 E5500 또는 E5600에서 지원되지 않습니다.
* iSCSI HIC가 있는 E5400 또는 E5500에서는 기존 RVM(원격 볼륨 미러링)이 지원되지 않습니다.
* iSCSI HIC가 있는 E5400 또는 E5500에서는 Data Assurance가 지원되지 않습니다.
* E5700 컨트롤러는 SAS-2 선반에 배치할 수 없습니다.

 a| 
E5400, E5500 및 E5600 컨트롤러는 SAS-3 쉘프에 장착되지 않아야 합니다.



| EF5x0에서 EF5x0으로  a| 
이전 배터리를 다시 사용합니다.
 a| 
EF540을 EF550 또는 EF560으로 업그레이드할 때 추가 단계 필요
 a| 
* EF550/EF560에 대한 기존 스냅샷 없음
* iSCSI를 지원하는 EF550/EF560의 Data Assurance는 없으며
* EF570 컨트롤러는 SAS-3 쉘프에 배치하면 안 됩니다.

 a| 
EF540, EF550 및 EF560 컨트롤러는 SAS-3 쉘프에 장착되어서는 안 됩니다.

|===
--
====


== SAS 엔클로저

E5700은 헤드 업그레이드를 통해 DE5600 및 DE6600 SAS-2 엔클로저를 지원합니다. E5700 컨트롤러가 SAS-2 케이스에 설치되면 기본 호스트 포트 지원이 비활성화됩니다.

|===
| SAS-2 쉘프 | SAS-3 쉘프 


 a| 
SAS-2 쉘프는 다음과 같은 모델을 포함합니다.

* DE1600, DE5600 및 DE6600 드라이브 트레이
* E5400, E5500 및 E5600 컨트롤러-드라이브 트레이
* EF540, EF550 및 EF560 Flash Array
* E2600 및 E2700 컨트롤러 드라이브 트레이

 a| 
SAS-3 쉘프는 다음과 같은 모델을 포함합니다.

* E4000 컨트롤러 쉘프
* EF600 컨트롤러 쉘프 1
* EF300 컨트롤러 쉘프 1
* E2800 컨트롤러 쉘프
* E5700 컨트롤러 쉘프
* DE212C, DE224C, DE460C 드라이브 쉘프


|===
참고:

. EF600 및 EF300 컨트롤러는 SAS-3 쉘프만 확장할 수 있습니다.




== SAS-2에서 SAS-3에 대한 투자 보호

새로운 SAS-3 컨트롤러 쉘프(E57XX/EF570/E28XX) 뒤에 사용하도록 SAS-2 시스템을 재구성할 수 있습니다.


NOTE: 이 절차를 수행하려면 Feature Product Variance Request(FPVR)가 필요합니다. FPVR을 파일로 첨부하려면 영업 팀에 문의하십시오.
