---
permalink: upgrade-controllers/prepare-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade controller key management, prepare upgrade controller, upgrade controller preparation, preparing controller upgrade 
summary: 드라이브 보안 키를 저장하고 지원 데이터를 수집하며 컨트롤러를 오프라인으로 전환하여 컨트롤러를 업그레이드할 준비를 합니다. 
---
= 컨트롤러 업그레이드를 준비합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Drive Security 키(사용하는 경우)를 저장하고, 일련 번호를 기록하고, 지원 데이터를 수집하고, 특정 기능을 비활성화하고(사용하는 경우) 컨트롤러를 오프라인으로 전환하여 컨트롤러를 업그레이드할 준비를 합니다.


NOTE: 지원 데이터를 수집하면 스토리지 시스템의 성능에 일시적으로 영향을 줄 수 있습니다.

.단계
. 기존 스토리지 어레이를 현재 컨트롤러에서 사용할 수 있는 최신 운영 체제(컨트롤러 펌웨어) 버전으로 업데이트해야 합니다. SANtricity 시스템 관리자에서 소프트웨어 및 펌웨어 인벤토리를 보려면 [업그레이드 센터] 메뉴로 이동합니다.
+

NOTE: SANtricity OS 버전 8.50을 지원하는 컨트롤러로 업그레이드하는 경우 새 컨트롤러를 설치하고 전원을 켠 후에 SANtricity OS의 최신 버전과 최신 NVSRAM을 설치해야 합니다. 이 업그레이드를 수행하지 않으면 ALB(자동 로드 밸런싱)에 맞게 스토리지 배열을 구성하지 못할 수도 있습니다.

. 보안 지원 드라이브가 설치되어 있고 전체 컨트롤러 교체를 수행하려는 경우 다음 표를 참조하여 보안 유형(내부 또는 외부) 및 드라이브 상태에 대한 적절한 단계를 완료하십시오. 보안 지원 드라이브가 설치되어 있지 * 않은 경우, 이 단계를 건너뛰고 표 아래의 3단계로 이동할 수 있습니다.
+

NOTE: 표의 일부 단계에서는 CLI(Command Line Interface) 명령이 필요합니다. 이러한 명령 사용에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/e-series-cli/index.html["명령줄 인터페이스 참조"].

+
|===
| 보안 유형 및 컨텍스트 | 단계 


 a| 
내부 키 관리, 하나 이상의 드라이브가 잠겨 있습니다
 a| 
내부 보안 키 파일을 관리 클라이언트의 알려진 위치(System Manager 액세스에 사용되는 브라우저가 있는 시스템)로 내보냅니다. 를 사용합니다 `export storageArray securityKey` CLI 명령: 보안 키와 관련된 암호를 제공하고 키를 저장할 위치를 지정해야 합니다.



 a| 
외부 키 관리, 모든 드라이브 잠김, 컨트롤러 교체를 위해 일시적으로 내부 키 관리로 전환할 수 있습니다(권장).
 a| 
다음 단계를 순서대로 수행합니다.

.. 외부 KMS 서버 주소 및 포트 번호를 기록합니다. System Manager에서 설정 [시스템 > 보안 키 관리 > 키 관리 서버 설정 보기/편집] 메뉴로 이동합니다.
.. 로컬 호스트에서 클라이언트 및 서버 인증서를 사용할 수 있는지 확인하여 컨트롤러 교체가 완료된 후 스토리지 어레이와 키 관리 서버가 서로를 인증할 수 있도록 합니다. 를 사용합니다 `save storageArray keyManagementCertificate` 인증서를 저장하는 CLI 명령입니다. 명령을 와 함께 두 번 실행해야 합니다 `certificateType` 매개 변수를 로 설정합니다 `client`, 및 매개 변수가 로 설정된 다른 가 표시됩니다 `server`.
.. 'disable storageArray externalKeyManagement' CLI 명령어를 실행하여 내부 키 관리로 전환합니다.
.. 내부 보안 키 파일을 관리 클라이언트의 알려진 위치(System Manager 액세스에 사용되는 브라우저가 있는 시스템)로 내보냅니다. 를 사용합니다 `export storageArray securityKey` CLI 명령: 보안 키와 관련된 암호를 제공하고 키를 저장할 위치를 지정해야 합니다.




 a| 
외부 키 관리, 모든 드라이브 잠김, 컨트롤러 교체를 위해 내부 키 관리로 일시적으로 전환할 수 없음 *.
 a| 
고객 지원 센터에 문의하십시오.



 a| 
외부 키 관리, 부분 드라이브 잠금
 a| 
추가 단계는 필요하지 않습니다.

|===
+

NOTE: 클라이언트 및 서버 인증서를 검색하려면 스토리지 배열이 최적 상태여야 합니다. 인증서를 검색할 수 없는 경우 새 CSR을 생성하고 CSR에 서명한 후 EKMS(외부 키 관리 서버)에서 서버 인증서를 다운로드해야 합니다.

. 스토리지 배열의 일련 번호를 기록합니다.
+
.. System Manager에서 Support [Support Center > Support Resources] 메뉴를 선택합니다.
.. 아래로 스크롤하여 * 자세한 스토리지 배열 정보 시작 * 을 선택한 다음 * 스토리지 배열 프로파일 * 을 선택합니다.
+
화면에 보고서가 나타납니다.

.. 스토리지 배열 프로파일 아래에서 섀시 일련 번호를 찾으려면 * 찾기 * 텍스트 상자에 * 일련 번호 * 를 입력한 다음 * 찾기 * 를 클릭합니다.
+
일치하는 모든 용어가 강조 표시됩니다. 모든 결과를 한 번에 하나씩 스크롤하려면 * 찾기 * 를 계속 클릭합니다.

.. 섀시 일련 번호 기록을 만듭니다.
+
의 단계를 수행하려면 이 일련 번호가 필요합니다 link:complete-upgrade-controllers-task.html["컨트롤러 업그레이드를 완료합니다"].



. GUI 또는 CLI를 사용하여 스토리지 어레이에 대한 지원 데이터를 수집합니다.
+
** System Manager를 사용하여 스토리지 어레이의 지원 번들을 수집하고 저장합니다.
+
*** System Manager에서 지원 [지원 센터 > 진단 탭] 메뉴를 선택합니다. 그런 다음 * 지원 데이터 수집 * 을 선택하고 * 수집 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 'upport-data.7z'라는 이름으로 저장됩니다.

+
선반에 서랍이 있는 경우 해당 셸프의 진단 데이터는 "tray-component-state-capture.7z"라는 별도의 압축 파일에 보관됩니다.



** CLI를 이용하여 'Save storageArray supportData' 명령어를 실행하여 스토리지 배열에 대한 종합적인 지원 데이터를 수집한다.


. 스토리지 시스템과 접속된 모든 호스트 간에 입출력 작업이 수행되지 않도록 합니다.
+
.. 스토리지에서 호스트로 매핑된 LUN이 포함된 모든 프로세스를 중지합니다.
.. 스토리지에서 호스트로 매핑된 LUN에 데이터를 쓰는 애플리케이션이 없는지 확인합니다.
.. 스토리지의 볼륨과 연결된 모든 파일 시스템을 마운트 해제합니다.
+

NOTE: 호스트 I/O 작업을 중지하는 정확한 단계는 호스트 운영 체제 및 구성에 따라 달라지며, 이 지침은 다루지 않습니다. 사용자 환경에서 호스트 I/O 작업을 중지하는 방법을 모르는 경우 호스트를 종료하는 것이 좋습니다.

+

CAUTION: * 데이터 손실 가능성 * -- I/O 작업이 진행되는 동안 이 절차를 계속하면 데이터가 손실될 수 있습니다.



. 스토리지 배열이 미러링 관계에 참여하는 경우 보조 스토리지 배열에 대한 모든 호스트 I/O 작업을 중지합니다.
. 비동기식 또는 동기식 미러링을 사용하는 경우 미러링된 쌍을 삭제하고 System Manager 또는 Array Management 창을 통해 미러링 관계를 비활성화하십시오.
. 씬 프로비저닝된 볼륨이 호스트에 씬 볼륨으로 보고되고 이전 어레이에서 UNMAP 기능을 지원하는 펌웨어(8.25 펌웨어 이상)를 실행 중인 경우 모든 씬 볼륨에 대해 Write Back Caching을 해제합니다.
+
.. System Manager에서 Storage [Volumes] 메뉴를 선택합니다.
.. 임의의 볼륨을 선택한 다음 MENU: More [Change cache settings](추가 [캐시 설정 변경])를 선택합니다.
+
캐시 설정 변경 대화 상자가 나타납니다. 스토리지 배열의 모든 볼륨이 이 대화 상자에 나타납니다.

.. 기본 * 탭을 선택하고 읽기 캐싱 및 쓰기 캐싱 설정을 비활성화합니다.
.. 저장 * 을 클릭합니다.
.. 캐시 메모리에 있는 데이터가 디스크로 플러시될 때까지 5분 정도 기다립니다.


. 컨트롤러에서 SAML(Security Assertion Markup Language)이 활성화된 경우 기술 지원 부서에 문의하여 SAML 인증을 비활성화하십시오.
+

NOTE: SAML이 활성화된 후에는 SANtricity 시스템 관리자 인터페이스를 통해 SAML을 비활성화할 수 없습니다. SAML 구성을 비활성화하려면 기술 지원 부서에 지원을 요청하십시오.

. 진행 중인 모든 작업이 완료될 때까지 기다린 후 다음 단계를 계속 진행하십시오.
+
.. System Manager의 * Home * 페이지에서 * View Operations in Progress * 를 선택합니다.
.. 계속하기 전에 * 작업 진행 중 * 창에 표시된 모든 작업이 완료되었는지 확인하십시오.


. 컨트롤러 드라이브 트레이의 전원을 끕니다
+
컨트롤러 드라이브 트레이의 모든 LED가 어두워지기를 기다립니다.

. 컨트롤러 드라이브 트레이에 연결된 각 드라이브 트레이의 전원을 끕니다
+
모든 드라이브가 스핀다운될 때까지 2분 정도 기다립니다.



.다음 단계
로 이동합니다 link:remove-controllers-task.html["컨트롤러를 제거합니다"].
