---
permalink: upgrade-controllers/reconfigure-sas-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, reconfigure SAS-2, SAS-2, SAS-3, convert controller shelf, convert drive shelf, 
summary: '승인된 SAS-2 어레이(E2700, E5550/EF5500, E5600/EF560)의 컨트롤러 쉘프를 드라이브 쉘프로 변환한 다음, 해당 쉘프 및 승인된 모든 SAS-2 드라이브 쉘프(DE1600, DE5600, DE6600)를 새로운 승인된 SAS-3 어레이(E2800, E5700/EF570) 및 승인된 SAS-3 드라이브 쉘프(DE212C, DE224C, DE460C) 뒤에 배치할 수 있습니다. 데이터 보존 없음.' 
---
= 새로운 SAS-3 컨트롤러 쉘프 뒤에서 SAS-2 시스템을 재구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요한 경우 새 SAS-3 컨트롤러 쉘프 뒤에 사용할 SAS-2 시스템을 재구성할 수 있습니다.

승인된 SAS-2 어레이에는 E2700, E5550/EF5500, E5600/EF560이 포함됩니다. 승인된 SAS-2 드라이브 쉘프에는 DE1600, DE5600, DE6600가 포함되어 있습니다. 승인된 SAS-3 어레이에는 E2800 및 E5700/EF570이 포함됩니다. 승인된 SAS-3 드라이브 쉘프에는 DE212C, DE224C 및 DE460C가 포함됩니다.

.이 작업에 대해
이 절차에서는 승인된 SAS-2 어레이에서 컨트롤러 쉘프를 드라이브 쉘프로 변환한 다음, 데이터 보존 없이 승인된 새로운 SAS-3 어레이 및 드라이브 쉘프 뒤에 쉘프를 배치합니다.

이 절차는 IOM12 및 IOM12B 드라이브 쉘프에 적용됩니다.


NOTE: IOM12B 모듈은 SANtricity OS 11.70.2 이상에서만 지원됩니다. IOM12B를 설치하거나 업그레이드하기 전에 컨트롤러의 펌웨어가 업데이트되었는지 확인합니다.

.시작하기 전에
이 절차의 복잡성으로 인해 다음이 필요합니다.

* 기능 제품 차이 요청(FPVR)이 있어야 합니다. FPVR을 파일로 첨부하려면 NetApp 프로페셔널 서비스에 문의하십시오.
+

NOTE: 이 절차를 시도하기 전에 FPVR을 취득하지 못하면 드라이브 장애가 발생하고 컨트롤러가 잠길 수 있습니다.

* 데이터를 백업할 수 있으면 NetApp 프로페셔널 서비스의 지원 없이 이 절차를 수행할 수 있습니다.
* 데이터를 백업할 수 없는 경우에는 NetApp 프로페셔널 서비스에 문의하여 이 절차를 지원받으십시오.
* 두 어레이가 절차를 위해 준비되어 있는지 확인합니다.
+
** * 기존 어레이 *: 전원이 켜진 SANtricity OS 8.25 이상이 있는 기존 어레이
** * 새 어레이 *: 새 어레이의 포장을 풀고 전원을 끕니다.


* 드라이브 쉘프로 변환할 SAS-2 컨트롤러 쉘프의 일련 번호를 기록합니다.




== 1단계: 컨트롤러 전원 끄기(데이터 보존 제외)

컨트롤러의 전원을 끄기 전에 모든 작업을 종료해야 합니다.

.단계
. 기존 SAS-2 어레이에 여전히 액세스할 수 있는 경우 모든 볼륨 그룹을 삭제하고 두 컨트롤러의 전원을 모두 끄고 모든 케이블을 분리합니다.
. 드라이브 쉘프로 변환할 SAS-2 컨트롤러 쉘프의 일련 번호를 기록합니다.
. 기존 어레이에 드라이브 보안을 사용하는 경우 보안 키를 사용할 수 있는지 확인합니다.




== 2단계: 컨트롤러 설치(비 데이터 보존)

성공적으로 종료되면 어레이의 컨트롤러를 교체할 수 있습니다.

.단계
. 기존 어레이에서 두 컨트롤러를 모두 IOM 또는 ESM으로 교체합니다.
. 가능한 경우 기존 어레이의 호스트 케이블과 네트워크 케이블을 사용하여 새 어레이의 컨트롤러에 연결합니다.
+

NOTE: 새 어레이의 호스트 연결에 따라 다른 케이블이 필요할 수 있습니다.

. 새 어레이의 컨트롤러 뒤에 있는 드라이브 쉘프에 케이블을 연결합니다.
+
기존 컨트롤러 드라이브 트레이와 연결된 드라이브 트레이는 드라이브 쉘프가 되며 새 어레이의 컨트롤러에 케이블로 연결될 수 있습니다.

+

NOTE: SAS-2를 SAS-3에 연결하려면 SAS HD-미니 SAS 케이블이 필요합니다. 특정 컨트롤러 및 확장 쉘프 구성에 대한 자세한 케이블링 정보는 를 참조하십시오 link:../install-hw-cabling/index.html["케이블 연결"] 또는 을 누릅니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749["E-Series 하드웨어 케이블 연결 가이드 를 참조하십시오"^].





== 3단계: 컨트롤러 전원 켜기(비 데이터 보존)

설치가 완료되면 컨트롤러의 전원을 켜고 구성 변경 사항을 NetApp 기술 지원 부서에 제출합니다.

.단계
. 연결된 드라이브 쉘프를 비롯한 새 어레이의 전원을 켭니다.
. 를 설치하여 관리 포트와 IP 주소를 구성합니다 https://mysupport.netapp.com/tools/info/ECMLP2563821I.html["SANtricity 빠른 연결"^] 유틸리티.
. 기존 어레이에서 드라이브 보안을 사용 중인 경우 보안 키를 가져옵니다.
. 이 절차를 수행하기 전에 기존 어레이에서 볼륨 그룹을 삭제할 수 없는 경우 모든 외부 드라이브를 기본 드라이브로 표시되도록 설정해야 합니다. 드라이브를 기본 드라이브로 설정하는 방법에 대한 자세한 내용은 SANtricity 온라인 도움말을 참조하십시오.
. 구성 변경 사항을 NetApp 기술 지원 부서에 보냅니다.
+
.. 2단계에서 기록한 이전 컨트롤러-드라이브 트레이의 일련 번호를 확인하십시오.
.. 에 로그인합니다 http://mysupport.netapp.com/eservice/assistant["NetApp Support 사이트"^].
.. 피드백 범주 * 의 드롭다운 목록에서 * 설치된 제품 > 서비스 해제 요청 * 을 선택합니다.
.. 케이스 생성 * 을 선택합니다. 컨트롤러-드라이브 트레이의 일련 번호를 일련 번호로 대체하면서 * Comments * 텍스트 상자에 다음 텍스트를 입력합니다.
+
"소유 권한이 시스템의 다른 일련 번호로 이동되었으므로 이 일련 번호를 사용 중단하십시오. SN 노트에서 참조하십시오

.. 제출 * 을 선택합니다.




완료된 SAS-2-SAS-3 구성 변경은 NetApp 기술 지원 팀에 제출됩니다.
