---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: 컨트롤러 업그레이드로 인해 공급업체 ID가 LSI에서 NetApp로 변경되는 경우 볼륨을 다시 마운트합니다. 
---
= 공급업체를 LSI에서 NetApp로 변경한 후 볼륨을 다시 마운트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 업그레이드로 인해 공급업체 ID를 LSI에서 NetApp으로 변경할 수 있는 경우, 호스트 유형에 적합한 절차를 따르십시오.

* <<Remount volumes on an AIX host>>
* <<Remount volumes on a VMware host>>
* <<Remount volumes on a Windows host>>




== AIX 호스트에서 볼륨을 다시 마운트합니다

컨트롤러를 교체한 후 호스트가 스토리지 배열의 새 볼륨을 표시하지만 원래 볼륨은 실패로 표시되는 것을 확인할 수 있습니다.

실패한 볼륨이 나타나면 "cfgmgr" 명령을 실행합니다.



== VMware 호스트에 볼륨을 다시 마운트합니다

컨트롤러를 교체한 후 다음 조건을 준수할 수 있습니다.

* VMware는 스토리지 시스템의 볼륨에 대한 새 경로를 표시하지만 원래 경로도 비활성 경로로 표시합니다.
* 호스트는 스토리지 배열의 볼륨을 LSI 공급업체 ID가 있는 것으로 계속 표시합니다. 이 문제는 시작 시 LSI 규칙에 의해 볼륨이 요청되었을 때 발생할 수 있으므로 볼륨이 다시 온라인 상태로 돌아올 때 동일한 LSI 규칙을 계속 사용합니다.
* 표시 이름은 LSI에서 NetApp로 변경된 사항을 반영하지 않습니다. 이 문제는 초기 검색 후 표시 이름이 무료 테스트가 되었기 때문에 발생할 수 있습니다. 이 경우 표시 이름을 수동으로 변경할 수 있습니다.


.단계
. 각 호스트에서 재검색을 수행합니다.
. 이 하위 시스템에 대한 모든 호스트 I/O 작업을 중지합니다.
. NetApp 규칙에 따라 볼륨을 재확보할 수 있습니다.
+
.. esxcli storage core device list 명령을 실행합니다. 명령의 출력을 확인하여 이름이 aa.xxxx인 볼륨을 식별하십시오.
.. LSI 공급업체 ID를 NetApp로 변경하려면 daim -d naa.xxxxx 명령을 실행하여 daesxcli storage core disclaim -d na.xxxxx 명령을 실행하십시오.






== Windows 호스트에서 볼륨을 다시 마운트합니다

컨트롤러를 교체한 후에는 연결된 호스트가 업그레이드된 스토리지 어레이에 있는 볼륨으로 I/O 작업을 수행할 수 있도록 Windows 호스트에 볼륨을 다시 마운트해야 합니다.

.단계
. 장치 관리자 * 에서 * 숨김 장치 표시 * 를 선택합니다.
. 장치 관리자 * 에 나열된 각 NetApp SCSI 디스크 장치에 대해 항목을 마우스 오른쪽 단추로 클릭하고 * 제거 * 를 선택합니다.
+
호스트를 재부팅해야 한다는 메시지가 포함된 대화 상자가 Windows에 표시되는 경우 하드웨어를 검색하고 재부팅하기 전에 모든 볼륨의 제거를 완료합니다.

. 장치 관리자 * 를 마우스 오른쪽 단추로 클릭한 다음 * 하드웨어 변경 사항 검색 * 을 선택합니다.
. 호스트를 재부팅합니다.

