---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: E2800 및 E5700 컨트롤러를 업그레이드하고 드라이브 보안 기능을 활성화한 경우 드라이브를 수동으로 잠금 해제해야 합니다. 
---
= 드라이브 잠금을 해제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이러한 컨트롤러의 드라이브 보안 기능은 드라이브를 부분적으로, 외부적으로 또는 내부적으로 잠급니다. 드라이브 보안 기능이 활성화된 경우 이러한 드라이브를 수동으로 잠금 해제해야 합니다.

다음에 대한 적절한 절차를 따르십시오.

* <<내부 키 관리>>
* <<외부 키 관리>>




== 내부 키 관리

모든 드라이브가 잠겨 있을 때 내부 키 관리를 위해 다음 단계를 수행하십시오.

.이 작업에 대해
새로 바꾼 컨트롤러는 * L5 * 의 7세그먼트 디스플레이 코드로 잠깁니다. 이 잠금은 드라이브가 자동 모드 동기화(ACS)를 수행할 수 없을 때 발생합니다. 보안 키를 가져오면 ACS가 새 컨트롤러를 다시 시작하고 업데이트합니다.


NOTE: 관리 포트 1을 사용하지 않는 경우 다른 기본 IP 주소를 사용해 봅니다. + Ctrl A 포트 1: 192.168.128.101 + Ctrl A 포트 2: 192.168.128.102 + Ctrl 포트 1: 192.168.129.101 + Ctrl B 포트 2: 192.168.129.102

.단계
. 스토리지 어레이와 SANtricity 클라이언트의 랩톱 또는 PC 간에 직접 전용 이더넷을 연결합니다. 방법:
+
.. RJ45 이더넷 케이블을 사용하여 랩톱을 컨트롤러 A의 관리 포트 1에 연결합니다
.. 연결을 완료하려면 랩톱을 컨트롤러 A와 동일한 서브넷에 있는 IP 주소에 할당해야 할 수 있습니다 컨트롤러를 잠글 때 컨트롤러 A의 관리 주소는 기본적으로 192.168.128.101입니다. 따라서 랩톱을 "192.168.128.201"과 같은 서브넷에 할당할 수 있습니다.


. username * admin * 과 패스워드가 비어 있는 IP 주소 192.168.128.101을 사용하여 을 사용하여 내부 키를 가져옵니다 `import storageArray securityKey file` 에서 보안 키를 저장한 상태에서 CLI 명령을 실행합니다 link:prepare-upgrade-controllers-task.html["컨트롤러 업그레이드를 준비합니다"]. 이 명령 사용에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/e-series-cli/index.html["명령줄 인터페이스 참조"].
+
* 예: * `SMcli 192.168.128.101 -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
또는 다음 호출을 통해 REST API를 통해 내부 키를 가져올 수 있습니다. `/storage-systems/{system-id}/security-key/import`



컨트롤러는 드라이브의 자동 코드 동기화 프로세스를 계속 수행하고 재부팅합니다. 재부팅 후 컨트롤러는 원래 IP 구성을 통해 액세스할 수 있습니다.



== 외부 키 관리

모든 드라이브가 잠겨 있을 때 외부 키 관리를 위해 다음 단계를 수행하십시오.

.이 작업에 대해
새로 바꾼 컨트롤러는 * L5 * 의 7세그먼트 디스플레이 코드로 잠깁니다. 이 잠금은 드라이브가 자동 모드 동기화(ACS)를 수행할 수 없을 때 발생합니다. 보안 키를 가져오면 ACS가 새 컨트롤러를 다시 시작하고 업데이트합니다.


NOTE: 클라이언트 및 서버 인증서를 검색하려면 스토리지 배열이 최적 상태여야 합니다. 인증서를 검색할 수 없는 경우 새 인증서 서명 요청(CSR)을 생성한 다음 외부 키 관리 서버에서 서버 인증서를 가져와야 합니다.

.단계
. 스토리지 어레이와 SANtricity 클라이언트의 랩톱 또는 PC 간에 직접 전용 이더넷을 연결합니다. 방법:
+
.. RJ45 이더넷 케이블을 사용하여 랩톱을 컨트롤러 A의 관리 포트 1에 연결합니다
.. 연결을 완료하려면 랩톱을 컨트롤러 A와 동일한 서브넷에 있는 IP 주소에 할당해야 할 수 있습니다 컨트롤러를 잠글 때 컨트롤러 A의 관리 주소는 기본적으로 192.168.128.101입니다. 따라서 랩톱을 "192.168.128.201"과 같은 서브넷에 할당할 수 있습니다.


. 사용자 이름 * admin * 과 비밀번호 공백으로 기본 IP 주소 192.168.128.101을 사용하여 를 사용하여 외부 키 관리 서버를 설정합니다 `set storageArray externalKeyManagement` 명령을 사용하여 를 제공합니다 `serverAddress` 및 `serverPort` 에서 저장되었습니다 link:prepare-upgrade-controllers-task.html["컨트롤러 업그레이드를 준비합니다"]. 이 명령 사용에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/e-series-cli/index.html["명령줄 인터페이스 참조"].
+
* 예: * `SMcli 192.168.128.101 -u admin -p "" -c "set storageArray externalKeyManagement serverAddress=<ServerIPAddress> serverPort=<serverPort>;"`

+
또는 다음 호출을 통해 REST API를 통해 외부 키 관리 서버를 설정할 수 있습니다. `/storage-systems/{system-id}/external-key-server`

. 사용자 이름 * admin * 과 비어 있는 암호를 사용하여 기본 IP 주소 192.168.128.101을 사용하여 인증서를 가져옵니다 `storageArray keyManagementCertificate` CLI 명령: 클라이언트 인증서에 대해 한 번, 서버 인증서에 대해 두 번째.
+
* 예 A: * `SMcli 192.168.128.101 -u admin -p "" -c "download storageArray keyManagementCertificate certificateType=client file=\"Directory&FileName\";"`

+
* 예 B: * `SMcli 192.168.128.101 -u admin -p "" -c "download storageArray keyManagementCertificate certificateType=server file=\"Directory&FileName\";"`

+
또는 다음 호출을 통해 REST API를 통해 키서버 인증서를 가져올 수 있습니다. `/storage-systems/{system-id}/external-key-server/certificate`

. 에서 저장된 보안 키를 사용합니다 link:prepare-upgrade-controllers-task.html["컨트롤러 업그레이드를 준비합니다"]에서 외부 키를 사용자 이름 * admin * 과 빈 암호를 사용하여 IP 주소 192.168.128.101로 가져옵니다.
+
* 예: * `SMcli 192.168.128.101 -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
또는 다음 호출을 통해 REST API를 통해 외부 키를 가져올 수 있습니다. `/storage-systems/{system-id}/security-key/import`



컨트롤러는 드라이브의 자동 코드 동기화 프로세스를 계속 수행하고 재부팅합니다. 재부팅 후 컨트롤러는 원래 IP 구성을 통해 액세스할 수 있습니다.
