---
permalink: remote-storage-volumes/system-reqs-concept.html 
sidebar: sidebar 
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series 
summary: 시스템은 원격 스토리지 볼륨에 대한 호환성 요구 사항을 충족해야 합니다. 
---
= SANtricity 원격 스토리지 볼륨 사용에 대한 요구 사항 및 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 스토리지 볼륨 기능을 구성하기 전에 다음 요구 사항 및 제한 사항을 검토하십시오.



== 하드웨어 요구 사항



=== 지원되는 프로토콜

원격 스토리지 볼륨 기능의 초기 릴리스의 경우 iSCSI 및 IPv4 프로토콜에서만 지원을 사용할 수 있습니다.

을 참조하십시오 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 원격 스토리지 볼륨 기능에 사용되는 호스트와 E-Series(대상) 어레이 간의 최신 지원 및 구성 정보를 확인할 수 있습니다.



=== 수행할 수 있습니다

E-Series 스토리지 시스템에는 다음이 포함되어야 합니다.

* 컨트롤러 2개(이중 모드)
* 하나 이상의 iSCSI 연결을 통해 두 E-Series 컨트롤러가 원격 스토리지 시스템과 통신할 수 있도록 지원합니다
* SANtricity OS 11.71 이상
* 하위 모델 ID(SMID)에서 활성화된 원격 스토리지 기능


원격 시스템은 E-Series 스토리지 시스템이거나 다른 공급업체의 시스템일 수 있습니다. iSCSI 지원 인터페이스를 포함해야 합니다.



== 볼륨 요구 사항

가져오기에 사용되는 볼륨은 크기, 상태 및 기타 조건에 대한 요구 사항을 충족해야 합니다.



=== 원격 스토리지 볼륨

가져오기의 소스 볼륨을 "원격 저장소 볼륨"이라고 합니다. 이 볼륨은 다음 기준을 충족해야 합니다.

* 다른 불러오기의 일부가 될 수 없습니다
* 온라인 상태여야 합니다


가져오기가 시작되면 컨트롤러 펌웨어가 백그라운드에서 원격 저장소 볼륨을 생성합니다. 이러한 백그라운드 프로세스로 인해 원격 스토리지 볼륨은 System Manager에서 관리할 수 없으며 가져오기 작업에만 사용할 수 있습니다.

생성된 원격 스토리지 볼륨은 E-Series 시스템에서 다른 표준 볼륨과 마찬가지로 취급되며, 다음과 같은 예외가 있습니다.

* 원격 스토리지 디바이스의 프록시로 사용할 수 있습니다.
* 다른 볼륨 복사본 또는 스냅샷의 대상으로 사용할 수 없습니다.
* 가져오기가 진행 중인 동안에는 Data Assurance 설정을 변경할 수 없습니다.
* 가져오기 작업을 위해 엄격하게 예약되었으므로 어떤 호스트에도 매핑할 수 없습니다.


각 원격 스토리지 볼륨은 하나의 원격 스토리지 오브젝트에만 연결되지만 하나의 원격 스토리지 객체는 여러 원격 스토리지 볼륨과 연결될 수 있습니다. 원격 스토리지 볼륨은 다음 조합을 사용하여 고유하게 식별됩니다.

* 원격 스토리지 객체 식별자입니다
* 원격 스토리지 디바이스 LUN 번호입니다




=== 타겟 볼륨 후보

타겟 볼륨은 로컬 E-Series 시스템의 타겟 볼륨입니다.

대상 볼륨은 다음 기준을 충족해야 합니다.

* RAID/DDP 볼륨이어야 합니다.
* 원격 스토리지 볼륨과 같거나 큰 용량이 있어야 합니다.
* 원격 스토리지 볼륨과 동일한 블록 크기가 있어야 합니다.
* 유효한 상태(최적)가 있어야 합니다.
* 볼륨 복사본, 스냅샷 복사본, 비동기식 또는 동기식 미러링과 같은 관계는 가질 수 없습니다.
* DDP, 동적 볼륨 확장, 동적 용량 확장, 동적 세그먼트 크기, 동적 RAID 마이그레이션, 동적 용량 감소 등의 재구성 작업을 수행할 수 없습니다. 또는 조각 모음.
* 가져오기를 시작하기 전에 호스트에 매핑할 수 없습니다. 하지만 가져오기를 시작한 후에 매핑할 수 있습니다.
* FRC(Flash Read Cached)를 활성화할 수 없습니다.


System Manager는 원격 스토리지 가져오기 마법사의 일부로 이러한 요구 사항을 자동으로 확인합니다. 대상 볼륨 선택을 위해 모든 요구 사항을 충족하는 볼륨만 표시됩니다.



== 제한 사항

원격 스토리지 기능에는 다음과 같은 제한 사항이 있습니다.

* 미러링이 비활성화되어야 합니다.
* E-Series 시스템의 타겟 볼륨에 스냅샷이 없어야 합니다.
* 가져오기를 시작하기 전에 E-Series 시스템의 타겟 볼륨을 호스트에 매핑해서는 안 됩니다.
* E-Series 시스템의 타겟 볼륨에 리소스 프로비저닝이 비활성화되어 있어야 합니다.
* 원격 스토리지 볼륨을 호스트나 여러 호스트에 직접 매핑하지 않습니다.
* 웹 서비스 프록시는 지원되지 않습니다.
* iSCSI CHAP 암호는 지원되지 않습니다.
* SMcli는 지원되지 않습니다.
* VMware 데이터 저장소는 지원되지 않습니다.
* 가져오기 페어가 있는 경우 관계/가져오기 페어에 있는 스토리지 시스템 하나만 한 번에 업그레이드할 수 있습니다.




== 생산 수입 준비

프로덕션을 가져오기 전에 테스트 또는 "dry run" 가져오기를 수행하여 스토리지 및 Fabric 구성이 올바른지 확인해야 합니다.

많은 변수가 가져오기 작업 및 완료 시간에 영향을 줄 수 있습니다. 프로덕션 가져오기가 성공하고 예상 기간을 가져오려면 이러한 테스트 가져오기를 사용하여 모든 연결이 예상대로 작동하고 가져오기 작업이 적절한 시간 내에 완료되는지 확인할 수 있습니다. 그런 다음 원하는 결과를 얻기 위해 조정을 수행한 후 생산 가져오기를 시작할 수 있습니다.
