---
permalink: remote-storage-volumes/view-import-progress-task.html 
sidebar: sidebar 
keywords: Remote Storage Volumes, RTV, remote volumes, remote storage E-Series 
summary: SANtricity 시스템 관리자의 원격 스토리지 화면의 결과 목록 섹션에서 각 원격 스토리지 가져오기의 상태를 볼 수 있습니다. 
---
= SANtricity 원격 스토리지 볼륨에 대한 가져오기 진행률을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가져오기 프로세스가 시작된 후 진행 상황을 확인하고 조치를 취할 수 있습니다.

각 가져오기 작업에 대해 작업 진행 중 페이지에는 완료율과 남은 예상 시간이 표시됩니다. 작업에는 가져오기 우선 순위 변경, 작업 중지 및 다시 시작, 작업 연결 해제 등이 있습니다.


NOTE: 홈 페이지(* 홈 > 진행 중인 작업 표시 *)에서 진행 중인 작업을 볼 수도 있습니다.

.단계
. SANtricity 시스템 관리자에서 원격 스토리지 페이지로 이동하여 * 작업 보기 * 를 선택합니다.
+
작업 진행 중 대화 상자가 표시됩니다.

. 필요한 경우 작업 열의 링크를 사용하여 작업을 중지 및 재개하거나, 우선 순위를 변경하거나, 작업 연결을 끊습니다.
+
** * 우선 순위 변경 * – 진행 중이거나 보류 중인 작업의 처리 우선 순위를 변경하려면 * 우선 순위 변경 * 을 선택합니다. 작업에 우선 순위를 적용하고 * OK * 를 클릭합니다.
** * Stop * (중지 *) – 원격 저장 장치에서 데이터 복사를 일시 중지하려면 * Stop * (중지 *)을 선택합니다. 가져오기 쌍 간의 관계는 그대로 유지되며 가져오기 작업을 계속할 준비가 되면 * Resume * 을 선택할 수 있습니다.
** * Resume * – 중지된 위치에서 중지되거나 실패한 프로세스를 시작하려면 * Resume * 을 선택합니다. 그런 다음 Resume 작업에 우선 순위를 적용하고 * OK * 를 클릭합니다.
+
재시작 작업은 처음부터 가져오기를 다시 시작하지 * 않습니다 *. 처음부터 프로세스를 다시 시작하려면 * Disconnect * 를 선택한 다음 원격 저장소 가져오기 마법사를 통해 가져오기를 다시 만들어야 합니다.

** * Disconnect * – 중지, 완료 또는 실패한 가져오기 작업을 위해 소스 볼륨과 대상 볼륨 간의 관계를 끊으려면 * Disconnect * 를 선택합니다.



