---
permalink: upgrade-santricity/overview-upgrade-consider-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 스토리지 어레이의 SANtricity OS 컨트롤러 소프트웨어 및 펌웨어 및 드라이브 펌웨어에 대한 업그레이드 고려 사항을 검토합니다. 
---
= 업그레이드 고려 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성공적인 업그레이드를 위해 다음 업그레이드 고려 사항을 검토하십시오.



== 컨트롤러 업그레이드(단일 또는 다중)

컨트롤러를 업그레이드하기 전에 이러한 주요 고려 사항을 검토하십시오.



=== 현재 버전

다음과 같이 소프트웨어 및 펌웨어의 현재 버전을 볼 수 있습니다.

* 단일 컨트롤러의 경우 SANtricity 시스템 관리자 인터페이스를 사용합니다. 지원 [업그레이드 센터] 메뉴로 이동한 다음 * 소프트웨어 및 펌웨어 인벤토리 * 링크를 클릭합니다.
* 여러 컨트롤러의 경우 SANtricity Unified Manager 인터페이스를 사용합니다. 검색된 스토리지 배열에 대한 * 관리 * 페이지로 이동합니다. 버전은 * SANtricity OS 소프트웨어 * 열에 표시됩니다. 각 행에서 SANtricity OS 버전을 클릭하면 컨트롤러 펌웨어 및 NVSRAM 정보를 팝업 대화 상자에서 사용할 수 있습니다.




=== 업그레이드에 포함된 구성 요소

SANtricity OS 업그레이드 프로세스에는 다음과 같은 구성 요소가 포함됩니다.

* * System Manager * -- System Manager는 스토리지 어레이를 관리하는 소프트웨어입니다.
* * 컨트롤러 펌웨어 * -- 컨트롤러 펌웨어는 호스트와 볼륨 간의 I/O를 관리합니다.
* * IOM 펌웨어 * -- I/O 모듈(IOM) 펌웨어는 컨트롤러와 드라이브 쉘프 간의 연결을 관리합니다. 또한 구성 요소의 상태를 모니터링합니다.
* * Supervisor 소프트웨어 * -- Supervisor 소프트웨어는 소프트웨어가 실행되는 컨트롤러의 가상 머신입니다.




=== 별도로 업그레이드할 구성 요소입니다

다음 구성 요소는 별도로 업그레이드해야 합니다.

* * 컨트롤러 NVSRAM * -- 컨트롤러 NVSRAM은 컨트롤러의 기본 설정을 지정하는 컨트롤러 파일입니다. NVSRAM 업그레이드 지침은 컨트롤러 업그레이드 지침과 함께 제공됩니다.
* * 드라이브 펌웨어 * -- 참조 link:upgrade-drive-firmware-task.html["드라이브 펌웨어를 업그레이드합니다"] 을 참조하십시오.
* * 다중 경로/장애 조치 드라이버 * -- 업그레이드 프로세스의 일부로 호스트의 다중 경로/장애 조치 드라이버도 업그레이드해야 호스트가 컨트롤러와 올바르게 상호 작용할 수 있습니다. Microsoft Windows 이외의 운영 체제를 실행하는 호스트에서 스토리지 시스템에 대한 I/O 연결이 있으면 해당 호스트의 다중 경로 드라이버를 업그레이드합니다. 호환성 정보는 을 참조하십시오 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성 매트릭스"^]. 업그레이드 지침은 을 참조하십시오 link:../config-linux/index.html["Linux Express 구성"], link:../config-windows/index.html["Windows Express 구성"], 또는 link:../config-vmware/index.html["VMware Express 구성"].
* * SANtricity Unified Manager * -- Unified Manager는 E4000, E2800, E5700, EF300, EF600 모델을 포함한 여러 스토리지 시스템을 관리하는 소프트웨어입니다. Unified Manager는 SANtricity 웹 서비스 프록시의 일부로, 호스트 시스템에 별도로 설치되는 RESTful API 서버로, 수백 개의 새로운 기존 NetApp E-Series 스토리지 시스템을 관리합니다. 자세한 내용은 을 link:../web-services-proxy/index.html["SANtricity 웹 서비스 프록시 개요"]참조하십시오.
* 유틸리티* -- 다른 관리 유틸리티는 SANtricity Windows 호스트 유틸리티, SANtricity Linux 호스트 유틸리티 및 SANtricity Windows DSM과 같은 별도의 업그레이드가 필요합니다. 이러한 유틸리티에 대한 자세한 내용은 를 참조하십시오 link:../config-linux/index.html["Linux Express 구성"], link:../config-windows/index.html["Windows Express 구성"], 또는 link:../config-vmware/index.html["VMware Express 구성"].
* * 레거시 시스템 * -- 스토리지 시스템이 이전 스토리지 시스템을 포함하는 스토리지 네트워크의 일부인 경우 기존 SANtricity 스토리지 관리자 엔터프라이즈 관리 창(EMW)을 사용하여 모든 스토리지 시스템에 대한 엔터프라이즈 보기를 제공해야 할 수 있습니다. 이 경우 SANtricity 스토리지 관리자의 최신 유지 관리 릴리스가 있는지 확인합니다.




=== 이중 컨트롤러 및 I/O 처리

스토리지 어레이에 2개의 컨트롤러가 포함되어 있고 다중 경로 드라이버가 설치되어 있는 경우, 업그레이드가 진행되는 동안 스토리지 어레이에서 I/O를 계속 처리할 수 있습니다. 업그레이드 중에 다음 프로세스가 발생합니다.

. 컨트롤러 A는 모든 LUN을 컨트롤러 B로 페일오버합니다
. 컨트롤러 A에서 업그레이드가 발생합니다
. 컨트롤러 A는 LUN과 모든 컨트롤러 B의 LUN을 백업합니다.
. 컨트롤러 B에서 업그레이드가 발생합니다


업그레이드가 완료된 후 컨트롤러 간에 볼륨을 수동으로 재배포하여 볼륨이 올바른 소유 컨트롤러로 돌아가도록 해야 할 수 있습니다.



=== 상태 점검

상태 점검은 업그레이드 프로세스의 일부로 실행됩니다. 이 상태 점검을 통해 모든 스토리지 시스템 구성 요소를 평가하여 업그레이드를 진행할 수 있는지 확인합니다. 다음 조건에서는 업그레이드가 되지 않을 수 있습니다.

* 할당된 드라이브에 오류가 발생했습니다
* 핫 스페어가 사용 중입니다
* 볼륨 그룹이 불완전합니다
* 단독 운영 실행 중
* 볼륨이 누락되었습니다
* 컨트롤러가 최적화되지 않은 상태입니다
* 이벤트 로그 이벤트의 수가 너무 넘습니다
* 구성 데이터베이스 유효성 검사에 실패했습니다
* DACstore의 이전 버전이 있는 드라이브입니다


업그레이드를 수행하지 않고 업그레이드 전 상태 점검을 별도로 실행할 수도 있습니다.



=== 즉시 또는 단계별 업그레이드

업그레이드를 즉시 활성화하거나 나중에 스테이징할 수 있습니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.

* * 시간 * -- 소프트웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 부하가 더 가벼워질 때까지 기다려야 할 수 있습니다. I/O 로드 및 캐시 크기에 따라 컨트롤러 업그레이드를 완료하는 데 일반적으로 15~25분 정도 걸릴 수 있습니다. 활성화 중에 컨트롤러가 재부팅되고 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
* * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.




== 드라이브 펌웨어의 업그레이드

드라이브 펌웨어를 업그레이드하기 전에 이러한 주요 고려 사항을 검토하십시오.



=== 드라이브 호환성

각 드라이브 펌웨어 파일에는 펌웨어가 실행되는 드라이브 유형에 대한 정보가 들어 있습니다. 지정된 펌웨어 파일은 호환되는 드라이브에만 다운로드할 수 있습니다. System Manager는 업그레이드 프로세스 중에 호환성을 자동으로 확인합니다.



=== 드라이브 업그레이드 방법

드라이브 펌웨어의 업그레이드 방법에는 온라인 및 오프라인 두 가지가 있습니다.

|===
| 온라인 업그레이드 | 오프라인 업그레이드 


 a| 
온라인 업그레이드 중에 드라이브는 한 번에 하나씩 순차적으로 업그레이드됩니다. 스토리지 시스템은 업그레이드가 진행되는 동안 입출력을 계속 처리합니다. I/O를 중지할 필요가 없습니다 드라이브에서 온라인 업그레이드를 수행할 수 있는 경우 온라인 방법이 자동으로 사용됩니다.

온라인 업그레이드를 수행할 수 있는 드라이브는 다음과 같습니다.

* 드라이브가 최적의 풀에 있을 때
* 최적의 중복 볼륨 그룹의 드라이브(RAID 1, RAID 5 및 RAID 6)
* 할당되지 않은 드라이브
* 대기 핫 스페어 드라이브


드라이브 펌웨어의 온라인 업그레이드를 수행하는 데 몇 시간이 걸릴 수 있으며, 스토리지 어레이가 잠재적인 볼륨 장애에 노출될 수 있습니다. 다음과 같은 경우 볼륨 장애가 발생할 수 있습니다.

* RAID 1 또는 RAID 5 볼륨 그룹에서 볼륨 그룹의 다른 드라이브가 업그레이드되는 동안 하나의 드라이브에 장애가 발생합니다.
* RAID 6 풀 또는 볼륨 그룹에서 풀 또는 볼륨 그룹의 다른 드라이브가 업그레이드되는 동안 두 개의 드라이브에 장애가 발생합니다.

 a| 
오프라인 업그레이드 중에 동일한 드라이브 유형의 모든 드라이브가 동시에 업그레이드됩니다. 이 방법을 사용하려면 선택한 드라이브와 연결된 볼륨에 대한 I/O 작업을 중단해야 합니다. 여러 드라이브를 동시에 업그레이드할 수 있으므로(병렬로) 전체 다운타임이 크게 줄어듭니다. 드라이브에서 오프라인 업그레이드만 수행할 수 있는 경우 오프라인 방법이 자동으로 사용됩니다.

다음 드라이브는 오프라인 방법을 사용해야 합니다.

* 비중복 볼륨 그룹의 드라이브(RAID 0)
* 최적화되지 않은 풀 또는 볼륨 그룹의 드라이브입니다
* SSD 캐시 내 드라이브


|===