---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 드라이브의 펌웨어를 업그레이드하여 최신 기능 및 버그 수정 사항이 모두 있는지 확인합니다. 
---
= 드라이브 펌웨어를 업그레이드합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브의 펌웨어를 업그레이드하려면 다음 절차를 따르십시오. 최신 기능과 수정 사항이 모두 포함됩니다.



== 1단계: 드라이브 펌웨어 파일을 다운로드합니다

이 단계에서는 NetApp Support 사이트로 이동하여 드라이브 펌웨어 파일을 관리 클라이언트에 다운로드합니다.

.단계
. SANtricity 시스템 관리자에서 지원 [업그레이드 센터] 메뉴를 선택합니다.
. 드라이브 펌웨어 업그레이드 에서 * NetApp Support * 를 클릭하고 NetApp Support 사이트에 로그인합니다.
. 지원 사이트에서 * 다운로드 * 탭을 클릭한 다음 * 디스크 드라이브 및 펌웨어 매트릭스 * 를 선택합니다.
. E-Series 및 EF-Series 디스크 펌웨어 * 를 선택합니다
. 화면의 지시에 따라 파일을 다운로드합니다.




== 2단계: 드라이브 펌웨어 업그레이드를 시작합니다

이 단계에서는 드라이브의 펌웨어를 업그레이드합니다.

.시작하기 전에
* 디스크 간 백업, 볼륨 복사(계획된 펌웨어 업그레이드의 영향을 받지 않는 볼륨 그룹에) 또는 원격 미러를 사용하여 데이터를 백업합니다.
* 스토리지 배열이 Optimal(최적) 상태인지 확인합니다.
* 모든 드라이브가 최적의 상태인지 확인합니다.
* 스토리지 배열에서 구성 변경이 실행되고 있지 않은지 확인합니다.
* 드라이브가 오프라인 업그레이드만 가능한 경우 드라이브와 연결된 모든 볼륨에 대한 I/O 작업이 중지된다는 점을 이해해야 합니다.


.단계
. System Manager Upgrade Center(메뉴: 지원 [업그레이드 센터])의 "드라이브 펌웨어 업그레이드" 섹션에서 * 업그레이드 시작 * 을 클릭합니다.
+
현재 사용 중인 드라이브 펌웨어 파일이 나열된 대화 상자가 나타납니다.

. 지원 사이트에서 다운로드한 파일의 압축을 풉니다.
. 찾아보기 * 를 클릭하고 Support 사이트에서 다운로드한 새 드라이브 펌웨어 파일을 선택합니다.
+
드라이브 펌웨어 파일의 파일 이름은 D_HUC1012CSS600_30602291_MS01_2800_0002와 유사하며 확장명은 .DLP입니다.

+
한 번에 하나씩 최대 4개의 드라이브 펌웨어 파일을 선택할 수 있습니다. 둘 이상의 드라이브 펌웨어 파일이 동일한 드라이브와 호환되는 경우 파일 충돌 오류가 발생합니다. 업그레이드에 사용할 드라이브 펌웨어 파일을 결정하고 다른 드라이브 펌웨어 파일을 제거합니다.

. 다음 * 을 클릭합니다.
+
선택한 파일로 업그레이드할 수 있는 드라이브가 나열된 드라이브 선택 대화 상자가 나타납니다.

+
호환되는 드라이브만 나타납니다.

+
선택한 드라이브의 펌웨어가 * 제안된 펌웨어 * 정보 영역에 나타납니다. 펌웨어를 변경해야 하는 경우 * Back * 을 클릭하여 이전 대화 상자로 돌아갑니다.

. 수행할 업그레이드 유형을 선택합니다.
+
** * 온라인(기본값) * -- 스토리지 어레이가 I/O_를 처리하는 동안 펌웨어 다운로드를 지원할 수 있는 드라이브를 표시합니다. 이 업그레이드 방법을 선택할 때 이러한 드라이브를 사용하여 연결된 볼륨에 대한 I/O를 중지할 필요가 없습니다. 이러한 드라이브는 스토리지 어레이가 해당 드라이브에 대한 I/O를 처리하는 동안 한 번에 하나씩 업그레이드됩니다.
** * 오프라인(병렬) * -- 드라이브를 사용하는 볼륨에서 모든 I/O 작업이 중지되는 동안 펌웨어 다운로드를 지원할 수 있는 드라이브를 표시합니다. 이 업그레이드 방법을 선택할 때 업그레이드 중인 드라이브를 사용하는 모든 볼륨에서 모든 I/O 작업을 중지해야 합니다. 중복성이 없는 드라이브는 오프라인 작업으로 처리해야 합니다. 이 요구사항에는 SSD 캐시와 연결된 드라이브, RAID 0 볼륨 그룹 또는 성능이 저하된 풀 또는 볼륨 그룹이 포함됩니다. 오프라인(병렬) 업그레이드는 일반적으로 온라인(기본) 방법보다 빠릅니다.


. 테이블의 첫 번째 열에서 업그레이드할 드라이브를 선택합니다.
. 시작 * 을 클릭하고 작업을 수행할지 확인합니다.
+
업그레이드를 중지해야 하는 경우 * Stop * (중지 *)을 클릭합니다. 현재 진행 중인 모든 펌웨어 다운로드가 완료되었습니다. 시작되지 않은 모든 펌웨어 다운로드는 취소됩니다.

+

CAUTION: 드라이브 펌웨어 업그레이드를 중지하면 데이터가 손실되거나 드라이브를 사용할 수 없게 될 수 있습니다.

. (선택 사항) 업그레이드된 항목 목록을 보려면 * 로그 저장 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 drive_upgrade_log-timestamp.txt라는 이름으로 저장됩니다.

. 업그레이드 절차 중에 다음 오류가 발생하는 경우 적절한 권장 조치를 취하십시오.
+
|===
| 이 펌웨어 다운로드 오류가 발생하는 경우... | 그런 다음 다음을 수행합니다. 


 a| 
** 할당된 드라이브에 오류가 발생했습니다

 a| 
이 오류가 발생하는 한 가지 이유는 드라이브에 적절한 서명이 없을 수 있기 때문입니다. 영향을 받는 드라이브가 승인된 드라이브인지 확인합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.

드라이브를 교체할 때 교체 드라이브의 용량이 교체 중인 드라이브의 용량보다 크거나 같은지 확인하십시오.

스토리지 배열이 I/O를 수신하는 동안 오류가 발생한 드라이브를 교체할 수 있습니다



 a| 
스토리지 배열을 확인합니다
 a| 
** 각 컨트롤러에 IP 주소가 할당되었는지 확인합니다.
** 컨트롤러에 연결된 모든 케이블이 손상되지 않았는지 확인합니다.
** 모든 케이블이 단단히 연결되어 있는지 확인합니다.




 a| 
내장형 핫 스페어 드라이브
 a| 
펌웨어를 업그레이드하기 전에 이 오류 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
볼륨 그룹이 불완전합니다
 a| 
하나 이상의 볼륨 그룹 또는 디스크 풀이 불완전하면 펌웨어를 업그레이드하기 전에 이 오류 조건을 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
현재 모든 볼륨 그룹에서 실행 중인 단독 작업(백그라운드 미디어/패리티 검사 제외
 a| 
하나 이상의 배타적 작업이 진행 중인 경우 펌웨어를 업그레이드하기 전에 작업을 완료해야 합니다. System Manager를 사용하여 작업 진행률을 모니터링합니다.



 a| 
볼륨이 누락되었습니다
 a| 
펌웨어를 업그레이드하기 전에 누락된 볼륨 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
두 컨트롤러 중 하나가 Optimal(최적) 이외의 상태입니다
 a| 
스토리지 어레이 컨트롤러 중 하나에 주의가 필요합니다. 펌웨어를 업그레이드하기 전에 이 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
컨트롤러 오브젝트 그래프 간에 스토리지 파티션 정보가 일치하지 않습니다
 a| 
컨트롤러의 데이터를 검증하는 동안 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
SPM 데이터베이스 컨트롤러 확인 실패
 a| 
컨트롤러에서 스토리지 파티션 매핑 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
구성 데이터베이스 유효성 검사(스토리지 배열의 컨트롤러 버전에서 지원되는 경우)
 a| 
컨트롤러에서 구성 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
Mel 관련 검사
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 10개 이상의 DDE 정보 또는 중요 MEL 이벤트가 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 2개 이상의 2c 페이지 주요 MEL 이벤트가 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
최근 7일 동안 성능이 저하된 드라이브 채널 중요 MEL 이벤트가 2개 이상 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 4개 이상의 중요한 MEL 항목이 있습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

|===


드라이브 펌웨어 업그레이드가 완료되었습니다. 일반 작업을 다시 시작할 수 있습니다.
