---
permalink: upgrade-santricity/upgrade-multiple-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: SANtricity Unified Manager를 사용하여 동일한 유형의 여러 스토리지 어레이에서 SANtricity OS 소프트웨어를 업그레이드할 수 있습니다. 
---
= 여러 컨트롤러의 소프트웨어 및 펌웨어를 업그레이드합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Manager를 사용하면 같은 유형의 여러 컨트롤러를 업그레이드할 수 있습니다.

.시작하기 전에
* 검토 link:overview-upgrade-consider-task.html["업그레이드 고려 사항"].
* 소프트웨어 업그레이드를 지금 또는 나중에 활성화할지 결정합니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.
+
** * 시간 * -- 소프트웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 부하가 더 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 OS 소프트웨어를 테스트할 수 있습니다.


* 다음 예방 조치를 검토하십시오.



CAUTION: 데이터 손실 또는 스토리지 어레이 손상 위험 - 업그레이드가 진행되는 동안 스토리지 어레이를 변경하지 마십시오. 스토리지 어레이에 대한 전원을 유지합니다.


CAUTION: SG5612 또는 SG5760과 같이 StorageGRID 어플라이언스에서 SANtricity OS를 업그레이드하는 경우, 이 절차를 계속하기 전에 어플라이언스를 유지보수 모드로 전환하여 I/O 활동을 중지해야 합니다. 그렇지 않으면 데이터가 손실될 수 있습니다. 자세한 단계는 StorageGRID 어플라이언스의 설치 및 유지보수 지침을 참조하십시오.



== 1단계: 업그레이드 전 상태 점검을 수행합니다

상태 점검은 업그레이드 프로세스의 일부로 실행되지만 시작하기 전에 상태 점검을 별도로 실행할 수도 있습니다. 상태 점검을 통해 스토리지 시스템의 구성 요소를 평가하여 업그레이드를 진행할 수 있는지 확인합니다.

.단계
. Unified Manager를 엽니다.
. 기본 보기에서 * 관리 * 를 선택한 다음 메뉴: 업그레이드 센터 [업그레이드 전 상태 점검] 을 선택합니다.
+
업그레이드 전 상태 점검 대화 상자가 열리고 검색된 모든 스토리지 시스템이 나열됩니다.

. 필요한 경우 현재 최적의 상태가 아닌 모든 시스템을 볼 수 있도록 목록에서 스토리지 시스템을 필터링하거나 정렬합니다.
. 상태 점검을 통해 실행할 스토리지 시스템의 확인란을 선택합니다.
. 시작 * 을 클릭합니다.
+
상태 점검이 수행되는 동안 대화 상자에 진행 상황이 표시됩니다.

. 상태 점검이 완료되면 각 행의 오른쪽에 있는 줄임표(...)를 클릭하여 추가 정보를 보고 다른 작업을 수행할 수 있습니다.
+

NOTE: 상태 확인에 실패한 어레이가 있으면 해당 특정 어레이를 건너뛰고 다른 어레이를 계속 업그레이드할 수 있습니다. 또는 전체 프로세스를 중지하고 통과하지 못한 어레이의 문제를 해결할 수 있습니다.





== 2단계: 지원 사이트에서 소프트웨어 파일을 다운로드합니다

이 단계에서는 NetApp Support 사이트로 이동하여 새로운 다운로드 가능한 패키지(DLP) 소프트웨어 파일을 관리 호스트 시스템에 저장합니다.

.단계
. 스토리지 어레이에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버를 사용하지 않는 경우 스토리지 어레이에 대한 I/O 작업을 중지하여 응용 프로그램 오류를 방지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.
. Unified Manager의 기본 보기에서 * 관리 * 를 선택한 다음 업그레이드할 스토리지 어레이를 하나 이상 선택합니다.
. 메뉴: 업그레이드 센터 [SANtricity OS 소프트웨어 업그레이드]를 선택합니다.
+
SANtricity OS 소프트웨어 업그레이드 페이지가 나타납니다.

. NetApp Support 사이트에서 로컬 시스템으로 최신 SANtricity OS 소프트웨어 패키지를 다운로드하십시오.
+
.. 소프트웨어 리포지토리에 새 파일 추가 * 를 클릭합니다.
.. 최신 * SANtricity OS 다운로드 * 를 찾는 링크를 클릭합니다.
.. 최신 릴리스 다운로드 * 링크를 클릭합니다.
.. 나머지 지침에 따라 SANtricity OS 파일 및 NVSRAM 파일을 로컬 컴퓨터에 다운로드합니다.


+

NOTE: 버전 8.42 이상에서는 디지털 서명된 펌웨어가 필요합니다. 서명되지 않은 펌웨어를 다운로드하려고 하면 오류가 표시되고 다운로드가 중단됩니다.





== 3단계: 소프트웨어 파일을 컨트롤러로 전송합니다

SANtricity OS 소프트웨어 파일과 NVSRAM 파일을 리포지토리로 로드하면 Unified Manager 업그레이드 센터에서 액세스할 수 있습니다.


CAUTION: 데이터 손실 또는 스토리지 어레이 손상 위험 - 업그레이드가 진행되는 동안 스토리지 어레이를 변경하지 마십시오. 스토리지 어레이에 대한 전원을 유지합니다.

.단계
. Unified Manager의 기본 보기에서 * 관리 * 를 선택한 다음 업그레이드할 스토리지 어레이를 하나 이상 선택합니다.
. 메뉴: 업그레이드 센터 [SANtricity OS 소프트웨어 업그레이드]를 선택합니다.
+
SANtricity OS 소프트웨어 업그레이드 페이지가 나타납니다.

. NetApp Support 사이트에서 로컬 시스템으로 최신 SANtricity OS 소프트웨어 패키지를 다운로드하십시오.
+
.. 소프트웨어 리포지토리에 새 파일 추가 * 를 클릭합니다.
.. 최신 * SANtricity OS 다운로드 * 를 찾는 링크를 클릭합니다.
.. 최신 릴리스 다운로드 * 링크를 클릭합니다.
.. 나머지 지침에 따라 SANtricity OS 파일 및 NVSRAM 파일을 로컬 컴퓨터에 다운로드합니다.


+

NOTE: 버전 8.42 이상에서는 디지털 서명된 펌웨어가 필요합니다. 서명되지 않은 펌웨어를 다운로드하려고 하면 오류가 표시되고 다운로드가 중단됩니다.

. 컨트롤러를 업그레이드하는 데 사용할 OS 소프트웨어 파일과 NVSRAM 파일을 선택합니다.
+
.. SANtricity OS 소프트웨어 파일 선택 * 드롭다운에서 로컬 컴퓨터에 다운로드한 OS 파일을 선택합니다.
+
여러 개의 파일을 사용할 수 있는 경우 파일이 최신 날짜부터 가장 오래된 날짜순으로 정렬됩니다.

+

NOTE: 소프트웨어 리포지토리는 웹 서비스 프록시와 연결된 모든 소프트웨어 파일을 나열합니다. 사용할 파일이 표시되지 않으면 * 소프트웨어 리포지토리에 새 파일 추가 * 링크를 클릭하여 추가할 OS 파일이 있는 위치를 찾을 수 있습니다.

.. NVSRAM 파일 선택 * 드롭다운에서 사용할 컨트롤러 파일을 선택합니다.
+
파일이 여러 개 있는 경우 파일이 최신 날짜부터 가장 오래된 날짜순으로 정렬됩니다.



. Compatible Storage Array 표에서 선택한 OS 소프트웨어 파일과 호환되는 스토리지 배열을 검토한 다음 업그레이드할 스토리지를 선택합니다.
+
** 관리 보기에서 선택했으며 선택한 펌웨어 파일과 호환되는 스토리지 배열은 기본적으로 호환 가능한 스토리지 배열 테이블에서 선택됩니다.
** 선택한 펌웨어 파일로 업데이트할 수 없는 스토리지 배열은 * 호환되지 않음 * 상태로 표시된 호환 가능한 스토리지 배열 테이블에서 선택할 수 없습니다.


. (선택 사항) 소프트웨어 파일을 활성화하지 않고 스토리지 어레이로 전송하려면 * OS 소프트웨어를 스토리지 어레이로 전송, 스테이징으로 표시 및 나중에 활성화 * 확인란을 선택합니다.
. 시작 * 을 클릭합니다.
. 지금 활성화할지 아니면 나중에 활성화할지 여부에 따라 다음 중 하나를 수행합니다.
+
** 업그레이드하려는 어레이에서 제안된 OS 소프트웨어 버전을 전송할지 확인하려면 * TRANSFER * 를 입력하고 * TRANSFER * 를 클릭합니다.
+
전송된 소프트웨어를 활성화하려면 업그레이드 센터 [스테이징된 OS 소프트웨어 활성화] 메뉴를 선택합니다.

** 업그레이드 * 를 입력하여 업그레이드하도록 선택한 어레이에서 제안된 OS 소프트웨어 버전을 전송 및 활성화한 다음 * 업그레이드 * 를 클릭합니다.
+
시스템은 업그레이드를 위해 선택한 각 스토리지 어레이로 소프트웨어 파일을 전송한 다음 재부팅을 시작하여 해당 파일을 활성화합니다.



+
업그레이드 작업 중에 다음 작업이 수행됩니다.

+
** 업그레이드 전 상태 점검이 업그레이드 프로세스의 일부로 실행됩니다. 업그레이드 전 상태 점검을 통해 모든 스토리지 시스템 구성 요소를 평가하여 업그레이드를 진행할 수 있는지 확인합니다.
** 스토리지 배열에 대한 상태 검사에 실패하면 업그레이드가 중지됩니다. 줄임표(...)를 클릭하고 * 로그 저장 * 을 선택하여 오류를 검토할 수 있습니다. 상태 점검 오류를 재정의하도록 선택한 다음 * 계속 * 을 클릭하여 업그레이드를 진행할 수도 있습니다.
** 업그레이드 전 상태 점검 후 업그레이드 작업을 취소할 수 있습니다.


. (선택 사항) 업그레이드가 완료되면 줄임표(...)를 클릭한 다음 * Save Log * 를 선택하여 특정 스토리지 배열에 대해 업그레이드된 항목 목록을 볼 수 있습니다.
+
이 파일은 브라우저의 다운로드 폴더에 ''upgrade_log-<date>.json''이라는 이름으로 저장됩니다.





== 4단계: 스테이징된 소프트웨어 파일 활성화(선택 사항)

소프트웨어 파일을 즉시 활성화하거나 더 편리한 시간이 될 때까지 기다릴 수 있습니다. 이 절차에서는 나중에 소프트웨어 파일을 활성화하도록 선택한 것으로 가정합니다.


NOTE: 활성화 프로세스가 시작된 후에는 중지할 수 없습니다.

.단계
. Unified Manager의 기본 보기에서 * 관리 * 를 선택합니다. 필요한 경우 Status 열을 클릭하여 "OS Upgrade(활성화 대기 중)" 상태의 모든 스토리지 어레이를 정렬합니다.
. 소프트웨어를 활성화할 스토리지 어레이를 하나 이상 선택한 다음 메뉴: 업그레이드 센터 [스테이징된 OS 소프트웨어 활성화] 를 선택합니다.
+
업그레이드 작업 중에 다음 작업이 수행됩니다.

+
** 업그레이드 전 상태 점검이 활성화 프로세스의 일부로 실행됩니다. 업그레이드 전 상태 점검을 통해 모든 스토리지 시스템 구성 요소를 평가하여 활성화를 진행할 수 있는지 확인합니다.
** 스토리지 배열에 대한 상태 검사에 실패하면 활성화가 중지됩니다. 줄임표(...)를 클릭하고 * 로그 저장 * 을 선택하여 오류를 검토할 수 있습니다. 상태 점검 오류를 재정의하도록 선택한 다음 * 계속 * 을 클릭하여 활성화를 계속 진행할 수도 있습니다.
** 업그레이드 전 상태 점검 후 활성화 작업을 취소할 수 있습니다. 업그레이드 전 상태 점검이 성공적으로 완료되면 활성화가 발생합니다. 활성화하는 데 걸리는 시간은 스토리지 배열 구성과 활성화 중인 구성 요소에 따라 달라집니다.


. (선택 사항) 활성화가 완료된 후 줄임표(...)를 클릭한 다음 * Save Log * 를 선택하여 특정 스토리지 배열에 대해 활성화된 항목 목록을 볼 수 있습니다.
+
파일은 브라우저의 다운로드 폴더에 "activate_log-<date>.json"이라는 이름으로 저장됩니다.



컨트롤러 소프트웨어 업그레이드가 완료되었습니다. 일반 작업을 다시 시작할 수 있습니다.
