---
permalink: upgrade-santricity/upgrade-single-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 단일 E-Series 컨트롤러의 소프트웨어 및 펌웨어 업그레이드 
---
= 단일 컨트롤러의 소프트웨어 및 펌웨어를 업그레이드합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 컨트롤러를 업그레이드하여 최신 기능 및 수정 사항을 모두 유지할 수 있습니다.

이 프로세스에는 스토리지 어레이의 소프트웨어와 IOM 펌웨어 및 NVSRAM(Nonvolatile Static Random Access Memory)을 업그레이드할 수 있습니다(선택 사항).

.시작하기 전에
* 검토 link:overview-upgrade-consider-task.html["업그레이드 고려 사항"].
* 컨트롤러 NVSRAM 파일을 OS 펌웨어와 동시에 업그레이드할지 결정합니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 그러나 파일이 패치되었거나 사용자 정의 버전이고 덮어쓰지 않으려는 경우 컨트롤러 NVSRAM 파일을 업그레이드하지 않을 수 있습니다.

* IOM 펌웨어를 업그레이드할지 여부를 확인합니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 하지만 SANtricity OS 소프트웨어 업그레이드의 일부로 업그레이드하지 않으려는 경우 또는 기술 지원 부서에서 IOM 펌웨어를 다운그레이드하도록 지시한 경우(명령줄 인터페이스를 사용하여 펌웨어를 다운그레이드할 수만 있음) IOM 펌웨어를 업그레이드하지 않을 수도 있습니다.

* 지금 또는 나중에 OS 업그레이드를 활성화할지 결정합니다.
+
나중에 활성화하는 이유는 다음과 같습니다.

+
** * 시간 * – 소프트웨어 및 펌웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 로드가 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * – 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.






== 1단계: 지원 사이트에서 소프트웨어 파일을 다운로드합니다

이 단계에서는 NetApp Support 사이트로 이동하여 새로운 다운로드 가능한 패키지(DLP) 소프트웨어 파일을 관리 호스트 시스템에 저장합니다.

업그레이드에 필요한 시간은 스토리지 시스템 구성과 업그레이드 중인 구성 요소에 따라 달라집니다.

.단계
. 스토리지 배열에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버가 설치되어 있지 않은 경우, 어플리케이션 오류를 방지하기 위해 스토리지 배열에 대한 I/O 작업을 중지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.
+

CAUTION: SG5612 또는 SG5760과 같이 StorageGRID 어플라이언스에서 SANtricity OS를 업그레이드하는 경우, 이 절차를 계속하기 전에 어플라이언스를 유지보수 모드로 전환하여 I/O 활동을 중지해야 합니다. 그렇지 않으면 데이터가 손실될 수 있습니다. 자세한 단계는 StorageGRID 어플라이언스의 설치 및 유지보수 지침을 참조하십시오.

. System Manager 인터페이스에서 지원 [업그레이드 센터] 메뉴를 선택합니다.
. "SANtricity OS 소프트웨어 업그레이드" 영역에서 * NetApp SANtricity OS 다운로드 * 를 클릭하여 NetApp Support 사이트를 엽니다.
. 다운로드 페이지에서 * E-Series SANtricity OS 컨트롤러 소프트웨어 * 를 선택합니다.
+

NOTE: 버전 8.42 이상에서는 디지털 서명된 펌웨어가 필요합니다. 서명되지 않은 펌웨어를 다운로드하려고 하면 오류가 표시되고 다운로드가 중단됩니다.

. 화면의 지시에 따라 사용 중인 컨트롤러 모델에 맞는 최신 OS 소프트웨어를 다운로드합니다. NVSRAM을 업그레이드하려면 단일 컨트롤러에 대한 NVSRAM 파일을 다운로드하십시오.




== 2단계: 소프트웨어 파일을 컨트롤러로 전송합니다

이 단계에서는 소프트웨어 파일을 컨트롤러로 전송하여 업그레이드 프로세스를 시작할 수 있습니다. 이 구성 요소는 관리 클라이언트에서 컨트롤러로 복사되고 플래시 메모리의 스테이징 영역에 배치됩니다.


CAUTION: * 데이터 손실 또는 스토리지 배열 손상 위험 * -- 업그레이드 중에 스토리지 배열을 변경하지 마십시오. 스토리지 어레이에 대한 전원을 유지합니다.

.단계
. (선택 사항). 특정 유지 관리 기간 동안 업그레이드를 수행하려는 경우 업그레이드 전 상태 점검을 실행하여 주요 스토리지 어레이 문제가 사전에 있는지 확인할 수 있습니다. 이 경우 System Manager의 Upgrade Center(메뉴: 지원 [업그레이드 센터])에서 * 업그레이드 전 상태 점검 * 을 선택하고 화면에 표시되는 지침을 따릅니다. 그렇지 않으면 상태 점검이 업그레이드 프로세스의 일부이므로 이 단계를 건너뛸 수 있습니다.
. 현재 IOM 펌웨어를 업그레이드하지 않으려면 * IOM 자동 동기화 일시 중지 * 를 클릭하고 대화 상자의 지침을 따릅니다.
+
단일 컨트롤러가 있는 스토리지 어레이를 사용하는 경우 IOM 펌웨어가 업그레이드되지 않습니다.

. 시스템 관리자의 업그레이드 센터에서 "SANtricity OS 소프트웨어 업그레이드"에서 * 업그레이드 시작 * 을 클릭합니다.
+
SANtricity OS 소프트웨어 업그레이드 대화 상자가 나타납니다.

. 업그레이드 프로세스를 시작하려면 하나 이상의 파일을 선택하십시오.
+
.. 찾아보기 * 를 클릭하고 지원 사이트에서 다운로드한 OS 소프트웨어 파일을 탐색하여 SANtricity OS 소프트웨어 파일을 선택합니다.
.. [찾아보기] * 를 클릭하고 지원 사이트에서 다운로드한 NVSRAM 파일로 이동하여 컨트롤러 NVSRAM 파일을 선택합니다. 컨트롤러 NVSRAM 파일의 파일 이름은 N2800-830000-000.DLP와 유사합니다.


+
이러한 작업은 다음과 같이 수행됩니다.

+
** 기본적으로 현재 스토리지 배열 구성과 호환되는 파일만 표시됩니다.
** 업그레이드할 파일을 선택하면 파일 이름과 크기가 나타납니다.


. (선택 사항) 업그레이드할 SANtricity OS 소프트웨어 파일을 선택한 경우 지금 파일 전송 * 확인란을 선택하여 활성화하지 않고 컨트롤러로 파일을 전송할 수 있습니다(나중에 업그레이드 활성화) * 확인란을 선택합니다.
. 시작 * 을 클릭하고 작업을 수행할지 확인합니다.
+
업그레이드 전 상태 점검 중에는 작업을 취소할 수 있지만 전송 또는 활성화 중에는 취소할 수 없습니다.

. (선택 사항) 업그레이드된 항목 목록을 보려면 * 로그 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 drive_upgrade_log-timestamp.txt라는 이름으로 저장됩니다.



소프트웨어 파일을 이미 활성화한 경우 로 이동합니다 <<4단계: 소프트웨어 및 펌웨어 업그레이드를 완료합니다>>그렇지 않으면 로 이동합니다 <<3단계: 소프트웨어 파일을 활성화합니다>>.



== 3단계: 소프트웨어 파일을 활성화합니다

이전되었지만 활성화되지 않은 소프트웨어 또는 펌웨어가 있는 경우에만 이 단계를 수행하십시오. 이 상태를 확인하려면 System Manager 홈 페이지 또는 업그레이드 센터 페이지의 알림 영역에서 알림을 찾습니다.

활성화 작업을 수행하면 현재 소프트웨어 및 펌웨어가 새 소프트웨어 및 펌웨어로 교체됩니다. 활성화 프로세스가 시작된 후에는 중지할 수 없습니다.

.단계
. System Manager 인터페이스에서 지원 [업그레이드 센터] 메뉴를 선택합니다.
. "SANtricity OS 소프트웨어 업그레이드" 영역에서 * 활성화 * 를 클릭하고 작업을 수행할지 확인합니다.
. (선택 사항) 업그레이드된 항목 목록을 보려면 * 로그 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 drive_upgrade_log-timestamp.txt라는 이름으로 저장됩니다.





== 4단계: 소프트웨어 및 펌웨어 업그레이드를 완료합니다

소프트웨어 및 펌웨어 인벤토리 대화 상자에서 버전을 확인하여 소프트웨어 및 펌웨어 업그레이드를 완료합니다.

.시작하기 전에
* 소프트웨어 또는 펌웨어를 활성화해야 합니다.


.단계
. System Manager에서 모든 구성 요소가 하드웨어 페이지에 나타나는지 확인합니다.
. 소프트웨어 및 펌웨어 인벤토리 대화 상자(지원 [업그레이드 센터] 메뉴로 이동한 다음 * 소프트웨어 및 펌웨어 인벤토리 * 링크를 클릭하여 소프트웨어 및 펌웨어 버전을 확인합니다.
. 컨트롤러 NVSRAM을 업그레이드한 경우 기존 NVSRAM에 적용한 모든 사용자 정의 설정은 활성화 과정 중에 손실됩니다. 활성화 프로세스가 완료된 후 NVSRAM에 사용자 정의 설정을 다시 적용해야 합니다.
. 업그레이드 절차 중에 다음 오류가 발생하는 경우 적절한 권장 조치를 취하십시오.
+
|===
| 이 펌웨어 다운로드 오류가 발생하는 경우... | 그런 다음 다음을 수행합니다. 


 a| 
할당된 드라이브에 오류가 발생했습니다
 a| 
이 오류가 발생하는 한 가지 이유는 드라이브에 적절한 서명이 없을 수 있기 때문입니다. 영향을 받는 드라이브가 승인된 드라이브인지 확인합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.

드라이브를 교체할 때 교체 드라이브의 용량이 교체 중인 드라이브의 용량보다 크거나 같은지 확인하십시오.

스토리지 배열이 I/O를 수신하는 동안 오류가 발생한 드라이브를 교체할 수 있습니다



 a| 
스토리지 배열을 확인합니다
 a| 
** 각 컨트롤러에 IP 주소가 할당되었는지 확인합니다.
** 컨트롤러에 연결된 모든 케이블이 손상되지 않았는지 확인합니다.
** 모든 케이블이 단단히 연결되어 있는지 확인합니다.




 a| 
내장형 핫 스페어 드라이브
 a| 
펌웨어를 업그레이드하기 전에 이 오류 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
볼륨 그룹이 불완전합니다
 a| 
하나 이상의 볼륨 그룹 또는 디스크 풀이 불완전하면 펌웨어를 업그레이드하기 전에 이 오류 조건을 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
현재 모든 볼륨 그룹에서 실행 중인 단독 작업(백그라운드 미디어/패리티 검사 제외
 a| 
하나 이상의 배타적 작업이 진행 중인 경우 펌웨어를 업그레이드하기 전에 작업을 완료해야 합니다. System Manager를 사용하여 작업 진행률을 모니터링합니다.



 a| 
볼륨이 누락되었습니다
 a| 
펌웨어를 업그레이드하기 전에 누락된 볼륨 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
두 컨트롤러 중 하나가 Optimal(최적) 이외의 상태입니다
 a| 
스토리지 어레이 컨트롤러 중 하나에 주의가 필요합니다. 펌웨어를 업그레이드하기 전에 이 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
컨트롤러 오브젝트 그래프 간에 스토리지 파티션 정보가 일치하지 않습니다
 a| 
컨트롤러의 데이터를 검증하는 동안 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
SPM 데이터베이스 컨트롤러 확인 실패
 a| 
컨트롤러에서 스토리지 파티션 매핑 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
구성 데이터베이스 유효성 검사(스토리지 배열의 컨트롤러 버전에서 지원되는 경우)
 a| 
컨트롤러에서 구성 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
Mel 관련 검사
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 10개 이상의 DDE 정보 또는 중요 MEL 이벤트가 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 2개 이상의 2c 페이지 주요 MEL 이벤트가 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
최근 7일 동안 성능이 저하된 드라이브 채널 중요 MEL 이벤트가 2개 이상 보고되었습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 4개 이상의 중요한 MEL 항목이 있습니다
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.

|===


.다음 단계
컨트롤러 소프트웨어 업그레이드가 완료되었습니다. 일반 작업을 다시 시작할 수 있습니다.
