---
permalink: web-services-proxy/array-intro-concept.html 
sidebar: sidebar 
keywords: Web Services, WSP, SANtricity API, discover storage WSP, 
summary: 네트워크에서 스토리지 시스템을 관리하려면 먼저 스토리지 시스템을 검색한 다음 관리 목록에 추가해야 합니다. 
---
= 웹 서비스 프록시를 사용하여 스토리지 시스템을 관리합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크에서 스토리지 시스템을 관리하려면 먼저 스토리지 시스템을 검색한 다음 관리 목록에 추가해야 합니다.



== 스토리지 시스템을 검색합니다

자동 검색을 설정하거나 스토리지 시스템을 수동으로 검색할 수 있습니다.



=== 스토리지 시스템을 자동으로 검색합니다

wsconfig.xml 파일의 설정을 수정하여 네트워크에서 스토리지 시스템이 자동으로 검색되도록 지정할 수 있습니다. 기본적으로 IPv6 자동 검색은 사용되지 않고 IPv4는 사용하도록 설정됩니다.

스토리지 시스템을 추가하려면 관리 IP 또는 DNS 주소를 하나만 제공하면 됩니다. 경로가 구성되어 있지 않거나 경로가 구성되어 있고 회전 가능한 경우 서버가 모든 관리 경로를 자동으로 검색합니다.


NOTE: 초기 접속이 이루어진 후 컨트롤러 구성에서 스토리지 시스템을 자동으로 검색하기 위해 IPv6 프로토콜을 사용하려고 하면 프로세스가 실패할 수 있습니다. 스토리지 시스템에서 IP 주소 전달 또는 IPv6를 사용하는 동안 문제가 발생했지만 서버에서 활성화되어 있지 않은 경우 이러한 오류가 발생할 수 있습니다.

.시작하기 전에
IPv6 검색 설정을 활성화하기 전에 스토리지 시스템에 대한 IPv6 연결을 지원하는 인프라가 모든 연결 문제를 완화하는지 확인하십시오.

.단계
. 다음 위치에 있는 wsconfig.xml 파일을 엽니다.
+
** (Windows) -- C:\Program Files\NetApp\SANtricity Web Services Proxy
** (Linux) --/opt/NetApp/SANtricity_web_services_proxy


. 자동 검색 문자열에서 원하는 대로 설정을 true에서 false로 변경합니다. 다음 예를 참조하십시오.
+
[listing]
----
<env key="autodiscover.ipv6.enable">true</env>
----
+

NOTE: 서버가 주소로 라우팅할 수 있도록 경로가 구성되었지만 구성되지 않은 경우 간헐적 연결 오류가 발생합니다. 호스트에서 IP 주소를 라우팅할 수 있도록 설정할 수 없는 경우 자동 검색을 해제합니다('false'로 설정 변경).

. 파일을 저장합니다.




=== API 엔드포인트를 사용하여 스토리지 시스템을 검색하고 추가합니다

API 엔드포인트를 사용하여 스토리지 시스템을 검색하고 관리 대상 목록에 추가할 수 있습니다. 이 절차를 수행하면 스토리지 시스템과 API 간에 관리 접속이 생성됩니다.


NOTE: 이 작업에서는 REST API를 사용하여 스토리지 시스템을 검색 및 추가하는 방법을 설명합니다. 그러면 대화형 API 설명서에서 이러한 시스템을 관리할 수 있습니다. 하지만 대신 사용하기 쉬운 인터페이스를 제공하는 Unified Manager에서 스토리지 시스템을 관리할 수 있습니다. 자세한 내용은 Unified Manager와 함께 제공되는 온라인 도움말을 참조하십시오.

.시작하기 전에
SANtricity 버전 11.30 이상이 있는 스토리지 시스템의 경우 SANtricity 시스템 관리자 인터페이스에서 기호에 대한 기존 관리 인터페이스를 활성화해야 합니다. 그렇지 않으면 검색 엔드포인트가 실패합니다. System Manager를 열고 설정 [시스템 > 추가 설정 > 관리 인터페이스 변경] 메뉴로 이동하여 이 설정을 찾을 수 있습니다.

.단계
. 에 로그인합니다 link:install-login-task.html["대화형 API 설명서"].
. 다음과 같이 스토리지 시스템을 검색합니다.
+
.. API 설명서의 드롭다운에서 * V2 * 를 선택한 다음 * Storage-Systems * 범주를 확장합니다.
.. POST:/discovery * 끝점을 클릭한 다음 * try it * 를 클릭합니다.
.. 표에 설명된 대로 매개 변수를 입력합니다.
+
|===


 a| 
시작 IP입니다

endIP
 a| 
네트워크에 있는 하나 이상의 스토리지 시스템에 대한 시작 및 끝 IP 주소 범위로 문자열을 바꿉니다.



 a| 
사용 에이전트
 a| 
이 값을 다음 중 하나로 설정합니다.

*** True = 네트워크 스캔에 대역내 에이전트를 사용합니다.
*** False = 네트워크 스캔에 대역내 에이전트를 사용하지 않습니다.




 a| 
연결 시간 초과
 a| 
연결 시간이 초과되기 전에 스캔에 허용되는 초를 입력합니다.



 a| 
maxPortsToUse 를 선택합니다
 a| 
네트워크 스캔에 사용되는 최대 포트 수를 입력합니다.

|===
.. Execute * 를 클릭합니다.
+

NOTE: API 작업은 사용자 프롬프트 없이 실행됩니다.

+
검색 프로세스는 백그라운드에서 실행됩니다.

.. 코드가 202를 반환하는지 확인합니다.
.. 응답 본문 * 에서 RequestId에 대해 반환된 값을 찾습니다. 다음 단계에서 결과를 보려면 요청 ID가 필요합니다.


. 다음과 같이 검색 결과를 봅니다.
+
.. get:/discovery * 끝점을 클릭한 다음 * try it out * 을 클릭합니다.
.. 이전 단계의 요청 ID를 입력합니다. 요청 ID * 를 비워 두면 끝점의 기본값은 마지막으로 실행된 요청 ID로 설정됩니다.
.. Execute * 를 클릭합니다.
.. 코드가 200을 반환하는지 확인합니다.
.. 응답 본문에서 요청 ID와 storageSystems의 문자열을 찾습니다. 문자열은 다음 예제와 비슷합니다.
+
[listing]
----
"storageSystems": [
    {
      "serialNumber": "123456789",
      "wwn": "000A011000AF0000000000001A0C000E",
      "label": "EF570_Array",
      "firmware": "08.41.10.01",
      "nvsram": "N5700-841834-001",
      "ipAddresses": [
        "10.xxx.xx.213",
        "10.xxx.xx.214"
      ],
----
.. WWN, 레이블 및 IP 주소 값을 기록합니다. 다음 단계를 위해 필요한 것입니다.


. 다음과 같이 스토리지 시스템을 추가합니다.
+
.. POST:/storage-system* 끝점을 클릭한 다음 * try it out * 을 클릭합니다.
.. 표에 설명된 대로 매개 변수를 입력합니다.
+
|===


 a| 
ID입니다
 a| 
이 스토리지 시스템의 고유한 이름을 입력하십시오. 레이블(GET:/DISCOVERY의 응답에 표시됨)을 입력할 수 있지만 이름은 사용자가 선택한 문자열이 될 수 있습니다. 이 필드에 값을 제공하지 않으면 웹 서비스에서 자동으로 고유 식별자를 할당합니다.



 a| 
제어 주소
 a| 
GET:/DISCOVERY 응답에 표시된 IP 주소를 입력합니다. 이중 컨트롤러의 경우 IP 주소를 쉼표로 구분합니다. 예를 들면 다음과 같습니다.

""IP 주소 1", "IP 주소 2""



 a| 
검증
 a| 
"true"를 입력하면 웹 서비스가 스토리지 시스템에 연결될 수 있다는 확인 메시지를 받을 수 있습니다.



 a| 
암호
 a| 
스토리지 시스템의 관리 암호를 입력합니다.



 a| 
WWN입니다
 a| 
스토리지 시스템의 WWN을 입력합니다(GET:/DISCOVERY의 응답에 표시됨).

|===
.. 전체 문자열 집합이 다음 예제와 비슷하게 하려면 ""enableTrace":true" 뒤에 있는 모든 문자열을 제거합니다.
+
[listing]
----
{
  "id": "EF570_Array",
  "controllerAddresses": [
    "Controller-A-Mgmt-IP","Controller-B-Mgmt_IP"
  ],
  "validate":true,
  "password": "array-admin-password",
  "wwn": "000A011000AF0000000000001A0C000E",
  "enableTrace": true
}
----
.. Execute * 를 클릭합니다.
.. 코드 응답이 201인지 확인합니다. 이는 끝점이 성공적으로 실행되었음을 나타냅니다.
+
Post:/storage-systems * 엔드포인트가 대기열에 추가됩니다. 다음 단계에서 * get:/storage-systems * 끝점을 사용하여 결과를 볼 수 있습니다.



. 다음과 같이 목록 추가를 확인합니다.
+
.. get:/storage-system * 끝점을 클릭합니다.
+
매개 변수가 필요하지 않습니다.

.. Execute * 를 클릭합니다.
.. 코드 응답이 200인지 확인합니다. 이는 끝점이 성공적으로 실행되었음을 나타냅니다.
.. 응답 본문에서 스토리지 시스템 세부 정보를 찾습니다. 반환된 값은 다음 예제와 같이 관리되는 스토리지 목록에 성공적으로 추가되었음을 나타냅니다.
+
[listing]
----
[
  {
    "id": "EF570_Array",
    "name": "EF570_Array",
    "wwn": "000A011000AF0000000000001A0C000E",
    "passwordStatus": "valid",
    "passwordSet": true,
    "status": "optimal",
    "ip1": "10.xxx.xx.213",
    "ip2": "10.xxx.xx.214",
    "managementPaths": [
      "10.xxx.xx.213",
      "10.xxx.xx.214"
  ]
  }
]
----






== 관리형 스토리지 시스템의 수를 스케일업할 수 있습니다

기본적으로 API는 최대 100개의 스토리지 시스템을 관리할 수 있습니다. 더 많은 를 관리해야 하는 경우에는 서버의 메모리 요구 사항을 높여야 합니다.

서버는 512MB의 메모리를 사용하도록 설정되어 있습니다. 네트워크에 100개의 추가 스토리지 시스템이 추가될 때마다 이 숫자에 250MB를 추가하십시오. 물리적으로 보유한 것보다 더 많은 메모리를 추가하지 마십시오. 운영 체제 및 기타 응용 프로그램에 충분한 추가 공간을 제공합니다.


NOTE: 기본 캐시 크기는 8,192개의 이벤트입니다. MEL 이벤트 캐시의 대략적인 데이터 사용량은 8,192개 이벤트마다 1MB입니다. 따라서 기본값을 유지함으로써 스토리지 시스템의 캐시 사용량을 약 1MB로 설정해야 합니다.


NOTE: 메모리 외에도 프록시는 각 스토리지 시스템에 대해 네트워크 포트를 사용합니다. Linux와 Windows에서는 네트워크 포트를 파일 핸들로 고려합니다. 보안 조치로서 대부분의 운영 체제는 프로세스 또는 사용자가 한 번에 열 수 있는 열린 파일 핸들 수를 제한합니다. 특히 열린 TCP 연결이 파일 처리인 Linux 환경에서는 웹 서비스 프록시가 이 제한을 쉽게 초과할 수 있습니다. 픽스는 시스템에 따라 달라지므로 이 값을 올리는 방법은 운영 체제 설명서를 참조하십시오.

.단계
. 다음 중 하나를 수행합니다.
+
** Windows에서 appserver64.init 파일로 이동합니다. 'vmarg.3=-Xmx512M' 줄을 찾습니다
** Linux의 경우 webserver.sh 파일로 이동합니다. "java_options="-Xmx512M" 줄을 찾습니다


. 메모리를 늘리려면 512를 원하는 메모리(MB)로 바꾸십시오.
. 파일을 저장합니다.

