---
permalink: web-services-proxy/install-reqs-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: 웹 서비스 프록시에 대한 설치 및 업그레이드 요구 사항 및 고려 사항 
---
= 설치 및 업그레이드 요구 사항 검토
:icons: font
:imagesdir: ../media/


[role="lead"]
웹 서비스 프록시를 설치하기 전에 설치 요구 사항 및 업그레이드 고려 사항을 검토하십시오.



== 설치 요구 사항

Windows 또는 Linux 호스트 시스템에 웹 서비스 프록시를 설치 및 구성할 수 있습니다.

프록시 설치에는 다음 요구 사항이 포함됩니다.

|===
| 요구 사항 | 설명 


 a| 
호스트 이름 제한
 a| 
웹 서비스 프록시를 설치할 서버의 호스트 이름에 ASCII 문자, 숫자 및 하이픈(-)만 포함되어 있는지 확인합니다. 이 요구 사항은 서버에 대해 자체 서명된 인증서를 생성하는 데 사용되는 Java Keytool의 제한 사항 때문입니다. 서버의 호스트 이름에 밑줄(_)과 같은 다른 문자가 포함되어 있으면 설치 후 Webserver가 시작되지 않습니다.



 a| 
운영 체제
 a| 
다음 운영 체제에 프록시를 설치할 수 있습니다.

* 리눅스
* Windows


운영 체제 및 펌웨어 호환성에 대한 전체 목록은 를 참조하십시오 http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].



 a| 
Linux: 추가 고려 사항
 a| 
Webserver가 제대로 작동하려면 Linux 표준 기본 라이브러리(init-function)가 필요합니다. 운영 체제용 LSB/insserv 패키지를 설치해야 합니다. 자세한 내용은 Readme 파일의 "추가 패키지 필요" 섹션을 참조하십시오.



 a| 
다중 인스턴스
 a| 
서버에 웹 서비스 프록시 인스턴스를 하나만 설치할 수 있지만, 네트워크 내의 여러 서버에 프록시를 설치할 수 있습니다.



 a| 
용량 계획
 a| 
웹 서비스 프록시는 로깅에 충분한 공간을 필요로 합니다. 시스템이 다음과 같은 사용 가능한 디스크 공간 요구 사항을 충족하는지 확인합니다.

* 필요한 설치 공간 -- 275MB
* 최소 로깅 공간 -- 200MB
* 시스템 메모리 -- 2GB, 힙 공간은 기본적으로 1Gb입니다


디스크 공간 모니터링 툴을 사용하여 영구 스토리지 및 로깅을 위해 사용 가능한 디스크 드라이브 공간을 확인할 수 있습니다.



 a| 
라이센스
 a| 
웹 서비스 프록시는 라이센스 키가 필요하지 않은 독립 실행형 무료 제품입니다. 그러나 해당 저작권 및 서비스 약관이 적용됩니다. 프록시를 그래픽 또는 콘솔 모드로 설치하는 경우 최종 사용자 사용권 계약(EULA)에 동의해야 합니다.

|===


== 업그레이드 고려 사항

이전 버전에서 업그레이드하는 경우에는 일부 항목이 보존되거나 제거된다는 점에 유의하십시오.

* 웹 서비스 프록시의 경우 이전 구성 설정이 유지됩니다. 이러한 설정에는 사용자 암호, 검색된 모든 스토리지 시스템, 서버 인증서, 신뢰할 수 있는 인증서 및 서버 런타임 구성이 포함됩니다.
* Unified Manager의 경우, 이전에 저장소에 로드된 모든 SANtricity OS 파일이 업그레이드 중에 제거됩니다.

