---
permalink: web-services-proxy/install-wsp-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: 설치에는 파일을 다운로드한 다음 Linux 또는 Windows 서버에 프록시 패키지를 설치하는 과정이 포함됩니다. 
---
= SANtricity 웹 서비스 프록시 및 SANtricity Unified Manager 파일 설치 또는 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치에는 파일을 다운로드한 다음 Linux 또는 Windows 서버에 프록시 패키지를 설치하는 과정이 포함됩니다. 이 지침을 사용하여 프록시를 업그레이드할 수도 있습니다.



== 웹 서비스 프록시 파일을 다운로드합니다

NetApp Support 사이트의 소프트웨어 다운로드 페이지에서 설치 파일과 readme 파일을 다운로드할 수 있습니다.

다운로드 패키지에는 웹 서비스 프록시 및 Unified Manager 인터페이스가 포함되어 있습니다.

.단계
. 로 이동합니다 https://mysupport.netapp.com/site/downloads["NetApp 지원 - 다운로드"^].
. E-Series SANtricity 웹 서비스 프록시 * 를 선택합니다.
. 지침에 따라 파일을 다운로드합니다. 서버에 맞는 올바른 다운로드 패키지를 선택해야 합니다(예: Windows의 경우 EXE, Linux의 경우 bin 또는 RPM).
. 프록시 및 Unified Manager를 설치할 서버에 설치 파일을 다운로드합니다.




== Windows 또는 Linux 서버에 설치합니다

세 가지 모드(그래픽, 콘솔 또는 자동) 중 하나를 사용하거나 RPM 파일(Linux만 해당)을 사용하여 웹 서비스 프록시 및 Unified Manager를 설치할 수 있습니다.

.시작하기 전에
* link:install-reqs-task.html["설치 요구 사항을 검토합니다"].
* 프록시 및 Unified Manager를 설치할 서버에 올바른 설치 파일(Windows의 경우 EXE, Linux의 경우 BIN)을 다운로드했는지 확인합니다.




=== 그래픽 모드 설치

Windows 또는 Linux의 그래픽 모드에서 설치를 실행할 수 있습니다. 그래픽 모드에서 프롬프트는 Windows 스타일 인터페이스에 나타납니다.

.단계
. 설치 파일을 다운로드한 폴더에 액세스합니다.
. 다음과 같이 Windows 또는 Linux에 대한 설치를 시작합니다.
+
** Windows -- 설치 파일을 두 번 클릭합니다.
+
'S antricity_webservices - windows_x64-nn.nn.nn.nn.nnnn.exe'

** Linux -- 'santricity_webservices -linux_x64-nn.nn.nn.nn.nn.bin' 명령을 실행합니다
+
위의 파일 이름에서 ' nn.nn.nn.nnnn'은 버전 번호를 나타냅니다.



+
설치 프로세스가 시작되고 NetApp SANtricity 웹 서비스 프록시 + Unified Manager 시작 화면이 나타납니다.

. 화면에 표시되는 메시지를 따릅니다.
+
설치 중에 여러 기능을 활성화하고 일부 구성 매개변수를 입력하라는 메시지가 표시됩니다. 필요한 경우 나중에 구성 파일에서 이러한 선택 항목을 변경할 수 있습니다.

+

NOTE: 업그레이드 중에는 구성 매개 변수를 묻는 메시지가 표시되지 않습니다.

. Webserver Started 메시지가 나타나면 * OK * 를 클릭하여 설치를 완료합니다.
+
설치 완료 대화 상자가 나타납니다.

. Unified Manager 또는 대화형 API 설명서를 실행하려면 확인란을 클릭한 다음 * 완료 * 를 클릭합니다.




=== 콘솔 모드 설치

Windows 또는 Linux의 경우 콘솔 모드에서 설치를 실행할 수 있습니다. 콘솔 모드에서는 터미널 창에 프롬프트가 나타납니다.

.단계
. '<파일 이름 설치> -i 콘솔' 명령을 실행합니다
+
위 명령에서 '<설치 파일 이름>'은 다운로드한 프록시 설치 파일의 이름을 나타냅니다(예: 'santricity_webservices-windows_x64-nn.nn.nn.nnnn.exe').

+

NOTE: 설치 과정 중 언제든지 설치를 취소하려면 명령 프롬프트에 quit를 입력합니다.

+
설치 프로세스가 시작되고 시작 설치 관리자 -- 소개 메시지가 나타납니다.

. 화면에 표시되는 메시지를 따릅니다.
+
설치 중에 여러 기능을 활성화하고 일부 구성 매개변수를 입력하라는 메시지가 표시됩니다. 필요한 경우 나중에 구성 파일에서 이러한 선택 항목을 변경할 수 있습니다.

+

NOTE: 업그레이드 중에는 구성 매개 변수를 묻는 메시지가 표시되지 않습니다.

. 설치가 완료되면 * Enter * 를 눌러 설치 프로그램을 종료합니다.




=== 자동 모드 설치

Windows 또는 Linux에서 자동 모드로 설치를 실행할 수 있습니다. 무음 모드에서는 터미널 창에 반환 메시지나 스크립트가 나타나지 않습니다.

.단계
. '<파일 이름 설치> -i silent' 명령을 실행합니다
+
위 명령에서 '<설치 파일 이름>'은 다운로드한 프록시 설치 파일의 이름을 나타냅니다(예: 'santricity_webservices-windows_x64-nn.nn.nn.nnnn.exe').

. Enter * 를 누릅니다.
+
설치 프로세스를 완료하는 데 몇 분 정도 걸릴 수 있습니다. 설치가 완료되면 터미널 창에 명령 프롬프트가 나타납니다.





=== rpm 명령 설치(Linux만 해당)

RPM 패키지 관리 시스템과 호환되는 Linux 시스템의 경우 선택적 RPM 파일을 사용하여 웹 서비스 프록시를 설치할 수 있습니다.

.단계
. RPM 파일을 프록시 및 Unified Manager를 설치할 서버로 다운로드합니다.
. 터미널 창을 엽니다.
. 다음 명령을 입력합니다.
+
`rpm -U santricity_webservices-nn.nn.nn.nnnn-n.x86_64.rpm`

+

NOTE: 위 명령에서 nn.nn.nn.nnnn은 버전 번호를 나타냅니다.

+
설치 프로세스를 완료하는 데 몇 분 정도 걸릴 수 있습니다. 설치가 완료되면 터미널 창에 명령 프롬프트가 나타납니다.


