---
permalink: web-services-proxy/install-config-task.html 
sidebar: sidebar 
keywords: configure Web Services Proxy, WSP configuration, start stop Webserver, start stop WSP service 
summary: 사용자 환경의 고유한 운영 및 성능 요구 사항에 맞게 웹 서비스 프록시 설정을 수정할 수 있습니다. 
---
= 웹 서비스 프록시를 구성합니다
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 환경의 고유한 운영 및 성능 요구 사항에 맞게 웹 서비스 프록시 설정을 수정할 수 있습니다.



== Webserver를 중지하거나 다시 시작합니다

Webserver 서비스는 설치 중에 시작되어 백그라운드에서 실행됩니다. 일부 구성 작업 중에 Webserver 서비스를 중지하거나 다시 시작해야 할 수 있습니다.

.단계
. 다음 중 하나를 수행합니다.
+
** Windows의 경우 * 시작 * 메뉴로 이동하여 관리 도구 [서비스] 메뉴를 선택하고 * NetApp SANtricity 웹 서비스 * 를 찾은 다음 * 중지 * 또는 * 재시작 * 을 선택합니다.
** Linux의 경우 운영 체제 버전의 Webserver를 중지하고 다시 시작하는 방법을 선택합니다. 설치 중에 어떤 데몬이 시작되었는지 팝업 대화 상자가 표시됩니다. 예를 들면 다음과 같습니다.
+
"web_services_proxy 웹 서버가 설치 및 시작되었습니다. systemctl start | stop | restart | status web_services_proxy.service` 를 사용하여 IT와 상호 작용할 수 있습니다

+
이 서비스와 상호 작용하는 가장 일반적인 방법은 'emctl' 명령을 사용하는 것입니다.







== 포트 충돌을 해결합니다

정의된 주소 또는 포트에서 다른 응용 프로그램을 사용할 수 있는 동안 웹 서비스 프록시가 실행되고 있으면 wsconfig.xml 파일에서 포트 충돌을 해결할 수 있습니다.

.단계
. 다음 위치에 있는 wsconfig.xml 파일을 엽니다.
+
** (Windows) -- C:\Program Files\NetApp\SANtricity Web Services Proxy
** (Linux) --/opt/NetApp/SANtricity_web_services_proxy


. wsconfig.xml 파일에 다음 줄을 추가합니다. 이 때 _n_은 포트 번호입니다.
+
[listing]
----
<sslport clientauth=”request”>*n*</sslport>
<port>n</port>
----
+
다음 표에서는 HTTP 포트 및 HTTPS 포트를 제어하는 특성을 보여 줍니다.

+
|===
| 이름 | 설명 | 상위 노드 | 속성 | 필수 요소입니다 


 a| 
구성
 a| 
구성의 루트 노드입니다
 a| 
null입니다
 a| 
버전 - 구성 스키마의 버전은 현재 1.0입니다.
 a| 
예



 a| 
슬포트
 a| 
SSL 요청을 수신 대기하는 TCP 포트. 기본값은 8443입니다.
 a| 
구성
 a| 
클라이언트 인증
 a| 
아니요



 a| 
포트
 a| 
HTTP 요청을 수신할 TCP 포트, 기본값은 8080입니다.
 a| 
구성
 a| 
-
 a| 
아니요

|===
. 파일을 저장하고 닫습니다.
. Webserver 서비스를 다시 시작하여 변경 사항을 적용합니다.




== 로드 밸런싱 및/또는 고가용성을 구성합니다

고가용성(HA) 구성에서 웹 서비스 프록시를 사용하려면 로드 밸런싱을 구성할 수 있습니다. HA 구성에서 일반적으로 단일 노드는 모든 요청을 수신하지만 다른 노드는 대기 중이거나 모든 노드에 걸쳐 요청이 로드 밸런싱됩니다.

웹 서비스 프록시는 고가용성(HA) 환경에 존재할 수 있으며, 대부분의 API는 요청 수신자와 관계없이 올바르게 작동합니다. 태그 및 폴더는 로컬 데이터베이스에 저장되고 웹 서비스 프록시 인스턴스 간에 공유되지 않기 때문에 메타데이터 태그와 폴더는 두 가지 예외입니다.

그러나 일부 요청에서는 몇 가지 알려진 타이밍 문제가 발생합니다. 특히 프록시의 한 인스턴스는 작은 창의 두 번째 인스턴스보다 더 빠른 새 데이터를 가질 수 있습니다. 웹 서비스 프록시는 이 타이밍 문제를 제거하는 특수 구성을 포함합니다. 이 옵션은 데이터 일관성을 위해 서비스 요청에 소요되는 시간이 증가하므로 기본적으로 사용되지 않습니다. 이 옵션을 활성화하려면 .INI 파일(Windows의 경우) 또는 .SH 파일(Linux의 경우)에 속성을 추가해야 합니다.

.단계
. 다음 중 하나를 수행합니다.
+
** Windows: appserver64.ini 파일을 열고 Dload-balance.enabled=true 속성을 추가합니다.
+
예: ``vmarg.7=-Dload-balance.enabled=true’

** Linux: webserver.sh 파일을 열고 Dload-balance.enabled=true 속성을 추가합니다.
+
예: debug_start_options="-dload-balance.enabled=true""



. 변경 사항을 저장합니다.
. Webserver 서비스를 다시 시작하여 변경 사항을 적용합니다.




== 기호 HTTPS를 비활성화합니다

기호 명령(기본 설정)을 사용하지 않도록 설정하고 RPC(원격 프로시저 호출)를 통해 명령을 보낼 수 있습니다. 이 설정은 wsconfig.xml 파일에서 변경할 수 있습니다.

기본적으로 웹 서비스 프록시는 SANtricity OS 버전 08.40 이상을 실행하는 모든 E2800 시리즈 및 E5700 시리즈 스토리지 시스템에 대해 HTTPS를 통해 기호 명령을 보냅니다. HTTPS를 통해 전송되는 기호 명령이 스토리지 시스템에 인증됩니다. 필요한 경우 HTTPS 기호 지원을 사용하지 않도록 설정하고 RPC를 통해 명령을 보낼 수 있습니다. RPC를 통한 기호가 구성될 때마다 스토리지 시스템에 대한 모든 수동 명령이 인증 없이 설정됩니다.


NOTE: RPC를 통한 기호가 사용되는 경우 웹 서비스 프록시는 기호 관리 포트가 비활성화된 시스템에 연결할 수 없습니다.

.단계
. 다음 위치에 있는 wsconfig.xml 파일을 엽니다.
+
** (Windows) -- C:\Program Files\NetApp\SANtricity Web Services Proxy
** (Linux) --/opt/NetApp/SANtricity_web_services_proxy


. 'devic고객전략' 항목에서 'eudemgt Preferred' 값을 rpcOnly로 바꿉니다.
+
예를 들면 다음과 같습니다.

+
'< env key="devicemgt.symbolclientStrategy">rpcOnly</env>'

. 파일을 저장합니다.




== 오리진 간 리소스 공유를 구성합니다

CORS(Cross-origin Resource Sharing)를 구성할 수 있습니다. CORS는 다른 오리진의 서버에서 선택한 리소스에 액세스할 수 있는 권한을 가지도록 하나의 오리진에서 실행되는 웹 애플리케이션을 제공하는 추가 HTTP 헤더를 사용하는 메커니즘입니다.

CORS는 작업 디렉토리에 있는 cors.cfg 파일에 의해 처리됩니다. CORS 구성은 기본적으로 열려 있으므로 도메인 간 액세스는 제한되지 않습니다.

구성 파일이 없으면 CORS가 열려 있는 것입니다. 그러나 cors.cfg 파일이 있으면 이 파일이 사용됩니다. cors.cfg 파일이 비어 있으면 CORS 요청을 할 수 없습니다.

.단계
. 작업 디렉터리에 있는 cors.cfg 파일을 엽니다.
. 파일에 원하는 선을 추가합니다.
+
CORS 구성 파일의 각 줄은 일치시킬 정규식 패턴입니다. 원점 머리글은 cors.cfg 파일의 선과 일치해야 합니다. 오리진 헤더와 일치하는 회선 패턴이 있으면 요청이 허용됩니다. 호스트 요소뿐만 아니라 전체 원점을 비교합니다.

. 파일을 저장합니다.


요청은 호스트 및 다음과 같은 프로토콜에 따라 일치됩니다.

* localhost를 모든 프로토콜--"\ * localhost *"와 일치시킵니다
* HTTPS에 대해서만 localhost 일치 --'+https://localhost*+`

