---
permalink: web-services-proxy/install-login-task.html 
sidebar: sidebar 
keywords: log in API, log in Unified Manager 
summary: 웹 서비스 API 및 Unified Manager에 액세스 및 로그인합니다. 
---
= API 및 Unified Manager에 로그인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
웹 서비스에는 REST API와 직접 상호 작용할 수 있는 API 설명서가 포함되어 있습니다. 또한 여러 E-Series 스토리지 시스템을 관리하기 위한 브라우저 기반 인터페이스인 Unified Manager도 포함되어 있습니다.



== 웹 서비스 API에 로그인합니다

웹 서비스 프록시를 설치한 후 브라우저에서 대화형 API 설명서에 액세스할 수 있습니다.

API 설명서는 웹 서비스의 각 인스턴스에서 실행되며 NetApp Support 사이트에서 제공되는 정적 PDF 형식으로도 제공됩니다. 대화형 버전에 액세스하려면 브라우저를 열고 웹 서비스가 있는 위치(포함된 버전의 컨트롤러 또는 프록시의 서버)를 가리키는 URL을 입력합니다.


NOTE: 웹 서비스 API는 OpenAPI 사양(원래 Swagger 사양이라고 함)을 구현합니다.

초기 로그인의 경우 "admin" 자격 증명을 사용합니다. "관리자"는 모든 기능 및 역할에 액세스할 수 있는 슈퍼 관리자로 간주됩니다.

.단계
. 브라우저를 엽니다.
. 포함된 또는 프록시 구현의 URL을 입력합니다.
+
** 포함: '+https://<controller>:<port>/devmgr/docs/+`
+
이 URL에서 "<controller>"는 컨트롤러의 IP 주소 또는 FQDN이며 "<port>"는 컨트롤러의 관리 포트 번호입니다(기본값은 8443임).

** 프록시: "+http[s]://<server>:<port>/devmgr/docs/+"
+
이 URL에서 '<server>'는 프록시가 설치된 서버의 IP 주소 또는 FQDN이며 수신 포트 번호는 '<port>'입니다(기본값은 HTTP의 경우 8080, HTTPS의 경우 8443입니다).

+

NOTE: 수신 포트가 이미 사용 중인 경우 프록시는 충돌을 감지하고 다른 수신 포트를 선택하라는 메시지를 표시합니다.

+
브라우저에서 API 설명서가 열립니다.



. 대화형 API 문서가 열리면 페이지 오른쪽 상단의 드롭다운 메뉴로 이동하여 * utils * 를 선택합니다.
. 사용 가능한 끝점을 보려면 * 로그인 * 범주를 클릭합니다.
. POST:/login * 끝점을 클릭한 다음 * try it out * 을 클릭합니다.
. 처음 로그인하는 경우 사용자 이름 및 암호에 admin 을 입력합니다.
. Execute * 를 클릭합니다.
. 스토리지 관리를 위한 엔드포인트에 액세스하려면 오른쪽 상단의 드롭다운 메뉴로 이동하여 * v2 * 를 선택합니다.
+
끝점의 상위 수준 범주가 표시됩니다. 표에 설명된 대로 API 설명서를 탐색할 수 있습니다.

+
|===
| 영역 | 설명 


 a| 
드롭다운 메뉴를 선택합니다
 a| 
페이지 오른쪽 위에 있는 드롭다운 메뉴에서 버전 2의 API 설명서(V2), 기호 인터페이스(기호 V2) 및 로그인할 수 있는 API 유틸리티(유틸리티) 간에 전환할 수 있는 옵션을 제공합니다.


NOTE: API 설명서 버전 1은 사전 릴리스 버전이므로 일반적으로 사용할 수 없으므로 V1은 드롭다운 메뉴에 포함되지 않습니다.



 a| 
범주
 a| 
API 설명서는 상위 범주(예: Administration, Configuration)별로 구성되어 있습니다. 관련 끝점을 보려면 범주를 클릭합니다.



 a| 
엔드포인트
 a| 
URL이 반환될 가능성이 있는 URL 경로, 필수 매개 변수, 응답 본문 및 상태 코드를 보려면 끝점을 선택합니다.



 a| 
시도해 보십시오
 a| 
Try it Out * 을 클릭하여 끝점과 직접 상호 작용할 수 있습니다. 이 버튼은 엔드포인트의 확장 보기 각각에 제공됩니다.

버튼을 클릭하면 파라미터 입력을 위한 필드가 나타납니다(해당하는 경우). 그런 다음 값을 입력하고 * Execute * 를 클릭합니다.

대화형 설명서는 JavaScript를 사용하여 API에 직접 요청을 합니다. 테스트 요청이 아닙니다.

|===




== Unified Manager에 로그인합니다

웹 서비스 프록시를 설치한 후 Unified Manager에 액세스하여 웹 기반 인터페이스에서 여러 스토리지 시스템을 관리할 수 있습니다.

Unified Manager에 액세스하려면 브라우저를 열고 프록시가 설치된 위치를 가리키는 URL을 입력합니다. 다음 브라우저 및 버전이 지원됩니다.

|===
| 브라우저 | 최소 버전 


 a| 
Google Chrome
 a| 
79



 a| 
Microsoft Internet Explorer를 참조하십시오
 a| 
11



 a| 
Microsoft Edge를 참조하십시오
 a| 
79



 a| 
Mozilla Firefox
 a| 
70



 a| 
사파리
 a| 
12

|===
.단계
. 브라우저를 열고 다음 URL을 입력합니다.
+
'+http[s]://<server>:<port>/um+'

+
이 URL에서 "<server>"는 웹 서비스 프록시가 설치된 서버의 IP 주소 또는 FQDN을 나타내며 "<port>"는 수신 대기 포트 번호를 나타냅니다(기본값은 HTTP의 경우 8080, HTTPS의 경우 8443입니다).

+
Unified Manager 로그인 페이지가 열립니다.

. 처음 로그인하는 경우 사용자 이름에 admin을 입력한 다음 admin 사용자의 암호를 설정 및 확인합니다.
+
암호는 최대 30자까지 입력할 수 있습니다. 사용자 및 암호에 대한 자세한 내용은 Unified Manager 온라인 도움말의 액세스 관리 섹션을 참조하십시오.


