---
permalink: web-services-proxy/install-uninstall-task.html 
sidebar: sidebar 
keywords: uninstall Web Services Proxy, remove WSP, 
summary: '웹 서비스 프록시 및 Unified Manager를 제거하려면 프록시를 설치하는 데 사용한 방법에 관계없이 모든 모드(그래픽, 콘솔, 자동 또는 RPM 파일)를 사용할 수 있습니다.' 
---
= SANtricity 웹 서비스 프록시를 제거합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
웹 서비스 프록시 및 Unified Manager를 제거하려면 프록시를 설치하는 데 사용한 방법에 관계없이 모든 모드(그래픽, 콘솔, 자동 또는 RPM 파일)를 사용할 수 있습니다.



== 그래픽 모드 제거

Windows 또는 Linux의 그래픽 모드에서 제거를 실행할 수 있습니다. 그래픽 모드에서 프롬프트는 Windows 스타일 인터페이스에 나타납니다.

.단계
. 다음과 같이 Windows 또는 Linux에 대한 제거를 실행합니다.
+
** Windows -- uninstall_web_services_proxy 제거 파일이 들어 있는 디렉터리로 이동합니다. 기본 디렉토리는 C:/Program Files/NetApp/SANtricity Web Services Proxy/ 입니다. uninstall_web_services_proxy.exe를 두 번 클릭합니다.
+

NOTE: 또는 제어판 [프로그램 > 프로그램 제거] 메뉴로 이동한 다음 "NetApp SANtricity 웹 서비스 프록시"를 선택합니다.

** Linux -- 웹 서비스 프록시 제거 파일이 들어 있는 디렉터리로 이동합니다. 기본 디렉토리는 + "/opt/netapp/sSANtricity_web_services_proxy/uninstall_web_services_proxy"에 있습니다


. 다음 명령을 실행합니다.
+
uninstall_web_services_proxy-i gui

+
SANtricity 웹 서비스 프록시 시작 화면이 나타납니다.

. 제거 대화 상자에서 * 제거 * 를 클릭합니다.
+
설치 제거 프로그램 진행 표시줄이 나타나고 진행 상태가 표시됩니다.

. 제거 완료 메시지가 나타나면 * 완료 * 를 클릭합니다.




== 콘솔 모드 제거

Windows 또는 Linux의 콘솔 모드에서 제거를 실행할 수 있습니다. 콘솔 모드에서는 터미널 창에 프롬프트가 나타납니다.

.단계
. uninstall_web_services_proxy 디렉토리로 이동합니다.
. 다음 명령을 실행합니다.
+
uninstall_web_services_proxy-i console을 선택합니다

+
제거 프로세스가 시작됩니다.

. 제거가 완료되면 * Enter * 를 눌러 설치 프로그램을 종료합니다.




== 자동 모드 제거

Windows 또는 Linux의 경우 자동 모드에서 제거를 실행할 수 있습니다. 무음 모드에서는 터미널 창에 반환 메시지나 스크립트가 나타나지 않습니다.

.단계
. uninstall_web_services_proxy 디렉토리로 이동합니다.
. 다음 명령을 실행합니다.
+
'uninstall_web_services_proxy-i silent

+
제거 프로세스가 실행되지만 터미널 창에는 반환 메시지 또는 스크립트가 나타나지 않습니다. 웹 서비스 프록시를 성공적으로 제거한 후 터미널 창에 명령 프롬프트가 나타납니다.





== rpm 명령 제거(Linux만 해당)

RPM 명령을 사용하여 Linux 시스템에서 웹 서비스 프록시를 제거할 수 있습니다.

.단계
. 터미널 창을 엽니다.
. 다음 명령줄을 입력합니다.
+
rpm -e sSANtricity_webservices를 나타냅니다

+

NOTE: 제거 프로세스는 원본 설치에 포함되지 않은 파일을 남겨둘 수 있습니다. 이러한 파일을 수동으로 삭제하여 웹 서비스 프록시를 완전히 제거합니다.


