---
permalink: web-services-proxy/polling-intro-concept.html 
sidebar: sidebar 
keywords: polling Web Services Proxy, WSP statistics, poll WSP, 
summary: 검색된 스토리지 시스템의 모든 디스크 및 볼륨 통계에 대한 자동 폴링을 구성할 수 있습니다. 
---
= 웹 서비스 프록시 통계에 대한 자동 폴링을 관리합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
검색된 스토리지 시스템의 모든 디스크 및 볼륨 통계에 대한 자동 폴링을 구성할 수 있습니다.



== 통계 개요

통계는 스토리지 시스템의 데이터 수집 속도 및 성능에 대한 정보를 제공합니다.

웹 서비스 프록시는 다음과 같은 유형의 통계에 대한 액세스를 제공합니다.

* raw statistics -- 데이터 수집 시점의 데이터 지점에 대한 총 카운터입니다. 원시 통계는 총 읽기 작업 또는 총 쓰기 작업에 사용할 수 있습니다.
* 분석된 통계 -- 간격에 대한 계산된 정보입니다. 분석된 통계의 예로는 초당 읽기 입출력 작업(IOPS) 또는 쓰기 처리량이 있습니다.


원시 통계는 선형이므로 일반적으로 최소 2개의 수집된 데이터 포인트가 가용 데이터를 도출해야 합니다. 분석된 통계는 중요한 메트릭을 제공하는 원시 통계의 파생입니다. 원시 통계에서 파생될 수 있는 많은 값은 사용자의 편의를 위해 분석된 통계에서 사용 가능한 시점 형식으로 표시됩니다.

자동 폴링이 활성화되었는지 여부에 관계없이 원시 통계를 검색할 수 있습니다. URL 끝에 usecache=true 쿼리 문자열을 추가하여 마지막 폴에서 캐시된 통계를 검색할 수 있습니다. 캐시된 결과를 사용하면 통계 검색 성능이 크게 향상됩니다. 그러나 구성된 폴링 간격 캐시와 같거나 작은 속도로 여러 건의 통화가 동일한 데이터를 검색합니다.



== 통계 기능

웹 서비스 프록시는 지원되는 하드웨어 모델 및 소프트웨어 버전에서 원시 및 분석된 컨트롤러 및 인터페이스 통계를 검색할 수 있는 API 엔드포인트를 제공합니다.



=== 원시 통계 API

* '+/storage-systems/{system-id}/controller-statistics+'
* '+/storage-systems/{system-id}/drive-statistics/{디스크 ID 목록}+'
* '+/storage-systems/{system-id}/interface-statistics/{인터페이스 ID 목록}+'
* '+/storage-systems/{system-id}/volume-statistics/{볼륨 ID 목록}+'




=== 분석된 통계 API

* '+/storage-systems/{id}/분석됨-controller-statistics/+'
* '+/storage-systems/{id}/분석됨-drive-statistics/{디스크 ID 목록}+'
* '+/storage-systems/{id}/분석됨-interface-statistics/{인터페이스 ID의 선택적 목록}+'
* '+/storage-systems/{id}/분석됨-volume-statistics/{볼륨 ID 목록}+'


이러한 URL은 마지막 폴링에서 분석된 통계를 검색하며 폴링이 활성화된 경우에만 사용할 수 있습니다. 이러한 URL에는 다음과 같은 입력 출력 데이터가 포함됩니다.

* 초당 작업 수입니다
* 초당 메가바이트 단위의 처리량
* 응답 시간(밀리초)


이 계산은 가장 일반적인 스토리지 성능 측정인 통계 폴링 반복 간의 차이를 기반으로 합니다. 이러한 통계는 분석되지 않은 통계보다 선호됩니다.


NOTE: 시스템이 시작될 때 다양한 메트릭을 계산하는 데 사용할 이전 통계 수집이 없으므로 분석된 통계에는 데이터를 반환하기 위해 시작 후 최소 하나의 폴링 주기가 필요합니다. 또한 누적 카운터가 재설정되는 경우 다음 폴링 주기에 예측할 수 없는 데이터 수가 있습니다.



== 폴링 간격을 구성합니다

폴링 간격을 구성하려면 wsconfig.xml 파일을 수정하여 폴링 간격을 초 단위로 지정합니다.


NOTE: 통계가 메모리에 캐시되기 때문에 각 스토리지 시스템에 대해 약 1.5MB의 메모리 사용량이 증가할 수 있습니다.

.시작하기 전에
* 스토리지 시스템은 프록시에서 검색되어야 합니다.


.단계
. 다음 위치에 있는 wsconfig.xml 파일을 엽니다.
+
** (Windows) -- C:\Program Files\NetApp\SANtricity Web Services Proxy
** (Linux) --/opt/NetApp/SANtricity_web_services_proxy


. '<env-entries>' 태그 안에 다음 줄을 추가합니다. 이 때 n은 폴링 요청 사이의 간격(초)입니다.
+
[listing]
----
<env key="stats.poll.interval">n</env>
----
+
예를 들어, 60을 입력하면 60초 간격으로 폴링이 시작됩니다. 즉, 이전 폴링 기간이 완료된 후 60초 후에 시스템이 폴링을 시작하도록 요청합니다(이전 폴링 기간의 지속 시간과 상관 없음). 모든 통계는 검색된 정확한 시간에 타임 스탬프로 표시됩니다. 시스템은 60초 계산의 기반이 되는 시간 스탬프 또는 시간 차이를 사용합니다.

. 파일을 저장합니다.

